CREATE TABLE [dbo].[AO_54C900_CONTENT_BLUEPRINT_AO]
(
[CREATE_RESULT] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[HOW_TO_USE_TEMPLATE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[ID] [int] NOT NULL IDENTITY(1, 1),
[INDEX_DISABLED] [bit] NULL,
[INDEX_KEY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[INDEX_TITLE_I18N_KEY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[NAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[PLUGIN_CLONE] [bit] NULL,
[PLUGIN_MODULE_KEY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[SPACE_KEY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[UUID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_54C900_CONTENT_BLUEPRINT_AO] ADD CONSTRAINT [pk_AO_54C900_CONTENT_BLUEPRINT_AO_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
