CREATE TABLE [dbo].[EXTRNLNKS]
(
[LINKID] [numeric] (19, 0) NOT NULL,
[CONTENTTYPE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
[VIEWCOUNT] [int] NOT NULL,
[URL] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
[LOWERURL] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
[CONTENTID] [numeric] (19, 0) NOT NULL,
[CREATOR] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[CREATIONDATE] [datetime] NULL,
[LASTMODIFIER] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[LASTMODDATE] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[EXTRNLNKS] ADD CONSTRAINT [PK__EXTRNLNK__04E1D4C7916776AC] PRIMARY KEY CLUSTERED  ([LINKID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [el_contentid_idx] ON [dbo].[EXTRNLNKS] ([CONTENTID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [el_creator_idx] ON [dbo].[EXTRNLNKS] ([CREATOR]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [el_lastmodifier_idx] ON [dbo].[EXTRNLNKS] ([LASTMODIFIER]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[EXTRNLNKS] ADD CONSTRAINT [FK_EXTRNLNKS_CREATOR] FOREIGN KEY ([CREATOR]) REFERENCES [dbo].[user_mapping] ([user_key])
GO
ALTER TABLE [dbo].[EXTRNLNKS] ADD CONSTRAINT [FK_EXTRNLNKS_LASTMODIFIER] FOREIGN KEY ([LASTMODIFIER]) REFERENCES [dbo].[user_mapping] ([user_key])
GO
ALTER TABLE [dbo].[EXTRNLNKS] ADD CONSTRAINT [FK97C10FE78DD41734] FOREIGN KEY ([CONTENTID]) REFERENCES [dbo].[CONTENT] ([CONTENTID])
GO
