CREATE TABLE [dbo].[CONTENT_LABEL]
(
[ID] [numeric] (19, 0) NOT NULL,
[LABELID] [numeric] (19, 0) NOT NULL,
[CONTENTID] [numeric] (19, 0) NULL,
[PAGETEMPLATEID] [numeric] (19, 0) NULL,
[OWNER] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[CREATIONDATE] [datetime] NULL,
[LASTMODDATE] [datetime] NULL,
[LABELABLEID] [numeric] (19, 0) NULL,
[LABELABLETYPE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CONTENT_LABEL] ADD CONSTRAINT [PK__CONTENT___3214EC27B486E180] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [cl_contentid_idx] ON [dbo].[CONTENT_LABEL] ([CONTENTID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [cl_labelable_idx] ON [dbo].[CONTENT_LABEL] ([LABELABLEID], [LABELABLETYPE]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [cl_labelid_idx] ON [dbo].[CONTENT_LABEL] ([LABELID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [cl_lastmoddate_idx] ON [dbo].[CONTENT_LABEL] ([LASTMODDATE]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [cl_owner_idx] ON [dbo].[CONTENT_LABEL] ([OWNER]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [cl_pagetemplateid_idx] ON [dbo].[CONTENT_LABEL] ([PAGETEMPLATEID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CONTENT_LABEL] ADD CONSTRAINT [FK_CONTENT_LABEL_OWNER] FOREIGN KEY ([OWNER]) REFERENCES [dbo].[user_mapping] ([user_key])
GO
ALTER TABLE [dbo].[CONTENT_LABEL] ADD CONSTRAINT [FKF0E7436E27072AEF] FOREIGN KEY ([LABELID]) REFERENCES [dbo].[LABEL] ([LABELID])
GO
ALTER TABLE [dbo].[CONTENT_LABEL] ADD CONSTRAINT [FKF0E7436E8DD41734] FOREIGN KEY ([CONTENTID]) REFERENCES [dbo].[CONTENT] ([CONTENTID])
GO
ALTER TABLE [dbo].[CONTENT_LABEL] ADD CONSTRAINT [FKF0E7436ED32042E4] FOREIGN KEY ([PAGETEMPLATEID]) REFERENCES [dbo].[PAGETEMPLATES] ([TEMPLATEID])
GO
