CREATE TABLE [dbo].[AO_9412A1_USER_APP_LINK]
(
[APPLICATION_LINK_ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[AUTH_VERIFIED] [bit] NULL,
[CREATED] [datetime] NULL,
[ID] [bigint] NOT NULL IDENTITY(1, 1),
[UPDATED] [datetime] NULL,
[USER_ID] [bigint] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_9412A1_USER_APP_LINK] ADD CONSTRAINT [pk_AO_9412A1_USER_APP_LINK_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_9412a1_use643533071] ON [dbo].[AO_9412A1_USER_APP_LINK] ([APPLICATION_LINK_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_9412a1_use1222319987] ON [dbo].[AO_9412A1_USER_APP_LINK] ([USER_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_9412A1_USER_APP_LINK] ADD CONSTRAINT [fk_ao_9412a1_user_app_link_user_id] FOREIGN KEY ([USER_ID]) REFERENCES [dbo].[AO_9412A1_AOUSER] ([ID])
GO
