CREATE TABLE [dbo].[CLUSTERSAFETY]
(
[CLUSTERSAFETYID] [numeric] (19, 0) NOT NULL,
[SAFETYNUMBER] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CLUSTERSAFETY] ADD CONSTRAINT [PK__CLUSTERS__0E347EE2E446CC67] PRIMARY KEY CLUSTERED  ([CLUSTERSAFETYID]) ON [PRIMARY]
GO
