CREATE TABLE [dbo].[AUDIT_CHANGED_VALUE]
(
[ID] [numeric] (19, 0) NOT NULL,
[NAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
[OLDVALUE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[NEWVALUE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[AUDITRECORDID] [numeric] (19, 0) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AUDIT_CHANGED_VALUE] ADD CONSTRAINT [PK__AUDIT_CH__3214EC2757438EF5] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [a_values_parent_index] ON [dbo].[AUDIT_CHANGED_VALUE] ([AUDITRECORDID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AUDIT_CHANGED_VALUE] ADD CONSTRAINT [FK_CHANGED_VALUE_RECORD] FOREIGN KEY ([AUDITRECORDID]) REFERENCES [dbo].[AUDITRECORD] ([AUDITRECORDID])
GO
