CREATE TABLE [dbo].[AO_DC98AE_AOHELP_TIP]
(
[DISMISSED_HELP_TIP] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[ID] [int] NOT NULL IDENTITY(1, 1),
[USER_KEY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_DC98AE_AOHELP_TIP] ADD CONSTRAINT [pk_AO_DC98AE_AOHELP_TIP_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_dc98ae_aoh411805038] ON [dbo].[AO_DC98AE_AOHELP_TIP] ([DISMISSED_HELP_TIP]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_dc98ae_aoh1533992358] ON [dbo].[AO_DC98AE_AOHELP_TIP] ([USER_KEY]) ON [PRIMARY]
GO
