CREATE TABLE [dbo].[IMAGEDETAILS]
(
[ATTACHMENTID] [numeric] (19, 0) NOT NULL,
[HEIGHT] [int] NULL,
[WIDTH] [int] NULL,
[MIMETYPE] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CS_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[IMAGEDETAILS] ADD CONSTRAINT [PK__IMAGEDET__23CEF7B0A3BE5729] PRIMARY KEY CLUSTERED  ([ATTACHMENTID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[IMAGEDETAILS] ADD CONSTRAINT [FKA768048734A4917E] FOREIGN KEY ([ATTACHMENTID]) REFERENCES [dbo].[CONTENT] ([CONTENTID])
GO
