CREATE TABLE [dbo].[AO_950DC3_TC_JIRA_REMI_EVENTS]
(
[ALL_DAY] [bit] NULL,
[ASSIGNEE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[DESCRIPTION] [ntext] COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[EVENT_TYPE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[ID] [int] NOT NULL IDENTITY(1, 1),
[ISSUE_ICON_URL] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[ISSUE_LINK] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[JQL] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[KEY_ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[STATUS] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[SUB_CALENDAR_ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[TICKET_ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[TITLE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[USER_ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[UTC_END] [bigint] NULL,
[UTC_START] [bigint] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_950DC3_TC_JIRA_REMI_EVENTS] ADD CONSTRAINT [pk_AO_950DC3_TC_JIRA_REMI_EVENTS_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_950DC3_TC_JIRA_REMI_EVENTS] ADD CONSTRAINT [fk_ao_950dc3_tc_jira_remi_events_sub_calendar_id] FOREIGN KEY ([SUB_CALENDAR_ID]) REFERENCES [dbo].[AO_950DC3_TC_SUBCALS] ([ID])
GO
