CREATE TABLE [dbo].[NOTIFICATIONS]
(
[NOTIFICATIONID] [numeric] (19, 0) NOT NULL,
[CONTENTID] [numeric] (19, 0) NULL,
[LABELID] [numeric] (19, 0) NULL,
[SPACEID] [numeric] (19, 0) NULL,
[USERNAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
[CREATOR] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[CREATIONDATE] [datetime] NULL,
[LASTMODIFIER] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[LASTMODDATE] [datetime] NULL,
[DIGEST] [tinyint] NULL,
[NETWORK] [tinyint] NULL,
[CONTENTTYPE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NOTIFICATIONS] ADD CONSTRAINT [PK__NOTIFICA__EAF93BF4395A6801] PRIMARY KEY CLUSTERED  ([NOTIFICATIONID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [n_contentid_idx] ON [dbo].[NOTIFICATIONS] ([CONTENTID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [n_creator_idx] ON [dbo].[NOTIFICATIONS] ([CREATOR]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [n_labelid_idx] ON [dbo].[NOTIFICATIONS] ([LABELID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [n_lastmodifier_idx] ON [dbo].[NOTIFICATIONS] ([LASTMODIFIER]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [n_spaceid_idx] ON [dbo].[NOTIFICATIONS] ([SPACEID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [n_username_idx] ON [dbo].[NOTIFICATIONS] ([USERNAME]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NOTIFICATIONS] ADD CONSTRAINT [FK_NOTIFICATIONS_CONTENT] FOREIGN KEY ([CONTENTID]) REFERENCES [dbo].[CONTENT] ([CONTENTID])
GO
ALTER TABLE [dbo].[NOTIFICATIONS] ADD CONSTRAINT [FK_NOTIFICATIONS_CREATOR] FOREIGN KEY ([CREATOR]) REFERENCES [dbo].[user_mapping] ([user_key])
GO
ALTER TABLE [dbo].[NOTIFICATIONS] ADD CONSTRAINT [FK_NOTIFICATIONS_LASTMODIFIER] FOREIGN KEY ([LASTMODIFIER]) REFERENCES [dbo].[user_mapping] ([user_key])
GO
ALTER TABLE [dbo].[NOTIFICATIONS] ADD CONSTRAINT [FK_NOTIFICATIONS_USERNAME] FOREIGN KEY ([USERNAME]) REFERENCES [dbo].[user_mapping] ([user_key])
GO
ALTER TABLE [dbo].[NOTIFICATIONS] ADD CONSTRAINT [FK594ACC827072AEF] FOREIGN KEY ([LABELID]) REFERENCES [dbo].[LABEL] ([LABELID])
GO
ALTER TABLE [dbo].[NOTIFICATIONS] ADD CONSTRAINT [FK594ACC8B2DC6081] FOREIGN KEY ([SPACEID]) REFERENCES [dbo].[SPACES] ([SPACEID])
GO
