CREATE TABLE [dbo].[LINKS]
(
[LINKID] [numeric] (19, 0) NOT NULL,
[DESTPAGETITLE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[LOWERDESTPAGETITLE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[DESTSPACEKEY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
[LOWERDESTSPACEKEY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[CONTENTID] [numeric] (19, 0) NOT NULL,
[CREATOR] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[CREATIONDATE] [datetime] NULL,
[LASTMODIFIER] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[LASTMODDATE] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LINKS] ADD CONSTRAINT [PK__LINKS__04E1D4C7768C9DE0] PRIMARY KEY CLUSTERED  ([LINKID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [l_contentid_idx] ON [dbo].[LINKS] ([CONTENTID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [links_creator_idx] ON [dbo].[LINKS] ([CREATOR]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [l_destpgtitle_idx] ON [dbo].[LINKS] ([DESTPAGETITLE]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [l_destspacekey_idx] ON [dbo].[LINKS] ([DESTSPACEKEY]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [links_lastmodifier_idx] ON [dbo].[LINKS] ([LASTMODIFIER]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [l_ldestpgtitle_idx] ON [dbo].[LINKS] ([LOWERDESTPAGETITLE]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [l_ldestspacekey_idx] ON [dbo].[LINKS] ([LOWERDESTSPACEKEY]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LINKS] ADD CONSTRAINT [FK_LINKS_CREATOR] FOREIGN KEY ([CREATOR]) REFERENCES [dbo].[user_mapping] ([user_key])
GO
ALTER TABLE [dbo].[LINKS] ADD CONSTRAINT [FK_LINKS_LASTMODIFIER] FOREIGN KEY ([LASTMODIFIER]) REFERENCES [dbo].[user_mapping] ([user_key])
GO
ALTER TABLE [dbo].[LINKS] ADD CONSTRAINT [FK45157998DD41734] FOREIGN KEY ([CONTENTID]) REFERENCES [dbo].[CONTENT] ([CONTENTID])
GO
