CREATE TABLE [dbo].[BANDANA]
(
[BANDANAID] [numeric] (19, 0) NOT NULL,
[BANDANACONTEXT] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
[BANDANAKEY] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
[BANDANAVALUE] [ntext] COLLATE SQL_Latin1_General_CP1_CS_AS NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[BANDANA] ADD CONSTRAINT [PK__BANDANA__DCCFB409D68226C8] PRIMARY KEY CLUSTERED  ([BANDANAID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [band_context_idx] ON [dbo].[BANDANA] ([BANDANACONTEXT]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [band_cont_key_idx] ON [dbo].[BANDANA] ([BANDANACONTEXT], [BANDANAKEY]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BANDANA] ADD CONSTRAINT [bandana_unique_key] UNIQUE NONCLUSTERED  ([BANDANACONTEXT], [BANDANAKEY]) ON [PRIMARY]
GO
