CREATE TABLE [dbo].[AUDITRECORD]
(
[AUDITRECORDID] [numeric] (19, 0) NOT NULL,
[SUMMARY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[DESCRIPTION] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[CATEGORY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[ADDRESS] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[SYSAMDIN] [tinyint] NOT NULL,
[AUTHORNAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[AUTHORFULLNAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[AUTHORKEY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[OBJECTNAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[OBJECTTYPE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[SEARCHSTRING] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[CREATIONDATE] [numeric] (19, 0) NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AUDITRECORD] ADD CONSTRAINT [PK__AUDITREC__B410B3CEF3815645] PRIMARY KEY CLUSTERED  ([AUDITRECORDID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [a_author_key_idx] ON [dbo].[AUDITRECORD] ([AUTHORKEY]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [a_category_idx] ON [dbo].[AUDITRECORD] ([CATEGORY]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [a_date_idx] ON [dbo].[AUDITRECORD] ([CREATIONDATE]) ON [PRIMARY]
GO
