CREATE TABLE [dbo].[AO_54C900_SPACE_BLUEPRINT_AO]
(
[CATEGORY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[HOME_PAGE_ID] [int] NULL,
[ID] [int] NOT NULL IDENTITY(1, 1),
[NAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[PLUGIN_CLONE] [bit] NULL,
[PLUGIN_MODULE_KEY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[PROMOTED_BPS] [ntext] COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[UUID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_54C900_SPACE_BLUEPRINT_AO] ADD CONSTRAINT [pk_AO_54C900_SPACE_BLUEPRINT_AO_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_54c900_spa357134289] ON [dbo].[AO_54C900_SPACE_BLUEPRINT_AO] ([HOME_PAGE_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_54C900_SPACE_BLUEPRINT_AO] ADD CONSTRAINT [fk_ao_54c900_space_blueprint_ao_home_page_id] FOREIGN KEY ([HOME_PAGE_ID]) REFERENCES [dbo].[AO_54C900_C_TEMPLATE_REF] ([ID])
GO
