CREATE TABLE [dbo].[SPACEPERMISSIONS]
(
[PERMID] [numeric] (19, 0) NOT NULL,
[SPACEID] [numeric] (19, 0) NULL,
[PERMTYPE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
[PERMGROUPNAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[PERMUSERNAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[PERMALLUSERSSUBJECT] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[CREATOR] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[CREATIONDATE] [datetime] NULL,
[LASTMODIFIER] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[LASTMODDATE] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SPACEPERMISSIONS] ADD CONSTRAINT [PK__SPACEPER__507D17721E7AE489] PRIMARY KEY CLUSTERED  ([PERMID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [sp_creator_idx] ON [dbo].[SPACEPERMISSIONS] ([CREATOR]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [sp_lastmodifier_idx] ON [dbo].[SPACEPERMISSIONS] ([LASTMODIFIER]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [sp_pgname_idx] ON [dbo].[SPACEPERMISSIONS] ([PERMGROUPNAME]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [sp_permtype_idx] ON [dbo].[SPACEPERMISSIONS] ([PERMTYPE]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [sp_comp_idx] ON [dbo].[SPACEPERMISSIONS] ([PERMTYPE], [PERMGROUPNAME]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [sp_puname_idx] ON [dbo].[SPACEPERMISSIONS] ([PERMUSERNAME]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [sp_spaceid_idx] ON [dbo].[SPACEPERMISSIONS] ([SPACEID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SPACEPERMISSIONS] ADD CONSTRAINT [FK_SPACEPERMISSIONS_CREATOR] FOREIGN KEY ([CREATOR]) REFERENCES [dbo].[user_mapping] ([user_key])
GO
ALTER TABLE [dbo].[SPACEPERMISSIONS] ADD CONSTRAINT [FK_SPACEPERMISSIONS_LASTMODIFI] FOREIGN KEY ([LASTMODIFIER]) REFERENCES [dbo].[user_mapping] ([user_key])
GO
ALTER TABLE [dbo].[SPACEPERMISSIONS] ADD CONSTRAINT [FK_SPACEPERMISSIONS_PERMUSERNA] FOREIGN KEY ([PERMUSERNAME]) REFERENCES [dbo].[user_mapping] ([user_key])
GO
ALTER TABLE [dbo].[SPACEPERMISSIONS] ADD CONSTRAINT [FKD33F23BEB2DC6081] FOREIGN KEY ([SPACEID]) REFERENCES [dbo].[SPACES] ([SPACEID])
GO
