CREATE TABLE [dbo].[AO_88263F_HEALTH_CHECK_STATUS]
(
[APPLICATION_NAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[COMPLETE_KEY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[DESCRIPTION] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[FAILED_DATE] [datetime] NULL,
[FAILURE_REASON] [nvarchar] (450) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[ID] [int] NOT NULL IDENTITY(1, 1),
[IS_HEALTHY] [bit] NULL,
[IS_RESOLVED] [bit] NULL,
[RESOLVED_DATE] [datetime] NULL,
[SEVERITY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[STATUS_NAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_88263F_HEALTH_CHECK_STATUS] ADD CONSTRAINT [pk_AO_88263F_HEALTH_CHECK_STATUS_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
