CREATE TABLE [dbo].[LABEL]
(
[LABELID] [numeric] (19, 0) NOT NULL,
[NAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[OWNER] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[NAMESPACE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[CREATIONDATE] [datetime] NULL,
[LASTMODDATE] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LABEL] ADD CONSTRAINT [PK__LABEL__5A29322BA805B0E0] PRIMARY KEY CLUSTERED  ([LABELID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [l_name_idx] ON [dbo].[LABEL] ([NAME]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [l_namespace_idx] ON [dbo].[LABEL] ([NAMESPACE]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [l_owner_idx] ON [dbo].[LABEL] ([OWNER]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LABEL] ADD CONSTRAINT [FK_LABEL_OWNER] FOREIGN KEY ([OWNER]) REFERENCES [dbo].[user_mapping] ([user_key])
GO
