CREATE TABLE [dbo].[AO_950DC3_TC_REMINDER_SETTINGS]
(
[CUSTOM_EVENT_TYPE_ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
[LAST_MODIFIER] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[PERIOD] [bigint] NULL,
[STORE_KEY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[SUB_CALENDAR_ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_950DC3_TC_REMINDER_SETTINGS] ADD CONSTRAINT [pk_AO_950DC3_TC_REMINDER_SETTINGS_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
