CREATE TABLE [dbo].[TRUSTEDAPP]
(
[TRUSTEDAPPID] [numeric] (19, 0) NOT NULL,
[NAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
[TIMEOUT] [int] NOT NULL,
[PUBLIC_KEY_ID] [numeric] (19, 0) NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TRUSTEDAPP] ADD CONSTRAINT [PK__TRUSTEDA__9860A76964F8AD12] PRIMARY KEY CLUSTERED  ([TRUSTEDAPPID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TRUSTEDAPP] ADD CONSTRAINT [UQ__TRUSTEDA__D9C1FA0026677172] UNIQUE NONCLUSTERED  ([NAME]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TRUSTEDAPP] ADD CONSTRAINT [UQ__TRUSTEDA__C12E55A374DA04FE] UNIQUE NONCLUSTERED  ([PUBLIC_KEY_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TRUSTEDAPP] ADD CONSTRAINT [FKDDB119CA9C85ADB1] FOREIGN KEY ([PUBLIC_KEY_ID]) REFERENCES [dbo].[KEYSTORE] ([KEYID])
GO
