CREATE TABLE [dbo].[DECORATOR]
(
[DECORATORID] [numeric] (19, 0) NOT NULL,
[SPACEKEY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[DECORATORNAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[BODY] [ntext] COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[LASTMODDATE] [datetime] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[DECORATOR] ADD CONSTRAINT [PK__DECORATO__EB1D158C3E106EA2] PRIMARY KEY CLUSTERED  ([DECORATORID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [dec_name_idx] ON [dbo].[DECORATOR] ([DECORATORNAME]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [dec_key_idx] ON [dbo].[DECORATOR] ([SPACEKEY]) ON [PRIMARY]
GO
