CREATE TABLE [dbo].[PLUGINDATA]
(
[PLUGINDATAID] [numeric] (19, 0) NOT NULL,
[PLUGINKEY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
[FILENAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
[LASTMODDATE] [datetime] NULL,
[DATA] [image] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[PLUGINDATA] ADD CONSTRAINT [PK__PLUGINDA__41D03A0F0F8619E0] PRIMARY KEY CLUSTERED  ([PLUGINDATAID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PLUGINDATA] ADD CONSTRAINT [UQ__PLUGINDA__A73D5C312D4C55F7] UNIQUE NONCLUSTERED  ([FILENAME]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PLUGINDATA] ADD CONSTRAINT [UQ__PLUGINDA__A9D8812DBA8BFE69] UNIQUE NONCLUSTERED  ([PLUGINKEY]) ON [PRIMARY]
GO
