CREATE TABLE [dbo].[SPACES]
(
[SPACEID] [numeric] (19, 0) NOT NULL,
[SPACENAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[SPACEKEY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
[LOWERSPACEKEY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[SPACEDESCID] [numeric] (19, 0) NULL,
[HOMEPAGE] [numeric] (19, 0) NULL,
[CREATOR] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[CREATIONDATE] [datetime] NULL,
[LASTMODIFIER] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[LASTMODDATE] [datetime] NULL,
[SPACETYPE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[SPACESTATUS] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SPACES] ADD CONSTRAINT [PK__SPACES__15F06AE9E85B6397] PRIMARY KEY CLUSTERED  ([SPACEID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [s_creationdate_idx] ON [dbo].[SPACES] ([CREATIONDATE]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [s_creator_idx] ON [dbo].[SPACES] ([CREATOR]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [s_homepage_idx] ON [dbo].[SPACES] ([HOMEPAGE]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [s_lastmodifier_idx] ON [dbo].[SPACES] ([LASTMODIFIER]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [s_lspacekey_idx] ON [dbo].[SPACES] ([LOWERSPACEKEY]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [s_spacedescid_idx] ON [dbo].[SPACES] ([SPACEDESCID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SPACES] ADD CONSTRAINT [UQ__SPACES__5D89918B5EFDF60B] UNIQUE NONCLUSTERED  ([SPACEKEY]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [s_spacestatus_idx] ON [dbo].[SPACES] ([SPACESTATUS]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SPACES] ADD CONSTRAINT [FK_SPACES_CREATOR] FOREIGN KEY ([CREATOR]) REFERENCES [dbo].[user_mapping] ([user_key])
GO
ALTER TABLE [dbo].[SPACES] ADD CONSTRAINT [FK_SPACES_LASTMODIFIER] FOREIGN KEY ([LASTMODIFIER]) REFERENCES [dbo].[user_mapping] ([user_key])
GO
ALTER TABLE [dbo].[SPACES] ADD CONSTRAINT [FK9228242D11B7BFEE] FOREIGN KEY ([HOMEPAGE]) REFERENCES [dbo].[CONTENT] ([CONTENTID])
GO
ALTER TABLE [dbo].[SPACES] ADD CONSTRAINT [FK9228242D2C72D3D2] FOREIGN KEY ([SPACEDESCID]) REFERENCES [dbo].[CONTENT] ([CONTENTID])
GO
