CREATE TABLE [dbo].[AO_88BB94_BATCH_NOTIFICATION]
(
[BATCHING_COLUMN] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
[CONTENT_TYPE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
[ID] [int] NOT NULL IDENTITY(1, 1),
[NOTIFICATION_KEY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
[PAYLOAD] [ntext] COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_88BB94_BATCH_NOTIFICATION] ADD CONSTRAINT [pk_AO_88BB94_BATCH_NOTIFICATION_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
