CREATE TABLE [dbo].[INDEXQUEUEENTRIES]
(
[ENTRYID] [numeric] (19, 0) NOT NULL,
[CREATIONDATE] [datetime] NULL,
[TYPE] [int] NULL,
[HANDLE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[INDEXQUEUEENTRIES] ADD CONSTRAINT [PK__INDEXQUE__83A4CBD379DE070D] PRIMARY KEY CLUSTERED  ([ENTRYID]) ON [PRIMARY]
GO
