CREATE TABLE [dbo].[CONTENT_PERM_SET]
(
[ID] [numeric] (19, 0) NOT NULL,
[CONT_PERM_TYPE] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
[CONTENT_ID] [numeric] (19, 0) NOT NULL,
[CREATIONDATE] [datetime] NULL,
[LASTMODDATE] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CONTENT_PERM_SET] ADD CONSTRAINT [PK__CONTENT___3214EC27E3E547C7] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [cps_permtype_idx] ON [dbo].[CONTENT_PERM_SET] ([CONT_PERM_TYPE]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [cps_content_idx] ON [dbo].[CONTENT_PERM_SET] ([CONTENT_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CONTENT_PERM_SET] ADD CONSTRAINT [cps_unique_type] UNIQUE NONCLUSTERED  ([CONTENT_ID], [CONT_PERM_TYPE]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CONTENT_PERM_SET] ADD CONSTRAINT [FKBF45A7992CAF22C1] FOREIGN KEY ([CONTENT_ID]) REFERENCES [dbo].[CONTENT] ([CONTENTID])
GO
