CREATE TABLE [dbo].[AO_88263F_PROPERTIES]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[PROPERTY_NAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
[PROPERTY_VALUE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_88263F_PROPERTIES] ADD CONSTRAINT [pk_AO_88263F_PROPERTIES_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
