CREATE TABLE [dbo].[AO_950DC3_TC_SUBCALS]
(
[COLOUR] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[CREATED] [bigint] NULL,
[CREATOR] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[DESCRIPTION] [ntext] COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
[NAME] [ntext] COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[PARENT_ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[SPACE_KEY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[STORE_KEY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[SUBSCRIPTION_ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[TIME_ZONE_ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[USING_CUSTOM_EVENT_TYPE_ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_950DC3_TC_SUBCALS] ADD CONSTRAINT [pk_AO_950DC3_TC_SUBCALS_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_950DC3_TC_SUBCALS] ADD CONSTRAINT [fk_ao_950dc3_tc_subcals_parent_id] FOREIGN KEY ([PARENT_ID]) REFERENCES [dbo].[AO_950DC3_TC_SUBCALS] ([ID])
GO
ALTER TABLE [dbo].[AO_950DC3_TC_SUBCALS] ADD CONSTRAINT [fk_ao_950dc3_tc_subcals_subscription_id] FOREIGN KEY ([SUBSCRIPTION_ID]) REFERENCES [dbo].[AO_950DC3_TC_SUBCALS] ([ID])
GO
