CREATE TABLE [dbo].[ATTACHMENTDATA]
(
[ATTACHMENTDATAID] [numeric] (19, 0) NOT NULL,
[HIBERNATEVERSION] [int] NOT NULL CONSTRAINT [DF__ATTACHMEN__HIBER__753864A1] DEFAULT ((0)),
[ATTVERSION] [int] NOT NULL,
[DATA] [image] NULL,
[ATTACHMENTID] [numeric] (19, 0) NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[ATTACHMENTDATA] ADD CONSTRAINT [PK__ATTACHME__0FF5FB0AE03BB5F6] PRIMARY KEY CLUSTERED  ([ATTACHMENTDATAID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ATTACHMENTDATA] ADD CONSTRAINT [UQ__ATTACHME__23CEF7B1F657F825] UNIQUE NONCLUSTERED  ([ATTACHMENTID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [attch_idver_idx] ON [dbo].[ATTACHMENTDATA] ([ATTVERSION], [ATTACHMENTID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ATTACHMENTDATA] ADD CONSTRAINT [FK9DC3E34D34A4917E] FOREIGN KEY ([ATTACHMENTID]) REFERENCES [dbo].[CONTENT] ([CONTENTID])
GO
