CREATE TABLE [dbo].[LIKES]
(
[ID] [numeric] (19, 0) NOT NULL,
[CONTENTID] [numeric] (19, 0) NOT NULL,
[USERNAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
[CREATIONDATE] [datetime] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LIKES] ADD CONSTRAINT [PK__LIKES__3214EC27EF8028C7] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [like_cid_idx] ON [dbo].[LIKES] ([CONTENTID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [like_cdate_idx] ON [dbo].[LIKES] ([CREATIONDATE]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [like_username_idx] ON [dbo].[LIKES] ([USERNAME]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LIKES] ADD CONSTRAINT [FK_LIKES_USERNAME] FOREIGN KEY ([USERNAME]) REFERENCES [dbo].[user_mapping] ([user_key])
GO
ALTER TABLE [dbo].[LIKES] ADD CONSTRAINT [FK4514B9C8DD41734] FOREIGN KEY ([CONTENTID]) REFERENCES [dbo].[CONTENT] ([CONTENTID])
GO
