CREATE TABLE [dbo].[AO_7CDE43_NOTIFICATION_SCHEME]
(
[DESCRIPTION] [ntext] COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[ID] [int] NOT NULL IDENTITY(1, 1),
[SCHEME_NAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_7CDE43_NOTIFICATION_SCHEME] ADD CONSTRAINT [pk_AO_7CDE43_NOTIFICATION_SCHEME_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
