CREATE TABLE [dbo].[AO_7CDE43_SERVER_CONFIG]
(
[CUSTOM_TEMPLATE_PATH] [ntext] COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[DEFAULT_USER_ID_TEMPLATE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[ENABLED_FOR_ALL_USERS] [bit] NULL,
[GROUPS_WITH_ACCESS] [ntext] COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[ID] [int] NOT NULL IDENTITY(1, 1),
[NOTIFICATION_MEDIUM_KEY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[SERVER_NAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_7CDE43_SERVER_CONFIG] ADD CONSTRAINT [pk_AO_7CDE43_SERVER_CONFIG_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
