CREATE TABLE [dbo].[TRACKBACKLINKS]
(
[LINKID] [numeric] (19, 0) NOT NULL,
[CONTENTTYPE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
[VIEWCOUNT] [int] NOT NULL,
[URL] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
[LOWERURL] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
[TITLE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[BLOGNAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[EXCERPT] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[CONTENTID] [numeric] (19, 0) NOT NULL,
[CREATOR] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[CREATIONDATE] [datetime] NULL,
[LASTMODIFIER] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[LASTMODDATE] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TRACKBACKLINKS] ADD CONSTRAINT [PK__TRACKBAC__04E1D4C782BE34C4] PRIMARY KEY CLUSTERED  ([LINKID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [tbl_contentid_idx] ON [dbo].[TRACKBACKLINKS] ([CONTENTID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [tbl_creator_idx] ON [dbo].[TRACKBACKLINKS] ([CREATOR]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [tbl_lastmodifier_idx] ON [dbo].[TRACKBACKLINKS] ([LASTMODIFIER]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TRACKBACKLINKS] ADD CONSTRAINT [FK_TRACKBACKLINKS_CREATOR] FOREIGN KEY ([CREATOR]) REFERENCES [dbo].[user_mapping] ([user_key])
GO
ALTER TABLE [dbo].[TRACKBACKLINKS] ADD CONSTRAINT [FK_TRACKBACKLINKS_LASTMODIFIER] FOREIGN KEY ([LASTMODIFIER]) REFERENCES [dbo].[user_mapping] ([user_key])
GO
ALTER TABLE [dbo].[TRACKBACKLINKS] ADD CONSTRAINT [FKF6977A478DD41734] FOREIGN KEY ([CONTENTID]) REFERENCES [dbo].[CONTENT] ([CONTENTID])
GO
