CREATE TABLE [dbo].[AO_BAF3AA_AOINLINE_TASK]
(
[ASSIGNEE_USER_KEY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[BODY] [ntext] COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[COMPLETE_DATE] [datetime] NULL,
[COMPLETE_USER_KEY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[CONTENT_ID] [bigint] NULL CONSTRAINT [df_AO_BAF3AA_AOINLINE_TASK_CONTENT_ID] DEFAULT ((0)),
[CREATE_DATE] [datetime] NULL,
[CREATOR_USER_KEY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[DUE_DATE] [datetime] NULL,
[GLOBAL_ID] [bigint] NOT NULL IDENTITY(1, 1),
[ID] [bigint] NULL CONSTRAINT [df_AO_BAF3AA_AOINLINE_TASK_ID] DEFAULT ((0)),
[TASK_STATUS] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[UPDATE_DATE] [datetime] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_BAF3AA_AOINLINE_TASK] ADD CONSTRAINT [pk_AO_BAF3AA_AOINLINE_TASK_GLOBAL_ID] PRIMARY KEY CLUSTERED  ([GLOBAL_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_baf3aa_aoi866493194] ON [dbo].[AO_BAF3AA_AOINLINE_TASK] ([ASSIGNEE_USER_KEY]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_baf3aa_aoi1066945234] ON [dbo].[AO_BAF3AA_AOINLINE_TASK] ([CONTENT_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_baf3aa_aoi1389674752] ON [dbo].[AO_BAF3AA_AOINLINE_TASK] ([CREATE_DATE]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_baf3aa_aoi1395974671] ON [dbo].[AO_BAF3AA_AOINLINE_TASK] ([CREATOR_USER_KEY]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_baf3aa_aoi1978441610] ON [dbo].[AO_BAF3AA_AOINLINE_TASK] ([DUE_DATE]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_baf3aa_aoi1143751131] ON [dbo].[AO_BAF3AA_AOINLINE_TASK] ([TASK_STATUS]) ON [PRIMARY]
GO
