CREATE TABLE [dbo].[AO_7CDE43_SERVER_PARAM]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[PARAM_KEY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[PARAM_VALUE] [ntext] COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[SERVER_CONFIG_ID] [int] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_7CDE43_SERVER_PARAM] ADD CONSTRAINT [pk_AO_7CDE43_SERVER_PARAM_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_7cde43_ser828034299] ON [dbo].[AO_7CDE43_SERVER_PARAM] ([SERVER_CONFIG_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_7CDE43_SERVER_PARAM] ADD CONSTRAINT [fk_ao_7cde43_server_param_server_config_id] FOREIGN KEY ([SERVER_CONFIG_ID]) REFERENCES [dbo].[AO_7CDE43_SERVER_CONFIG] ([ID])
GO
