CREATE TABLE [dbo].[AO_6384AB_FEATURE_METADATA_AO]
(
[CONTEXT] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[ID] [int] NOT NULL IDENTITY(1, 1),
[INSTALLATION_DATE] [datetime] NULL,
[KEY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_6384AB_FEATURE_METADATA_AO] ADD CONSTRAINT [pk_AO_6384AB_FEATURE_METADATA_AO_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
