CREATE TABLE [dbo].[FOLLOW_CONNECTIONS]
(
[CONNECTIONID] [numeric] (19, 0) NOT NULL,
[FOLLOWER] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[FOLLOWEE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[FOLLOW_CONNECTIONS] ADD CONSTRAINT [PK__FOLLOW_C__D4A5C81262B534CE] PRIMARY KEY CLUSTERED  ([CONNECTIONID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [cn_followee_idx] ON [dbo].[FOLLOW_CONNECTIONS] ([FOLLOWEE]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [cn_follower_idx] ON [dbo].[FOLLOW_CONNECTIONS] ([FOLLOWER]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[FOLLOW_CONNECTIONS] ADD CONSTRAINT [FK_FOLLOW_CONNECTIONS_FOLLOWEE] FOREIGN KEY ([FOLLOWEE]) REFERENCES [dbo].[user_mapping] ([user_key])
GO
ALTER TABLE [dbo].[FOLLOW_CONNECTIONS] ADD CONSTRAINT [FK_FOLLOW_CONNECTIONS_FOLLOWER] FOREIGN KEY ([FOLLOWER]) REFERENCES [dbo].[user_mapping] ([user_key])
GO
