CREATE TABLE [dbo].[AO_54C900_C_TEMPLATE_REF]
(
[CB_INDEX_PARENTID] [int] NULL,
[CB_PARENTID] [int] NULL,
[ID] [int] NOT NULL IDENTITY(1, 1),
[NAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[PARENT_ID] [int] NULL,
[PLUGIN_CLONE] [bit] NULL,
[PLUGIN_MODULE_KEY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[TEMPLATE_ID] [bigint] NULL CONSTRAINT [df_AO_54C900_C_TEMPLATE_REF_TEMPLATE_ID] DEFAULT ((0)),
[UUID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_54C900_C_TEMPLATE_REF] ADD CONSTRAINT [pk_AO_54C900_C_TEMPLATE_REF_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_54c900_c_t667820477] ON [dbo].[AO_54C900_C_TEMPLATE_REF] ([CB_INDEX_PARENTID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_54c900_c_t757546442] ON [dbo].[AO_54C900_C_TEMPLATE_REF] ([CB_PARENTID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_54c900_c_t852152353] ON [dbo].[AO_54C900_C_TEMPLATE_REF] ([PARENT_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_54C900_C_TEMPLATE_REF] ADD CONSTRAINT [fk_ao_54c900_c_template_ref_cb_index_parentid] FOREIGN KEY ([CB_INDEX_PARENTID]) REFERENCES [dbo].[AO_54C900_CONTENT_BLUEPRINT_AO] ([ID])
GO
ALTER TABLE [dbo].[AO_54C900_C_TEMPLATE_REF] ADD CONSTRAINT [fk_ao_54c900_c_template_ref_cb_parentid] FOREIGN KEY ([CB_PARENTID]) REFERENCES [dbo].[AO_54C900_CONTENT_BLUEPRINT_AO] ([ID])
GO
ALTER TABLE [dbo].[AO_54C900_C_TEMPLATE_REF] ADD CONSTRAINT [fk_ao_54c900_c_template_ref_parent_id] FOREIGN KEY ([PARENT_ID]) REFERENCES [dbo].[AO_54C900_C_TEMPLATE_REF] ([ID])
GO
