CREATE TABLE [dbo].[AO_187CCC_SIDEBAR_LINK]
(
[CATEGORY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[CUSTOM_ICON_CLASS] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[CUSTOM_TITLE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[DEST_PAGE_ID] [bigint] NULL CONSTRAINT [df_AO_187CCC_SIDEBAR_LINK_DEST_PAGE_ID] DEFAULT ((0)),
[HARDCODED_URL] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[HIDDEN] [bit] NULL,
[ID] [int] NOT NULL IDENTITY(1, 1),
[POSITION] [int] NULL CONSTRAINT [df_AO_187CCC_SIDEBAR_LINK_POSITION] DEFAULT ((0)),
[SPACE_KEY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[TYPE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[WEB_ITEM_KEY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_187CCC_SIDEBAR_LINK] ADD CONSTRAINT [pk_AO_187CCC_SIDEBAR_LINK_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
