CREATE TABLE [dbo].[CONTENT_RELATION]
(
[RELATIONID] [numeric] (19, 0) NOT NULL,
[TARGETCONTENTID] [numeric] (19, 0) NOT NULL,
[SOURCECONTENTID] [numeric] (19, 0) NOT NULL,
[TARGETTYPE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
[SOURCETYPE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
[RELATIONNAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
[CREATIONDATE] [datetime] NOT NULL,
[LASTMODDATE] [datetime] NOT NULL,
[CREATOR] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
[LASTMODIFIER] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CONTENT_RELATION] ADD CONSTRAINT [PK__CONTENT___E909023E3BC69C8D] PRIMARY KEY CLUSTERED  ([RELATIONID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [relation_c2c_cdate_idx] ON [dbo].[CONTENT_RELATION] ([CREATIONDATE]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [r_c2c_creator_idx] ON [dbo].[CONTENT_RELATION] ([CREATOR]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [r_c2c_lastmodifier_idx] ON [dbo].[CONTENT_RELATION] ([LASTMODIFIER]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [relation_c2c_relationname_idx] ON [dbo].[CONTENT_RELATION] ([RELATIONNAME]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [relation_c2c_sourcecontent_idx] ON [dbo].[CONTENT_RELATION] ([SOURCECONTENTID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [relation_c2c_sourcetype_idx] ON [dbo].[CONTENT_RELATION] ([SOURCETYPE]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [relation_c2c_targetcontent_idx] ON [dbo].[CONTENT_RELATION] ([TARGETCONTENTID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CONTENT_RELATION] ADD CONSTRAINT [c2c_relation_unique] UNIQUE NONCLUSTERED  ([TARGETCONTENTID], [SOURCECONTENTID], [RELATIONNAME]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [relation_c2c_targettype_idx] ON [dbo].[CONTENT_RELATION] ([TARGETTYPE]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CONTENT_RELATION] ADD CONSTRAINT [FK_C2CRELATION_CREATOR] FOREIGN KEY ([CREATOR]) REFERENCES [dbo].[user_mapping] ([user_key])
GO
ALTER TABLE [dbo].[CONTENT_RELATION] ADD CONSTRAINT [FK_C2CRELATION_LASTMODIFIER] FOREIGN KEY ([LASTMODIFIER]) REFERENCES [dbo].[user_mapping] ([user_key])
GO
ALTER TABLE [dbo].[CONTENT_RELATION] ADD CONSTRAINT [FK841CAF22351D64C3] FOREIGN KEY ([TARGETCONTENTID]) REFERENCES [dbo].[CONTENT] ([CONTENTID])
GO
ALTER TABLE [dbo].[CONTENT_RELATION] ADD CONSTRAINT [FK841CAF22DB772979] FOREIGN KEY ([SOURCECONTENTID]) REFERENCES [dbo].[CONTENT] ([CONTENTID])
GO
