CREATE TABLE [dbo].[CONTENT_PERM]
(
[ID] [numeric] (19, 0) NOT NULL,
[CP_TYPE] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
[USERNAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[GROUPNAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[CPS_ID] [numeric] (19, 0) NOT NULL,
[CREATOR] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[CREATIONDATE] [datetime] NULL,
[LASTMODIFIER] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[LASTMODDATE] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CONTENT_PERM] ADD CONSTRAINT [PK__CONTENT___3214EC27B6EC3492] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [cp_os_idx] ON [dbo].[CONTENT_PERM] ([CPS_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CONTENT_PERM] ADD CONSTRAINT [cp_unique_user_groups] UNIQUE NONCLUSTERED  ([CPS_ID], [CP_TYPE], [USERNAME], [GROUPNAME]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [cp_creator_idx] ON [dbo].[CONTENT_PERM] ([CREATOR]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [cp_gn_idx] ON [dbo].[CONTENT_PERM] ([GROUPNAME]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [cp_lastmodifier_idx] ON [dbo].[CONTENT_PERM] ([LASTMODIFIER]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [cp_un_idx] ON [dbo].[CONTENT_PERM] ([USERNAME]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CONTENT_PERM] ADD CONSTRAINT [FK_CONTENT_PERM_CREATOR] FOREIGN KEY ([CREATOR]) REFERENCES [dbo].[user_mapping] ([user_key])
GO
ALTER TABLE [dbo].[CONTENT_PERM] ADD CONSTRAINT [FK_CONTENT_PERM_LASTMODIFIER] FOREIGN KEY ([LASTMODIFIER]) REFERENCES [dbo].[user_mapping] ([user_key])
GO
ALTER TABLE [dbo].[CONTENT_PERM] ADD CONSTRAINT [FK_CONTENT_PERM_USERNAME] FOREIGN KEY ([USERNAME]) REFERENCES [dbo].[user_mapping] ([user_key])
GO
ALTER TABLE [dbo].[CONTENT_PERM] ADD CONSTRAINT [FKBD74B31676E33274] FOREIGN KEY ([CPS_ID]) REFERENCES [dbo].[CONTENT_PERM_SET] ([ID])
GO
