CREATE TABLE [dbo].[AO_A0B856_WEB_HOOK_LISTENER_AO]
(
[ENABLED] [bit] NULL,
[EVENTS] [ntext] COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[ID] [int] NOT NULL IDENTITY(1, 1),
[LAST_UPDATED] [datetime] NOT NULL,
[LAST_UPDATED_USER] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[NAME] [ntext] COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
[PARAMETERS] [ntext] COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[REGISTRATION_METHOD] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
[URL] [ntext] COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
[DESCRIPTION] [ntext] COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[EXCLUDE_BODY] [bit] NULL,
[FILTERS] [ntext] COLLATE SQL_Latin1_General_CP1_CS_AS NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_A0B856_WEB_HOOK_LISTENER_AO] ADD CONSTRAINT [pk_AO_A0B856_WEB_HOOK_LISTENER_AO_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
