CREATE TABLE [dbo].[AO_9412A1_AONOTIFICATION]
(
[ACTION] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[ACTION_ICON_URL] [ntext] COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[APPLICATION] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[APPLICATION_LINK_ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[CREATED] [datetime] NULL,
[DESCRIPTION] [ntext] COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[ENTITY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[GLOBAL_ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[GROUPING_ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[ICON_URL] [ntext] COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[ID] [bigint] NOT NULL IDENTITY(1, 1),
[ITEM_ICON_URL] [ntext] COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[ITEM_TITLE] [ntext] COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[ITEM_URL] [ntext] COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[METADATA] [ntext] COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[PINNED] [bit] NULL CONSTRAINT [df_AO_9412A1_AONOTIFICATION_PINNED] DEFAULT ((0)),
[READ] [bit] NULL CONSTRAINT [df_AO_9412A1_AONOTIFICATION_READ] DEFAULT ((0)),
[STATUS] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[TITLE] [ntext] COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[UPDATED] [datetime] NULL,
[URL] [ntext] COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[USER] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_9412A1_AONOTIFICATION] ADD CONSTRAINT [pk_AO_9412A1_AONOTIFICATION_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_9412a1_aon1547032463] ON [dbo].[AO_9412A1_AONOTIFICATION] ([CREATED]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_9412a1_aon849931648] ON [dbo].[AO_9412A1_AONOTIFICATION] ([GLOBAL_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_9412a1_aon648423710] ON [dbo].[AO_9412A1_AONOTIFICATION] ([USER]) ON [PRIMARY]
GO
