CREATE TABLE [dbo].[AO_950DC3_TC_CUSTOM_EV_TYPES]
(
[BELONG_SUB_CALENDAR_ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[CREATED] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[ICON] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
[TITLE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_950DC3_TC_CUSTOM_EV_TYPES] ADD CONSTRAINT [pk_AO_950DC3_TC_CUSTOM_EV_TYPES_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_950DC3_TC_CUSTOM_EV_TYPES] ADD CONSTRAINT [fk_ao_950dc3_tc_custom_ev_types_belong_sub_calendar_id] FOREIGN KEY ([BELONG_SUB_CALENDAR_ID]) REFERENCES [dbo].[AO_950DC3_TC_SUBCALS] ([ID])
GO
