CREATE TABLE [dbo].[AO_950DC3_TC_SUBCALS_PROPS]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[KEY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[SUB_CALENDAR_ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[VALUE] [ntext] COLLATE SQL_Latin1_General_CP1_CS_AS NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_950DC3_TC_SUBCALS_PROPS] ADD CONSTRAINT [pk_AO_950DC3_TC_SUBCALS_PROPS_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_950DC3_TC_SUBCALS_PROPS] ADD CONSTRAINT [fk_ao_950dc3_tc_subcals_props_sub_calendar_id] FOREIGN KEY ([SUB_CALENDAR_ID]) REFERENCES [dbo].[AO_950DC3_TC_SUBCALS] ([ID])
GO
