CREATE TABLE [dbo].[AO_9412A1_AOREGISTRATION]
(
[DATA] [ntext] COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
[UPDATED] [datetime] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_9412A1_AOREGISTRATION] ADD CONSTRAINT [pk_AO_9412A1_AOREGISTRATION_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
