CREATE TABLE [dbo].[AO_7CDE43_NOTIFICATION]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[NOTIFICATION_SCHEME_ID] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_7CDE43_NOTIFICATION] ADD CONSTRAINT [pk_AO_7CDE43_NOTIFICATION_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_7cde43_not7362182] ON [dbo].[AO_7CDE43_NOTIFICATION] ([NOTIFICATION_SCHEME_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_7CDE43_NOTIFICATION] ADD CONSTRAINT [fk_ao_7cde43_notification_notification_scheme_id] FOREIGN KEY ([NOTIFICATION_SCHEME_ID]) REFERENCES [dbo].[AO_7CDE43_NOTIFICATION_SCHEME] ([ID])
GO
