CREATE TABLE [dbo].[AO_5F3884_FEATURE_DISCOVERY]
(
[DISCOVERED] [bit] NULL,
[ID] [int] NOT NULL IDENTITY(1, 1),
[USER_KEY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_5F3884_FEATURE_DISCOVERY] ADD CONSTRAINT [pk_AO_5F3884_FEATURE_DISCOVERY_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
