CREATE TABLE [dbo].[AO_26DB7F_ENTITIES_TO_ROOMS]
(
[ENTITY_KEY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[ID] [int] NOT NULL IDENTITY(1, 1),
[MESSAGE_TYPE_KEY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[ROOM_ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_26DB7F_ENTITIES_TO_ROOMS] ADD CONSTRAINT [pk_AO_26DB7F_ENTITIES_TO_ROOMS_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_26db7f_ent940053222] ON [dbo].[AO_26DB7F_ENTITIES_TO_ROOMS] ([ENTITY_KEY]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_26db7f_ent831223480] ON [dbo].[AO_26DB7F_ENTITIES_TO_ROOMS] ([ROOM_ID]) ON [PRIMARY]
GO
