CREATE TABLE [dbo].[CONFVERSION]
(
[CONFVERSIONID] [numeric] (19, 0) NOT NULL,
[BUILDNUMBER] [int] NOT NULL,
[INSTALLDATE] [datetime] NULL,
[VERSIONTAG] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[CREATIONDATE] [datetime] NULL,
[LASTMODDATE] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CONFVERSION] ADD CONSTRAINT [PK__CONFVERS__CDF3B209BF3EF7CC] PRIMARY KEY CLUSTERED  ([CONFVERSIONID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CONFVERSION] ADD CONSTRAINT [UQ__CONFVERS__7F4CBDDEAD7E7CBE] UNIQUE NONCLUSTERED  ([BUILDNUMBER]) ON [PRIMARY]
GO
