CREATE TABLE [dbo].[AO_7CDE43_EVENT]
(
[EVENT_KEY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[ID] [int] NOT NULL IDENTITY(1, 1),
[NOTIFICATION_ID] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_7CDE43_EVENT] ADD CONSTRAINT [pk_AO_7CDE43_EVENT_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_7cde43_eve1433596955] ON [dbo].[AO_7CDE43_EVENT] ([NOTIFICATION_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_7CDE43_EVENT] ADD CONSTRAINT [fk_ao_7cde43_event_notification_id] FOREIGN KEY ([NOTIFICATION_ID]) REFERENCES [dbo].[AO_7CDE43_NOTIFICATION] ([ID])
GO
