CREATE TABLE [dbo].[KEYSTORE]
(
[KEYID] [numeric] (19, 0) NOT NULL,
[ALIAS] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
[TYPE] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
[ALGORITHM] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
[KEYSPEC] [ntext] COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[KEYSTORE] ADD CONSTRAINT [PK__KEYSTORE__28BF303AC1515F08] PRIMARY KEY CLUSTERED  ([KEYID]) ON [PRIMARY]
GO
