CREATE TABLE [dbo].[TRUSTEDAPPRESTRICTION]
(
[TRUSTEDAPPRESTRICTIONID] [numeric] (19, 0) NOT NULL,
[TYPE] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
[restriction] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[TRUSTEDAPPID] [numeric] (19, 0) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TRUSTEDAPPRESTRICTION] ADD CONSTRAINT [PK__TRUSTEDA__0E0038A94F9AF4B7] PRIMARY KEY CLUSTERED  ([TRUSTEDAPPRESTRICTIONID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [c_trustedappid_idx] ON [dbo].[TRUSTEDAPPRESTRICTION] ([TRUSTEDAPPID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TRUSTEDAPPRESTRICTION] ADD CONSTRAINT [FKE8496BA235D1D865] FOREIGN KEY ([TRUSTEDAPPID]) REFERENCES [dbo].[TRUSTEDAPP] ([TRUSTEDAPPID])
GO
