CREATE TABLE [dbo].[AO_5FB9D7_AOHIP_CHAT_USER]
(
[HIP_CHAT_LINK_ID] [int] NULL,
[HIP_CHAT_USER_ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[HIP_CHAT_USER_NAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[ID] [int] NOT NULL IDENTITY(1, 1),
[REFRESH_CODE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[USER_KEY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[USER_SCOPES] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[USER_TOKEN] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[USER_TOKEN_EXPIRY] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_5FB9D7_AOHIP_CHAT_USER] ADD CONSTRAINT [pk_AO_5FB9D7_AOHIP_CHAT_USER_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_5fb9d7_aoh49772492] ON [dbo].[AO_5FB9D7_AOHIP_CHAT_USER] ([HIP_CHAT_LINK_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_5fb9d7_aoh1981563178] ON [dbo].[AO_5FB9D7_AOHIP_CHAT_USER] ([USER_KEY]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_5FB9D7_AOHIP_CHAT_USER] ADD CONSTRAINT [fk_ao_5fb9d7_aohip_chat_user_hip_chat_link_id] FOREIGN KEY ([HIP_CHAT_LINK_ID]) REFERENCES [dbo].[AO_5FB9D7_AOHIP_CHAT_LINK] ([ID])
GO
