CREATE TABLE [dbo].[AO_6384AB_DISCOVERED]
(
[DATE] [datetime] NULL,
[ID] [int] NOT NULL IDENTITY(1, 1),
[KEY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[PLUGIN_KEY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[USER_KEY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_6384AB_DISCOVERED] ADD CONSTRAINT [pk_AO_6384AB_DISCOVERED_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
