CREATE TABLE [dbo].[AUDIT_AFFECTED_OBJECT]
(
[ID] [numeric] (19, 0) NOT NULL,
[NAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[TYPE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[AUDITRECORDID] [numeric] (19, 0) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AUDIT_AFFECTED_OBJECT] ADD CONSTRAINT [PK__AUDIT_AF__3214EC2767227A17] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [a_objects_parent_index] ON [dbo].[AUDIT_AFFECTED_OBJECT] ([AUDITRECORDID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AUDIT_AFFECTED_OBJECT] ADD CONSTRAINT [FK_AFFECTED_OBJECT_RECORD] FOREIGN KEY ([AUDITRECORDID]) REFERENCES [dbo].[AUDITRECORD] ([AUDITRECORDID])
GO
