CREATE TABLE [Internal].[EntityEnrollment]
(
[ActualBeginDate] [datetime] NULL,
[ActualBeginGap] [smallint] NULL,
[ActualBeginGapDays] [smallint] NULL,
[ActualEndDate] [datetime] NULL,
[ActualEndGap] [smallint] NULL,
[ActualEndGapDays] [smallint] NULL,
[ActualEnrollGroupID] [int] NULL,
[ActualFirstRow] [bit] NOT NULL CONSTRAINT [DF_EntityEnrollment_ActualFirstRow] DEFAULT ((0)),
[ActualGapDays] [smallint] NULL,
[ActualGapMaxDays] [smallint] NULL,
[ActualGaps] [smallint] NULL,
[ActualHasAnchor] [tinyint] NOT NULL CONSTRAINT [DF_EntityEnrollment_ActualHasAnchor] DEFAULT ((0)),
[ActualHasPayer] [tinyint] NOT NULL CONSTRAINT [DF_EntityEnrollment_ActualHasPayer] DEFAULT ((0)),
[ActualLastRow] [bit] NOT NULL CONSTRAINT [DF_EntityEnrollment_ActualLastRow] DEFAULT ((0)),
[AdminGapDays] [smallint] NOT NULL,
[AdminGaps] [smallint] NOT NULL,
[AnchorDate] [datetime] NULL,
[BatchID] [int] NOT NULL,
[BeginDate] [datetime] NOT NULL,
[BeginDOBDate] [datetime] NULL,
[BeginEnrollDate] [datetime] NULL,
[BenefitID] [smallint] NOT NULL,
[BitBenefits] [bigint] NOT NULL CONSTRAINT [DF_EntityEnrollment_BitBenefits] DEFAULT ((0)),
[BitProductLines] [bigint] NOT NULL CONSTRAINT [DF_EntityEnrollment_BitProductLines] DEFAULT ((0)),
[DataRunID] [int] NOT NULL,
[DataSetID] [int] NOT NULL,
[DSMemberID] [bigint] NOT NULL,
[EndDate] [datetime] NULL,
[EndDOBDate] [datetime] NULL,
[EndEnrollDate] [datetime] NULL,
[EnrollGroupID] [int] NOT NULL,
[EnrollItemID] [bigint] NOT NULL,
[EnrollSegBeginDate] [datetime] NOT NULL,
[EnrollSegEndDate] [datetime] NULL,
[EntityBaseID] [bigint] NOT NULL,
[EntityEnrollID] [bigint] NOT NULL IDENTITY(1, 1),
[EntityEnrollSetID] [bigint] NULL,
[EntityEnrollSetLineID] [bigint] NULL,
[EntityID] [int] NOT NULL,
[GapDays] [smallint] NOT NULL,
[Gaps] [smallint] NOT NULL,
[Gender] [tinyint] NULL,
[LastSegBeginDate] [datetime] NULL,
[LastSegEndDate] [datetime] NULL,
[MeasEnrollID] [int] NOT NULL,
[OptionNbr] [tinyint] NOT NULL,
[PayerDate] [datetime] NULL,
[ProductClassID] [tinyint] NOT NULL,
[SpId] [int] NOT NULL CONSTRAINT [DF_EntityEnrollment_SpId] DEFAULT (@@spid)
) ON [PRIMARY]
GO
ALTER TABLE [Internal].[EntityEnrollment] ADD CONSTRAINT [PK_EntityEnrollment] PRIMARY KEY NONCLUSTERED  ([EntityEnrollID]) ON [PRIMARY]
GO
CREATE UNIQUE CLUSTERED INDEX [IX_EntityEnrollment] ON [Internal].[EntityEnrollment] ([SpId], [EntityEnrollID]) ON [PRIMARY]
GO
