SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

-- =============================================
-- Author:		Travis Parker
-- Create date:	08/18/2016
-- Description:	Updates the reference keys in the HEDIS staging table
-- =============================================
CREATE PROCEDURE [dbo].[spUpdateHEDISReferenceKeys]
AS
    BEGIN
	


        SET NOCOUNT ON;


        UPDATE  i
        SET     CentauriMemberID = m.CentauriMemberID ,
                CentauriProviderID = p.CentauriProviderID ,
                CentauriNetworkID = n.CentauriNetworkID ,
                HEDIS_BK = CONCAT(RTRIM(LTRIM(COALESCE(i.RecordSource, ''))), ':', RTRIM(LTRIM(COALESCE(i.[PRODUCT_ROLLUP_ID], ''))), ':', RTRIM(LTRIM(COALESCE(i.[MEM_NBR], '')))) ,
                H_HEDIS_RK = UPPER(CONVERT(CHAR(32), HASHBYTES('MD5', UPPER(CONCAT(RTRIM(LTRIM(COALESCE(i.RecordSource, ''))), ':', RTRIM(LTRIM(COALESCE(i.[PRODUCT_ROLLUP_ID], ''))), ':', RTRIM(LTRIM(COALESCE(i.[MEM_NBR], '')))))), 2)) ,
                H_Provider_RK = UPPER(CONVERT( CHAR(32), HASHBYTES('MD5', UPPER(RTRIM(LTRIM(COALESCE(p.CentauriProviderID, ''))))), 2)),
			 H_Network_RK = UPPER(CONVERT( CHAR(32), HASHBYTES('MD5', UPPER(RTRIM(LTRIM(COALESCE(n.CentauriNetworkID, ''))))), 2)),
			 H_Member_RK = UPPER(CONVERT( CHAR(32), HASHBYTES('MD5', UPPER(RTRIM(LTRIM(COALESCE(m.CentauriMemberID, ''))))), 2)),
			 L_ProviderNetwork_RK = UPPER(CONVERT( CHAR(32), HASHBYTES('MD5', UPPER(CONCAT(RTRIM(LTRIM(COALESCE(p.CentauriProviderID, ''))), ':', RTRIM(LTRIM(COALESCE(n.CentauriNetworkID, '')))))), 2)),
			 L_ProviderHEDIS_RK = UPPER(CONVERT(CHAR(32), HASHBYTES('MD5', UPPER(CONCAT(RTRIM(LTRIM(COALESCE(p.CentauriProviderID, ''))), ':', RTRIM(LTRIM(COALESCE(i.RecordSource, ''))), ':', RTRIM(LTRIM(COALESCE(i.[PRODUCT_ROLLUP_ID], ''))), ':', RTRIM(LTRIM(COALESCE(i.[MEM_NBR], '')))))), 2)) ,
			 L_MemberProvider_RK = UPPER(CONVERT( CHAR(32), HASHBYTES('MD5', UPPER(CONCAT(RTRIM(LTRIM(COALESCE(m.CentauriMemberID, ''))), ':', RTRIM(LTRIM(COALESCE(p.CentauriProviderID, '')))))), 2)),
			 L_MemberHEDIS_RK = UPPER(CONVERT(CHAR(32), HASHBYTES('MD5', UPPER(CONCAT(RTRIM(LTRIM(COALESCE(m.CentauriMemberID, ''))), ':', RTRIM(LTRIM(COALESCE(i.RecordSource, ''))), ':', RTRIM(LTRIM(COALESCE(i.[PRODUCT_ROLLUP_ID], ''))), ':', RTRIM(LTRIM(COALESCE(i.[MEM_NBR], '')))))), 2)) ,
			 S_HEDISDetail_RK = UPPER(CONVERT(CHAR(32), HASHBYTES('MD5',UPPER(RTRIM(LTRIM(COALESCE(i.RecordSource,''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.LoadDate,''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[PRODUCT_ROLLUP_ID],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[MEM_NBR],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[MMS_MED],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[MMS_RX],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[MMS_MH_INP],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[MMS_MH_INT],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[MMS_MH_AMB],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[MMS_CD_INP],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[MMS_CD_INT],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[MMS_CD_AMB],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[MMS_DENT],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[AAP_DEN1],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[AAP_DEN2],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[AAP_DEN3],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[AAP_NUM1],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[AAP_NUM2],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[AAP_NUM3],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CAP_DEN1],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CAP_DEN2],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CAP_DEN3],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CAP_DEN4],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CAP_NUM1],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CAP_NUM2],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CAP_NUM3],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CAP_NUM4],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[PPC_DEN],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[PPC_NUM1],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[PPC_NUM2],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[ADV_DEN1],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[ADV_DEN2],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[ADV_DEN3],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[ADV_DEN4],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[ADV_DEN5],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[ADV_DEN6],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[ADV_NUM1],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[ADV_NUM2],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[ADV_NUM3],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[ADV_NUM4],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[ADV_NUM5],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[ADV_NUM6],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[IET_DEN1],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[IET_DEN2],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[IET_NUM1_1],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[IET_NUM1_2],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[IET_NUM2_1],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[IET_NUM2_2],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[APP_DEN1],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[APP_DEN2],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[APP_DEN3],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[APP_NUM1],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[APP_NUM2],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[APP_NUM3],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CIS_DEN],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CIS_NUM1],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CIS_NUM2],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CIS_NUM3],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CIS_NUM4],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CIS_NUM5],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CIS_NUM6],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CIS_NUM7],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CIS_NUM8],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CIS_NUM9],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CIS_NUM10],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CIS_NUM11],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CIS_NUM12],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CIS_NUM13],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CIS_NUM14],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CIS_NUM15],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CIS_NUM16],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CIS_NUM17],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CIS_NUM18],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CIS_NUM19],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[URI_DEN],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[URI_NUM],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CWP_DEN],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CWP_NUM],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[COL_DEN],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[COL_NUM],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[BCS_DEN],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[BCS_NUM],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CCS_DEN],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CCS_NUM],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CHL_DEN1],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CHL_DEN2],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CHL_NUM1],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CHL_NUM2],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[OMW_DEN],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[OMW_NUM],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CBP_DEN],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CBP_NUM],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[PBH_DEN],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[PBH_NUM],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CMC_DEN],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CMC_NUM1],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CMC_NUM2],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CMC_NUM3],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CDC_DEN],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CDC_DEN3],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CDC_NUM1],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CDC_NUM2],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CDC_NUM3],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CDC_NUM4],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CDC_NUM5],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CDC_NUM6],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CDC_NUM7],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CDC_NUM8],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CDC_NUM9],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CDC_NUM10],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[ASM_DEN1],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[ASM_DEN2],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[ASM_DEN3],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[ASM_DEN4],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[ASM_NUM1],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[ASM_NUM2],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[ASM_NUM3],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[ASM_NUM4],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[FUH_DEN],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[FUH_NUM1],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[FUH_NUM2],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[AMM_DEN],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[AMM_NUM1],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[AMM_NUM2],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[AMM_NUM3],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[GSO_DEN],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[GSO_NUM],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[LBP_DEN],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[LBP_NUM],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[AAB_DEN],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[AAB_NUM],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[SPR_DEN],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[SPR_NUM],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[ADD_DEN1],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[ADD_NUM1],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[ADD_DEN2],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[ADD_NUM2],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[ART_DEN],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[ART_NUM],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[MPM_DEN1],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[MPM_DEN2],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[MPM_DEN3],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[MPM_DEN4],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[MPM_NE1],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[MPM_NE2],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[MPM_NE3],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[MPM_NE4],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[DAE_DEN],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[DAE_NUM1],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[DAE_NUM2],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[DDE_DEN1],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[DDE_DEN2],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[DDE_DEN3],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[DDE_NUM1],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[DDE_NUM2],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[DDE_NUM3],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[PCE_DEN],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[PCE_NUM1],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[PCE_NUM2],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[LSC_DEN],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[LSC_NUM],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[ABA_DEN],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[ABA_NUM],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[WCC_DEN1_1],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[WCC_NUM1_1],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[WCC_DEN1_2],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[WCC_NUM1_2],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[WCC_DEN2_1],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[WCC_NUM2_1],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[WCC_DEN2_2],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[WCC_NUM2_2],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[WCC_DEN3_1],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[WCC_NUM3_1],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[WCC_DEN3_2],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[WCC_NUM3_2],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[COA_DEN],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[COA_NUM1],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[COA_NUM2],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[COA_NUM3],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[COA_NUM4],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[MRP_DEN],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[MRP_NUM],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[IMA_DEN],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[IMA_NUM1],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[IMA_NUM2],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[IMA_NUM3],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[HPV_DEN],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[HPV_NUM],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[MMA_DEN1],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[MMA_NUM1_1],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[MMA_NUM1_2],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[MMA_DEN2],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[MMA_NUM2_1],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[MMA_NUM2_2],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[MMA_DEN3],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[MMA_NUM3_1],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[MMA_NUM3_2],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[MMA_DEN4],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[MMA_NUM4_1],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[MMA_NUM4_2],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[MMA_DEN5],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[MMA_NUM5_1],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[MMA_NUM5_2],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[MMA_DEN6],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[MMA_NUM6_1],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[MMA_NUM6_2],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[AMR_DEN1],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[AMR_DEN2],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[AMR_DEN3],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[AMR_DEN4],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[AMR_DEN5],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[AMR_DEN6],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[AMR_NUM1],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[AMR_NUM2],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[AMR_NUM3],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[AMR_NUM4],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[AMR_NUM5],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[AMR_NUM6],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[SMD_DEN],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[SMD_NUM],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[SAA_DEN],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[SAA_NUM],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[SSD_DEN],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[SSD_NUM],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[SMC_DEN],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[SMC_NUM],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[NCS_DEN],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[NCS_NUM],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[PSA_DEN],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[PSA_NUM],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[APC_DEN1],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[APC_DEN2],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[APC_DEN3],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[APC_NUM1],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[APC_NUM2],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[APC_NUM3],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[APM_DEN1],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[APM_DEN2],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[APM_DEN3],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[APM_NUM1],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[APM_NUM2],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[APM_NUM3],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[FPC_DEN],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[FPC_NUM1],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[FPC_NUM2],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[FPC_NUM3],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[FPC_NUM4],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[FPC_NUM5],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[W15_DEN],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[W15_NUM1],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[W15_NUM2],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[W15_NUM3],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[W15_NUM4],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[W15_NUM5],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[W15_NUM6],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[W15_NUM7],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[W34_DEN],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[W34_NUM],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[AWC_DEN],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[AWC_NUM],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[FSP_CABG],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[FSP_PTCA],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[FSP_CC],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[FSP_CE],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[FSP_RDF],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[FSP_THR],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[FSP_TKR],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[FSP_EXL],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[FSP_CHO],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[FSP_CHC],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[FSP_HYA],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[FSP_HYV],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[FSP_PROS],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[FSP_DC],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[FSP_BACK],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[FSP_MYR],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[FSP_TON],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[FSP_MAST],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[FSP_LUMP],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[FSP_BARI],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[IPU_DISCH_TOT],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[IPU_DAYS_TOT],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[IPU_DISCH_MAT],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[IPU_DAYS_MAT],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[IPU_DISCH_SUR],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[IPU_DAYS_SUR],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[IPU_DISCH_MED],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[IPU_DAYS_MED],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[AMB_OV],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[AMB_ED],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[AMB_AS],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[AMB_OR],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[MPT_ANY],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[MPT_INP],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[MPT_DN],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[MPT_AMB],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[IAD_ANY],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[IAD_INP],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[IAD_DN],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[IAD_AMB],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[TOTAL_ABX_SCRIPTS],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[TOTAL_ABX_DAYS],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[ABX_CONCERN_SCRIPTS],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[ABXQUIN_PMPY],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[ABXZITH_PMPY],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[ABXCEPH2_PMPY],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[ABXCEPH3_PMPY],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[ABXAMOX_PMPY],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[ABXKETO_PMPY],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[ABXCLIND_PMPY],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[ABXMISC_PMPY],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[ABXABSORB_PMPY],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[ABXAMINO_PMPY],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[ABXCEPH1_PMPY],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[ABXLINCO_PMPY],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[ABXMACRO_PMPY],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[ABXPEN_PMPY],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[ABXTET_PMPY],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[ABXMISO_PMPY],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[ABX_ALLOTHER_SCRIPTS],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[PCR_DEN],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[PCR_NUM],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[SUM_WEIGHTS],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[PRED_READM],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[RDI_DEN],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[RDI_EXCL_REQ],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[RAS_DEN],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[RAS_EXCL_REQ],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[RCA_DEN],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[RCA_EXCL_REQ],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[RCO_DEN],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[RCO_EXCL_REQ],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[RHY_DEN],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[RHY_EXCL_REQ],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[EM_COUNT],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[RRU_LOS],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[RX_COUNT],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[PROC_COUNT],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CAP_INPATIENT],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CAP_EM_INPATIENT],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CAP_EM_OUTPATIENT],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CAP_PROC_INPATIENT],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CAP_PROC_OUTPATIENT],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CAP_RX],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CAP_LAB],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CAP_IMG],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[NCQA_PRICE_EM_INP],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[NCQA_PRICE_EM_OUT],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[TOTAL_COST_EM],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[NCQA_PRICE_INP],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[TOTAL_COST_INP],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[NCQA_PRICE_PROC_INP],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[NCQA_PRICE_PROC_OUT],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[TOTAL_COST_PROC],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[NCQA_PRICE_RX],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[TOTAL_COST_RX],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[NCQA_PRICE_LAB],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[NCQA_PRICE_IMG],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[LAB_COUNT],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[IMG_COUNT],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[RRU_MMS_MED],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[RRU_MMS_RX],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[ED_COUNT],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[FREQ_CABG],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[FREQ_CE],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[FREQ_PCI],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[FREQ_CC],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[FREQ_CASDT],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[FREQ_CAD_EBCT],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[FREQ_CCT],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[RRU_INP_DISCH],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[RRU_INP_DAYS],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[RRU_IPU_DISCH],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[RRU_IPU_DAYS],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[RRU_IPU_MED_DISCH],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[RRU_IPU_MED_DAYS],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[RRU_IPU_SURG_DISCH],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[RRU_IPU_SURG_DAYS],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[RRU_NON_DISCH],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[RRU_NON_DAYS],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[RX_N1],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[RX_N2],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[RX_G1],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[RX_G2],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[RRUAG_WEIGHT],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[RASAG_WEIGHT],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[COMORB_WEIGHT],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[RRU_RISK_GROUP],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[RAS_RISK_GROUP],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[SPC_DEN1_1],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[SPC_DEN2_1],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[SPC_NUM1_1],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[SPC_NUM2_1],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[SPC_DEN1_2],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[SPC_DEN2_2],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[SPC_NUM1_2],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[SPC_NUM2_2],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[SPD_DEN1],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[SPD_DEN2],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[SPD_NUM1],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[SPD_NUM2],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[PDC_DEN1],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[PDC_NUM1],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[PDC_DEN2],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[PDC_NUM2],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[PDC_DEN3],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[PDC_NUM3],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[IHU_DEN],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[INP_SUR_CNT],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[INP_MED_CNT],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[INP_TOT_CNT],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[EDU_DEN],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[ER_CNT],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[EXP_ER_CNT],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[HPC_DEN],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[CHRONIC_ACSC_CNT],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[ACUTE_ACSC_CNT],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[HPC_INP_TOT_CNT],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[EXP_INP_HPCA],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[EXP_INP_HPCCH],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[EXP_INP_HPTOT],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[HPCA_PPD_COMORB_WT],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[HPCCH_PPD_COMORB_WT],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[HPCT_PPD_COMORB_WT],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[HPCA_PPD_AGE_WT],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[HPCCH_PPD_AGE_WT],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[HPCT_PPD_AGE_WT],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[HPCA_PPD_BASE_WT],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[HPCCH_PPD_BASE_WT],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[HPCT_PPD_BASE_WT],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[HPCA_PUCD_COMORB_WT],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[HPCCH_PUCD_COMORB_WT],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[HPCT_PUCD_COMORB_WT],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[HPCA_PUCD_AGE_WT],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[HPCCH_PUCD_AGE_WT],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[HPCT_PUCD_AGE_WT],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[HPCA_PUCD_BASE_WT],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[HPCCH_PUCD_BASE_WT],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[HPCT_PUCD_BASE_WT],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[SUR_PPD_COMORB_WT],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[MED_PPD_COMORB_WT],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[TOT_PPD_COMORB_WT],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[SUR_PPD_AGE_WT],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[MED_PPD_AGE_WT],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[TOT_PPD_AGE_WT],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[SUR_PPD_BASE_WT],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[MED_PPD_BASE_WT],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[TOT_PPD_BASE_WT],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[SUR_PUCD_COMORB_WT],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[MED_PUCD_COMORB_WT],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[TOT_PUCD_COMORB_WT],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[SUR_PUCD_AGE_WT],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[MED_PUCD_AGE_WT],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[TOT_PUCD_AGE_WT],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[SUR_PUCD_BASE_WT],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[MED_PUCD_BASE_WT],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[TOT_PUCD_BASE_WT],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[PPV_COMORB_WT],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[PPV_AGE_WT],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[PPV_BASE_WT],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[PUCV_COMORB_WT],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[PUCV_AGE_WT],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[PUCV_BASE_WT],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[Case Manager],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[PHO ID],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[PHO Name],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[PCP Name],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[PCP ID],'')))
				)),2)),
			 S_HEDISDetail_HashDiff = UPPER(CONVERT(CHAR(32), HASHBYTES('MD5',UPPER(
				RTRIM(LTRIM(COALESCE(i.[PRODUCT_ROLLUP_ID],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[MEM_NBR],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[MMS_MED],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[MMS_RX],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[MMS_MH_INP],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[MMS_MH_INT],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[MMS_MH_AMB],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[MMS_CD_INP],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[MMS_CD_INT],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[MMS_CD_AMB],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[MMS_DENT],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[AAP_DEN1],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[AAP_DEN2],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[AAP_DEN3],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[AAP_NUM1],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[AAP_NUM2],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[AAP_NUM3],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CAP_DEN1],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CAP_DEN2],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CAP_DEN3],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CAP_DEN4],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CAP_NUM1],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CAP_NUM2],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CAP_NUM3],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CAP_NUM4],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[PPC_DEN],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[PPC_NUM1],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[PPC_NUM2],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[ADV_DEN1],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[ADV_DEN2],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[ADV_DEN3],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[ADV_DEN4],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[ADV_DEN5],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[ADV_DEN6],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[ADV_NUM1],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[ADV_NUM2],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[ADV_NUM3],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[ADV_NUM4],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[ADV_NUM5],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[ADV_NUM6],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[IET_DEN1],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[IET_DEN2],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[IET_NUM1_1],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[IET_NUM1_2],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[IET_NUM2_1],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[IET_NUM2_2],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[APP_DEN1],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[APP_DEN2],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[APP_DEN3],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[APP_NUM1],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[APP_NUM2],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[APP_NUM3],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CIS_DEN],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CIS_NUM1],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CIS_NUM2],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CIS_NUM3],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CIS_NUM4],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CIS_NUM5],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CIS_NUM6],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CIS_NUM7],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CIS_NUM8],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CIS_NUM9],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CIS_NUM10],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CIS_NUM11],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CIS_NUM12],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CIS_NUM13],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CIS_NUM14],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CIS_NUM15],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CIS_NUM16],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CIS_NUM17],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CIS_NUM18],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CIS_NUM19],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[URI_DEN],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[URI_NUM],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CWP_DEN],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CWP_NUM],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[COL_DEN],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[COL_NUM],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[BCS_DEN],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[BCS_NUM],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CCS_DEN],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CCS_NUM],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CHL_DEN1],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CHL_DEN2],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CHL_NUM1],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CHL_NUM2],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[OMW_DEN],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[OMW_NUM],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CBP_DEN],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CBP_NUM],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[PBH_DEN],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[PBH_NUM],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CMC_DEN],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CMC_NUM1],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CMC_NUM2],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CMC_NUM3],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CDC_DEN],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CDC_DEN3],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CDC_NUM1],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CDC_NUM2],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CDC_NUM3],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CDC_NUM4],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CDC_NUM5],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CDC_NUM6],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CDC_NUM7],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CDC_NUM8],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CDC_NUM9],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CDC_NUM10],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[ASM_DEN1],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[ASM_DEN2],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[ASM_DEN3],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[ASM_DEN4],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[ASM_NUM1],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[ASM_NUM2],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[ASM_NUM3],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[ASM_NUM4],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[FUH_DEN],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[FUH_NUM1],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[FUH_NUM2],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[AMM_DEN],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[AMM_NUM1],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[AMM_NUM2],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[AMM_NUM3],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[GSO_DEN],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[GSO_NUM],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[LBP_DEN],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[LBP_NUM],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[AAB_DEN],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[AAB_NUM],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[SPR_DEN],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[SPR_NUM],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[ADD_DEN1],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[ADD_NUM1],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[ADD_DEN2],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[ADD_NUM2],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[ART_DEN],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[ART_NUM],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[MPM_DEN1],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[MPM_DEN2],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[MPM_DEN3],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[MPM_DEN4],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[MPM_NE1],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[MPM_NE2],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[MPM_NE3],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[MPM_NE4],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[DAE_DEN],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[DAE_NUM1],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[DAE_NUM2],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[DDE_DEN1],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[DDE_DEN2],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[DDE_DEN3],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[DDE_NUM1],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[DDE_NUM2],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[DDE_NUM3],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[PCE_DEN],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[PCE_NUM1],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[PCE_NUM2],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[LSC_DEN],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[LSC_NUM],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[ABA_DEN],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[ABA_NUM],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[WCC_DEN1_1],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[WCC_NUM1_1],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[WCC_DEN1_2],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[WCC_NUM1_2],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[WCC_DEN2_1],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[WCC_NUM2_1],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[WCC_DEN2_2],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[WCC_NUM2_2],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[WCC_DEN3_1],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[WCC_NUM3_1],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[WCC_DEN3_2],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[WCC_NUM3_2],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[COA_DEN],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[COA_NUM1],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[COA_NUM2],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[COA_NUM3],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[COA_NUM4],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[MRP_DEN],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[MRP_NUM],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[IMA_DEN],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[IMA_NUM1],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[IMA_NUM2],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[IMA_NUM3],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[HPV_DEN],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[HPV_NUM],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[MMA_DEN1],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[MMA_NUM1_1],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[MMA_NUM1_2],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[MMA_DEN2],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[MMA_NUM2_1],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[MMA_NUM2_2],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[MMA_DEN3],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[MMA_NUM3_1],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[MMA_NUM3_2],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[MMA_DEN4],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[MMA_NUM4_1],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[MMA_NUM4_2],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[MMA_DEN5],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[MMA_NUM5_1],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[MMA_NUM5_2],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[MMA_DEN6],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[MMA_NUM6_1],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[MMA_NUM6_2],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[AMR_DEN1],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[AMR_DEN2],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[AMR_DEN3],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[AMR_DEN4],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[AMR_DEN5],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[AMR_DEN6],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[AMR_NUM1],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[AMR_NUM2],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[AMR_NUM3],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[AMR_NUM4],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[AMR_NUM5],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[AMR_NUM6],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[SMD_DEN],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[SMD_NUM],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[SAA_DEN],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[SAA_NUM],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[SSD_DEN],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[SSD_NUM],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[SMC_DEN],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[SMC_NUM],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[NCS_DEN],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[NCS_NUM],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[PSA_DEN],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[PSA_NUM],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[APC_DEN1],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[APC_DEN2],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[APC_DEN3],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[APC_NUM1],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[APC_NUM2],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[APC_NUM3],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[APM_DEN1],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[APM_DEN2],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[APM_DEN3],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[APM_NUM1],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[APM_NUM2],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[APM_NUM3],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[FPC_DEN],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[FPC_NUM1],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[FPC_NUM2],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[FPC_NUM3],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[FPC_NUM4],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[FPC_NUM5],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[W15_DEN],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[W15_NUM1],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[W15_NUM2],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[W15_NUM3],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[W15_NUM4],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[W15_NUM5],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[W15_NUM6],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[W15_NUM7],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[W34_DEN],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[W34_NUM],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[AWC_DEN],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[AWC_NUM],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[FSP_CABG],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[FSP_PTCA],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[FSP_CC],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[FSP_CE],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[FSP_RDF],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[FSP_THR],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[FSP_TKR],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[FSP_EXL],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[FSP_CHO],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[FSP_CHC],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[FSP_HYA],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[FSP_HYV],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[FSP_PROS],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[FSP_DC],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[FSP_BACK],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[FSP_MYR],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[FSP_TON],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[FSP_MAST],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[FSP_LUMP],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[FSP_BARI],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[IPU_DISCH_TOT],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[IPU_DAYS_TOT],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[IPU_DISCH_MAT],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[IPU_DAYS_MAT],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[IPU_DISCH_SUR],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[IPU_DAYS_SUR],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[IPU_DISCH_MED],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[IPU_DAYS_MED],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[AMB_OV],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[AMB_ED],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[AMB_AS],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[AMB_OR],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[MPT_ANY],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[MPT_INP],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[MPT_DN],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[MPT_AMB],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[IAD_ANY],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[IAD_INP],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[IAD_DN],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[IAD_AMB],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[TOTAL_ABX_SCRIPTS],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[TOTAL_ABX_DAYS],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[ABX_CONCERN_SCRIPTS],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[ABXQUIN_PMPY],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[ABXZITH_PMPY],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[ABXCEPH2_PMPY],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[ABXCEPH3_PMPY],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[ABXAMOX_PMPY],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[ABXKETO_PMPY],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[ABXCLIND_PMPY],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[ABXMISC_PMPY],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[ABXABSORB_PMPY],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[ABXAMINO_PMPY],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[ABXCEPH1_PMPY],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[ABXLINCO_PMPY],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[ABXMACRO_PMPY],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[ABXPEN_PMPY],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[ABXTET_PMPY],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[ABXMISO_PMPY],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[ABX_ALLOTHER_SCRIPTS],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[PCR_DEN],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[PCR_NUM],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[SUM_WEIGHTS],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[PRED_READM],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[RDI_DEN],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[RDI_EXCL_REQ],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[RAS_DEN],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[RAS_EXCL_REQ],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[RCA_DEN],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[RCA_EXCL_REQ],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[RCO_DEN],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[RCO_EXCL_REQ],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[RHY_DEN],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[RHY_EXCL_REQ],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[EM_COUNT],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[RRU_LOS],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[RX_COUNT],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[PROC_COUNT],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CAP_INPATIENT],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CAP_EM_INPATIENT],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CAP_EM_OUTPATIENT],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CAP_PROC_INPATIENT],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CAP_PROC_OUTPATIENT],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CAP_RX],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CAP_LAB],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[CAP_IMG],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[NCQA_PRICE_EM_INP],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[NCQA_PRICE_EM_OUT],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[TOTAL_COST_EM],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[NCQA_PRICE_INP],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[TOTAL_COST_INP],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[NCQA_PRICE_PROC_INP],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[NCQA_PRICE_PROC_OUT],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[TOTAL_COST_PROC],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[NCQA_PRICE_RX],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[TOTAL_COST_RX],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[NCQA_PRICE_LAB],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[NCQA_PRICE_IMG],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[LAB_COUNT],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[IMG_COUNT],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[RRU_MMS_MED],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[RRU_MMS_RX],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[ED_COUNT],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[FREQ_CABG],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[FREQ_CE],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[FREQ_PCI],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[FREQ_CC],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[FREQ_CASDT],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[FREQ_CAD_EBCT],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[FREQ_CCT],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[RRU_INP_DISCH],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[RRU_INP_DAYS],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[RRU_IPU_DISCH],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[RRU_IPU_DAYS],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[RRU_IPU_MED_DISCH],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[RRU_IPU_MED_DAYS],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[RRU_IPU_SURG_DISCH],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[RRU_IPU_SURG_DAYS],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[RRU_NON_DISCH],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[RRU_NON_DAYS],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[RX_N1],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[RX_N2],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[RX_G1],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[RX_G2],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[RRUAG_WEIGHT],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[RASAG_WEIGHT],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[COMORB_WEIGHT],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[RRU_RISK_GROUP],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[RAS_RISK_GROUP],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[SPC_DEN1_1],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[SPC_DEN2_1],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[SPC_NUM1_1],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[SPC_NUM2_1],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[SPC_DEN1_2],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[SPC_DEN2_2],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[SPC_NUM1_2],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[SPC_NUM2_2],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[SPD_DEN1],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[SPD_DEN2],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[SPD_NUM1],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[SPD_NUM2],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[PDC_DEN1],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[PDC_NUM1],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[PDC_DEN2],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[PDC_NUM2],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[PDC_DEN3],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[PDC_NUM3],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[IHU_DEN],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[INP_SUR_CNT],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[INP_MED_CNT],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[INP_TOT_CNT],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[EDU_DEN],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[ER_CNT],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[EXP_ER_CNT],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[HPC_DEN],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[CHRONIC_ACSC_CNT],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[ACUTE_ACSC_CNT],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[HPC_INP_TOT_CNT],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[EXP_INP_HPCA],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[EXP_INP_HPCCH],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[EXP_INP_HPTOT],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[HPCA_PPD_COMORB_WT],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[HPCCH_PPD_COMORB_WT],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[HPCT_PPD_COMORB_WT],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[HPCA_PPD_AGE_WT],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[HPCCH_PPD_AGE_WT],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[HPCT_PPD_AGE_WT],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[HPCA_PPD_BASE_WT],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[HPCCH_PPD_BASE_WT],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[HPCT_PPD_BASE_WT],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[HPCA_PUCD_COMORB_WT],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[HPCCH_PUCD_COMORB_WT],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[HPCT_PUCD_COMORB_WT],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[HPCA_PUCD_AGE_WT],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[HPCCH_PUCD_AGE_WT],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[HPCT_PUCD_AGE_WT],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[HPCA_PUCD_BASE_WT],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[HPCCH_PUCD_BASE_WT],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[HPCT_PUCD_BASE_WT],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[SUR_PPD_COMORB_WT],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[MED_PPD_COMORB_WT],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[TOT_PPD_COMORB_WT],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[SUR_PPD_AGE_WT],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[MED_PPD_AGE_WT],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[TOT_PPD_AGE_WT],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[SUR_PPD_BASE_WT],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[MED_PPD_BASE_WT],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[TOT_PPD_BASE_WT],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[SUR_PUCD_COMORB_WT],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[MED_PUCD_COMORB_WT],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[TOT_PUCD_COMORB_WT],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[SUR_PUCD_AGE_WT],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[MED_PUCD_AGE_WT],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[TOT_PUCD_AGE_WT],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[SUR_PUCD_BASE_WT],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[MED_PUCD_BASE_WT],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[TOT_PUCD_BASE_WT],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[PPV_COMORB_WT],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[PPV_AGE_WT],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[PPV_BASE_WT],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[PUCV_COMORB_WT],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[PUCV_AGE_WT],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[PUCV_BASE_WT],''))) + ':' +
				RTRIM(LTRIM(COALESCE(i.[Case Manager],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[PHO ID],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[PHO Name],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[PCP Name],''))) + ':' + 
				RTRIM(LTRIM(COALESCE(i.[PCP ID],'')))
				)),2)),
			 S_ProviderDemo_RK = UPPER(CONVERT( CHAR(32), HASHBYTES('MD5', UPPER(CONCAT(RTRIM(LTRIM(COALESCE(i.RecordSource, ''))), ':', RTRIM(LTRIM(COALESCE(i.LoadDate, ''))), ':', RTRIM(LTRIM(COALESCE(p.CentauriProviderID, ''))), ':', RTRIM(LTRIM(COALESCE(dbo.ufn_parsefind(REPLACE(i.[PCP Name],', ',':'),':',1), ''))), ':', RTRIM(LTRIM(COALESCE(dbo.ufn_parsefind(REPLACE(i.[PCP Name],', ',':'),':',2), '')))))), 2)),
			 S_ProviderDemo_HashDiff = UPPER(CONVERT( CHAR(32), HASHBYTES('MD5', UPPER(CONCAT(RTRIM(LTRIM(COALESCE(p.CentauriProviderID, ''))), ':', RTRIM(LTRIM(COALESCE(dbo.ufn_parsefind(REPLACE(i.[PCP Name],', ',':'),':',1), ''))), ':', RTRIM(LTRIM(COALESCE(dbo.ufn_parsefind(REPLACE(i.[PCP Name],', ',':'),':',2), '')))))), 2)),
			 S_Network_HashDiff = UPPER(CONVERT(CHAR(32), HASHBYTES('MD5',UPPER(CONCAT(RTRIM(LTRIM(COALESCE(n.CentauriNetworkID,''))),':',RTRIM(LTRIM(COALESCE(i.[PHO Name],'')))))),2)),
			 S_Network_RK = UPPER(CONVERT(CHAR(32), HASHBYTES('MD5',UPPER(CONCAT(RTRIM(LTRIM(COALESCE(i.RecordSource, ''))), ':', RTRIM(LTRIM(COALESCE(i.LoadDate, ''))), ':', RTRIM(LTRIM(COALESCE(n.CentauriNetworkID,''))),':',RTRIM(LTRIM(COALESCE(i.[PHO Name],'')))))),2))
        FROM    CHSStaging.hedis.RawImport i
                CROSS JOIN dbo.H_Client c
                INNER JOIN CHSDV.dbo.R_Member m ON i.MEM_NBR = m.ClientMemberID
                                                   AND m.ClientID = c.Client_BK
                LEFT JOIN CHSDV.dbo.R_Provider p ON i.[PCP ID] = p.ClientProviderID
                                                     AND p.ClientID = c.Client_BK
                LEFT JOIN CHSDV.dbo.R_Network n ON i.[PHO ID] = n.ClientNetworkID
                                                   AND n.ClientID = c.Client_BK;


        
    END;

GO
