CREATE SCHEMA [FaxAutomation]
AUTHORIZATION [dbo]
GO
GRANT INSERT ON SCHEMA:: [FaxAutomation] TO [SSRS_REPORTING]
GO
GRANT DELETE ON SCHEMA:: [FaxAutomation] TO [SSRS_REPORTING]
GO
GRANT UPDATE ON SCHEMA:: [FaxAutomation] TO [SSRS_REPORTING]
GO
