CREATE TABLE [import].[StagingVisits]
(
[memid] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[date_s] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[date_adm] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[date_disch] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dayscov] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cpt] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cptmod_1] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cptmod_2] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[hcpcs] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cpt2] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[diag_i_1] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[diag_i_2] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[diag_i_3] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[diag_i_4] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[diag_i_5] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[diag_i_6] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[diag_i_7] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[diag_i_8] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[diag_i_9] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[diag_i_10] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[proc_i_1] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[proc_i_2] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[proc_i_3] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[proc_i_4] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[proc_i_5] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[proc_i_6] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[icd_flag] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[drg] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dischstatus] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[rev] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[billtype] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[nbr_times] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[hcfapos] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[claimstatus] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[provid] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_StagingVisits_provid] DEFAULT ('unk001'),
[suppdata] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
