CREATE TABLE [import].[Visits]
(
[memid] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[date_s] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[date_adm] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[date_disch] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dayscov] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cpt] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cptmod_1] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cptmod_2] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[hcpcs] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cpt2] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[diag_i_1] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[diag_i_2] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[diag_i_3] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[diag_i_4] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[diag_i_5] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[diag_i_6] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[diag_i_7] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[diag_i_8] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[diag_i_9] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[diag_i_10] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[proc_i_1] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[proc_i_2] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[proc_i_3] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[proc_i_4] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[proc_i_5] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[proc_i_6] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[icd_flag] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[drg] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dischstatus] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[rev] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[billtype] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[nbr_times] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[hcfapos] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[claimstatus] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[provid] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[suppdata] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[measureset] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[measure] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ihds_member_id] [int] NULL,
[ihds_provider_id_servicing] [int] NULL,
[id] [bigint] NOT NULL IDENTITY(1, 1)
) ON [PRIMARY]
GO
ALTER TABLE [import].[Visits] ADD CONSTRAINT [PK_Visits] PRIMARY KEY CLUSTERED  ([id]) ON [PRIMARY]
GO
