CREATE TABLE [dbo].[S_MKM302Details]
(
[S_MKM302Details_RK] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[LoadDate] [datetime] NULL,
[H_Claims_RK] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CLAIM_NO   ] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EVAL ] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PAID_DATE] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ADMIT_DATE] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DISCHG_DTE] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ALLOW_AMT] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SUBMI_AMT] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COINS_AMT] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COPAY_AMT] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DEDUCT_AMT] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PAID_AMT] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NONCOV_AMT] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[APC_COPAY_AMT] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GROUP ] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CAT_3 ] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PAR IND] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PROVFIX] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COVDAYS] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NONCOVDAYS] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ADMITTYPE] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DRG] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MEMNO] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IN_OUT] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CPAYDEDCT] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DIAGNOS] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DIAG1] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DIAG2] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DIAG3] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DIAG4] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DIAG5] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DIAG6] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DIAG7] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DIAG8] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DIAG9] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[P PROC] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[P PRDTE] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PROCED1] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PRODTE1] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PROCED2] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PRODTE2] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PROCED3] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PRODTE3] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PROCED4] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PRODTE4] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PROCED5] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PRODTE5] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PROCED6] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PRODTE6] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PROCED7] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PRODTE7] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ADMITDIAG] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TREAT_PLAN] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CERTIFICATE] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CLMTYPE] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PRICRSON_1] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PRICRSON_2] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PRICELEV] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FSCALCIN ] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TARGET_SRV] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[N_OCCURS] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FACILITY] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TOTPAYAMT] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ICD-TYPE-IND] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HashDiff] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RecordSource] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RecordEndDate] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[S_MKM302Details] ADD CONSTRAINT [PK_S_MKM302Details] PRIMARY KEY CLUSTERED  ([S_MKM302Details_RK]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[S_MKM302Details] ADD CONSTRAINT [FK_H_Claims_RK1] FOREIGN KEY ([H_Claims_RK]) REFERENCES [dbo].[H_Claims] ([H_Claims_RK]) ON DELETE CASCADE ON UPDATE CASCADE
GO
