CREATE TABLE [dbo].[H_MKM301]
(
[H_MKM301_RK] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[MKM301_BK] [int] NULL,
[ClientMKM301ID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RecordSource] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LoadDate] [datetime] NULL CONSTRAINT [DF_H_MKM301_LoadDate] DEFAULT (getdate())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[H_MKM301] ADD CONSTRAINT [PK_H_MKM301] PRIMARY KEY CLUSTERED  ([H_MKM301_RK]) ON [PRIMARY]
GO
