CREATE TABLE [dbo].[AO_A415DF_AOPERSON]
(
[AOEXTERNAL_ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[AOPLAN_ID] [int] NULL,
[DESCRIPTION] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[DETAILS] [ntext] COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[EXTERNAL] [bit] NULL,
[ID_OTHER] [int] NOT NULL IDENTITY(1, 1),
[TITLE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[VERSION] [bigint] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_A415DF_AOPERSON] ADD CONSTRAINT [pk_AO_A415DF_AOPERSON_ID_OTHER] PRIMARY KEY CLUSTERED  ([ID_OTHER]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_a415df_aop1188979497] ON [dbo].[AO_A415DF_AOPERSON] ([AOPLAN_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_A415DF_AOPERSON] ADD CONSTRAINT [fk_ao_a415df_aoperson_aoplan_id] FOREIGN KEY ([AOPLAN_ID]) REFERENCES [dbo].[AO_A415DF_AOPLAN] ([ID_OTHER])
GO
