CREATE TABLE [dbo].[AO_38321B_CUSTOM_CONTENT_LINK]
(
[CONTENT_KEY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[ID] [int] NOT NULL IDENTITY(1, 1),
[LINK_LABEL] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[LINK_URL] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[SEQUENCE] [int] NULL CONSTRAINT [df_AO_38321B_CUSTOM_CONTENT_LINK_SEQUENCE] DEFAULT ((0))
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_38321B_CUSTOM_CONTENT_LINK] ADD CONSTRAINT [pk_AO_38321B_CUSTOM_CONTENT_LINK_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_38321b_cus1828044926] ON [dbo].[AO_38321B_CUSTOM_CONTENT_LINK] ([CONTENT_KEY]) ON [PRIMARY]
GO
