CREATE TABLE [dbo].[AO_2C4E5C_MAILITEM]
(
[CREATED_TIMESTAMP] [bigint] NULL CONSTRAINT [df_AO_2C4E5C_MAILITEM_CREATED_TIMESTAMP] DEFAULT ((0)),
[ID] [int] NOT NULL IDENTITY(1, 1),
[MAIL_CONNECTION_ID] [int] NOT NULL CONSTRAINT [df_AO_2C4E5C_MAILITEM_MAIL_CONNECTION_ID] DEFAULT ((0)),
[STATUS] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[UPDATED_TIMESTAMP] [bigint] NULL CONSTRAINT [df_AO_2C4E5C_MAILITEM_UPDATED_TIMESTAMP] DEFAULT ((0))
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_2C4E5C_MAILITEM] ADD CONSTRAINT [pk_AO_2C4E5C_MAILITEM_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
