CREATE TABLE [dbo].[nodeassociation]
(
[SOURCE_NODE_ID] [numeric] (18, 0) NOT NULL,
[SOURCE_NODE_ENTITY] [nvarchar] (60) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL,
[SINK_NODE_ID] [numeric] (18, 0) NOT NULL,
[SINK_NODE_ENTITY] [nvarchar] (60) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL,
[ASSOCIATION_TYPE] [nvarchar] (60) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL,
[SEQUENCE] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[nodeassociation] ADD CONSTRAINT [PK_nodeassociation] PRIMARY KEY CLUSTERED  ([SOURCE_NODE_ID], [SOURCE_NODE_ENTITY], [SINK_NODE_ID], [SINK_NODE_ENTITY], [ASSOCIATION_TYPE]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [node_sink] ON [dbo].[nodeassociation] ([SINK_NODE_ID], [SINK_NODE_ENTITY]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [node_source] ON [dbo].[nodeassociation] ([SOURCE_NODE_ID], [SOURCE_NODE_ENTITY]) ON [PRIMARY]
GO
