CREATE TABLE [dbo].[AO_9B2E3B_THEN_ACT_EXECUTION]
(
[FINISH_TIME_MILLIS] [bigint] NULL,
[ID] [bigint] NOT NULL IDENTITY(1, 1),
[MESSAGE] [ntext] COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[OUTCOME] [nvarchar] (127) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL,
[START_TIME_MILLIS] [bigint] NULL,
[THEN_ACTION_CONFIG_ID] [bigint] NOT NULL,
[THEN_EXECUTION_ID] [bigint] NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_9B2E3B_THEN_ACT_EXECUTION] ADD CONSTRAINT [pk_AO_9B2E3B_THEN_ACT_EXECUTION_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_9b2e3b_the293379586] ON [dbo].[AO_9B2E3B_THEN_ACT_EXECUTION] ([THEN_EXECUTION_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_9B2E3B_THEN_ACT_EXECUTION] ADD CONSTRAINT [fk_ao_9b2e3b_then_act_execution_then_execution_id] FOREIGN KEY ([THEN_EXECUTION_ID]) REFERENCES [dbo].[AO_9B2E3B_THEN_EXECUTION] ([ID])
GO
