CREATE TABLE [dbo].[JQUARTZ_FIRED_TRIGGERS]
(
[SCHED_NAME] [varchar] (120) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[ENTRY_ID] [varchar] (95) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL,
[TRIGGER_NAME] [varchar] (200) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[TRIGGER_GROUP] [varchar] (200) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[IS_VOLATILE] [varchar] (1) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[INSTANCE_NAME] [varchar] (200) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[FIRED_TIME] [bigint] NULL,
[SCHED_TIME] [bigint] NULL,
[PRIORITY] [int] NULL,
[STATE] [varchar] (16) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[JOB_NAME] [varchar] (200) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[JOB_GROUP] [varchar] (200) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[IS_STATEFUL] [varchar] (1) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[IS_NONCONCURRENT] [varchar] (1) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[IS_UPDATE_DATA] [varchar] (1) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[REQUESTS_RECOVERY] [varchar] (1) COLLATE SQL_Latin1_General_CP437_CI_AI NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[JQUARTZ_FIRED_TRIGGERS] ADD CONSTRAINT [PK_JQUARTZ_FIRED_TRIGGERS] PRIMARY KEY CLUSTERED  ([ENTRY_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [idx_qrtz_ft_trig_inst_name] ON [dbo].[JQUARTZ_FIRED_TRIGGERS] ([SCHED_NAME], [INSTANCE_NAME]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [idx_qrtz_ft_inst_job_req_rcvry] ON [dbo].[JQUARTZ_FIRED_TRIGGERS] ([SCHED_NAME], [INSTANCE_NAME], [REQUESTS_RECOVERY]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [idx_qrtz_ft_jg] ON [dbo].[JQUARTZ_FIRED_TRIGGERS] ([SCHED_NAME], [JOB_GROUP]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [idx_qrtz_ft_j_g] ON [dbo].[JQUARTZ_FIRED_TRIGGERS] ([SCHED_NAME], [JOB_NAME], [JOB_GROUP]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [idx_qrtz_ft_tg] ON [dbo].[JQUARTZ_FIRED_TRIGGERS] ([SCHED_NAME], [TRIGGER_GROUP]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [idx_qrtz_ft_t_g] ON [dbo].[JQUARTZ_FIRED_TRIGGERS] ([SCHED_NAME], [TRIGGER_NAME], [TRIGGER_GROUP]) ON [PRIMARY]
GO
