CREATE TABLE [dbo].[AO_575BF5_PROVIDER_ISSUE]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[ISSUE_ID] [bigint] NOT NULL CONSTRAINT [df_AO_575BF5_PROVIDER_ISSUE_ISSUE_ID] DEFAULT ((0)),
[PROVIDER_SOURCE_ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL,
[STALE_AFTER] [bigint] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_575BF5_PROVIDER_ISSUE] ADD CONSTRAINT [pk_AO_575BF5_PROVIDER_ISSUE_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_575bf5_pro741170824] ON [dbo].[AO_575BF5_PROVIDER_ISSUE] ([ISSUE_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_575bf5_pro1348521624] ON [dbo].[AO_575BF5_PROVIDER_ISSUE] ([PROVIDER_SOURCE_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_575bf5_pro1117502689] ON [dbo].[AO_575BF5_PROVIDER_ISSUE] ([STALE_AFTER]) ON [PRIMARY]
GO
