CREATE TABLE [dbo].[AO_E8B6CC_ISSUE_MAPPING_V2]
(
[AUTHOR] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[BRANCH] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[DATE] [datetime] NULL,
[FILES_DATA] [ntext] COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[ID] [int] NOT NULL IDENTITY(1, 1),
[ISSUE_ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[MESSAGE] [ntext] COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[NODE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[PARENTS_DATA] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[RAW_AUTHOR] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[RAW_NODE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[REPOSITORY_ID] [int] NULL,
[VERSION] [int] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_E8B6CC_ISSUE_MAPPING_V2] ADD CONSTRAINT [pk_AO_E8B6CC_ISSUE_MAPPING_V2_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
