CREATE TABLE [dbo].[AO_E8B6CC_MESSAGE]
(
[ADDRESS] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL,
[ID] [int] NOT NULL IDENTITY(1, 1),
[PAYLOAD] [ntext] COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL,
[PAYLOAD_TYPE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL,
[PRIORITY] [int] NOT NULL CONSTRAINT [df_AO_E8B6CC_MESSAGE_PRIORITY] DEFAULT ((0))
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_E8B6CC_MESSAGE] ADD CONSTRAINT [pk_AO_E8B6CC_MESSAGE_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_e8b6cc_mes1247039512] ON [dbo].[AO_E8B6CC_MESSAGE] ([ADDRESS]) ON [PRIMARY]
GO
