CREATE TABLE [dbo].[AO_60DB71_BOARDADMINS]
(
[ID] [bigint] NOT NULL IDENTITY(1, 1),
[KEY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL,
[RAPID_VIEW_ID] [bigint] NOT NULL,
[TYPE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_60DB71_BOARDADMINS] ADD CONSTRAINT [pk_AO_60DB71_BOARDADMINS_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_60db71_boa2110227660] ON [dbo].[AO_60DB71_BOARDADMINS] ([RAPID_VIEW_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_60DB71_BOARDADMINS] ADD CONSTRAINT [fk_ao_60db71_boardadmins_rapid_view_id] FOREIGN KEY ([RAPID_VIEW_ID]) REFERENCES [dbo].[AO_60DB71_RAPIDVIEW] ([ID])
GO
