CREATE TABLE [dbo].[AO_E8B6CC_ISSUE_TO_CHANGESET]
(
[CHANGESET_ID] [int] NULL,
[ID] [int] NOT NULL IDENTITY(1, 1),
[ISSUE_KEY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[PROJECT_KEY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_E8B6CC_ISSUE_TO_CHANGESET] ADD CONSTRAINT [pk_AO_E8B6CC_ISSUE_TO_CHANGESET_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_e8b6cc_iss1229805759] ON [dbo].[AO_E8B6CC_ISSUE_TO_CHANGESET] ([CHANGESET_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_e8b6cc_iss417950110] ON [dbo].[AO_E8B6CC_ISSUE_TO_CHANGESET] ([ISSUE_KEY]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_e8b6cc_iss648895902] ON [dbo].[AO_E8B6CC_ISSUE_TO_CHANGESET] ([PROJECT_KEY]) ON [PRIMARY]
GO
