CREATE TABLE [dbo].[AO_A415DF_AOSOLUTION_STORE]
(
[AOPLAN_ID] [int] NOT NULL,
[ID_OTHER] [int] NOT NULL IDENTITY(1, 1),
[SOLUTION] [ntext] COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL,
[SOLUTION_VERSION] [bigint] NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_A415DF_AOSOLUTION_STORE] ADD CONSTRAINT [pk_AO_A415DF_AOSOLUTION_STORE_ID_OTHER] PRIMARY KEY CLUSTERED  ([ID_OTHER]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_A415DF_AOSOLUTION_STORE] ADD CONSTRAINT [U_AO_A415DF_AOSOLUT752937716] UNIQUE NONCLUSTERED  ([AOPLAN_ID]) ON [PRIMARY]
GO
