CREATE TABLE [dbo].[AO_F1B27B_KEY_COMP_HISTORY]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[KEY] [nvarchar] (450) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL,
[TIMED_PROMISE_ID] [int] NOT NULL,
[VALUE] [nvarchar] (450) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_F1B27B_KEY_COMP_HISTORY] ADD CONSTRAINT [pk_AO_F1B27B_KEY_COMP_HISTORY_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_f1b27b_key828117107] ON [dbo].[AO_F1B27B_KEY_COMP_HISTORY] ([TIMED_PROMISE_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_F1B27B_KEY_COMP_HISTORY] ADD CONSTRAINT [fk_ao_f1b27b_key_comp_history_timed_promise_id] FOREIGN KEY ([TIMED_PROMISE_ID]) REFERENCES [dbo].[AO_F1B27B_PROMISE_HISTORY] ([ID])
GO
