CREATE TABLE [dbo].[AO_A415DF_AOTEAM]
(
[AOPLAN_ID] [int] NULL,
[AUTO_ADJUST_TO_ABSENCES] [bit] NULL,
[DESCRIPTION] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[DETAILS] [ntext] COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[ID_OTHER] [int] NOT NULL IDENTITY(1, 1),
[INCREMENTAL_ADJUSTMENT] [float] NULL,
[ITERATION_START_TYPE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[ORDER_RANGE_IDENTIFIER] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[PLANNING_MODE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[SORT_ORDER] [bigint] NULL,
[TITLE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[VELOCITY] [float] NULL,
[VERSION] [bigint] NULL,
[WEEKS_PER_SPRINT] [int] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_A415DF_AOTEAM] ADD CONSTRAINT [pk_AO_A415DF_AOTEAM_ID_OTHER] PRIMARY KEY CLUSTERED  ([ID_OTHER]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_a415df_aot1876296753] ON [dbo].[AO_A415DF_AOTEAM] ([AOPLAN_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_A415DF_AOTEAM] ADD CONSTRAINT [fk_ao_a415df_aoteam_aoplan_id] FOREIGN KEY ([AOPLAN_ID]) REFERENCES [dbo].[AO_A415DF_AOPLAN] ([ID_OTHER])
GO
