CREATE TABLE [dbo].[AO_A415DF_AOPLAN]
(
[AODATE] [bigint] NULL,
[AOREPLANNING_DATE] [bigint] NULL,
[DESCRIPTION] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[DETAILS] [ntext] COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[ID_OTHER] [int] NOT NULL IDENTITY(1, 1),
[IN_REPLANNING] [bit] NULL,
[IN_STREAM_MODE] [bit] NULL,
[PLAN_VERSION] [bigint] NULL,
[REPLANNING_VERSION] [bigint] NULL,
[SCHEDULING_VERSION] [bigint] NULL,
[TITLE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[VERSION] [bigint] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_A415DF_AOPLAN] ADD CONSTRAINT [pk_AO_A415DF_AOPLAN_ID_OTHER] PRIMARY KEY CLUSTERED  ([ID_OTHER]) ON [PRIMARY]
GO
