CREATE TABLE [dbo].[AO_54307E_TIMEMETRIC]
(
[CREATED_DATE] [bigint] NULL,
[CUSTOM_FIELD_ID] [bigint] NULL,
[DEFINITION_CHANGE_DATE] [datetime] NULL,
[DEFINITION_CHANGE_MS_EPOCH] [bigint] NULL,
[GOALS_CHANGE_DATE] [datetime] NULL,
[GOALS_CHANGE_MS_EPOCH] [bigint] NULL,
[ID] [int] NOT NULL IDENTITY(1, 1),
[NAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL,
[SERVICE_DESK_ID] [int] NOT NULL,
[THRESHOLDS_CHANGE_MS_EPOCH] [bigint] NULL,
[THRESHOLDS_CONFIG_CHANGE_DATE] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_54307E_TIMEMETRIC] ADD CONSTRAINT [pk_AO_54307E_TIMEMETRIC_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_54307e_tim1369106182] ON [dbo].[AO_54307E_TIMEMETRIC] ([SERVICE_DESK_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_54307E_TIMEMETRIC] ADD CONSTRAINT [fk_ao_54307e_timemetric_service_desk_id] FOREIGN KEY ([SERVICE_DESK_ID]) REFERENCES [dbo].[AO_54307E_SERVICEDESK] ([ID])
GO
