CREATE TABLE [dbo].[AO_9B2E3B_WHEN_HANDLER_CONFIG]
(
[ID] [bigint] NOT NULL IDENTITY(1, 1),
[MODULE_KEY] [nvarchar] (450) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL,
[ORDINAL] [int] NOT NULL,
[RULE_ID] [bigint] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_9B2E3B_WHEN_HANDLER_CONFIG] ADD CONSTRAINT [pk_AO_9B2E3B_WHEN_HANDLER_CONFIG_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_9b2e3b_whe716528203] ON [dbo].[AO_9B2E3B_WHEN_HANDLER_CONFIG] ([RULE_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_9B2E3B_WHEN_HANDLER_CONFIG] ADD CONSTRAINT [fk_ao_9b2e3b_when_handler_config_rule_id] FOREIGN KEY ([RULE_ID]) REFERENCES [dbo].[AO_9B2E3B_RULE] ([ID])
GO
