CREATE TABLE [dbo].[AO_F1B27B_PROMISE_HISTORY]
(
[CLASSIFICATION] [nvarchar] (127) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL,
[ID] [int] NOT NULL IDENTITY(1, 1),
[KEY_HASH] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL,
[TASK_KEY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_F1B27B_PROMISE_HISTORY] ADD CONSTRAINT [pk_AO_F1B27B_PROMISE_HISTORY_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_F1B27B_PROMISE_HISTORY] ADD CONSTRAINT [U_AO_F1B27B_PROMISE1620912431] UNIQUE NONCLUSTERED  ([KEY_HASH]) ON [PRIMARY]
GO
