CREATE TABLE [dbo].[AO_D9132D_SCENARIO_RESOURCE]
(
[AVAILABILITY_CHANGED] [bit] NULL,
[C_KEY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL,
[ID] [bigint] NOT NULL IDENTITY(1, 1),
[ITEM_KEY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL,
[JOIN_DATE] [bigint] NULL,
[JOIN_DATE_CHANGED] [bit] NULL,
[LAST_CHANGE_TIMESTAMP] [bigint] NULL,
[LAST_CHANGE_USER] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[LEAVE_DATE] [bigint] NULL,
[LEAVE_DATE_CHANGED] [bit] NULL,
[PERSON_ITEM_KEY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[SCENARIO_ID] [bigint] NULL,
[SCENARIO_TYPE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL,
[TEAM_ITEM_KEY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[WEEKLY_HOURS] [float] NULL,
[WEEKLY_HOURS_CHANGED] [bit] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_D9132D_SCENARIO_RESOURCE] ADD CONSTRAINT [pk_AO_D9132D_SCENARIO_RESOURCE_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_D9132D_SCENARIO_RESOURCE] ADD CONSTRAINT [U_AO_D9132D_SCENARI1732287022] UNIQUE NONCLUSTERED  ([C_KEY]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_d9132d_sce355910425] ON [dbo].[AO_D9132D_SCENARIO_RESOURCE] ([ITEM_KEY]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_d9132d_sce168803159] ON [dbo].[AO_D9132D_SCENARIO_RESOURCE] ([PERSON_ITEM_KEY]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_d9132d_sce970354186] ON [dbo].[AO_D9132D_SCENARIO_RESOURCE] ([SCENARIO_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_d9132d_sce502118059] ON [dbo].[AO_D9132D_SCENARIO_RESOURCE] ([SCENARIO_TYPE]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_d9132d_sce29849183] ON [dbo].[AO_D9132D_SCENARIO_RESOURCE] ([TEAM_ITEM_KEY]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_D9132D_SCENARIO_RESOURCE] ADD CONSTRAINT [fk_ao_d9132d_scenario_resource_scenario_id] FOREIGN KEY ([SCENARIO_ID]) REFERENCES [dbo].[AO_D9132D_SCENARIO] ([ID])
GO
