CREATE TABLE [dbo].[AO_E8B6CC_PROJECT_MAPPING_V2]
(
[ACCESS_TOKEN] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[ADMIN_PASSWORD] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[ADMIN_USERNAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[ID] [int] NOT NULL IDENTITY(1, 1),
[LAST_COMMIT_DATE] [datetime] NULL,
[PROJECT_KEY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[REPOSITORY_NAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[REPOSITORY_TYPE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[REPOSITORY_URL] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_E8B6CC_PROJECT_MAPPING_V2] ADD CONSTRAINT [pk_AO_E8B6CC_PROJECT_MAPPING_V2_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
