CREATE TABLE [dbo].[remotelink]
(
[ID] [numeric] (18, 0) NOT NULL,
[ISSUEID] [numeric] (18, 0) NULL,
[GLOBALID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[TITLE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[SUMMARY] [ntext] COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[URL] [ntext] COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[ICONURL] [ntext] COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[ICONTITLE] [ntext] COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[RELATIONSHIP] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[RESOLVED] [nchar] (1) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[STATUSNAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[STATUSDESCRIPTION] [ntext] COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[STATUSICONURL] [ntext] COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[STATUSICONTITLE] [ntext] COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[STATUSICONLINK] [ntext] COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[STATUSCATEGORYKEY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[STATUSCATEGORYCOLORNAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[APPLICATIONTYPE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[APPLICATIONNAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[remotelink] ADD CONSTRAINT [PK_remotelink] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [remotelink_globalid] ON [dbo].[remotelink] ([GLOBALID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [remotelink_issueid] ON [dbo].[remotelink] ([ISSUEID], [GLOBALID]) ON [PRIMARY]
GO
