CREATE TABLE [dbo].[AO_D9132D_SCENARIO_STAGE]
(
[COLOR] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[COLOR_CHANGED] [bit] NULL,
[C_KEY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL,
[ID] [bigint] NOT NULL IDENTITY(1, 1),
[ITEM_KEY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL,
[LAST_CHANGE_TIMESTAMP] [bigint] NULL,
[LAST_CHANGE_USER] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[SCENARIO_ID] [bigint] NULL,
[SCENARIO_TYPE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL,
[TITLE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[TITLE_CHANGED] [bit] NULL,
[WEIGHT] [float] NULL,
[WEIGHT_CHANGED] [bit] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_D9132D_SCENARIO_STAGE] ADD CONSTRAINT [pk_AO_D9132D_SCENARIO_STAGE_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_D9132D_SCENARIO_STAGE] ADD CONSTRAINT [U_AO_D9132D_SCENARI2129424734] UNIQUE NONCLUSTERED  ([C_KEY]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_d9132d_sce1120228753] ON [dbo].[AO_D9132D_SCENARIO_STAGE] ([ITEM_KEY]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_d9132d_sce1478246132] ON [dbo].[AO_D9132D_SCENARIO_STAGE] ([SCENARIO_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_d9132d_sce1039993579] ON [dbo].[AO_D9132D_SCENARIO_STAGE] ([SCENARIO_TYPE]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_D9132D_SCENARIO_STAGE] ADD CONSTRAINT [fk_ao_d9132d_scenario_stage_scenario_id] FOREIGN KEY ([SCENARIO_ID]) REFERENCES [dbo].[AO_D9132D_SCENARIO] ([ID])
GO
