CREATE TABLE [dbo].[AO_9B2E3B_THEN_ACT_CONF_DATA]
(
[CONFIG_DATA_KEY] [nvarchar] (127) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL,
[CONFIG_DATA_VALUE] [ntext] COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[ID] [bigint] NOT NULL IDENTITY(1, 1),
[THEN_ACTION_CONFIG_ID] [bigint] NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_9B2E3B_THEN_ACT_CONF_DATA] ADD CONSTRAINT [pk_AO_9B2E3B_THEN_ACT_CONF_DATA_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_9b2e3b_the1398825512] ON [dbo].[AO_9B2E3B_THEN_ACT_CONF_DATA] ([THEN_ACTION_CONFIG_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_9B2E3B_THEN_ACT_CONF_DATA] ADD CONSTRAINT [fk_ao_9b2e3b_then_act_conf_data_then_action_config_id] FOREIGN KEY ([THEN_ACTION_CONFIG_ID]) REFERENCES [dbo].[AO_9B2E3B_THEN_ACTION_CONFIG] ([ID])
GO
