CREATE TABLE [dbo].[AO_D4AF4C_DEVICE]
(
[ACTIVE] [bit] NULL,
[APP_ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[BADGE_NUMBER] [int] NULL CONSTRAINT [df_AO_D4AF4C_DEVICE_BADGE_NUMBER] DEFAULT ((0)),
[COMMENT_ADDED] [bit] NULL,
[COMMENT_MODIFIED] [bit] NULL,
[DESCRIPTION] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[DEVICE_ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[DEVICE_TYPE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[GENERIC_EVENT] [bit] NULL,
[ID] [int] NOT NULL IDENTITY(1, 1),
[ISSUE_ASSIGNED] [bit] NULL,
[ISSUE_CLOSED] [bit] NULL,
[ISSUE_CREATED] [bit] NULL,
[ISSUE_DELETED] [bit] NULL,
[ISSUE_MOVED] [bit] NULL,
[ISSUE_REOPENED] [bit] NULL,
[ISSUE_RESOLVED] [bit] NULL,
[ISSUE_UPDATED] [bit] NULL,
[LAST_ACCESSED] [datetime] NULL,
[PROFILE_ID] [int] NULL CONSTRAINT [df_AO_D4AF4C_DEVICE_PROFILE_ID] DEFAULT ((0)),
[USER_NAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[WORKLOG_ADDED] [bit] NULL,
[WORKLOG_DELETED] [bit] NULL,
[WORKLOG_UPDATED] [bit] NULL,
[WORK_STARTED] [bit] NULL,
[WORK_STOPPED] [bit] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_D4AF4C_DEVICE] ADD CONSTRAINT [pk_AO_D4AF4C_DEVICE_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
