CREATE TABLE [dbo].[AO_9B2E3B_RULE_EXECUTION]
(
[EXECUTOR_USER_KEY] [nvarchar] (127) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[FINISH_TIME_MILLIS] [bigint] NULL,
[ID] [bigint] NOT NULL IDENTITY(1, 1),
[MESSAGE] [ntext] COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[OUTCOME] [nvarchar] (127) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL,
[RULE_ID] [bigint] NOT NULL,
[START_TIME_MILLIS] [bigint] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_9B2E3B_RULE_EXECUTION] ADD CONSTRAINT [pk_AO_9B2E3B_RULE_EXECUTION_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
