CREATE TABLE [dbo].[AO_54307E_GOAL]
(
[CALENDAR_ID] [int] NULL,
[DEFAULT_GOAL] [bit] NULL,
[ID] [int] NOT NULL IDENTITY(1, 1),
[JQL_QUERY] [ntext] COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[POS] [int] NOT NULL CONSTRAINT [df_AO_54307E_GOAL_POS] DEFAULT ((0)),
[TARGET_DURATION] [bigint] NULL,
[TIME_METRIC_ID] [int] NOT NULL,
[TIME_UPDATED_DATE] [datetime] NULL,
[TIME_UPDATED_MS_EPOCH] [bigint] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_54307E_GOAL] ADD CONSTRAINT [pk_AO_54307E_GOAL_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_54307e_goa1428193453] ON [dbo].[AO_54307E_GOAL] ([TIME_METRIC_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_54307E_GOAL] ADD CONSTRAINT [fk_ao_54307e_goal_time_metric_id] FOREIGN KEY ([TIME_METRIC_ID]) REFERENCES [dbo].[AO_54307E_TIMEMETRIC] ([ID])
GO
