CREATE TABLE [dbo].[AO_E8B6CC_PR_ISSUE_KEY]
(
[DOMAIN_ID] [int] NOT NULL CONSTRAINT [df_AO_E8B6CC_PR_ISSUE_KEY_DOMAIN_ID] DEFAULT ((0)),
[ID] [int] NOT NULL IDENTITY(1, 1),
[ISSUE_KEY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[PULL_REQUEST_ID] [int] NULL CONSTRAINT [df_AO_E8B6CC_PR_ISSUE_KEY_PULL_REQUEST_ID] DEFAULT ((0))
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_E8B6CC_PR_ISSUE_KEY] ADD CONSTRAINT [pk_AO_E8B6CC_PR_ISSUE_KEY_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_e8b6cc_pr_1639282617] ON [dbo].[AO_E8B6CC_PR_ISSUE_KEY] ([DOMAIN_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_e8b6cc_pr_2106805302] ON [dbo].[AO_E8B6CC_PR_ISSUE_KEY] ([ISSUE_KEY]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_e8b6cc_pr_281193494] ON [dbo].[AO_E8B6CC_PR_ISSUE_KEY] ([PULL_REQUEST_ID]) ON [PRIMARY]
GO
