CREATE TABLE [dbo].[AO_21D670_WHITELIST_RULES]
(
[ALLOWINBOUND] [bit] NULL,
[EXPRESSION] [ntext] COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL,
[ID] [int] NOT NULL IDENTITY(1, 1),
[TYPE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_21D670_WHITELIST_RULES] ADD CONSTRAINT [pk_AO_21D670_WHITELIST_RULES_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
