CREATE TABLE [dbo].[AO_2C4E5C_MAILGLOBALHANDLER]
(
[CREATED_TIMESTAMP] [bigint] NULL CONSTRAINT [df_AO_2C4E5C_MAILGLOBALHANDLER_CREATED_TIMESTAMP] DEFAULT ((0)),
[HANDLER_TYPE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[ID] [int] NOT NULL IDENTITY(1, 1),
[MODULE_COMPLETE_KEY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[UPDATED_TIMESTAMP] [bigint] NULL CONSTRAINT [df_AO_2C4E5C_MAILGLOBALHANDLER_UPDATED_TIMESTAMP] DEFAULT ((0))
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_2C4E5C_MAILGLOBALHANDLER] ADD CONSTRAINT [pk_AO_2C4E5C_MAILGLOBALHANDLER_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
