CREATE TABLE [dbo].[AO_E8B6CC_BRANCH_HEAD_MAPPING]
(
[BRANCH_NAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[HEAD] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[ID] [int] NOT NULL IDENTITY(1, 1),
[REPOSITORY_ID] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_E8B6CC_BRANCH_HEAD_MAPPING] ADD CONSTRAINT [pk_AO_E8B6CC_BRANCH_HEAD_MAPPING_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_e8b6cc_bra1368852151] ON [dbo].[AO_E8B6CC_BRANCH_HEAD_MAPPING] ([REPOSITORY_ID]) ON [PRIMARY]
GO
