CREATE TABLE [dbo].[AO_D9132D_SCENARIO_ISSUE_RES]
(
[ID] [bigint] NOT NULL IDENTITY(1, 1),
[RESOURCE_ITEM_KEY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[SCENARIO_ISSUE_ID] [bigint] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_D9132D_SCENARIO_ISSUE_RES] ADD CONSTRAINT [pk_AO_D9132D_SCENARIO_ISSUE_RES_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_d9132d_sce1697093730] ON [dbo].[AO_D9132D_SCENARIO_ISSUE_RES] ([RESOURCE_ITEM_KEY]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_d9132d_sce1883185710] ON [dbo].[AO_D9132D_SCENARIO_ISSUE_RES] ([SCENARIO_ISSUE_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_D9132D_SCENARIO_ISSUE_RES] ADD CONSTRAINT [fk_ao_d9132d_scenario_issue_res_scenario_issue_id] FOREIGN KEY ([SCENARIO_ISSUE_ID]) REFERENCES [dbo].[AO_D9132D_SCENARIO_ISSUES] ([ID])
GO
