CREATE TABLE [dbo].[AO_82B313_RESOURCE]
(
[ID] [bigint] NOT NULL IDENTITY(1, 1),
[JOIN_DATE] [bigint] NULL,
[LEAVE_DATE] [bigint] NULL,
[PERSON_ID] [bigint] NULL,
[TEAM_ID] [bigint] NULL,
[WEEKLY_HOURS] [float] NULL CONSTRAINT [df_AO_82B313_RESOURCE_WEEKLY_HOURS] DEFAULT ((0.0))
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_82B313_RESOURCE] ADD CONSTRAINT [pk_AO_82B313_RESOURCE_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_82b313_res425524126] ON [dbo].[AO_82B313_RESOURCE] ([PERSON_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_82b313_res832797798] ON [dbo].[AO_82B313_RESOURCE] ([TEAM_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_82B313_RESOURCE] ADD CONSTRAINT [fk_ao_82b313_resource_person_id] FOREIGN KEY ([PERSON_ID]) REFERENCES [dbo].[AO_82B313_PERSON] ([ID])
GO
ALTER TABLE [dbo].[AO_82B313_RESOURCE] ADD CONSTRAINT [fk_ao_82b313_resource_team_id] FOREIGN KEY ([TEAM_ID]) REFERENCES [dbo].[AO_82B313_TEAM] ([ID])
GO
