CREATE TABLE [dbo].[AO_A415DF_AODEPENDENCY]
(
[DEPENDEE] [int] NULL,
[DEPENDENT] [int] NULL,
[ID_OTHER] [int] NOT NULL IDENTITY(1, 1)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_A415DF_AODEPENDENCY] ADD CONSTRAINT [pk_AO_A415DF_AODEPENDENCY_ID_OTHER] PRIMARY KEY CLUSTERED  ([ID_OTHER]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_a415df_aod780424464] ON [dbo].[AO_A415DF_AODEPENDENCY] ([DEPENDEE]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_a415df_aod1576645787] ON [dbo].[AO_A415DF_AODEPENDENCY] ([DEPENDENT]) ON [PRIMARY]
GO
