CREATE TABLE [dbo].[AO_2C4E5C_MAILRUNAUDIT]
(
[CREATED_TIMESTAMP] [bigint] NULL CONSTRAINT [df_AO_2C4E5C_MAILRUNAUDIT_CREATED_TIMESTAMP] DEFAULT ((0)),
[FAILURE_MESSAGE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[ID] [int] NOT NULL IDENTITY(1, 1),
[MAIL_CHANNEL_NAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[MAIL_CONNECTION_ID] [int] NOT NULL CONSTRAINT [df_AO_2C4E5C_MAILRUNAUDIT_MAIL_CONNECTION_ID] DEFAULT ((0)),
[NO_OF_RETRY] [int] NULL CONSTRAINT [df_AO_2C4E5C_MAILRUNAUDIT_NO_OF_RETRY] DEFAULT ((0)),
[RUN_OUTCOME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[UPDATED_TIMESTAMP] [bigint] NULL CONSTRAINT [df_AO_2C4E5C_MAILRUNAUDIT_UPDATED_TIMESTAMP] DEFAULT ((0))
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_2C4E5C_MAILRUNAUDIT] ADD CONSTRAINT [pk_AO_2C4E5C_MAILRUNAUDIT_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
