CREATE TABLE [dbo].[AO_575BF5_PROCESSED_COMMITS]
(
[COMMIT_HASH] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL,
[ID] [int] NOT NULL IDENTITY(1, 1),
[METADATA_HASH] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_575BF5_PROCESSED_COMMITS] ADD CONSTRAINT [pk_AO_575BF5_PROCESSED_COMMITS_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_575bf5_pro1681808571] ON [dbo].[AO_575BF5_PROCESSED_COMMITS] ([COMMIT_HASH]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_575bf5_pro78019725] ON [dbo].[AO_575BF5_PROCESSED_COMMITS] ([METADATA_HASH]) ON [PRIMARY]
GO
