CREATE TABLE [dbo].[AO_E8B6CC_ORG_TO_PROJECT]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[ORGANIZATION_ID] [int] NULL,
[PROJECT_KEY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_E8B6CC_ORG_TO_PROJECT] ADD CONSTRAINT [pk_AO_E8B6CC_ORG_TO_PROJECT_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_e8b6cc_org1899590324] ON [dbo].[AO_E8B6CC_ORG_TO_PROJECT] ([ORGANIZATION_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_E8B6CC_ORG_TO_PROJECT] ADD CONSTRAINT [fk_ao_e8b6cc_org_to_project_organization_id] FOREIGN KEY ([ORGANIZATION_ID]) REFERENCES [dbo].[AO_E8B6CC_ORGANIZATION_MAPPING] ([ID])
GO
