CREATE TABLE [dbo].[AO_D9132D_CONFIGURATION]
(
[HIERARCHY_ISSUE_LIMIT] [bigint] NULL,
[ID] [bigint] NOT NULL IDENTITY(1, 1),
[ISSUE_LIMIT] [bigint] NULL,
[PROJECT_LIMIT] [bigint] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_D9132D_CONFIGURATION] ADD CONSTRAINT [pk_AO_D9132D_CONFIGURATION_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
