CREATE TABLE [dbo].[AO_60DB71_ISSUERANKING]
(
[CUSTOM_FIELD_ID] [bigint] NOT NULL CONSTRAINT [df_AO_60DB71_ISSUERANKING_CUSTOM_FIELD_ID] DEFAULT ((0)),
[ID] [bigint] NOT NULL IDENTITY(1, 1),
[ISSUE_ID] [bigint] NOT NULL CONSTRAINT [df_AO_60DB71_ISSUERANKING_ISSUE_ID] DEFAULT ((0)),
[NEXT_ID] [bigint] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_60DB71_ISSUERANKING] ADD CONSTRAINT [pk_AO_60DB71_ISSUERANKING_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_60db71_iss1786461035] ON [dbo].[AO_60DB71_ISSUERANKING] ([CUSTOM_FIELD_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_60db71_iss1616896230] ON [dbo].[AO_60DB71_ISSUERANKING] ([ISSUE_ID]) ON [PRIMARY]
GO
