CREATE TABLE [dbo].[AO_D9132D_SCENARIO_TEAM]
(
[ADD_TO_PLAN] [bit] NULL,
[AVATAR] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[AVATAR_CHANGED] [bit] NULL,
[C_KEY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL,
[ID] [bigint] NOT NULL IDENTITY(1, 1),
[ISSUE_SOURCE_CHANGED] [bit] NULL,
[ISSUE_SOURCE_ID] [bigint] NULL,
[ITEM_KEY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL,
[ITERATION_LENGTH] [bigint] NULL,
[ITERATION_LENGTH_CHANGED] [bit] NULL,
[LAST_CHANGE_TIMESTAMP] [bigint] NULL,
[LAST_CHANGE_USER] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[SCENARIO_ID] [bigint] NULL,
[SCENARIO_TYPE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL,
[SCHEDULING_MODE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[SCHEDULING_MODE_CHANGED] [bit] NULL,
[TITLE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[TITLE_CHANGED] [bit] NULL,
[VELOCITY] [float] NULL,
[VELOCITY_CHANGED] [bit] NULL,
[WEEKLY_HOURS] [float] NULL,
[WEEKLY_HOURS_CHANGED] [bit] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_D9132D_SCENARIO_TEAM] ADD CONSTRAINT [pk_AO_D9132D_SCENARIO_TEAM_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_D9132D_SCENARIO_TEAM] ADD CONSTRAINT [U_AO_D9132D_SCENARI1025062113] UNIQUE NONCLUSTERED  ([C_KEY]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_d9132d_sce410924660] ON [dbo].[AO_D9132D_SCENARIO_TEAM] ([ISSUE_SOURCE_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_d9132d_sce434778360] ON [dbo].[AO_D9132D_SCENARIO_TEAM] ([ITEM_KEY]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_d9132d_sce838588485] ON [dbo].[AO_D9132D_SCENARIO_TEAM] ([SCENARIO_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_d9132d_sce1569966108] ON [dbo].[AO_D9132D_SCENARIO_TEAM] ([SCENARIO_TYPE]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_D9132D_SCENARIO_TEAM] ADD CONSTRAINT [fk_ao_d9132d_scenario_team_issue_source_id] FOREIGN KEY ([ISSUE_SOURCE_ID]) REFERENCES [dbo].[AO_D9132D_ISSUE_SOURCE] ([ID])
GO
ALTER TABLE [dbo].[AO_D9132D_SCENARIO_TEAM] ADD CONSTRAINT [fk_ao_d9132d_scenario_team_scenario_id] FOREIGN KEY ([SCENARIO_ID]) REFERENCES [dbo].[AO_D9132D_SCENARIO] ([ID])
GO
