CREATE TABLE [dbo].[AO_A415DF_AOABILITY]
(
[ABILITY_VALUE] [float] NULL,
[AOPERSON_ID] [int] NULL,
[ID_OTHER] [int] NOT NULL IDENTITY(1, 1),
[TARGET_ID] [int] NULL,
[TARGET_TYPE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[VERSION] [bigint] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_A415DF_AOABILITY] ADD CONSTRAINT [pk_AO_A415DF_AOABILITY_ID_OTHER] PRIMARY KEY CLUSTERED  ([ID_OTHER]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_a415df_aoa576235854] ON [dbo].[AO_A415DF_AOABILITY] ([AOPERSON_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_A415DF_AOABILITY] ADD CONSTRAINT [fk_ao_a415df_aoability_aoperson_id] FOREIGN KEY ([AOPERSON_ID]) REFERENCES [dbo].[AO_A415DF_AOPERSON] ([ID_OTHER])
GO
