CREATE TABLE [dbo].[AO_82B313_ABSENCE]
(
[END] [bigint] NULL,
[ID] [bigint] NOT NULL IDENTITY(1, 1),
[PERSON_ID] [bigint] NULL,
[START] [bigint] NULL,
[TITLE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_82B313_ABSENCE] ADD CONSTRAINT [pk_AO_82B313_ABSENCE_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_82b313_abs847540213] ON [dbo].[AO_82B313_ABSENCE] ([PERSON_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_82B313_ABSENCE] ADD CONSTRAINT [fk_ao_82b313_absence_person_id] FOREIGN KEY ([PERSON_ID]) REFERENCES [dbo].[AO_82B313_PERSON] ([ID])
GO
