CREATE TABLE [dbo].[AO_60DB71_SPRINT]
(
[CLOSED] [bit] NOT NULL,
[COMPLETE_DATE] [bigint] NULL,
[END_DATE] [bigint] NULL,
[ID] [bigint] NOT NULL IDENTITY(1, 1),
[NAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL,
[RAPID_VIEW_ID] [bigint] NULL,
[SEQUENCE] [bigint] NULL,
[STARTED] [bit] NULL,
[START_DATE] [bigint] NULL,
[GOAL] [ntext] COLLATE SQL_Latin1_General_CP437_CI_AI NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_60DB71_SPRINT] ADD CONSTRAINT [pk_AO_60DB71_SPRINT_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_60db71_spr1457658269] ON [dbo].[AO_60DB71_SPRINT] ([SEQUENCE]) ON [PRIMARY]
GO
