CREATE TABLE [dbo].[AO_54307E_SUBSCRIPTION]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[ISSUE_ID] [bigint] NOT NULL,
[SUBSCRIBED] [bit] NOT NULL,
[USER_KEY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_54307E_SUBSCRIPTION] ADD CONSTRAINT [pk_AO_54307E_SUBSCRIPTION_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_54307e_sub749517042] ON [dbo].[AO_54307E_SUBSCRIPTION] ([ISSUE_ID]) ON [PRIMARY]
GO
