CREATE TABLE [dbo].[AO_A415DF_AODOOR_STOP]
(
[ID] [int] NOT NULL IDENTITY(1, 1)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_A415DF_AODOOR_STOP] ADD CONSTRAINT [pk_AO_A415DF_AODOOR_STOP_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
