CREATE TABLE [dbo].[AO_0201F0_STATS_EVENT_PARAM]
(
[ID] [bigint] NOT NULL IDENTITY(1, 1),
[PARAM_NAME] [nvarchar] (127) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[PARAM_VALUE] [nvarchar] (450) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[STATS_EVENT_ID] [bigint] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_0201F0_STATS_EVENT_PARAM] ADD CONSTRAINT [pk_AO_0201F0_STATS_EVENT_PARAM_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_0201f0_sta556470213] ON [dbo].[AO_0201F0_STATS_EVENT_PARAM] ([STATS_EVENT_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_0201F0_STATS_EVENT_PARAM] ADD CONSTRAINT [fk_ao_0201f0_stats_event_param_stats_event_id] FOREIGN KEY ([STATS_EVENT_ID]) REFERENCES [dbo].[AO_0201F0_STATS_EVENT] ([ID])
GO
