CREATE TABLE [dbo].[AO_A415DF_AOPERMISSION]
(
[HOLDER_ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[HOLDER_TYPE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[ID_OTHER] [int] NOT NULL IDENTITY(1, 1),
[PERMISSION] [int] NULL,
[TARGET_ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[TARGET_TYPE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[VERSION] [bigint] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_A415DF_AOPERMISSION] ADD CONSTRAINT [pk_AO_A415DF_AOPERMISSION_ID_OTHER] PRIMARY KEY CLUSTERED  ([ID_OTHER]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_a415df_aop577302103] ON [dbo].[AO_A415DF_AOPERMISSION] ([TARGET_ID]) ON [PRIMARY]
GO
