CREATE TABLE [dbo].[AO_D9132D_PLANTHEME]
(
[C_KEY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL,
[ID] [bigint] NOT NULL IDENTITY(1, 1),
[PLAN_ID] [bigint] NULL,
[THEME_ID] [bigint] NULL,
[WEIGHT] [float] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_D9132D_PLANTHEME] ADD CONSTRAINT [pk_AO_D9132D_PLANTHEME_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_D9132D_PLANTHEME] ADD CONSTRAINT [U_AO_D9132D_PLANTHEME_C_KEY] UNIQUE NONCLUSTERED  ([C_KEY]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_d9132d_pla228745504] ON [dbo].[AO_D9132D_PLANTHEME] ([PLAN_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_d9132d_pla2036165122] ON [dbo].[AO_D9132D_PLANTHEME] ([THEME_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_D9132D_PLANTHEME] ADD CONSTRAINT [fk_ao_d9132d_plantheme_plan_id] FOREIGN KEY ([PLAN_ID]) REFERENCES [dbo].[AO_D9132D_PLAN] ([ID])
GO
ALTER TABLE [dbo].[AO_D9132D_PLANTHEME] ADD CONSTRAINT [fk_ao_d9132d_plantheme_theme_id] FOREIGN KEY ([THEME_ID]) REFERENCES [dbo].[AO_D9132D_THEME] ([ID])
GO
