CREATE TABLE [dbo].[AO_54307E_CONFLUENCEKBLABELS]
(
[CONFLUENCE_KBID] [int] NOT NULL,
[FORM_ID] [int] NOT NULL,
[ID] [int] NOT NULL IDENTITY(1, 1),
[LABEL] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[SERVICE_DESK_ID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_54307E_CONFLUENCEKBLABELS] ADD CONSTRAINT [pk_AO_54307E_CONFLUENCEKBLABELS_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_54307e_con714018041] ON [dbo].[AO_54307E_CONFLUENCEKBLABELS] ([CONFLUENCE_KBID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_54307e_con1117703894] ON [dbo].[AO_54307E_CONFLUENCEKBLABELS] ([FORM_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_54307e_con1589156183] ON [dbo].[AO_54307E_CONFLUENCEKBLABELS] ([SERVICE_DESK_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_54307E_CONFLUENCEKBLABELS] ADD CONSTRAINT [fk_ao_54307e_confluencekblabels_confluence_kbid] FOREIGN KEY ([CONFLUENCE_KBID]) REFERENCES [dbo].[AO_54307E_CONFLUENCEKB] ([ID])
GO
ALTER TABLE [dbo].[AO_54307E_CONFLUENCEKBLABELS] ADD CONSTRAINT [fk_ao_54307e_confluencekblabels_form_id] FOREIGN KEY ([FORM_ID]) REFERENCES [dbo].[AO_54307E_VIEWPORTFORM] ([ID])
GO
ALTER TABLE [dbo].[AO_54307E_CONFLUENCEKBLABELS] ADD CONSTRAINT [fk_ao_54307e_confluencekblabels_service_desk_id] FOREIGN KEY ([SERVICE_DESK_ID]) REFERENCES [dbo].[AO_54307E_SERVICEDESK] ([ID])
GO
