CREATE TABLE [dbo].[AO_E8B6CC_ISSUE_TO_BRANCH]
(
[BRANCH_ID] [int] NULL,
[ID] [int] NOT NULL IDENTITY(1, 1),
[ISSUE_KEY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_E8B6CC_ISSUE_TO_BRANCH] ADD CONSTRAINT [pk_AO_E8B6CC_ISSUE_TO_BRANCH_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_e8b6cc_iss1325927291] ON [dbo].[AO_E8B6CC_ISSUE_TO_BRANCH] ([BRANCH_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_e8b6cc_iss353204826] ON [dbo].[AO_E8B6CC_ISSUE_TO_BRANCH] ([ISSUE_KEY]) ON [PRIMARY]
GO
