CREATE TABLE [dbo].[AO_D9132D_SCENARIO_PERSON]
(
[C_KEY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL,
[ID] [bigint] NOT NULL IDENTITY(1, 1),
[ITEM_KEY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL,
[LAST_CHANGE_TIMESTAMP] [bigint] NULL,
[LAST_CHANGE_USER] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[SCENARIO_ID] [bigint] NULL,
[SCENARIO_TYPE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL,
[TITLE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[TITLE_CHANGED] [bit] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_D9132D_SCENARIO_PERSON] ADD CONSTRAINT [pk_AO_D9132D_SCENARIO_PERSON_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_D9132D_SCENARIO_PERSON] ADD CONSTRAINT [U_AO_D9132D_SCENARI1228886055] UNIQUE NONCLUSTERED  ([C_KEY]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_d9132d_sce338333120] ON [dbo].[AO_D9132D_SCENARIO_PERSON] ([ITEM_KEY]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_d9132d_sce1310871043] ON [dbo].[AO_D9132D_SCENARIO_PERSON] ([SCENARIO_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_d9132d_sce1321303140] ON [dbo].[AO_D9132D_SCENARIO_PERSON] ([SCENARIO_TYPE]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_D9132D_SCENARIO_PERSON] ADD CONSTRAINT [fk_ao_d9132d_scenario_person_scenario_id] FOREIGN KEY ([SCENARIO_ID]) REFERENCES [dbo].[AO_D9132D_SCENARIO] ([ID])
GO
