CREATE TABLE [dbo].[AO_54307E_QUEUECOLUMN]
(
[COLUMN_ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[COLUMN_ORDER] [int] NULL,
[ID] [int] NOT NULL IDENTITY(1, 1),
[QUEUE_ID] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_54307E_QUEUECOLUMN] ADD CONSTRAINT [pk_AO_54307E_QUEUECOLUMN_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_54307e_que1582220046] ON [dbo].[AO_54307E_QUEUECOLUMN] ([QUEUE_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_54307E_QUEUECOLUMN] ADD CONSTRAINT [fk_ao_54307e_queuecolumn_queue_id] FOREIGN KEY ([QUEUE_ID]) REFERENCES [dbo].[AO_54307E_QUEUE] ([ID])
GO
