CREATE TABLE [dbo].[JQUARTZ_LOCKS]
(
[SCHED_NAME] [varchar] (120) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[LOCK_NAME] [varchar] (40) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[JQUARTZ_LOCKS] ADD CONSTRAINT [PK_JQUARTZ_LOCKS] PRIMARY KEY CLUSTERED  ([LOCK_NAME]) ON [PRIMARY]
GO
