CREATE TABLE [dbo].[AO_3B1893_LOOP_DETECTION]
(
[COUNTER] [int] NOT NULL CONSTRAINT [df_AO_3B1893_LOOP_DETECTION_COUNTER] DEFAULT ((0)),
[EXPIRES_AT] [bigint] NOT NULL CONSTRAINT [df_AO_3B1893_LOOP_DETECTION_EXPIRES_AT] DEFAULT ((0)),
[ID] [int] NOT NULL IDENTITY(1, 1),
[SENDER_EMAIL] [ntext] COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_3B1893_LOOP_DETECTION] ADD CONSTRAINT [pk_AO_3B1893_LOOP_DETECTION_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
