CREATE TABLE [dbo].[AO_56464C_APPROVERDECISION]
(
[APPROVAL_ID] [int] NULL,
[DECISION] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL,
[ID] [int] NOT NULL IDENTITY(1, 1),
[SENT_DATE] [bigint] NOT NULL,
[USER_KEY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_56464C_APPROVERDECISION] ADD CONSTRAINT [pk_AO_56464C_APPROVERDECISION_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_56464c_app1713999422] ON [dbo].[AO_56464C_APPROVERDECISION] ([APPROVAL_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_56464C_APPROVERDECISION] ADD CONSTRAINT [fk_ao_56464c_approverdecision_approval_id] FOREIGN KEY ([APPROVAL_ID]) REFERENCES [dbo].[AO_56464C_APPROVAL] ([ID])
GO
