CREATE TABLE [dbo].[AO_60DB71_WORKINGDAYS]
(
[FRIDAY] [bit] NOT NULL,
[ID] [bigint] NOT NULL IDENTITY(1, 1),
[MONDAY] [bit] NOT NULL,
[RAPID_VIEW_ID] [bigint] NOT NULL,
[SATURDAY] [bit] NOT NULL,
[SUNDAY] [bit] NOT NULL,
[THURSDAY] [bit] NOT NULL,
[TIMEZONE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL,
[TUESDAY] [bit] NOT NULL,
[WEDNESDAY] [bit] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_60DB71_WORKINGDAYS] ADD CONSTRAINT [pk_AO_60DB71_WORKINGDAYS_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_60db71_wor1205491794] ON [dbo].[AO_60DB71_WORKINGDAYS] ([RAPID_VIEW_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_60DB71_WORKINGDAYS] ADD CONSTRAINT [fk_ao_60db71_workingdays_rapid_view_id] FOREIGN KEY ([RAPID_VIEW_ID]) REFERENCES [dbo].[AO_60DB71_RAPIDVIEW] ([ID])
GO
