CREATE TABLE [dbo].[AO_D9132D_PLAN_CUSTOM_FIELD]
(
[CUSTOM_FIELD_ID] [bigint] NULL,
[C_KEY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL,
[ID] [bigint] NOT NULL IDENTITY(1, 1),
[PLAN_ID] [bigint] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_D9132D_PLAN_CUSTOM_FIELD] ADD CONSTRAINT [pk_AO_D9132D_PLAN_CUSTOM_FIELD_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_D9132D_PLAN_CUSTOM_FIELD] ADD CONSTRAINT [U_AO_D9132D_PLAN_CU1349022185] UNIQUE NONCLUSTERED  ([C_KEY]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_d9132d_pla641747585] ON [dbo].[AO_D9132D_PLAN_CUSTOM_FIELD] ([CUSTOM_FIELD_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_d9132d_pla1111913698] ON [dbo].[AO_D9132D_PLAN_CUSTOM_FIELD] ([PLAN_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_D9132D_PLAN_CUSTOM_FIELD] ADD CONSTRAINT [fk_ao_d9132d_plan_custom_field_plan_id] FOREIGN KEY ([PLAN_ID]) REFERENCES [dbo].[AO_D9132D_PLAN] ([ID])
GO
