CREATE TABLE [dbo].[AO_A415DF_AOSTREAM]
(
[AOPLAN_ID] [int] NULL,
[COLOR] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[DESCRIPTION] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[DETAILS] [ntext] COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[DYNAMIC_START_STREAM] [bit] NULL,
[ID_OTHER] [int] NOT NULL IDENTITY(1, 1),
[ORDER_RANGE_IDENTIFIER] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[SHORT_NAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[SORT_ORDER] [bigint] NULL,
[TITLE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[VERSION] [bigint] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_A415DF_AOSTREAM] ADD CONSTRAINT [pk_AO_A415DF_AOSTREAM_ID_OTHER] PRIMARY KEY CLUSTERED  ([ID_OTHER]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_a415df_aos598285716] ON [dbo].[AO_A415DF_AOSTREAM] ([AOPLAN_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_A415DF_AOSTREAM] ADD CONSTRAINT [fk_ao_a415df_aostream_aoplan_id] FOREIGN KEY ([AOPLAN_ID]) REFERENCES [dbo].[AO_A415DF_AOPLAN] ([ID_OTHER])
GO
