CREATE TABLE [dbo].[AO_D9132D_SCEN_CUSTOM_FIELD]
(
[C_KEY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL,
[DOUBLE_VALUE] [float] NULL,
[ID] [bigint] NOT NULL IDENTITY(1, 1),
[NUMBER_VALUE] [bigint] NULL,
[PLAN_CUSTOM_FIELD_ID] [bigint] NULL,
[SCENARIO_ISSUE_ID] [bigint] NULL,
[STRING_VALUE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[TEXT_VALUE] [ntext] COLLATE SQL_Latin1_General_CP437_CI_AI NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_D9132D_SCEN_CUSTOM_FIELD] ADD CONSTRAINT [pk_AO_D9132D_SCEN_CUSTOM_FIELD_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_D9132D_SCEN_CUSTOM_FIELD] ADD CONSTRAINT [U_AO_D9132D_SCEN_CU98345031] UNIQUE NONCLUSTERED  ([C_KEY]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_d9132d_sce789931767] ON [dbo].[AO_D9132D_SCEN_CUSTOM_FIELD] ([PLAN_CUSTOM_FIELD_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_d9132d_sce1281362417] ON [dbo].[AO_D9132D_SCEN_CUSTOM_FIELD] ([SCENARIO_ISSUE_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_D9132D_SCEN_CUSTOM_FIELD] ADD CONSTRAINT [fk_ao_d9132d_scen_custom_field_plan_custom_field_id] FOREIGN KEY ([PLAN_CUSTOM_FIELD_ID]) REFERENCES [dbo].[AO_D9132D_PLAN_CUSTOM_FIELD] ([ID])
GO
ALTER TABLE [dbo].[AO_D9132D_SCEN_CUSTOM_FIELD] ADD CONSTRAINT [fk_ao_d9132d_scen_custom_field_scenario_issue_id] FOREIGN KEY ([SCENARIO_ISSUE_ID]) REFERENCES [dbo].[AO_D9132D_SCENARIO_ISSUES] ([ID])
GO
