CREATE TABLE [dbo].[AO_E8B6CC_ORGANIZATION_MAPPING]
(
[ACCESS_TOKEN] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[ADMIN_PASSWORD] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[ADMIN_USERNAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[APPROVAL_STATE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[AUTOLINK_NEW_REPOS] [bit] NULL,
[DEFAULT_GROUPS_SLUGS] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[DVCS_TYPE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[HOST_URL] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[ID] [int] NOT NULL IDENTITY(1, 1),
[NAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[OAUTH_KEY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[OAUTH_SECRET] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[PRINCIPAL_ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[SMARTCOMMITS_FOR_NEW_REPOS] [bit] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_E8B6CC_ORGANIZATION_MAPPING] ADD CONSTRAINT [pk_AO_E8B6CC_ORGANIZATION_MAPPING_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_e8b6cc_org1513110290] ON [dbo].[AO_E8B6CC_ORGANIZATION_MAPPING] ([DVCS_TYPE]) ON [PRIMARY]
GO
