CREATE TABLE [dbo].[AO_D9132D_PLANVERSION]
(
[C_KEY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL,
[ID] [bigint] NOT NULL IDENTITY(1, 1),
[PLAN_ID] [bigint] NULL,
[VERSION_ID] [bigint] NULL,
[XPROJECT_VERSION_ID] [bigint] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_D9132D_PLANVERSION] ADD CONSTRAINT [pk_AO_D9132D_PLANVERSION_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_D9132D_PLANVERSION] ADD CONSTRAINT [U_AO_D9132D_PLANVERSION_C_KEY] UNIQUE NONCLUSTERED  ([C_KEY]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_d9132d_pla958319633] ON [dbo].[AO_D9132D_PLANVERSION] ([PLAN_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_d9132d_pla62020034] ON [dbo].[AO_D9132D_PLANVERSION] ([XPROJECT_VERSION_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_D9132D_PLANVERSION] ADD CONSTRAINT [fk_ao_d9132d_planversion_plan_id] FOREIGN KEY ([PLAN_ID]) REFERENCES [dbo].[AO_D9132D_PLAN] ([ID])
GO
ALTER TABLE [dbo].[AO_D9132D_PLANVERSION] ADD CONSTRAINT [fk_ao_d9132d_planversion_xproject_version_id] FOREIGN KEY ([XPROJECT_VERSION_ID]) REFERENCES [dbo].[AO_D9132D_X_PROJECT_VERSION] ([ID])
GO
