CREATE TABLE [dbo].[AO_2C4E5C_MAILHANDLER]
(
[CREATED_TIMESTAMP] [bigint] NULL CONSTRAINT [df_AO_2C4E5C_MAILHANDLER_CREATED_TIMESTAMP] DEFAULT ((0)),
[HANDLER_TYPE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[ID] [int] NOT NULL IDENTITY(1, 1),
[MAIL_CHANNEL_ID] [int] NULL,
[MODULE_COMPLETE_KEY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[UPDATED_TIMESTAMP] [bigint] NULL CONSTRAINT [df_AO_2C4E5C_MAILHANDLER_UPDATED_TIMESTAMP] DEFAULT ((0))
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_2C4E5C_MAILHANDLER] ADD CONSTRAINT [pk_AO_2C4E5C_MAILHANDLER_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_2c4e5c_mai737633864] ON [dbo].[AO_2C4E5C_MAILHANDLER] ([MAIL_CHANNEL_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_2C4E5C_MAILHANDLER] ADD CONSTRAINT [fk_ao_2c4e5c_mailhandler_mail_channel_id] FOREIGN KEY ([MAIL_CHANNEL_ID]) REFERENCES [dbo].[AO_2C4E5C_MAILCHANNEL] ([ID])
GO
