CREATE TABLE [dbo].[AO_D9132D_VERSION_ENRICHMENT]
(
[DELTA] [bigint] NULL,
[ENV_ID] [bigint] NOT NULL,
[ID] [bigint] NOT NULL IDENTITY(1, 1)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_D9132D_VERSION_ENRICHMENT] ADD CONSTRAINT [pk_AO_D9132D_VERSION_ENRICHMENT_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_D9132D_VERSION_ENRICHMENT] ADD CONSTRAINT [U_AO_D9132D_VERSION472426003] UNIQUE NONCLUSTERED  ([ENV_ID]) ON [PRIMARY]
GO
