CREATE TABLE [dbo].[SEQUENCE_VALUE_ITEM]
(
[SEQ_NAME] [nvarchar] (40) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL,
[SEQ_ID] [numeric] (18, 0) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SEQUENCE_VALUE_ITEM] ADD CONSTRAINT [PK_SEQUENCE_VALUE_ITEM] PRIMARY KEY CLUSTERED  ([SEQ_NAME]) ON [PRIMARY]
GO
