CREATE TABLE [dbo].[AO_56464C_NOTIFICATIONRECORD]
(
[APPROVAL_ID] [int] NULL,
[ID] [int] NOT NULL IDENTITY(1, 1),
[SENT_DATE] [bigint] NOT NULL,
[USER_KEY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_56464C_NOTIFICATIONRECORD] ADD CONSTRAINT [pk_AO_56464C_NOTIFICATIONRECORD_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_56464c_not5371299] ON [dbo].[AO_56464C_NOTIFICATIONRECORD] ([APPROVAL_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_56464C_NOTIFICATIONRECORD] ADD CONSTRAINT [fk_ao_56464c_notificationrecord_approval_id] FOREIGN KEY ([APPROVAL_ID]) REFERENCES [dbo].[AO_56464C_APPROVAL] ([ID])
GO
