CREATE TABLE [dbo].[AO_7A2604_HOLIDAY]
(
[CALENDAR_ID] [int] NULL,
[DATE_STRING] [nvarchar] (63) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL,
[ID] [int] NOT NULL IDENTITY(1, 1),
[NAME] [nvarchar] (63) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL,
[RECURRING] [bit] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_7A2604_HOLIDAY] ADD CONSTRAINT [pk_AO_7A2604_HOLIDAY_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_7a2604_hol2069343764] ON [dbo].[AO_7A2604_HOLIDAY] ([CALENDAR_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_7A2604_HOLIDAY] ADD CONSTRAINT [fk_ao_7a2604_holiday_calendar_id] FOREIGN KEY ([CALENDAR_ID]) REFERENCES [dbo].[AO_7A2604_CALENDAR] ([ID])
GO
