CREATE TABLE [dbo].[AO_D9132D_RANK_ITEM]
(
[DOMAIN] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[ID] [bigint] NOT NULL IDENTITY(1, 1),
[KEY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL,
[RANGE_ID] [bigint] NOT NULL CONSTRAINT [df_AO_D9132D_RANK_ITEM_RANGE_ID] DEFAULT ((0)),
[UNIQUE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_D9132D_RANK_ITEM] ADD CONSTRAINT [pk_AO_D9132D_RANK_ITEM_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_d9132d_ran1612448239] ON [dbo].[AO_D9132D_RANK_ITEM] ([DOMAIN]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_d9132d_rank_item_key] ON [dbo].[AO_D9132D_RANK_ITEM] ([KEY]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_d9132d_ran1797004856] ON [dbo].[AO_D9132D_RANK_ITEM] ([RANGE_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_D9132D_RANK_ITEM] ADD CONSTRAINT [U_AO_D9132D_RANK_ITEM_UNIQUE] UNIQUE NONCLUSTERED  ([UNIQUE]) ON [PRIMARY]
GO
