CREATE TABLE [dbo].[AO_54307E_CONFLUENCEKB]
(
[APPLINKS_APPLICATION_ID] [nvarchar] (63) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[APPLINK_NAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[APPLINK_URL] [ntext] COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[ID] [int] NOT NULL IDENTITY(1, 1),
[SERVICE_DESK_ID] [int] NOT NULL,
[SPACE_KEY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[SPACE_NAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[SPACE_URL] [ntext] COLLATE SQL_Latin1_General_CP437_CI_AI NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_54307E_CONFLUENCEKB] ADD CONSTRAINT [pk_AO_54307E_CONFLUENCEKB_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_54307e_con15134888] ON [dbo].[AO_54307E_CONFLUENCEKB] ([SERVICE_DESK_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_54307E_CONFLUENCEKB] ADD CONSTRAINT [fk_ao_54307e_confluencekb_service_desk_id] FOREIGN KEY ([SERVICE_DESK_ID]) REFERENCES [dbo].[AO_54307E_SERVICEDESK] ([ID])
GO
