CREATE TABLE [dbo].[AO_A415DF_AOSKILL]
(
[AOSTAGE_ID] [int] NULL,
[DESCRIPTION] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[DETAILS] [ntext] COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[ID_OTHER] [int] NOT NULL IDENTITY(1, 1),
[ORDER_RANGE_IDENTIFIER] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[PERCENTAGE] [float] NULL,
[SORT_ORDER] [bigint] NULL,
[STAGE_ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[TITLE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[VERSION] [bigint] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_A415DF_AOSKILL] ADD CONSTRAINT [pk_AO_A415DF_AOSKILL_ID_OTHER] PRIMARY KEY CLUSTERED  ([ID_OTHER]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_a415df_aos617973864] ON [dbo].[AO_A415DF_AOSKILL] ([AOSTAGE_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_A415DF_AOSKILL] ADD CONSTRAINT [fk_ao_a415df_aoskill_aostage_id] FOREIGN KEY ([AOSTAGE_ID]) REFERENCES [dbo].[AO_A415DF_AOSTAGE] ([ID_OTHER])
GO
