CREATE TABLE [dbo].[AO_D9132D_X_PROJECT_VERSION]
(
[ID] [bigint] NOT NULL IDENTITY(1, 1),
[PLAN_ID] [bigint] NULL,
[TITLE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_D9132D_X_PROJECT_VERSION] ADD CONSTRAINT [pk_AO_D9132D_X_PROJECT_VERSION_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_d9132d_x_p689485877] ON [dbo].[AO_D9132D_X_PROJECT_VERSION] ([PLAN_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_D9132D_X_PROJECT_VERSION] ADD CONSTRAINT [fk_ao_d9132d_x_project_version_plan_id] FOREIGN KEY ([PLAN_ID]) REFERENCES [dbo].[AO_D9132D_PLAN] ([ID])
GO
