CREATE TABLE [dbo].[AO_54307E_SERIES]
(
[COLOR] [nvarchar] (63) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[CREATED_DATE] [datetime] NULL,
[ID] [int] NOT NULL IDENTITY(1, 1),
[JQL] [ntext] COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[REPORT_ID] [int] NULL,
[SERIES_DATA_TYPE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[SERIES_LABEL] [nvarchar] (63) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[TIME_METRIC_ID] [bigint] NULL,
[UPDATED_DATE] [datetime] NULL,
[GOAL_ID] [int] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_54307E_SERIES] ADD CONSTRAINT [pk_AO_54307E_SERIES_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_54307e_ser315001103] ON [dbo].[AO_54307E_SERIES] ([REPORT_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_54307E_SERIES] ADD CONSTRAINT [fk_ao_54307e_series_report_id] FOREIGN KEY ([REPORT_ID]) REFERENCES [dbo].[AO_54307E_REPORT] ([ID])
GO
