CREATE TABLE [dbo].[AO_60DB71_ISSUERANKINGLOG]
(
[CUSTOM_FIELD_ID] [bigint] NULL,
[ID] [bigint] NOT NULL IDENTITY(1, 1),
[ISSUE_ID] [bigint] NULL,
[LOG_TYPE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[NEW_NEXT_ID] [bigint] NULL,
[NEW_PREVIOUS_ID] [bigint] NULL,
[OLD_NEXT_ID] [bigint] NULL,
[OLD_PREVIOUS_ID] [bigint] NULL,
[SANITY_CHECKED] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_60DB71_ISSUERANKINGLOG] ADD CONSTRAINT [pk_AO_60DB71_ISSUERANKINGLOG_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
