CREATE TABLE [dbo].[AO_54307E_IMAGES]
(
[CONTENTS] [ntext] COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[ID] [int] NOT NULL IDENTITY(1, 1)
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_54307E_IMAGES] ADD CONSTRAINT [pk_AO_54307E_IMAGES_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
