CREATE TABLE [dbo].[AO_82B313_AVAILABILITY]
(
[END] [bigint] NOT NULL,
[ID] [bigint] NOT NULL IDENTITY(1, 1),
[RESOURCE_ID] [bigint] NULL,
[START] [bigint] NOT NULL,
[TITLE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[WEEKLY_HOURS] [float] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_82B313_AVAILABILITY] ADD CONSTRAINT [pk_AO_82B313_AVAILABILITY_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_82b313_ava1174130538] ON [dbo].[AO_82B313_AVAILABILITY] ([RESOURCE_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_82B313_AVAILABILITY] ADD CONSTRAINT [fk_ao_82b313_availability_resource_id] FOREIGN KEY ([RESOURCE_ID]) REFERENCES [dbo].[AO_82B313_RESOURCE] ([ID])
GO
