CREATE TABLE [dbo].[AO_ED669C_SEEN_ASSERTIONS]
(
[ASSERTION_ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL,
[EXPIRY_TIMESTAMP] [bigint] NOT NULL CONSTRAINT [df_AO_ED669C_SEEN_ASSERTIONS_EXPIRY_TIMESTAMP] DEFAULT ((0)),
[ID] [int] NOT NULL IDENTITY(1, 1)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_ED669C_SEEN_ASSERTIONS] ADD CONSTRAINT [pk_AO_ED669C_SEEN_ASSERTIONS_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_ED669C_SEEN_ASSERTIONS] ADD CONSTRAINT [U_AO_ED669C_SEEN_AS1055534769] UNIQUE NONCLUSTERED  ([ASSERTION_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_ed669c_see20117222] ON [dbo].[AO_ED669C_SEEN_ASSERTIONS] ([EXPIRY_TIMESTAMP]) ON [PRIMARY]
GO
