CREATE TABLE [dbo].[AO_7A2604_WORKINGTIME]
(
[CALENDAR_ID] [int] NULL,
[DAY] [nvarchar] (63) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL,
[END_TIME] [bigint] NOT NULL,
[ID] [int] NOT NULL IDENTITY(1, 1),
[START_TIME] [bigint] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_7A2604_WORKINGTIME] ADD CONSTRAINT [pk_AO_7A2604_WORKINGTIME_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_7a2604_wor1607107950] ON [dbo].[AO_7A2604_WORKINGTIME] ([CALENDAR_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_7A2604_WORKINGTIME] ADD CONSTRAINT [fk_ao_7a2604_workingtime_calendar_id] FOREIGN KEY ([CALENDAR_ID]) REFERENCES [dbo].[AO_7A2604_CALENDAR] ([ID])
GO
