CREATE TABLE [dbo].[AO_F1B27B_HISTORY_RECORD]
(
[EVENT_TIME_MILLIS] [bigint] NULL,
[EVENT_TYPE] [nvarchar] (63) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL,
[ID] [int] NOT NULL IDENTITY(1, 1),
[MESSAGE] [nvarchar] (450) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL,
[TARGET_TIME_MILLIS] [bigint] NULL,
[TIMED_PROMISE_HISTORY_KEY_HASH] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_F1B27B_HISTORY_RECORD] ADD CONSTRAINT [pk_AO_F1B27B_HISTORY_RECORD_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
