CREATE TABLE [dbo].[AO_E8B6CC_CHANGESET_MAPPING]
(
[AUTHOR] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[AUTHOR_EMAIL] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[BRANCH] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[DATE] [datetime] NULL,
[FILES_DATA] [ntext] COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[FILE_COUNT] [int] NULL CONSTRAINT [df_AO_E8B6CC_CHANGESET_MAPPING_FILE_COUNT] DEFAULT ((0)),
[FILE_DETAILS_JSON] [ntext] COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[ID] [int] NOT NULL IDENTITY(1, 1),
[ISSUE_KEY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[MESSAGE] [ntext] COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[NODE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[PARENTS_DATA] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[PROJECT_KEY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[RAW_AUTHOR] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[RAW_NODE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[REPOSITORY_ID] [int] NULL CONSTRAINT [df_AO_E8B6CC_CHANGESET_MAPPING_REPOSITORY_ID] DEFAULT ((0)),
[SMARTCOMMIT_AVAILABLE] [bit] NULL,
[VERSION] [int] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_E8B6CC_CHANGESET_MAPPING] ADD CONSTRAINT [pk_AO_E8B6CC_CHANGESET_MAPPING_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_e8b6cc_cha897886051] ON [dbo].[AO_E8B6CC_CHANGESET_MAPPING] ([AUTHOR]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_e8b6cc_cha1483243924] ON [dbo].[AO_E8B6CC_CHANGESET_MAPPING] ([NODE]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_e8b6cc_cha509722037] ON [dbo].[AO_E8B6CC_CHANGESET_MAPPING] ([RAW_NODE]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_e8b6cc_cha1086340152] ON [dbo].[AO_E8B6CC_CHANGESET_MAPPING] ([SMARTCOMMIT_AVAILABLE]) ON [PRIMARY]
GO
