CREATE TABLE [dbo].[AO_563AEE_ACTOR_ENTITY]
(
[FULL_NAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[ID] [int] NOT NULL IDENTITY(1, 1),
[PROFILE_PAGE_URI] [nvarchar] (450) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[PROFILE_PICTURE_URI] [nvarchar] (450) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[USERNAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_563AEE_ACTOR_ENTITY] ADD CONSTRAINT [pk_AO_563AEE_ACTOR_ENTITY_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
