CREATE TABLE [dbo].[JQUARTZ_SIMPROP_TRIGGERS]
(
[SCHED_NAME] [varchar] (120) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[TRIGGER_NAME] [varchar] (200) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL,
[TRIGGER_GROUP] [varchar] (200) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL,
[STR_PROP_1] [varchar] (512) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[STR_PROP_2] [varchar] (512) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[STR_PROP_3] [varchar] (512) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[INT_PROP_1] [int] NULL,
[INT_PROP_2] [int] NULL,
[LONG_PROP_1] [bigint] NULL,
[LONG_PROP_2] [bigint] NULL,
[DEC_PROP_1] [numeric] (13, 4) NULL,
[DEC_PROP_2] [numeric] (13, 4) NULL,
[BOOL_PROP_1] [varchar] (1) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[BOOL_PROP_2] [varchar] (1) COLLATE SQL_Latin1_General_CP437_CI_AI NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[JQUARTZ_SIMPROP_TRIGGERS] ADD CONSTRAINT [PK_JQUARTZ_SIMPROP_TRIGGERS] PRIMARY KEY CLUSTERED  ([TRIGGER_NAME], [TRIGGER_GROUP]) ON [PRIMARY]
GO
