CREATE TABLE [dbo].[AO_60DB71_COLUMN]
(
[ID] [bigint] NOT NULL IDENTITY(1, 1),
[MAXIM] [float] NULL,
[MINIM] [float] NULL,
[NAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[POS] [int] NOT NULL CONSTRAINT [df_AO_60DB71_COLUMN_POS] DEFAULT ((0)),
[RAPID_VIEW_ID] [bigint] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_60DB71_COLUMN] ADD CONSTRAINT [pk_AO_60DB71_COLUMN_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_60db71_col2098611346] ON [dbo].[AO_60DB71_COLUMN] ([RAPID_VIEW_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_60DB71_COLUMN] ADD CONSTRAINT [fk_ao_60db71_column_rapid_view_id] FOREIGN KEY ([RAPID_VIEW_ID]) REFERENCES [dbo].[AO_60DB71_RAPIDVIEW] ([ID])
GO
