CREATE TABLE [dbo].[AO_60DB71_LEXORANK]
(
[FIELD_ID] [bigint] NOT NULL CONSTRAINT [df_AO_60DB71_LEXORANK_FIELD_ID] DEFAULT ((0)),
[ID] [bigint] NOT NULL IDENTITY(1, 1),
[ISSUE_ID] [bigint] NOT NULL CONSTRAINT [df_AO_60DB71_LEXORANK_ISSUE_ID] DEFAULT ((0)),
[LOCK_HASH] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[LOCK_TIME] [bigint] NULL,
[RANK] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL,
[TYPE] [int] NOT NULL CONSTRAINT [df_AO_60DB71_LEXORANK_TYPE] DEFAULT ((0)),
[BUCKET] [int] NULL CONSTRAINT [df_AO_60DB71_LEXORANK_BUCKET] DEFAULT ((0))
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_60DB71_LEXORANK] ADD CONSTRAINT [pk_AO_60DB71_LEXORANK_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_60db71_lex1694305086] ON [dbo].[AO_60DB71_LEXORANK] ([FIELD_ID], [BUCKET], [RANK]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_60db71_lex1569533973] ON [dbo].[AO_60DB71_LEXORANK] ([FIELD_ID], [RANK]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_60db71_lex604083109] ON [dbo].[AO_60DB71_LEXORANK] ([ISSUE_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_60db71_lex1632828616] ON [dbo].[AO_60DB71_LEXORANK] ([LOCK_HASH]) ON [PRIMARY]
GO
