CREATE TABLE [dbo].[AO_C7F17E_LINGO]
(
[CATEGORY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[CREATED_TIMESTAMP] [bigint] NOT NULL,
[ID] [bigint] NOT NULL IDENTITY(1, 1),
[LOGICAL_ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[PROJECT_ID] [bigint] NULL,
[SYSTEM_I18N] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_C7F17E_LINGO] ADD CONSTRAINT [pk_AO_C7F17E_LINGO_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_c7f17e_lin614942907] ON [dbo].[AO_C7F17E_LINGO] ([LOGICAL_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_c7f17e_lin523964875] ON [dbo].[AO_C7F17E_LINGO] ([PROJECT_ID]) ON [PRIMARY]
GO
