CREATE TABLE [dbo].[AO_54307E_PARTICIPANTSETTINGS]
(
[AUTOCOMPLETE_ENABLED] [bit] NULL,
[ID] [int] NOT NULL IDENTITY(1, 1),
[MANAGE_ENABLED] [bit] NULL,
[SERVICE_DESK_ID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_54307E_PARTICIPANTSETTINGS] ADD CONSTRAINT [pk_AO_54307E_PARTICIPANTSETTINGS_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_54307e_par1577879197] ON [dbo].[AO_54307E_PARTICIPANTSETTINGS] ([SERVICE_DESK_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_54307E_PARTICIPANTSETTINGS] ADD CONSTRAINT [fk_ao_54307e_participantsettings_service_desk_id] FOREIGN KEY ([SERVICE_DESK_ID]) REFERENCES [dbo].[AO_54307E_SERVICEDESK] ([ID])
GO
