CREATE TABLE [dbo].[AO_9B2E3B_RULE]
(
[ID] [bigint] NOT NULL IDENTITY(1, 1),
[ORDINAL] [int] NOT NULL,
[RULESET_REVISION_ID] [bigint] NOT NULL,
[ENABLED] [bit] NOT NULL CONSTRAINT [df_AO_9B2E3B_RULE_ENABLED] DEFAULT ((1))
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_9B2E3B_RULE] ADD CONSTRAINT [pk_AO_9B2E3B_RULE_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_9b2e3b_rul1074875245] ON [dbo].[AO_9B2E3B_RULE] ([RULESET_REVISION_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_9B2E3B_RULE] ADD CONSTRAINT [fk_ao_9b2e3b_rule_ruleset_revision_id] FOREIGN KEY ([RULESET_REVISION_ID]) REFERENCES [dbo].[AO_9B2E3B_RULESET_REVISION] ([ID])
GO
