CREATE TABLE [dbo].[JQUARTZ_JOB_LISTENERS]
(
[JOB_NAME] [varchar] (200) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL,
[JOB_GROUP] [varchar] (200) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL,
[JOB_LISTENER] [varchar] (200) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[JQUARTZ_JOB_LISTENERS] ADD CONSTRAINT [PK_JQUARTZ_JOB_LISTENERS] PRIMARY KEY CLUSTERED  ([JOB_NAME], [JOB_GROUP], [JOB_LISTENER]) ON [PRIMARY]
GO
