CREATE TABLE [dbo].[AO_0201F0_STATS_EVENT]
(
[EVENT_KEY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[EVENT_TIME] [bigint] NULL,
[ID] [bigint] NOT NULL IDENTITY(1, 1)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_0201F0_STATS_EVENT] ADD CONSTRAINT [pk_AO_0201F0_STATS_EVENT_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
