CREATE TABLE [dbo].[AO_D9132D_PLAN]
(
[ASSIGNEE_SCHEDULING_LEVEL] [bigint] NULL CONSTRAINT [df_AO_D9132D_PLAN_ASSIGNEE_SCHEDULING_LEVEL] DEFAULT ((0)),
[COMMIT_ISSUE_ASSIGNEE] [int] NULL,
[DEFAULT_ESTIMATES] [ntext] COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[DEFAULT_TEAM_WEEKLY_CAPACITY] [float] NULL CONSTRAINT [df_AO_D9132D_PLAN_DEFAULT_TEAM_WEEKLY_CAPACITY] DEFAULT ((0.0)),
[DEF_EST_MAP] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[DEPENDENCY_MODE] [bigint] NULL,
[GLOBAL_DEFAULT_VELOCITY] [float] NULL CONSTRAINT [df_AO_D9132D_PLAN_GLOBAL_DEFAULT_VELOCITY] DEFAULT ((0.0)),
[GLOBAL_SPRINT_LENGTH] [int] NULL CONSTRAINT [df_AO_D9132D_PLAN_GLOBAL_SPRINT_LENGTH] DEFAULT ((0)),
[HAS_SPRINT_CONSTRAINT] [int] NULL CONSTRAINT [df_AO_D9132D_PLAN_HAS_SPRINT_CONSTRAINT] DEFAULT ((0)),
[HEURISTIC_THRESHOLD] [int] NULL CONSTRAINT [df_AO_D9132D_PLAN_HEURISTIC_THRESHOLD] DEFAULT ((0)),
[HOURS_PER_DAY] [float] NULL CONSTRAINT [df_AO_D9132D_PLAN_HOURS_PER_DAY] DEFAULT ((0.0)),
[ID] [bigint] NOT NULL IDENTITY(1, 1),
[MAX_RESOURCES_PER_STORY] [bigint] NULL CONSTRAINT [df_AO_D9132D_PLAN_MAX_RESOURCES_PER_STORY] DEFAULT ((0)),
[MIN_LOAD_UNSTR_EPICS] [bigint] NULL CONSTRAINT [df_AO_D9132D_PLAN_MIN_LOAD_UNSTR_EPICS] DEFAULT ((0)),
[PLANNING_UNIT] [bigint] NULL,
[SCHEDULING_VERBOSITY] [bigint] NULL CONSTRAINT [df_AO_D9132D_PLAN_SCHEDULING_VERBOSITY] DEFAULT ((0)),
[SPRINT_EXCEEDED_WARN] [int] NULL CONSTRAINT [df_AO_D9132D_PLAN_SPRINT_EXCEEDED_WARN] DEFAULT ((0)),
[STRICT_STAGE_DIVISION] [int] NULL CONSTRAINT [df_AO_D9132D_PLAN_STRICT_STAGE_DIVISION] DEFAULT ((0)),
[SYNC_START_ENABLED] [int] NULL CONSTRAINT [df_AO_D9132D_PLAN_SYNC_START_ENABLED] DEFAULT ((0)),
[TITLE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[UNESTIMATED_ISSUES_OPTION] [bigint] NULL CONSTRAINT [df_AO_D9132D_PLAN_UNESTIMATED_ISSUES_OPTION] DEFAULT ((0)),
[WEEKDAY_CONFIGURATION] [int] NULL CONSTRAINT [df_AO_D9132D_PLAN_WEEKDAY_CONFIGURATION] DEFAULT ((0))
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_D9132D_PLAN] ADD CONSTRAINT [pk_AO_D9132D_PLAN_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
