CREATE TABLE [dbo].[AO_563AEE_OBJECT_ENTITY]
(
[CONTENT] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[DISPLAY_NAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[ID] [int] NOT NULL IDENTITY(1, 1),
[IMAGE_ID] [int] NULL,
[OBJECT_ID] [nvarchar] (450) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[OBJECT_TYPE] [nvarchar] (450) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[SUMMARY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[URL] [nvarchar] (450) COLLATE SQL_Latin1_General_CP437_CI_AI NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_563AEE_OBJECT_ENTITY] ADD CONSTRAINT [pk_AO_563AEE_OBJECT_ENTITY_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_563aee_obj696886343] ON [dbo].[AO_563AEE_OBJECT_ENTITY] ([IMAGE_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_563AEE_OBJECT_ENTITY] ADD CONSTRAINT [fk_ao_563aee_object_entity_image_id] FOREIGN KEY ([IMAGE_ID]) REFERENCES [dbo].[AO_563AEE_MEDIA_LINK_ENTITY] ([ID])
GO
