CREATE TABLE [dbo].[AO_D9132D_PERMISSIONS]
(
[HOLDER_KEY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL,
[HOLDER_TYPE] [int] NOT NULL CONSTRAINT [df_AO_D9132D_PERMISSIONS_HOLDER_TYPE] DEFAULT ((0)),
[ID] [bigint] NOT NULL IDENTITY(1, 1),
[PERMISSION] [int] NOT NULL CONSTRAINT [df_AO_D9132D_PERMISSIONS_PERMISSION] DEFAULT ((0)),
[PLAN_ID] [bigint] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_D9132D_PERMISSIONS] ADD CONSTRAINT [pk_AO_D9132D_PERMISSIONS_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_d9132d_per1164836380] ON [dbo].[AO_D9132D_PERMISSIONS] ([PLAN_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_D9132D_PERMISSIONS] ADD CONSTRAINT [fk_ao_d9132d_permissions_plan_id] FOREIGN KEY ([PLAN_ID]) REFERENCES [dbo].[AO_D9132D_PLAN] ([ID])
GO
