CREATE TABLE [dbo].[AO_E8B6CC_COMMIT]
(
[AUTHOR] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[AUTHOR_AVATAR_URL] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[DATE] [datetime] NOT NULL,
[DOMAIN_ID] [int] NOT NULL CONSTRAINT [df_AO_E8B6CC_COMMIT_DOMAIN_ID] DEFAULT ((0)),
[ID] [int] NOT NULL IDENTITY(1, 1),
[MERGE] [bit] NULL,
[MESSAGE] [ntext] COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[NODE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[RAW_AUTHOR] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_E8B6CC_COMMIT] ADD CONSTRAINT [pk_AO_E8B6CC_COMMIT_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_e8b6cc_com1308336834] ON [dbo].[AO_E8B6CC_COMMIT] ([DOMAIN_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_e8b6cc_commit_node] ON [dbo].[AO_E8B6CC_COMMIT] ([NODE]) ON [PRIMARY]
GO
