CREATE TABLE [dbo].[AO_60DB71_AUDITENTRY]
(
[CATEGORY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL,
[DATA] [ntext] COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL,
[ENTITY_CLASS] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL,
[ENTITY_ID] [bigint] NOT NULL,
[ID] [bigint] NOT NULL IDENTITY(1, 1),
[TIME] [bigint] NULL,
[USER] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_60DB71_AUDITENTRY] ADD CONSTRAINT [pk_AO_60DB71_AUDITENTRY_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_60db71_aud1756477597] ON [dbo].[AO_60DB71_AUDITENTRY] ([CATEGORY]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_60db71_aud137736645] ON [dbo].[AO_60DB71_AUDITENTRY] ([ENTITY_CLASS]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_60db71_aud604788536] ON [dbo].[AO_60DB71_AUDITENTRY] ([ENTITY_ID]) ON [PRIMARY]
GO
