CREATE TABLE [dbo].[AO_A415DF_AOSPRINT]
(
[AOTEAM_ID] [int] NULL,
[DESCRIPTION] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[DETAILS] [ntext] COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[END_DATE] [bigint] NULL,
[ID_OTHER] [int] NOT NULL IDENTITY(1, 1),
[ORDER_RANGE_IDENTIFIER] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[SORT_ORDER] [bigint] NULL,
[START_DATE] [bigint] NULL,
[TITLE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[VERSION] [bigint] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_A415DF_AOSPRINT] ADD CONSTRAINT [pk_AO_A415DF_AOSPRINT_ID_OTHER] PRIMARY KEY CLUSTERED  ([ID_OTHER]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_a415df_aos1271634950] ON [dbo].[AO_A415DF_AOSPRINT] ([AOTEAM_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_A415DF_AOSPRINT] ADD CONSTRAINT [fk_ao_a415df_aosprint_aoteam_id] FOREIGN KEY ([AOTEAM_ID]) REFERENCES [dbo].[AO_A415DF_AOTEAM] ([ID_OTHER])
GO
