CREATE TABLE [dbo].[AO_7A2604_CALENDAR]
(
[CONTEXT] [ntext] COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL,
[ID] [int] NOT NULL IDENTITY(1, 1),
[NAME] [nvarchar] (63) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL,
[TIMEZONE] [nvarchar] (63) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_7A2604_CALENDAR] ADD CONSTRAINT [pk_AO_7A2604_CALENDAR_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
