CREATE TABLE [dbo].[AO_2C4E5C_MAILITEMCHUNK]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[MAIL_ITEM_ID] [int] NULL,
[MIME_MSG_CHUNK] [ntext] COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[MIME_MSG_CHUNK_IDX] [int] NULL CONSTRAINT [df_AO_2C4E5C_MAILITEMCHUNK_MIME_MSG_CHUNK_IDX] DEFAULT ((0))
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_2C4E5C_MAILITEMCHUNK] ADD CONSTRAINT [pk_AO_2C4E5C_MAILITEMCHUNK_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_2c4e5c_mai9620346] ON [dbo].[AO_2C4E5C_MAILITEMCHUNK] ([MAIL_ITEM_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_2C4E5C_MAILITEMCHUNK] ADD CONSTRAINT [fk_ao_2c4e5c_mailitemchunk_mail_item_id] FOREIGN KEY ([MAIL_ITEM_ID]) REFERENCES [dbo].[AO_2C4E5C_MAILITEM] ([ID])
GO
