CREATE TABLE [dbo].[AO_A415DF_AOEXTENSION_LINK]
(
[AOEXTENDABLE_ID] [int] NULL,
[AOEXTENDABLE_TYPE] [nvarchar] (127) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[EXTENSION_KEY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[EXTENSION_LINK] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[ID_OTHER] [int] NOT NULL IDENTITY(1, 1),
[VERSION] [bigint] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_A415DF_AOEXTENSION_LINK] ADD CONSTRAINT [pk_AO_A415DF_AOEXTENSION_LINK_ID_OTHER] PRIMARY KEY CLUSTERED  ([ID_OTHER]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_a415df_aoe449475677] ON [dbo].[AO_A415DF_AOEXTENSION_LINK] ([AOEXTENDABLE_ID]) ON [PRIMARY]
GO
