CREATE TABLE [dbo].[JQUARTZ_SCHEDULER_STATE]
(
[SCHED_NAME] [varchar] (120) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[INSTANCE_NAME] [varchar] (200) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL,
[LAST_CHECKIN_TIME] [bigint] NULL,
[CHECKIN_INTERVAL] [bigint] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[JQUARTZ_SCHEDULER_STATE] ADD CONSTRAINT [PK_JQUARTZ_SCHEDULER_STATE] PRIMARY KEY CLUSTERED  ([INSTANCE_NAME]) ON [PRIMARY]
GO
