CREATE TABLE [dbo].[AO_82B313_PERSON]
(
[AVATAR_URL] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[END] [bigint] NULL,
[ID] [bigint] NOT NULL IDENTITY(1, 1),
[JIRA_USER_ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[START] [bigint] NULL,
[TITLE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_82B313_PERSON] ADD CONSTRAINT [pk_AO_82B313_PERSON_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_82b313_per1958357978] ON [dbo].[AO_82B313_PERSON] ([JIRA_USER_ID]) ON [PRIMARY]
GO
