CREATE TABLE [dbo].[AO_60DB71_ESTIMATESTATISTIC]
(
[FIELD_ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[ID] [bigint] NOT NULL IDENTITY(1, 1),
[RAPID_VIEW_ID] [bigint] NOT NULL,
[TYPE_ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_60DB71_ESTIMATESTATISTIC] ADD CONSTRAINT [pk_AO_60DB71_ESTIMATESTATISTIC_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_60db71_est1680565966] ON [dbo].[AO_60DB71_ESTIMATESTATISTIC] ([RAPID_VIEW_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_60DB71_ESTIMATESTATISTIC] ADD CONSTRAINT [fk_ao_60db71_estimatestatistic_rapid_view_id] FOREIGN KEY ([RAPID_VIEW_ID]) REFERENCES [dbo].[AO_60DB71_RAPIDVIEW] ([ID])
GO
