CREATE TABLE [dbo].[AO_D9132D_ISSUE_SOURCE]
(
[CONVERSION_FACTOR] [float] NULL,
[ID] [bigint] NOT NULL IDENTITY(1, 1),
[PLAN_ID] [bigint] NULL,
[SOURCE_TYPE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[SOURCE_VALUE] [ntext] COLLATE SQL_Latin1_General_CP437_CI_AI NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_D9132D_ISSUE_SOURCE] ADD CONSTRAINT [pk_AO_D9132D_ISSUE_SOURCE_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_d9132d_iss1919689979] ON [dbo].[AO_D9132D_ISSUE_SOURCE] ([PLAN_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_D9132D_ISSUE_SOURCE] ADD CONSTRAINT [fk_ao_d9132d_issue_source_plan_id] FOREIGN KEY ([PLAN_ID]) REFERENCES [dbo].[AO_D9132D_PLAN] ([ID])
GO
