CREATE TABLE [dbo].[AO_97EDAB_USERINVITATION]
(
[APPLICATION_KEYS] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[EMAIL_ADDRESS] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[EXPIRY] [datetime] NULL,
[ID] [int] NOT NULL IDENTITY(1, 1),
[REDEEMED] [bit] NULL,
[SENDER_USERNAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[TOKEN] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_97EDAB_USERINVITATION] ADD CONSTRAINT [pk_AO_97EDAB_USERINVITATION_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
