CREATE TABLE [dbo].[AO_A415DF_AOSTREAM_TO_TEAM]
(
[AOSTREAM_ID] [int] NULL,
[AOTEAM_ID] [int] NULL,
[ID_OTHER] [int] NOT NULL IDENTITY(1, 1),
[VERSION] [bigint] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_A415DF_AOSTREAM_TO_TEAM] ADD CONSTRAINT [pk_AO_A415DF_AOSTREAM_TO_TEAM_ID_OTHER] PRIMARY KEY CLUSTERED  ([ID_OTHER]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_a415df_aos495640191] ON [dbo].[AO_A415DF_AOSTREAM_TO_TEAM] ([AOSTREAM_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_a415df_aos562466878] ON [dbo].[AO_A415DF_AOSTREAM_TO_TEAM] ([AOTEAM_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_A415DF_AOSTREAM_TO_TEAM] ADD CONSTRAINT [fk_ao_a415df_aostream_to_team_aostream_id] FOREIGN KEY ([AOSTREAM_ID]) REFERENCES [dbo].[AO_A415DF_AOSTREAM] ([ID_OTHER])
GO
ALTER TABLE [dbo].[AO_A415DF_AOSTREAM_TO_TEAM] ADD CONSTRAINT [fk_ao_a415df_aostream_to_team_aoteam_id] FOREIGN KEY ([AOTEAM_ID]) REFERENCES [dbo].[AO_A415DF_AOTEAM] ([ID_OTHER])
GO
