CREATE TABLE [dbo].[JQUARTZ_TRIGGER_LISTENERS]
(
[TRIGGER_NAME] [varchar] (200) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[TRIGGER_GROUP] [varchar] (200) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL,
[TRIGGER_LISTENER] [varchar] (200) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[JQUARTZ_TRIGGER_LISTENERS] ADD CONSTRAINT [PK_JQUARTZ_TRIGGER_LISTENERS] PRIMARY KEY CLUSTERED  ([TRIGGER_GROUP], [TRIGGER_LISTENER]) ON [PRIMARY]
GO
