CREATE TABLE [dbo].[AO_A415DF_AOWORK_ITEM]
(
[AOBUSINESS_VALUE] [float] NULL,
[AOEARLIEST_START] [bigint] NULL,
[AOPARENT_ID] [int] NULL,
[AOPLAN_ID] [int] NULL,
[AORELEASE_ID] [int] NULL,
[AOSPRINT_ID] [int] NULL,
[AOSTREAM_ID] [int] NULL,
[AOTARGET_END] [bigint] NULL,
[AOTARGET_START] [bigint] NULL,
[AOTEAM_ID] [int] NULL,
[AOTHEME_ID] [int] NULL,
[DESCRIPTION] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[DETAILS] [ntext] COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[EARLIEST_START] [bigint] NULL,
[HAS_ORIGINAL_ESTIMATES] [bit] NULL,
[ID_OTHER] [int] NOT NULL IDENTITY(1, 1),
[ORDER_RANGE_IDENTIFIER] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[PARENT_ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[REPLANNING_STATUS] [int] NULL,
[SORT_ORDER] [bigint] NULL,
[STATUS] [int] NULL,
[TITLE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[TYPE] [int] NULL,
[VERSION] [bigint] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_A415DF_AOWORK_ITEM] ADD CONSTRAINT [pk_AO_A415DF_AOWORK_ITEM_ID_OTHER] PRIMARY KEY CLUSTERED  ([ID_OTHER]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_a415df_aow1337278188] ON [dbo].[AO_A415DF_AOWORK_ITEM] ([AOPARENT_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_a415df_aow1728248629] ON [dbo].[AO_A415DF_AOWORK_ITEM] ([AOPLAN_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_a415df_aow221278351] ON [dbo].[AO_A415DF_AOWORK_ITEM] ([AORELEASE_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_a415df_aow1977806428] ON [dbo].[AO_A415DF_AOWORK_ITEM] ([AOSPRINT_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_a415df_aow571736702] ON [dbo].[AO_A415DF_AOWORK_ITEM] ([AOSTREAM_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_a415df_aow782862209] ON [dbo].[AO_A415DF_AOWORK_ITEM] ([AOTEAM_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_a415df_aow1276121741] ON [dbo].[AO_A415DF_AOWORK_ITEM] ([AOTHEME_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_a415df_aow1085872694] ON [dbo].[AO_A415DF_AOWORK_ITEM] ([ORDER_RANGE_IDENTIFIER]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_A415DF_AOWORK_ITEM] ADD CONSTRAINT [fk_ao_a415df_aowork_item_aoparent_id] FOREIGN KEY ([AOPARENT_ID]) REFERENCES [dbo].[AO_A415DF_AOWORK_ITEM] ([ID_OTHER])
GO
ALTER TABLE [dbo].[AO_A415DF_AOWORK_ITEM] ADD CONSTRAINT [fk_ao_a415df_aowork_item_aoplan_id] FOREIGN KEY ([AOPLAN_ID]) REFERENCES [dbo].[AO_A415DF_AOPLAN] ([ID_OTHER])
GO
ALTER TABLE [dbo].[AO_A415DF_AOWORK_ITEM] ADD CONSTRAINT [fk_ao_a415df_aowork_item_aorelease_id] FOREIGN KEY ([AORELEASE_ID]) REFERENCES [dbo].[AO_A415DF_AORELEASE] ([ID_OTHER])
GO
ALTER TABLE [dbo].[AO_A415DF_AOWORK_ITEM] ADD CONSTRAINT [fk_ao_a415df_aowork_item_aosprint_id] FOREIGN KEY ([AOSPRINT_ID]) REFERENCES [dbo].[AO_A415DF_AOSPRINT] ([ID_OTHER])
GO
ALTER TABLE [dbo].[AO_A415DF_AOWORK_ITEM] ADD CONSTRAINT [fk_ao_a415df_aowork_item_aostream_id] FOREIGN KEY ([AOSTREAM_ID]) REFERENCES [dbo].[AO_A415DF_AOSTREAM] ([ID_OTHER])
GO
ALTER TABLE [dbo].[AO_A415DF_AOWORK_ITEM] ADD CONSTRAINT [fk_ao_a415df_aowork_item_aoteam_id] FOREIGN KEY ([AOTEAM_ID]) REFERENCES [dbo].[AO_A415DF_AOTEAM] ([ID_OTHER])
GO
ALTER TABLE [dbo].[AO_A415DF_AOWORK_ITEM] ADD CONSTRAINT [fk_ao_a415df_aowork_item_aotheme_id] FOREIGN KEY ([AOTHEME_ID]) REFERENCES [dbo].[AO_A415DF_AOTHEME] ([ID_OTHER])
GO
