CREATE TABLE [dbo].[AO_D9132D_HIERARCHY_CONFIG]
(
[ICON_URL] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[ID] [bigint] NOT NULL IDENTITY(1, 1),
[ISSUE_TYPE_IDS] [ntext] COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[TITLE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_D9132D_HIERARCHY_CONFIG] ADD CONSTRAINT [pk_AO_D9132D_HIERARCHY_CONFIG_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
