CREATE TABLE [dbo].[AO_E8B6CC_SYNC_EVENT]
(
[EVENT_CLASS] [ntext] COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL,
[EVENT_DATE] [datetime] NOT NULL,
[EVENT_JSON] [ntext] COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL,
[ID] [int] NOT NULL IDENTITY(1, 1),
[REPO_ID] [int] NOT NULL CONSTRAINT [df_AO_E8B6CC_SYNC_EVENT_REPO_ID] DEFAULT ((0)),
[SCHEDULED_SYNC] [bit] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_E8B6CC_SYNC_EVENT] ADD CONSTRAINT [pk_AO_E8B6CC_SYNC_EVENT_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_e8b6cc_syn493078035] ON [dbo].[AO_E8B6CC_SYNC_EVENT] ([REPO_ID]) ON [PRIMARY]
GO
