CREATE TABLE [dbo].[AO_D9132D_SCENARIO_AVLBLTY]
(
[END] [bigint] NULL,
[ID] [bigint] NOT NULL IDENTITY(1, 1),
[SCENARIO_RESOURCE_ID] [bigint] NULL,
[START] [bigint] NULL,
[TITLE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[WEEKLY_HOURS] [float] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_D9132D_SCENARIO_AVLBLTY] ADD CONSTRAINT [pk_AO_D9132D_SCENARIO_AVLBLTY_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_d9132d_sce175198003] ON [dbo].[AO_D9132D_SCENARIO_AVLBLTY] ([SCENARIO_RESOURCE_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_D9132D_SCENARIO_AVLBLTY] ADD CONSTRAINT [fk_ao_d9132d_scenario_avlblty_scenario_resource_id] FOREIGN KEY ([SCENARIO_RESOURCE_ID]) REFERENCES [dbo].[AO_D9132D_SCENARIO_RESOURCE] ([ID])
GO
