CREATE TABLE [dbo].[AO_54307E_GROUP]
(
[GROUP_NAME] [nvarchar] (127) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[ID] [int] NOT NULL IDENTITY(1, 1),
[VIEWPORT_ID] [int] NULL,
[DELETED_TIME] [bigint] NULL,
[ORDER] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_54307E_GROUP] ADD CONSTRAINT [pk_AO_54307E_GROUP_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_54307e_gro236699933] ON [dbo].[AO_54307E_GROUP] ([VIEWPORT_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_54307E_GROUP] ADD CONSTRAINT [fk_ao_54307e_group_viewport_id] FOREIGN KEY ([VIEWPORT_ID]) REFERENCES [dbo].[AO_54307E_VIEWPORT] ([ID])
GO
