CREATE TABLE [dbo].[AO_54307E_THRESHOLD]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[REMAINING_TIME] [bigint] NOT NULL,
[TIME_METRIC_ID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_54307E_THRESHOLD] ADD CONSTRAINT [pk_AO_54307E_THRESHOLD_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_54307e_thr78312131] ON [dbo].[AO_54307E_THRESHOLD] ([TIME_METRIC_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_54307E_THRESHOLD] ADD CONSTRAINT [fk_ao_54307e_threshold_time_metric_id] FOREIGN KEY ([TIME_METRIC_ID]) REFERENCES [dbo].[AO_54307E_TIMEMETRIC] ([ID])
GO
