CREATE TABLE [dbo].[AO_319474_QUEUE]
(
[CLAIMANT] [nvarchar] (127) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[CLAIMANT_TIME] [bigint] NULL,
[CREATED_TIME] [bigint] NOT NULL,
[ID] [bigint] NOT NULL IDENTITY(1, 1),
[MESSAGE_COUNT] [bigint] NOT NULL,
[MODIFIED_TIME] [bigint] NOT NULL,
[NAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL,
[PURPOSE] [nvarchar] (450) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL,
[TOPIC] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_319474_QUEUE] ADD CONSTRAINT [pk_AO_319474_QUEUE_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_319474_queue_claimant] ON [dbo].[AO_319474_QUEUE] ([CLAIMANT]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_319474_QUEUE] ADD CONSTRAINT [U_AO_319474_QUEUE_NAME] UNIQUE NONCLUSTERED  ([NAME]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_319474_queue_topic] ON [dbo].[AO_319474_QUEUE] ([TOPIC]) ON [PRIMARY]
GO
