CREATE TABLE [dbo].[AO_9B2E3B_RSETREV_USER_CONTEXT]
(
[ID] [bigint] NOT NULL IDENTITY(1, 1),
[RULESET_REVISION_ID] [bigint] NOT NULL,
[STRATEGY] [nvarchar] (127) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL,
[USER_KEY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_9B2E3B_RSETREV_USER_CONTEXT] ADD CONSTRAINT [pk_AO_9B2E3B_RSETREV_USER_CONTEXT_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_9b2e3b_rse1331505122] ON [dbo].[AO_9B2E3B_RSETREV_USER_CONTEXT] ([RULESET_REVISION_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_9B2E3B_RSETREV_USER_CONTEXT] ADD CONSTRAINT [fk_ao_9b2e3b_rsetrev_user_context_ruleset_revision_id] FOREIGN KEY ([RULESET_REVISION_ID]) REFERENCES [dbo].[AO_9B2E3B_RULESET_REVISION] ([ID])
GO
