CREATE TABLE [dbo].[AO_60DB71_NONWORKINGDAY]
(
[ID] [bigint] NOT NULL IDENTITY(1, 1),
[ISO8601_DATE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL,
[WORKING_DAYS_ID] [bigint] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_60DB71_NONWORKINGDAY] ADD CONSTRAINT [pk_AO_60DB71_NONWORKINGDAY_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_60db71_non1145824037] ON [dbo].[AO_60DB71_NONWORKINGDAY] ([WORKING_DAYS_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_60DB71_NONWORKINGDAY] ADD CONSTRAINT [fk_ao_60db71_nonworkingday_working_days_id] FOREIGN KEY ([WORKING_DAYS_ID]) REFERENCES [dbo].[AO_60DB71_WORKINGDAYS] ([ID])
GO
