CREATE TABLE [dbo].[AO_54307E_EMAILSETTINGS]
(
[EMAIL_ADDRESS] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[ENABLED] [bit] NULL,
[ID] [int] NOT NULL IDENTITY(1, 1),
[JIRA_MAIL_SERVER_ID] [bigint] NOT NULL,
[LAST_PROCEEDED_TIME] [bigint] NULL,
[ON_DEMAND] [bit] NULL,
[REQUEST_TYPE_ID] [int] NOT NULL,
[SERVICE_DESK_ID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_54307E_EMAILSETTINGS] ADD CONSTRAINT [pk_AO_54307E_EMAILSETTINGS_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_54307e_ema1700110113] ON [dbo].[AO_54307E_EMAILSETTINGS] ([REQUEST_TYPE_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_54307e_ema648278202] ON [dbo].[AO_54307E_EMAILSETTINGS] ([SERVICE_DESK_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_54307E_EMAILSETTINGS] ADD CONSTRAINT [fk_ao_54307e_emailsettings_request_type_id] FOREIGN KEY ([REQUEST_TYPE_ID]) REFERENCES [dbo].[AO_54307E_VIEWPORTFORM] ([ID])
GO
ALTER TABLE [dbo].[AO_54307E_EMAILSETTINGS] ADD CONSTRAINT [fk_ao_54307e_emailsettings_service_desk_id] FOREIGN KEY ([SERVICE_DESK_ID]) REFERENCES [dbo].[AO_54307E_SERVICEDESK] ([ID])
GO
