CREATE TABLE [dbo].[AO_D9132D_NONWORKINGDAYS]
(
[END] [bigint] NULL,
[ID] [bigint] NOT NULL IDENTITY(1, 1),
[PLAN_ID] [bigint] NULL,
[START] [bigint] NULL,
[TITLE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_D9132D_NONWORKINGDAYS] ADD CONSTRAINT [pk_AO_D9132D_NONWORKINGDAYS_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_d9132d_non561724511] ON [dbo].[AO_D9132D_NONWORKINGDAYS] ([PLAN_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_D9132D_NONWORKINGDAYS] ADD CONSTRAINT [fk_ao_d9132d_nonworkingdays_plan_id] FOREIGN KEY ([PLAN_ID]) REFERENCES [dbo].[AO_D9132D_PLAN] ([ID])
GO
