CREATE TABLE [dbo].[AO_A44657_HEALTH_CHECK_ENTITY]
(
[ID] [int] NOT NULL IDENTITY(1, 1)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_A44657_HEALTH_CHECK_ENTITY] ADD CONSTRAINT [pk_AO_A44657_HEALTH_CHECK_ENTITY_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
