CREATE TABLE [dbo].[AO_54307E_VIEWPORTFIELDVALUE]
(
[FIELD_ID] [int] NULL,
[FIELD_NAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[ID] [int] NOT NULL IDENTITY(1, 1),
[VALUE] [ntext] COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[VALUE_ORDER] [int] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_54307E_VIEWPORTFIELDVALUE] ADD CONSTRAINT [pk_AO_54307E_VIEWPORTFIELDVALUE_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_54307e_vie1674919217] ON [dbo].[AO_54307E_VIEWPORTFIELDVALUE] ([FIELD_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_54307E_VIEWPORTFIELDVALUE] ADD CONSTRAINT [fk_ao_54307e_viewportfieldvalue_field_id] FOREIGN KEY ([FIELD_ID]) REFERENCES [dbo].[AO_54307E_VIEWPORTFIELD] ([ID])
GO
