CREATE TABLE [dbo].[AO_E8B6CC_PR_PARTICIPANT]
(
[APPROVED] [bit] NULL,
[DOMAIN_ID] [int] NOT NULL CONSTRAINT [df_AO_E8B6CC_PR_PARTICIPANT_DOMAIN_ID] DEFAULT ((0)),
[ID] [int] NOT NULL IDENTITY(1, 1),
[PULL_REQUEST_ID] [int] NULL,
[ROLE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[USERNAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_E8B6CC_PR_PARTICIPANT] ADD CONSTRAINT [pk_AO_E8B6CC_PR_PARTICIPANT_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_e8b6cc_pr_758084799] ON [dbo].[AO_E8B6CC_PR_PARTICIPANT] ([DOMAIN_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_e8b6cc_pr_1105917040] ON [dbo].[AO_E8B6CC_PR_PARTICIPANT] ([PULL_REQUEST_ID]) ON [PRIMARY]
GO
