CREATE TABLE [dbo].[AO_D9132D_DEP_ISSUE_LINK_TYPES]
(
[ID] [bigint] NOT NULL IDENTITY(1, 1),
[LINK_ID] [bigint] NOT NULL CONSTRAINT [df_AO_D9132D_DEP_ISSUE_LINK_TYPES_LINK_ID] DEFAULT ((0)),
[OUTWARD] [bit] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_D9132D_DEP_ISSUE_LINK_TYPES] ADD CONSTRAINT [pk_AO_D9132D_DEP_ISSUE_LINK_TYPES_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_D9132D_DEP_ISSUE_LINK_TYPES] ADD CONSTRAINT [U_AO_D9132D_DEP_ISS229485530] UNIQUE NONCLUSTERED  ([LINK_ID]) ON [PRIMARY]
GO
