CREATE TABLE [dbo].[AO_A415DF_AOWORK_ITEM_TO_RES]
(
[AORESOURCE_ID] [int] NULL,
[AOWORK_ITEM_ID] [int] NULL,
[ID_OTHER] [int] NOT NULL IDENTITY(1, 1),
[REPLANNING] [bit] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_A415DF_AOWORK_ITEM_TO_RES] ADD CONSTRAINT [pk_AO_A415DF_AOWORK_ITEM_TO_RES_ID_OTHER] PRIMARY KEY CLUSTERED  ([ID_OTHER]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_a415df_aow1045989527] ON [dbo].[AO_A415DF_AOWORK_ITEM_TO_RES] ([AORESOURCE_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_a415df_aow2028612028] ON [dbo].[AO_A415DF_AOWORK_ITEM_TO_RES] ([AOWORK_ITEM_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_A415DF_AOWORK_ITEM_TO_RES] ADD CONSTRAINT [fk_ao_a415df_aowork_item_to_res_aoresource_id] FOREIGN KEY ([AORESOURCE_ID]) REFERENCES [dbo].[AO_A415DF_AORESOURCE] ([ID_OTHER])
GO
ALTER TABLE [dbo].[AO_A415DF_AOWORK_ITEM_TO_RES] ADD CONSTRAINT [fk_ao_a415df_aowork_item_to_res_aowork_item_id] FOREIGN KEY ([AOWORK_ITEM_ID]) REFERENCES [dbo].[AO_A415DF_AOWORK_ITEM] ([ID_OTHER])
GO
