CREATE TABLE [dbo].[AO_E8B6CC_MESSAGE_TAG]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[MESSAGE_ID] [int] NULL,
[TAG] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_E8B6CC_MESSAGE_TAG] ADD CONSTRAINT [pk_AO_E8B6CC_MESSAGE_TAG_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_e8b6cc_mes1391090780] ON [dbo].[AO_E8B6CC_MESSAGE_TAG] ([MESSAGE_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_e8b6cc_mes1648007831] ON [dbo].[AO_E8B6CC_MESSAGE_TAG] ([TAG]) ON [PRIMARY]
GO
