CREATE TABLE [dbo].[AO_A415DF_AOESTIMATE]
(
[AOWORK_ITEM_ID] [int] NULL,
[CURRENCY] [int] NULL,
[ESTIMATE] [float] NULL,
[ID_OTHER] [int] NOT NULL IDENTITY(1, 1),
[ORIGINAL] [bit] NULL,
[REPLANNING] [bit] NULL,
[TARGET_ID] [int] NULL,
[TARGET_TYPE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[VERSION] [bigint] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_A415DF_AOESTIMATE] ADD CONSTRAINT [pk_AO_A415DF_AOESTIMATE_ID_OTHER] PRIMARY KEY CLUSTERED  ([ID_OTHER]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_a415df_aoe1359587886] ON [dbo].[AO_A415DF_AOESTIMATE] ([AOWORK_ITEM_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_A415DF_AOESTIMATE] ADD CONSTRAINT [fk_ao_a415df_aoestimate_aowork_item_id] FOREIGN KEY ([AOWORK_ITEM_ID]) REFERENCES [dbo].[AO_A415DF_AOWORK_ITEM] ([ID_OTHER])
GO
