CREATE TABLE [dbo].[AO_82B313_SKILL]
(
[ID] [bigint] NOT NULL IDENTITY(1, 1),
[SHAREABLE] [bit] NULL,
[TITLE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_82B313_SKILL] ADD CONSTRAINT [pk_AO_82B313_SKILL_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
