CREATE TABLE [dbo].[AO_D9132D_SCENARIO_ISSUE_LABEL]
(
[ID] [bigint] NOT NULL IDENTITY(1, 1),
[LABEL] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[SCENARIO_ISSUE_ID] [bigint] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_D9132D_SCENARIO_ISSUE_LABEL] ADD CONSTRAINT [pk_AO_D9132D_SCENARIO_ISSUE_LABEL_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_d9132d_sce307133478] ON [dbo].[AO_D9132D_SCENARIO_ISSUE_LABEL] ([LABEL]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_d9132d_sce1010364482] ON [dbo].[AO_D9132D_SCENARIO_ISSUE_LABEL] ([SCENARIO_ISSUE_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_D9132D_SCENARIO_ISSUE_LABEL] ADD CONSTRAINT [fk_ao_d9132d_scenario_issue_label_scenario_issue_id] FOREIGN KEY ([SCENARIO_ISSUE_ID]) REFERENCES [dbo].[AO_D9132D_SCENARIO_ISSUES] ([ID])
GO
