CREATE TABLE [dbo].[board]
(
[ID] [numeric] (18, 0) NOT NULL,
[JQL] [ntext] COLLATE SQL_Latin1_General_CP437_CI_AI NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[board] ADD CONSTRAINT [PK_board] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
