CREATE TABLE [dbo].[AO_54307E_EMAILCHANNELSETTING]
(
[EMAIL_ADDRESS] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[ID] [int] NOT NULL IDENTITY(1, 1),
[LAST_PROCEEDED_TIME] [bigint] NULL,
[MAIL_CHANNEL_KEY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL,
[ON_DEMAND] [bit] NULL,
[REQUEST_TYPE_ID] [int] NOT NULL,
[SERVICE_DESK_ID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_54307E_EMAILCHANNELSETTING] ADD CONSTRAINT [pk_AO_54307E_EMAILCHANNELSETTING_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_54307e_ema1343392873] ON [dbo].[AO_54307E_EMAILCHANNELSETTING] ([REQUEST_TYPE_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_54307e_ema1899742512] ON [dbo].[AO_54307E_EMAILCHANNELSETTING] ([SERVICE_DESK_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_54307E_EMAILCHANNELSETTING] ADD CONSTRAINT [fk_ao_54307e_emailchannelsetting_request_type_id] FOREIGN KEY ([REQUEST_TYPE_ID]) REFERENCES [dbo].[AO_54307E_VIEWPORTFORM] ([ID])
GO
ALTER TABLE [dbo].[AO_54307E_EMAILCHANNELSETTING] ADD CONSTRAINT [fk_ao_54307e_emailchannelsetting_service_desk_id] FOREIGN KEY ([SERVICE_DESK_ID]) REFERENCES [dbo].[AO_54307E_SERVICEDESK] ([ID])
GO
