CREATE TABLE [dbo].[AO_F1B27B_PROMISE]
(
[CLASSIFICATION] [nvarchar] (127) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL,
[CONTENT] [ntext] COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[CREATED_TIME_MILLIS] [bigint] NULL,
[ID] [int] NOT NULL IDENTITY(1, 1),
[KEY_HASH] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL,
[MIME_TYPE] [nvarchar] (127) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[STATUS] [nvarchar] (63) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL,
[TARGET_TIME_MILLIS] [bigint] NULL,
[TASK_KEY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL,
[UPDATED_TIME_MILLIS] [bigint] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_F1B27B_PROMISE] ADD CONSTRAINT [pk_AO_F1B27B_PROMISE_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_F1B27B_PROMISE] ADD CONSTRAINT [U_AO_F1B27B_PROMISE_KEY_HASH] UNIQUE NONCLUSTERED  ([KEY_HASH]) ON [PRIMARY]
GO
