CREATE TABLE [dbo].[AO_4AEACD_WEBHOOK_DAO]
(
[ENABLED] [bit] NULL,
[ENCODED_EVENTS] [ntext] COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[EXCLUDE_ISSUE_DETAILS] [bit] NULL,
[FILTER] [ntext] COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[ID] [int] NOT NULL IDENTITY(1, 1),
[JQL] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[LAST_UPDATED] [datetime] NOT NULL,
[LAST_UPDATED_USER] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL,
[NAME] [ntext] COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL,
[PARAMETERS] [ntext] COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[REGISTRATION_METHOD] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL,
[URL] [ntext] COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_4AEACD_WEBHOOK_DAO] ADD CONSTRAINT [pk_AO_4AEACD_WEBHOOK_DAO_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
