CREATE TABLE [dbo].[AO_56464C_APPROVER]
(
[APPROVAL_ID] [int] NULL,
[ID] [int] NOT NULL IDENTITY(1, 1),
[TYPE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL,
[VALUE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_56464C_APPROVER] ADD CONSTRAINT [pk_AO_56464C_APPROVER_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_56464c_app893380122] ON [dbo].[AO_56464C_APPROVER] ([APPROVAL_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_56464C_APPROVER] ADD CONSTRAINT [fk_ao_56464c_approver_approval_id] FOREIGN KEY ([APPROVAL_ID]) REFERENCES [dbo].[AO_56464C_APPROVAL] ([ID])
GO
