CREATE TABLE [dbo].[AO_319474_MESSAGE_PROPERTY]
(
[ID] [bigint] NOT NULL IDENTITY(1, 1),
[LONG_VALUE] [bigint] NULL,
[MESSAGE_ID] [bigint] NOT NULL,
[NAME] [nvarchar] (450) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL,
[PROPERTY_TYPE] [nvarchar] (1) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL,
[STRING_VALUE] [nvarchar] (450) COLLATE SQL_Latin1_General_CP437_CI_AI NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_319474_MESSAGE_PROPERTY] ADD CONSTRAINT [pk_AO_319474_MESSAGE_PROPERTY_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_319474_mes1143973536] ON [dbo].[AO_319474_MESSAGE_PROPERTY] ([MESSAGE_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_319474_MESSAGE_PROPERTY] ADD CONSTRAINT [fk_ao_319474_message_property_message_id] FOREIGN KEY ([MESSAGE_ID]) REFERENCES [dbo].[AO_319474_MESSAGE] ([ID])
GO
