CREATE TABLE [dbo].[AO_9B2E3B_IF_COND_CONF_DATA]
(
[CONFIG_DATA_KEY] [nvarchar] (127) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL,
[CONFIG_DATA_VALUE] [ntext] COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[ID] [bigint] NOT NULL IDENTITY(1, 1),
[IF_CONDITION_CONFIG_ID] [bigint] NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_9B2E3B_IF_COND_CONF_DATA] ADD CONSTRAINT [pk_AO_9B2E3B_IF_COND_CONF_DATA_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_9b2e3b_if_1918018153] ON [dbo].[AO_9B2E3B_IF_COND_CONF_DATA] ([IF_CONDITION_CONFIG_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_9B2E3B_IF_COND_CONF_DATA] ADD CONSTRAINT [fk_ao_9b2e3b_if_cond_conf_data_if_condition_config_id] FOREIGN KEY ([IF_CONDITION_CONFIG_ID]) REFERENCES [dbo].[AO_9B2E3B_IF_CONDITION_CONFIG] ([ID])
GO
