CREATE TABLE [dbo].[AO_54307E_CAPABILITY]
(
[CAPABILITY_NAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL,
[CAPABILITY_VALUE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL,
[ID] [int] NOT NULL IDENTITY(1, 1),
[SERVICE_DESK_ID] [int] NOT NULL,
[USER_KEY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_54307E_CAPABILITY] ADD CONSTRAINT [pk_AO_54307E_CAPABILITY_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_54307e_cap794737505] ON [dbo].[AO_54307E_CAPABILITY] ([SERVICE_DESK_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_54307E_CAPABILITY] ADD CONSTRAINT [fk_ao_54307e_capability_service_desk_id] FOREIGN KEY ([SERVICE_DESK_ID]) REFERENCES [dbo].[AO_54307E_SERVICEDESK] ([ID])
GO
