CREATE TABLE [dbo].[AO_2C4E5C_MAILCHANNEL]
(
[CREATED_BY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[CREATED_TIMESTAMP] [bigint] NULL CONSTRAINT [df_AO_2C4E5C_MAILCHANNEL_CREATED_TIMESTAMP] DEFAULT ((0)),
[ENABLED] [bit] NULL,
[ID] [int] NOT NULL IDENTITY(1, 1),
[MAIL_CHANNEL_KEY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[MAIL_CONNECTION_ID] [int] NULL,
[MAX_RETRY_ON_FAILURE] [int] NULL CONSTRAINT [df_AO_2C4E5C_MAILCHANNEL_MAX_RETRY_ON_FAILURE] DEFAULT ((0)),
[MODIFIED_BY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[PROJECT_ID] [bigint] NULL CONSTRAINT [df_AO_2C4E5C_MAILCHANNEL_PROJECT_ID] DEFAULT ((0)),
[UPDATED_TIMESTAMP] [bigint] NULL CONSTRAINT [df_AO_2C4E5C_MAILCHANNEL_UPDATED_TIMESTAMP] DEFAULT ((0))
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_2C4E5C_MAILCHANNEL] ADD CONSTRAINT [pk_AO_2C4E5C_MAILCHANNEL_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_2c4e5c_mai809659826] ON [dbo].[AO_2C4E5C_MAILCHANNEL] ([MAIL_CONNECTION_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_2C4E5C_MAILCHANNEL] ADD CONSTRAINT [fk_ao_2c4e5c_mailchannel_mail_connection_id] FOREIGN KEY ([MAIL_CONNECTION_ID]) REFERENCES [dbo].[AO_2C4E5C_MAILCONNECTION] ([ID])
GO
