CREATE TABLE [dbo].[AO_54307E_VIEWPORTFIELD]
(
[DESCRIPTION] [ntext] COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[DISPLAYED] [bit] NULL,
[FIELD_ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL,
[FIELD_ORDER] [int] NULL,
[FIELD_TYPE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL,
[FORM_ID] [int] NULL,
[ID] [int] NOT NULL IDENTITY(1, 1),
[LABEL] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[REQUIRED] [bit] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_54307E_VIEWPORTFIELD] ADD CONSTRAINT [pk_AO_54307E_VIEWPORTFIELD_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_54307e_vie1903424282] ON [dbo].[AO_54307E_VIEWPORTFIELD] ([FORM_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_54307E_VIEWPORTFIELD] ADD CONSTRAINT [fk_ao_54307e_viewportfield_form_id] FOREIGN KEY ([FORM_ID]) REFERENCES [dbo].[AO_54307E_VIEWPORTFORM] ([ID])
GO
