CREATE TABLE [dbo].[AO_563AEE_ACTIVITY_ENTITY]
(
[ACTIVITY_ID] [bigint] NOT NULL IDENTITY(1, 1),
[ACTOR_ID] [int] NULL,
[CONTENT] [ntext] COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[GENERATOR_DISPLAY_NAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[GENERATOR_ID] [nvarchar] (450) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[ICON_ID] [int] NULL,
[ID] [nvarchar] (450) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[ISSUE_KEY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[OBJECT_ID] [int] NULL,
[POSTER] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[PROJECT_KEY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[PUBLISHED] [datetime] NULL,
[TARGET_ID] [int] NULL,
[TITLE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[URL] [nvarchar] (450) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[USERNAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[VERB] [nvarchar] (450) COLLATE SQL_Latin1_General_CP437_CI_AI NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_563AEE_ACTIVITY_ENTITY] ADD CONSTRAINT [pk_AO_563AEE_ACTIVITY_ENTITY_ACTIVITY_ID] PRIMARY KEY CLUSTERED  ([ACTIVITY_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_563aee_act995325379] ON [dbo].[AO_563AEE_ACTIVITY_ENTITY] ([ACTOR_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_563aee_act972488439] ON [dbo].[AO_563AEE_ACTIVITY_ENTITY] ([ICON_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_563aee_act1642652291] ON [dbo].[AO_563AEE_ACTIVITY_ENTITY] ([OBJECT_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_563aee_act1978295567] ON [dbo].[AO_563AEE_ACTIVITY_ENTITY] ([TARGET_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_563AEE_ACTIVITY_ENTITY] ADD CONSTRAINT [fk_ao_563aee_activity_entity_actor_id] FOREIGN KEY ([ACTOR_ID]) REFERENCES [dbo].[AO_563AEE_ACTOR_ENTITY] ([ID])
GO
ALTER TABLE [dbo].[AO_563AEE_ACTIVITY_ENTITY] ADD CONSTRAINT [fk_ao_563aee_activity_entity_icon_id] FOREIGN KEY ([ICON_ID]) REFERENCES [dbo].[AO_563AEE_MEDIA_LINK_ENTITY] ([ID])
GO
ALTER TABLE [dbo].[AO_563AEE_ACTIVITY_ENTITY] ADD CONSTRAINT [fk_ao_563aee_activity_entity_object_id] FOREIGN KEY ([OBJECT_ID]) REFERENCES [dbo].[AO_563AEE_OBJECT_ENTITY] ([ID])
GO
ALTER TABLE [dbo].[AO_563AEE_ACTIVITY_ENTITY] ADD CONSTRAINT [fk_ao_563aee_activity_entity_target_id] FOREIGN KEY ([TARGET_ID]) REFERENCES [dbo].[AO_563AEE_TARGET_ENTITY] ([ID])
GO
