CREATE TABLE [dbo].[AO_9B2E3B_RSETREV_PROJ_CONTEXT]
(
[ID] [bigint] NOT NULL IDENTITY(1, 1),
[PROJECT_ID] [bigint] NOT NULL,
[RULESET_REVISION_ID] [bigint] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_9B2E3B_RSETREV_PROJ_CONTEXT] ADD CONSTRAINT [pk_AO_9B2E3B_RSETREV_PROJ_CONTEXT_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_9b2e3b_rse1358405456] ON [dbo].[AO_9B2E3B_RSETREV_PROJ_CONTEXT] ([RULESET_REVISION_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_9B2E3B_RSETREV_PROJ_CONTEXT] ADD CONSTRAINT [fk_ao_9b2e3b_rsetrev_proj_context_ruleset_revision_id] FOREIGN KEY ([RULESET_REVISION_ID]) REFERENCES [dbo].[AO_9B2E3B_RULESET_REVISION] ([ID])
GO
