CREATE TABLE [dbo].[AO_D9132D_PLANSKILL]
(
[C_KEY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL,
[ID] [bigint] NOT NULL IDENTITY(1, 1),
[PLAN_ID] [bigint] NULL,
[SKILL_ID] [bigint] NULL,
[STAGE] [bigint] NULL,
[WEIGHT] [float] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_D9132D_PLANSKILL] ADD CONSTRAINT [pk_AO_D9132D_PLANSKILL_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_D9132D_PLANSKILL] ADD CONSTRAINT [U_AO_D9132D_PLANSKILL_C_KEY] UNIQUE NONCLUSTERED  ([C_KEY]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_d9132d_pla1554207320] ON [dbo].[AO_D9132D_PLANSKILL] ([PLAN_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_D9132D_PLANSKILL] ADD CONSTRAINT [fk_ao_d9132d_planskill_plan_id] FOREIGN KEY ([PLAN_ID]) REFERENCES [dbo].[AO_D9132D_PLAN] ([ID])
GO
