CREATE TABLE [dbo].[AO_587B34_GLANCE_CONFIG]
(
[APPLICATION_USER_KEY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[JQL] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[NAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[ROOM_ID] [bigint] NOT NULL CONSTRAINT [df_AO_587B34_GLANCE_CONFIG_ROOM_ID] DEFAULT ((0)),
[STATE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[SYNC_NEEDED] [bit] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_587B34_GLANCE_CONFIG] ADD CONSTRAINT [pk_AO_587B34_GLANCE_CONFIG_ROOM_ID] PRIMARY KEY CLUSTERED  ([ROOM_ID]) ON [PRIMARY]
GO
