CREATE TABLE [dbo].[OS_WFENTRY]
(
[ID] [numeric] (18, 0) NOT NULL,
[NAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[INITIALIZED] [int] NULL,
[STATE] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[OS_WFENTRY] ADD CONSTRAINT [PK_OS_WFENTRY] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
