CREATE TABLE [dbo].[AO_54307E_METRICCONDITION]
(
[CONDITION_ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL,
[FACTORY_KEY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL,
[ID] [int] NOT NULL IDENTITY(1, 1),
[PLUGIN_KEY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL,
[TIME_METRIC_ID] [int] NOT NULL,
[TYPE_NAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_54307E_METRICCONDITION] ADD CONSTRAINT [pk_AO_54307E_METRICCONDITION_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_54307e_met1835144061] ON [dbo].[AO_54307E_METRICCONDITION] ([TIME_METRIC_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_54307E_METRICCONDITION] ADD CONSTRAINT [fk_ao_54307e_metriccondition_time_metric_id] FOREIGN KEY ([TIME_METRIC_ID]) REFERENCES [dbo].[AO_54307E_TIMEMETRIC] ([ID])
GO
