CREATE TABLE [dbo].[AO_563AEE_MEDIA_LINK_ENTITY]
(
[DURATION] [int] NULL,
[HEIGHT] [int] NULL,
[ID] [int] NOT NULL IDENTITY(1, 1),
[URL] [nvarchar] (450) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[WIDTH] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_563AEE_MEDIA_LINK_ENTITY] ADD CONSTRAINT [pk_AO_563AEE_MEDIA_LINK_ENTITY_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
