CREATE TABLE [dbo].[AO_9B2E3B_THEN_ACTION_CONFIG]
(
[ID] [bigint] NOT NULL IDENTITY(1, 1),
[IF_THEN_ID] [bigint] NOT NULL,
[MODULE_KEY] [nvarchar] (450) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL,
[ORDINAL] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_9B2E3B_THEN_ACTION_CONFIG] ADD CONSTRAINT [pk_AO_9B2E3B_THEN_ACTION_CONFIG_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_9b2e3b_the554290529] ON [dbo].[AO_9B2E3B_THEN_ACTION_CONFIG] ([IF_THEN_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_9B2E3B_THEN_ACTION_CONFIG] ADD CONSTRAINT [fk_ao_9b2e3b_then_action_config_if_then_id] FOREIGN KEY ([IF_THEN_ID]) REFERENCES [dbo].[AO_9B2E3B_IF_THEN] ([ID])
GO
