CREATE TABLE [dbo].[AO_4E8AE6_OUT_EMAIL_SETTINGS]
(
[CSS] [ntext] COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[HTML_LINGO_ID] [bigint] NULL,
[ID] [int] NOT NULL IDENTITY(1, 1),
[PLAINTEXT_LINGO_ID] [bigint] NULL,
[PROJECT_ID] [bigint] NOT NULL,
[SUBJECT_LINGO_ID] [bigint] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_4E8AE6_OUT_EMAIL_SETTINGS] ADD CONSTRAINT [pk_AO_4E8AE6_OUT_EMAIL_SETTINGS_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
