CREATE TABLE [dbo].[AO_D9132D_EXCLUDED_VERSIONS]
(
[ID] [bigint] NOT NULL IDENTITY(1, 1),
[PLAN_ID] [bigint] NULL,
[VERSION] [bigint] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_D9132D_EXCLUDED_VERSIONS] ADD CONSTRAINT [pk_AO_D9132D_EXCLUDED_VERSIONS_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_d9132d_exc1861854128] ON [dbo].[AO_D9132D_EXCLUDED_VERSIONS] ([PLAN_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_D9132D_EXCLUDED_VERSIONS] ADD CONSTRAINT [fk_ao_d9132d_excluded_versions_plan_id] FOREIGN KEY ([PLAN_ID]) REFERENCES [dbo].[AO_D9132D_PLAN] ([ID])
GO
