CREATE TABLE [dbo].[AO_60DB71_LEXORANKBALANCER]
(
[DISABLE_RANK_OPERATIONS] [bit] NOT NULL,
[FIELD_ID] [bigint] NOT NULL,
[ID] [bigint] NOT NULL IDENTITY(1, 1),
[REBALANCE_TIME] [bigint] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_60DB71_LEXORANKBALANCER] ADD CONSTRAINT [pk_AO_60DB71_LEXORANKBALANCER_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
