CREATE TABLE [dbo].[AO_E8B6CC_GIT_HUB_EVENT]
(
[CREATED_AT] [datetime] NOT NULL,
[GIT_HUB_ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL CONSTRAINT [df_AO_E8B6CC_GIT_HUB_EVENT_GIT_HUB_ID] DEFAULT ('0'),
[ID] [int] NOT NULL IDENTITY(1, 1),
[REPOSITORY_ID] [int] NOT NULL,
[SAVE_POINT] [bit] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_E8B6CC_GIT_HUB_EVENT] ADD CONSTRAINT [pk_AO_E8B6CC_GIT_HUB_EVENT_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_e8b6cc_git1120895454] ON [dbo].[AO_E8B6CC_GIT_HUB_EVENT] ([GIT_HUB_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_e8b6cc_git1804640320] ON [dbo].[AO_E8B6CC_GIT_HUB_EVENT] ([REPOSITORY_ID]) ON [PRIMARY]
GO
