CREATE TABLE [dbo].[AO_D9132D_SHARED_REPORT]
(
[FILTER_CONFIGURATION] [ntext] COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL,
[FILTER_CONFIG_HASH] [int] NULL,
[HASH] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL,
[HIERARCHY_LEVEL] [int] NOT NULL,
[ID] [bigint] NOT NULL IDENTITY(1, 1),
[PLAN_ID] [bigint] NOT NULL,
[REPORT_CONFIGURATION] [ntext] COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[REPORT_CONFIG_HASH] [int] NULL,
[REPORT_ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_D9132D_SHARED_REPORT] ADD CONSTRAINT [pk_AO_D9132D_SHARED_REPORT_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_D9132D_SHARED_REPORT] ADD CONSTRAINT [U_AO_D9132D_SHARED_REPORT_HASH] UNIQUE NONCLUSTERED  ([HASH]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_d9132d_sha2017392082] ON [dbo].[AO_D9132D_SHARED_REPORT] ([PLAN_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_D9132D_SHARED_REPORT] ADD CONSTRAINT [fk_ao_d9132d_shared_report_plan_id] FOREIGN KEY ([PLAN_ID]) REFERENCES [dbo].[AO_D9132D_PLAN] ([ID])
GO
