CREATE TABLE [dbo].[JQUARTZ_PAUSED_TRIGGER_GRPS]
(
[SCHED_NAME] [varchar] (120) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[TRIGGER_GROUP] [varchar] (200) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[JQUARTZ_PAUSED_TRIGGER_GRPS] ADD CONSTRAINT [PK_JQUARTZ_PAUSED_TRIGGER_GRPS] PRIMARY KEY CLUSTERED  ([TRIGGER_GROUP]) ON [PRIMARY]
GO
