CREATE TABLE [dbo].[AO_60DB71_SWIMLANE]
(
[DEFAULT_LANE] [bit] NOT NULL,
[DESCRIPTION] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[ID] [bigint] NOT NULL IDENTITY(1, 1),
[LONG_QUERY] [ntext] COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[NAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL,
[POS] [int] NOT NULL CONSTRAINT [df_AO_60DB71_SWIMLANE_POS] DEFAULT ((0)),
[QUERY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[RAPID_VIEW_ID] [bigint] NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_60DB71_SWIMLANE] ADD CONSTRAINT [pk_AO_60DB71_SWIMLANE_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_60db71_swi1429284592] ON [dbo].[AO_60DB71_SWIMLANE] ([RAPID_VIEW_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_60DB71_SWIMLANE] ADD CONSTRAINT [fk_ao_60db71_swimlane_rapid_view_id] FOREIGN KEY ([RAPID_VIEW_ID]) REFERENCES [dbo].[AO_60DB71_RAPIDVIEW] ([ID])
GO
