CREATE TABLE [dbo].[AO_2C4E5C_MAILCONNECTION]
(
[CREATED_TIMESTAMP] [bigint] NULL CONSTRAINT [df_AO_2C4E5C_MAILCONNECTION_CREATED_TIMESTAMP] DEFAULT ((0)),
[EMAIL_ADDRESS] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL,
[FOLDER] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL,
[HOST_NAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL,
[ID] [int] NOT NULL IDENTITY(1, 1),
[PASSWORD] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL,
[PORT] [int] NOT NULL CONSTRAINT [df_AO_2C4E5C_MAILCONNECTION_PORT] DEFAULT ((0)),
[PROTOCOL] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL,
[PULL_FROM_DATE] [bigint] NULL CONSTRAINT [df_AO_2C4E5C_MAILCONNECTION_PULL_FROM_DATE] DEFAULT ((0)),
[TIMEOUT] [bigint] NULL CONSTRAINT [df_AO_2C4E5C_MAILCONNECTION_TIMEOUT] DEFAULT ((0)),
[TLS] [bit] NULL CONSTRAINT [df_AO_2C4E5C_MAILCONNECTION_TLS] DEFAULT ((0)),
[UPDATED_TIMESTAMP] [bigint] NULL CONSTRAINT [df_AO_2C4E5C_MAILCONNECTION_UPDATED_TIMESTAMP] DEFAULT ((0)),
[USER_NAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_2C4E5C_MAILCONNECTION] ADD CONSTRAINT [pk_AO_2C4E5C_MAILCONNECTION_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
