CREATE TABLE [dbo].[AO_A415DF_AOREPLANNING]
(
[ID_OTHER] [int] NOT NULL IDENTITY(1, 1),
[TARGET_ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[TARGET_TYPE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[WORK_ITEM_ID] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_A415DF_AOREPLANNING] ADD CONSTRAINT [pk_AO_A415DF_AOREPLANNING_ID_OTHER] PRIMARY KEY CLUSTERED  ([ID_OTHER]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_a415df_aor548036520] ON [dbo].[AO_A415DF_AOREPLANNING] ([WORK_ITEM_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_A415DF_AOREPLANNING] ADD CONSTRAINT [fk_ao_a415df_aoreplanning_work_item_id] FOREIGN KEY ([WORK_ITEM_ID]) REFERENCES [dbo].[AO_A415DF_AOWORK_ITEM] ([ID_OTHER])
GO
