CREATE TABLE [dbo].[AO_60DB71_RANK_ISSUE_LINK]
(
[ISSUE_ID] [bigint] NOT NULL,
[NEXT_ID] [bigint] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_60DB71_RANK_ISSUE_LINK] ADD CONSTRAINT [pk_AO_60DB71_RANK_ISSUE_LINK_ISSUE_ID] PRIMARY KEY CLUSTERED  ([ISSUE_ID]) ON [PRIMARY]
GO
