CREATE TABLE [dbo].[AO_D9132D_SCENARIO_VERSION]
(
[C_KEY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL,
[DELTA] [bigint] NULL,
[DELTA_CHANGED] [bit] NULL,
[DESCRIPTION] [ntext] COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[DESCRIPTION_CHANGED] [bit] NULL,
[END_DATE] [bigint] NULL,
[END_DATE_CHANGED] [bit] NULL,
[ID] [bigint] NOT NULL IDENTITY(1, 1),
[ITEM_KEY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL,
[LAST_CHANGE_TIMESTAMP] [bigint] NULL,
[LAST_CHANGE_USER] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[PROJECT_ID] [bigint] NULL,
[SCENARIO_ID] [bigint] NULL,
[SCENARIO_TYPE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL,
[START_DATE] [bigint] NULL,
[START_DATE_CHANGED] [bit] NULL,
[TITLE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[TITLE_CHANGED] [bit] NULL,
[XPROJECT_VERSION] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[XPROJECT_VERSION_CHANGED] [bit] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_D9132D_SCENARIO_VERSION] ADD CONSTRAINT [pk_AO_D9132D_SCENARIO_VERSION_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_D9132D_SCENARIO_VERSION] ADD CONSTRAINT [U_AO_D9132D_SCENARI1370120444] UNIQUE NONCLUSTERED  ([C_KEY]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_d9132d_sce1518982583] ON [dbo].[AO_D9132D_SCENARIO_VERSION] ([ITEM_KEY]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_d9132d_sce2082437338] ON [dbo].[AO_D9132D_SCENARIO_VERSION] ([SCENARIO_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_d9132d_sce232829573] ON [dbo].[AO_D9132D_SCENARIO_VERSION] ([SCENARIO_TYPE]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_D9132D_SCENARIO_VERSION] ADD CONSTRAINT [fk_ao_d9132d_scenario_version_scenario_id] FOREIGN KEY ([SCENARIO_ID]) REFERENCES [dbo].[AO_D9132D_SCENARIO] ([ID])
GO
