CREATE TABLE [dbo].[AO_54307E_VIEWPORTFORM]
(
[CALL_TO_ACTION] [ntext] COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[DESCRIPTION] [ntext] COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[FORM_ORDER] [int] NULL,
[ICON] [int] NULL,
[ICON_ID] [bigint] NULL,
[ID] [int] NOT NULL IDENTITY(1, 1),
[INTRO] [ntext] COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[ISSUE_TYPE_ID] [bigint] NOT NULL,
[KEY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL,
[NAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL,
[VIEWPORT_ID] [int] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_54307E_VIEWPORTFORM] ADD CONSTRAINT [pk_AO_54307E_VIEWPORTFORM_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_54307e_vie883303387] ON [dbo].[AO_54307E_VIEWPORTFORM] ([KEY]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_54307e_vie877344976] ON [dbo].[AO_54307E_VIEWPORTFORM] ([VIEWPORT_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_54307E_VIEWPORTFORM] ADD CONSTRAINT [fk_ao_54307e_viewportform_viewport_id] FOREIGN KEY ([VIEWPORT_ID]) REFERENCES [dbo].[AO_54307E_VIEWPORT] ([ID])
GO
