CREATE TABLE [dbo].[AO_E8B6CC_REPO_TO_PROJECT]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[PROJECT_KEY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[REPOSITORY_ID] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_E8B6CC_REPO_TO_PROJECT] ADD CONSTRAINT [pk_AO_E8B6CC_REPO_TO_PROJECT_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_e8b6cc_rep1928770529] ON [dbo].[AO_E8B6CC_REPO_TO_PROJECT] ([REPOSITORY_ID]) ON [PRIMARY]
GO
