CREATE TABLE [dbo].[AO_60DB71_STATSFIELD]
(
[ID] [bigint] NOT NULL IDENTITY(1, 1),
[RAPID_VIEW_ID] [bigint] NOT NULL,
[TYPE_ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_60DB71_STATSFIELD] ADD CONSTRAINT [pk_AO_60DB71_STATSFIELD_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_60db71_sta1907922871] ON [dbo].[AO_60DB71_STATSFIELD] ([RAPID_VIEW_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_60DB71_STATSFIELD] ADD CONSTRAINT [fk_ao_60db71_statsfield_rapid_view_id] FOREIGN KEY ([RAPID_VIEW_ID]) REFERENCES [dbo].[AO_60DB71_RAPIDVIEW] ([ID])
GO
