CREATE TABLE [dbo].[AO_54307E_STATUSMAPPING]
(
[FORM_ID] [int] NULL,
[ID] [int] NOT NULL IDENTITY(1, 1),
[STATUS_ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[STATUS_NAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_54307E_STATUSMAPPING] ADD CONSTRAINT [pk_AO_54307E_STATUSMAPPING_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_54307e_sta805003358] ON [dbo].[AO_54307E_STATUSMAPPING] ([FORM_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_54307E_STATUSMAPPING] ADD CONSTRAINT [fk_ao_54307e_statusmapping_form_id] FOREIGN KEY ([FORM_ID]) REFERENCES [dbo].[AO_54307E_VIEWPORTFORM] ([ID])
GO
