CREATE TABLE [dbo].[AO_54307E_VIEWPORT]
(
[DESCRIPTION] [ntext] COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[ID] [int] NOT NULL IDENTITY(1, 1),
[KEY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL,
[LOGO_ID] [int] NULL,
[NAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL,
[PROJECT_ID] [bigint] NOT NULL,
[SEND_EMAIL_NOTIFICATIONS] [bit] NULL,
[THEME_ID] [int] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_54307E_VIEWPORT] ADD CONSTRAINT [pk_AO_54307E_VIEWPORT_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_54307E_VIEWPORT] ADD CONSTRAINT [U_AO_54307E_VIEWPORT_KEY] UNIQUE NONCLUSTERED  ([KEY]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_54307e_vie1086593335] ON [dbo].[AO_54307E_VIEWPORT] ([PROJECT_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_54307e_vie1002606617] ON [dbo].[AO_54307E_VIEWPORT] ([THEME_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_54307E_VIEWPORT] ADD CONSTRAINT [fk_ao_54307e_viewport_theme_id] FOREIGN KEY ([THEME_ID]) REFERENCES [dbo].[AO_54307E_CUSTOMTHEME] ([ID])
GO
