CREATE TABLE [dbo].[AO_E8B6CC_ISSUE_MAPPING]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[ISSUE_ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[NODE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[PROJECT_KEY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[REPOSITORY_URI] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_E8B6CC_ISSUE_MAPPING] ADD CONSTRAINT [pk_AO_E8B6CC_ISSUE_MAPPING_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
