CREATE TABLE [dbo].[AO_319474_QUEUE_PROPERTY]
(
[ID] [bigint] NOT NULL IDENTITY(1, 1),
[LONG_VALUE] [bigint] NULL,
[NAME] [nvarchar] (450) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL,
[PROPERTY_TYPE] [nvarchar] (1) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL,
[QUEUE_ID] [bigint] NOT NULL,
[STRING_VALUE] [nvarchar] (450) COLLATE SQL_Latin1_General_CP437_CI_AI NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_319474_QUEUE_PROPERTY] ADD CONSTRAINT [pk_AO_319474_QUEUE_PROPERTY_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_319474_que568114656] ON [dbo].[AO_319474_QUEUE_PROPERTY] ([QUEUE_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_319474_QUEUE_PROPERTY] ADD CONSTRAINT [fk_ao_319474_queue_property_queue_id] FOREIGN KEY ([QUEUE_ID]) REFERENCES [dbo].[AO_319474_QUEUE] ([ID])
GO
