CREATE TABLE [dbo].[OS_CURRENTSTEP_PREV]
(
[ID] [numeric] (18, 0) NOT NULL,
[PREVIOUS_ID] [numeric] (18, 0) NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[OS_CURRENTSTEP_PREV] ADD CONSTRAINT [PK_OS_CURRENTSTEP_PREV] PRIMARY KEY CLUSTERED  ([ID], [PREVIOUS_ID]) ON [PRIMARY]
GO
