CREATE TABLE [dbo].[AO_2C4E5C_MAILITEMAUDIT]
(
[CREATED_TIMESTAMP] [bigint] NULL CONSTRAINT [df_AO_2C4E5C_MAILITEMAUDIT_CREATED_TIMESTAMP] DEFAULT ((0)),
[FROM_ADDRESS] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[HANDLER_NAME_KEY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[ID] [int] NOT NULL IDENTITY(1, 1),
[ISSUE_KEY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[MAIL_CHANNEL_ID] [int] NULL CONSTRAINT [df_AO_2C4E5C_MAILITEMAUDIT_MAIL_CHANNEL_ID] DEFAULT ((0)),
[MAIL_CHANNEL_NAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[MAIL_ITEM_ID] [int] NULL,
[MESSAGE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[NO_OF_RETRY] [int] NULL CONSTRAINT [df_AO_2C4E5C_MAILITEMAUDIT_NO_OF_RETRY] DEFAULT ((0)),
[RESULT_STATUS] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[SUBJECT] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[UPDATED_TIMESTAMP] [bigint] NULL CONSTRAINT [df_AO_2C4E5C_MAILITEMAUDIT_UPDATED_TIMESTAMP] DEFAULT ((0))
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_2C4E5C_MAILITEMAUDIT] ADD CONSTRAINT [pk_AO_2C4E5C_MAILITEMAUDIT_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_2c4e5c_mai1011024424] ON [dbo].[AO_2C4E5C_MAILITEMAUDIT] ([MAIL_ITEM_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_2C4E5C_MAILITEMAUDIT] ADD CONSTRAINT [fk_ao_2c4e5c_mailitemaudit_mail_item_id] FOREIGN KEY ([MAIL_ITEM_ID]) REFERENCES [dbo].[AO_2C4E5C_MAILITEM] ([ID])
GO
