CREATE TABLE [dbo].[AO_A415DF_AOCONFIGURATION]
(
[ID_OTHER] [int] NOT NULL IDENTITY(1, 1),
[INITIALIZED] [bit] NULL,
[INIT_STATE] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_A415DF_AOCONFIGURATION] ADD CONSTRAINT [pk_AO_A415DF_AOCONFIGURATION_ID_OTHER] PRIMARY KEY CLUSTERED  ([ID_OTHER]) ON [PRIMARY]
GO
