CREATE TABLE [dbo].[AO_54307E_REPORT]
(
[CREATED_DATE] [datetime] NULL,
[ID] [int] NOT NULL IDENTITY(1, 1),
[NAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[REPORT_ORDER] [int] NULL,
[REPORT_TYPE] [nvarchar] (63) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[SERVICE_DESK_ID] [int] NULL,
[UPDATED_DATE] [datetime] NULL,
[TARGET] [bigint] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_54307E_REPORT] ADD CONSTRAINT [pk_AO_54307E_REPORT_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_54307e_rep1824414723] ON [dbo].[AO_54307E_REPORT] ([SERVICE_DESK_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_54307E_REPORT] ADD CONSTRAINT [fk_ao_54307e_report_service_desk_id] FOREIGN KEY ([SERVICE_DESK_ID]) REFERENCES [dbo].[AO_54307E_SERVICEDESK] ([ID])
GO
