CREATE TABLE [dbo].[AO_4E8AE6_NOTIF_BATCH_QUEUE]
(
[AUTHOR_ID] [bigint] NULL,
[CONTEXT] [nvarchar] (63) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[EVENT_TIME] [bigint] NOT NULL,
[HTML_CONTENT] [ntext] COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[ID] [bigint] NOT NULL IDENTITY(1, 1),
[ISSUE_ID] [bigint] NULL,
[PROJECT_ID] [bigint] NOT NULL,
[RECIPIENT_ID] [bigint] NOT NULL,
[SENT_TIME] [bigint] NULL,
[TEXT_CONTENT] [ntext] COLLATE SQL_Latin1_General_CP437_CI_AI NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_4E8AE6_NOTIF_BATCH_QUEUE] ADD CONSTRAINT [pk_AO_4E8AE6_NOTIF_BATCH_QUEUE_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_4e8ae6_not850480572] ON [dbo].[AO_4E8AE6_NOTIF_BATCH_QUEUE] ([EVENT_TIME]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_4e8ae6_not1193702477] ON [dbo].[AO_4E8AE6_NOTIF_BATCH_QUEUE] ([ISSUE_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_4e8ae6_not1081986701] ON [dbo].[AO_4E8AE6_NOTIF_BATCH_QUEUE] ([RECIPIENT_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_4e8ae6_not1949617122] ON [dbo].[AO_4E8AE6_NOTIF_BATCH_QUEUE] ([SENT_TIME]) ON [PRIMARY]
GO
