CREATE TABLE [dbo].[AO_E8B6CC_REPO_TO_CHANGESET]
(
[CHANGESET_ID] [int] NULL,
[ID] [int] NOT NULL IDENTITY(1, 1),
[REPOSITORY_ID] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_E8B6CC_REPO_TO_CHANGESET] ADD CONSTRAINT [pk_AO_E8B6CC_REPO_TO_CHANGESET_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_e8b6cc_rep922992576] ON [dbo].[AO_E8B6CC_REPO_TO_CHANGESET] ([CHANGESET_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_e8b6cc_rep1082901832] ON [dbo].[AO_E8B6CC_REPO_TO_CHANGESET] ([REPOSITORY_ID]) ON [PRIMARY]
GO
