CREATE TABLE [dbo].[AO_9B2E3B_IF_THEN_EXECUTION]
(
[FINISH_TIME_MILLIS] [bigint] NULL,
[ID] [bigint] NOT NULL IDENTITY(1, 1),
[IF_THEN_ID] [bigint] NOT NULL,
[MESSAGE] [ntext] COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[OUTCOME] [nvarchar] (127) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL,
[RULE_EXECUTION_ID] [bigint] NOT NULL,
[START_TIME_MILLIS] [bigint] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_9B2E3B_IF_THEN_EXECUTION] ADD CONSTRAINT [pk_AO_9B2E3B_IF_THEN_EXECUTION_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_9b2e3b_if_180675374] ON [dbo].[AO_9B2E3B_IF_THEN_EXECUTION] ([RULE_EXECUTION_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_9B2E3B_IF_THEN_EXECUTION] ADD CONSTRAINT [fk_ao_9b2e3b_if_then_execution_rule_execution_id] FOREIGN KEY ([RULE_EXECUTION_ID]) REFERENCES [dbo].[AO_9B2E3B_RULE_EXECUTION] ([ID])
GO
