CREATE TABLE [dbo].[AO_54307E_GROUPTOREQUESTTYPE]
(
[GROUP_ID] [int] NULL,
[ID] [int] NOT NULL IDENTITY(1, 1),
[REQUEST_TYPE_ID] [int] NULL,
[ORDER] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_54307E_GROUPTOREQUESTTYPE] ADD CONSTRAINT [pk_AO_54307E_GROUPTOREQUESTTYPE_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_54307e_gro832680666] ON [dbo].[AO_54307E_GROUPTOREQUESTTYPE] ([GROUP_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_54307e_gro66949553] ON [dbo].[AO_54307E_GROUPTOREQUESTTYPE] ([REQUEST_TYPE_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_54307E_GROUPTOREQUESTTYPE] ADD CONSTRAINT [fk_ao_54307e_grouptorequesttype_group_id] FOREIGN KEY ([GROUP_ID]) REFERENCES [dbo].[AO_54307E_GROUP] ([ID])
GO
ALTER TABLE [dbo].[AO_54307E_GROUPTOREQUESTTYPE] ADD CONSTRAINT [fk_ao_54307e_grouptorequesttype_request_type_id] FOREIGN KEY ([REQUEST_TYPE_ID]) REFERENCES [dbo].[AO_54307E_VIEWPORTFORM] ([ID])
GO
