CREATE TABLE [dbo].[AO_CFF990_AOTRANSITION_FAILURE]
(
[ERROR_MESSAGES] [ntext] COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[FAILURE_TIME] [datetime] NULL,
[ID] [int] NOT NULL IDENTITY(1, 1),
[ISSUE_ID] [bigint] NULL CONSTRAINT [df_AO_CFF990_AOTRANSITION_FAILURE_ISSUE_ID] DEFAULT ((0)),
[LOG_REFERRAL_HASH] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[TRANSITION_ID] [bigint] NULL CONSTRAINT [df_AO_CFF990_AOTRANSITION_FAILURE_TRANSITION_ID] DEFAULT ((0)),
[TRIGGER_ID] [bigint] NULL CONSTRAINT [df_AO_CFF990_AOTRANSITION_FAILURE_TRIGGER_ID] DEFAULT ((0)),
[USER_KEY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[WORKFLOW_ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_CFF990_AOTRANSITION_FAILURE] ADD CONSTRAINT [pk_AO_CFF990_AOTRANSITION_FAILURE_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
