CREATE TABLE [dbo].[AO_D9132D_PLANTEAM]
(
[ID] [bigint] NOT NULL IDENTITY(1, 1),
[ISSUE_SOURCE_ID] [bigint] NULL,
[ITERATION_LENGTH] [bigint] NULL,
[PLAN_ID] [bigint] NULL,
[SCHEDULING_MODE] [bigint] NULL,
[TEAM_ID] [bigint] NULL,
[VELOCITY] [float] NULL,
[WEEKLY_HOURS] [float] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_D9132D_PLANTEAM] ADD CONSTRAINT [pk_AO_D9132D_PLANTEAM_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_d9132d_pla2082025806] ON [dbo].[AO_D9132D_PLANTEAM] ([ISSUE_SOURCE_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_d9132d_pla2100750794] ON [dbo].[AO_D9132D_PLANTEAM] ([PLAN_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_D9132D_PLANTEAM] ADD CONSTRAINT [fk_ao_d9132d_planteam_issue_source_id] FOREIGN KEY ([ISSUE_SOURCE_ID]) REFERENCES [dbo].[AO_D9132D_ISSUE_SOURCE] ([ID])
GO
ALTER TABLE [dbo].[AO_D9132D_PLANTEAM] ADD CONSTRAINT [fk_ao_d9132d_planteam_plan_id] FOREIGN KEY ([PLAN_ID]) REFERENCES [dbo].[AO_D9132D_PLAN] ([ID])
GO
