CREATE TABLE [dbo].[AO_D9132D_STAGE]
(
[COLOR] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[ID] [bigint] NOT NULL IDENTITY(1, 1),
[PLAN_ID] [bigint] NULL,
[SKILL_ID] [bigint] NULL,
[WEIGHT] [float] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_D9132D_STAGE] ADD CONSTRAINT [pk_AO_D9132D_STAGE_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_d9132d_stage_plan_id] ON [dbo].[AO_D9132D_STAGE] ([PLAN_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_D9132D_STAGE] ADD CONSTRAINT [fk_ao_d9132d_stage_plan_id] FOREIGN KEY ([PLAN_ID]) REFERENCES [dbo].[AO_D9132D_PLAN] ([ID])
GO
