CREATE TABLE [dbo].[AO_54307E_CUSTOMTHEME]
(
[HEADER_BGCOLOR] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[HEADER_LINK_COLOR] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[HEADER_LINK_HOVER_BGCOLOR] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[HEADER_LINK_HOVER_COLOR] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[ID] [int] NOT NULL IDENTITY(1, 1)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_54307E_CUSTOMTHEME] ADD CONSTRAINT [pk_AO_54307E_CUSTOMTHEME_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
