CREATE TABLE [dbo].[AO_A415DF_AORESOURCE]
(
[AOPERSON_ID] [int] NULL,
[AOTEAM_ID] [int] NULL,
[AVAILABILITY] [float] NULL,
[ID_OTHER] [int] NOT NULL IDENTITY(1, 1),
[ORDER_RANGE_IDENTIFIER] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[SORT_ORDER] [bigint] NULL,
[VERSION] [bigint] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_A415DF_AORESOURCE] ADD CONSTRAINT [pk_AO_A415DF_AORESOURCE_ID_OTHER] PRIMARY KEY CLUSTERED  ([ID_OTHER]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_a415df_aor287939766] ON [dbo].[AO_A415DF_AORESOURCE] ([AOPERSON_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_a415df_aor1533730578] ON [dbo].[AO_A415DF_AORESOURCE] ([AOTEAM_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_A415DF_AORESOURCE] ADD CONSTRAINT [fk_ao_a415df_aoresource_aoperson_id] FOREIGN KEY ([AOPERSON_ID]) REFERENCES [dbo].[AO_A415DF_AOPERSON] ([ID_OTHER])
GO
ALTER TABLE [dbo].[AO_A415DF_AORESOURCE] ADD CONSTRAINT [fk_ao_a415df_aoresource_aoteam_id] FOREIGN KEY ([AOTEAM_ID]) REFERENCES [dbo].[AO_A415DF_AOTEAM] ([ID_OTHER])
GO
