CREATE TABLE [dbo].[AO_54307E_OUT_EMAIL_SETTINGS]
(
[EMAIL_SUBJECT_PREFIX_ENABLED] [bit] NOT NULL,
[ID] [int] NOT NULL IDENTITY(1, 1),
[SERVICE_DESK_ID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_54307E_OUT_EMAIL_SETTINGS] ADD CONSTRAINT [pk_AO_54307E_OUT_EMAIL_SETTINGS_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_54307e_out808665536] ON [dbo].[AO_54307E_OUT_EMAIL_SETTINGS] ([SERVICE_DESK_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_54307E_OUT_EMAIL_SETTINGS] ADD CONSTRAINT [fk_ao_54307e_out_email_settings_service_desk_id] FOREIGN KEY ([SERVICE_DESK_ID]) REFERENCES [dbo].[AO_54307E_SERVICEDESK] ([ID])
GO
