CREATE TABLE [dbo].[AO_C7F17E_PROJECT_LANG_CONFIG]
(
[CREATED_TIMESTAMP] [bigint] NULL,
[ID] [bigint] NOT NULL IDENTITY(1, 1),
[PROJECT_ID] [bigint] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AO_C7F17E_PROJECT_LANG_CONFIG] ADD CONSTRAINT [pk_AO_C7F17E_PROJECT_LANG_CONFIG_ID] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [index_ao_c7f17e_pro1274623457] ON [dbo].[AO_C7F17E_PROJECT_LANG_CONFIG] ([PROJECT_ID]) ON [PRIMARY]
GO
