CREATE TABLE [dbo].[JQUARTZ_CALENDARS]
(
[SCHED_NAME] [varchar] (120) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[CALENDAR_NAME] [varchar] (200) COLLATE SQL_Latin1_General_CP437_CI_AI NOT NULL,
[CALENDAR] [image] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[JQUARTZ_CALENDARS] ADD CONSTRAINT [PK_JQUARTZ_CALENDARS] PRIMARY KEY CLUSTERED  ([CALENDAR_NAME]) ON [PRIMARY]
GO
