CREATE TABLE [dbo].[GuildNet_GHI_MKM301_MEDCLAIMS_DELM]
(
[CLAIM NO  ] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CLM LN NO  ] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NO-UNITS  ] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PAIDDTE  ] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F D S   ] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[L D S   ] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ALLOW AMT    ] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SUBMIT AMT   ] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COINS AMT    ] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COPAY AMT    ] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DEDUCT AMT   ] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PAID AMT     ] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COB AMT      ] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GROUP     ] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CAT   ] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EVAL ] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PROVIDER ] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TOP ] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PAR ] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CERTIFICA ] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MEMNO ] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DIAGNO ] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SERVCD ] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PROC-C ] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PLCSRV ] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NETWID ] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HDREVA ] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FUNDC ] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FUNDTP ] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CLMTYP ] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DFLTICD ] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DFLTCPT4 ] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DFLTCPT4M ] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ICD ] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ICDTYP ] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CPT4  ] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CPT4-M1] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CPT4-M2] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NOPYFLD] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PROVIDER-NPI] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Column 40] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FileName] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LoadDate] [datetime] NULL,
[GKEY] [int] NOT NULL,
[GHASH] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
