CREATE TABLE [dbo].[CCAIBabelProfessionalHistory]
(
[ClaimNumber] [int] NOT NULL,
[PlanMemberID] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MemberHICN] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MemberFirstName] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MemberLastName] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DOB] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gender] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MemberAddressLine] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MemberCityName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MemberStateCode] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MemberZipCode] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ClaimStatus] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[POS] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TOS] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TOB] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HRC] [char] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FromDate] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ToDate] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CPT] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Modifier1] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Modifier2] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Modifier3] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Modifier4] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Units] [int] NULL,
[AmountBilled] [money] NULL,
[AllowedCharge] [money] NULL,
[Copay] [money] NULL,
[Coinsurance] [money] NULL,
[COB] [money] NULL,
[TotalAllowed] [money] NULL,
[AmountPaid] [money] NULL,
[DOR] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DOP] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AdjustmentAmount] [money] NULL,
[AdjustmentReasonCode] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AdjudicationCode] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AdjudicationCodeDescription] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AuthorizationNumber] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReferralNumber] [int] NULL,
[CheckNumber] [int] NULL,
[RenderingProviderID] [int] NULL,
[RenderingProviderLast] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RenderingProviderFirst] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RenderingProviderNetworkStatus] [smallint] NULL,
[RenderingProviderFacilityStatus] [smallint] NULL,
[RenderingProviderNPI] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RenderingProviderSpecialtyCode] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RenderingProviderSpecialty] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TaxID] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Box32Name] [char] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Box32Street] [char] (55) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Box32Street2] [char] (55) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Box32City] [char] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Box32State] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Box32Zip] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Box33PayeeProviderID] [int] NULL,
[Box33PayeeProviderLast] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Box33PayeeProviderFirst] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Box33PayeeProviderNPI] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Box33PayeeProviderAddressType] [tinyint] NULL,
[BillingProviderBusinessMailingAddressLine1] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Box33PayeeProviderCity] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Box33PayeeProviderState] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Box33PayeeProviderZip] [varchar] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PCPProviderID] [int] NULL,
[PCPLast] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PCPFirst] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SequenceNumber] [int] NULL,
[LineItemControlNumber] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Claimtype] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DischargeStatus] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AdmissionDate] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DischargeDate] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AdmissionSourceCode] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Payor] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PrimaryDiagnosisCode] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PrimaryDiagnosisCodePOA] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AdmittingdiagnosisCode01] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OtherDiagnosisCode01] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OtherDiagnosisCodePOA01] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OtherDiagnosisCode02] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OtherDiagnosisCodePOA02] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OtherDiagnosisCode03] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OtherDiagnosisCodePOA03] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OtherDiagnosisCode04] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OtherDiagnosisCodePOA04] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OtherDiagnosisCode05] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OtherDiagnosisCodePOA05] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OtherDiagnosisCode06] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OtherDiagnosisCodePOA06] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OtherDiagnosisCode07] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OtherDiagnosisCodePOA07] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OtherDiagnosisCode08] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OtherDiagnosisCodePOA08] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OtherDiagnosisCode09] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OtherDiagnosisCodePOA09] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OtherDiagnosisCode10] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OtherDiagnosisCodePOA10] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OtherDiagnosisCode11] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OtherDiagnosisCodePOA11] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OtherDiagnosisCode12] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OtherDiagnosisCodePOA12] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OtherDiagnosisCode13] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OtherDiagnosisCodePOA13] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OtherDiagnosisCode14] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OtherDiagnosisCodePOA14] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OtherDiagnosisCode15] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OtherDiagnosisCodePOA15] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OtherDiagnosisCode16] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OtherDiagnosisCodePOA16] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OtherDiagnosisCode17] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OtherDiagnosisCodePOA17] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OtherDiagnosisCode18] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OtherDiagnosisCodePOA18] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OtherDiagnosisCode19] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OtherDiagnosisCodePOA19] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OtherDiagnosisCode20] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OtherDiagnosisCodePOA20] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OtherDiagnosisCode21] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OtherDiagnosisCodePOA21] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OtherDiagnosisCode22] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OtherDiagnosisCodePOA22] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OtherDiagnosisCode23] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OtherDiagnosisCodePOA23] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OtherDiagnosisCode24] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OtherDiagnosisCodePOA24] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DiagnosisRelatedGroup01] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ICDPrincipalProcedureCode] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ICDPrincipalProcedureDate] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ICDProcedureCode01] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ICDProcedureCodeDate01] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ICDProcedureCode02] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ICDProcedureCodeDate02] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ICDProcedureCode03] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ICDProcedureCodeDate03] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ICDProcedureCode04] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ICDProcedureCodeDate04] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ICDProcedureCode05] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ICDProcedureCodeDate05] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ICDProcedureCode06] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ICDProcedureCodeDate06] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ICDProcedureCode07] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ICDProcedureCodeDate07] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ICDProcedureCode08] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ICDProcedureCodeDate08] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ICDProcedureCode09] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ICDProcedureCodeDate09] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ICDProcedureCode10] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ICDProcedureCodeDate10] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ICDProcedureCode11] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ICDProcedureCodeDate11] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ICDProcedureCode12] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ICDProcedureCodeDate12] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ICDProcedureCode13] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ICDProcedureCodeDate13] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ICDProcedureCode14] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ICDProcedureCodeDate14] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ICDProcedureCode15] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ICDProcedureCodeDate15] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ICDProcedureCode16] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ICDProcedureCodeDate16] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ICDProcedureCode17] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ICDProcedureCodeDate17] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ICDProcedureCode18] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ICDProcedureCodeDate18] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ICDProcedureCode19] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ICDProcedureCodeDate19] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ICDProcedureCode20] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ICDProcedureCodeDate20] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ICDProcedureCode21] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ICDProcedureCodeDate21] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ICDProcedureCode22] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ICDProcedureCodeDate22] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ICDProcedureCode23] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ICDProcedureCodeDate23] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ICDProcedureCode24] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ICDProcedureCodeDate24] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ValueCode01] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ValueAmount01] [money] NULL,
[ValueCode02] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ValueAmount02] [money] NULL,
[ValueCode03] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ValueAmount03] [money] NULL,
[ValueCode04] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ValueAmount04] [money] NULL,
[ValueCode05] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ValueAmount05] [money] NULL,
[ValueCode06] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ValueAmount06] [money] NULL,
[ValueCode07] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ValueAmount07] [money] NULL,
[ValueCode08] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ValueAmount08] [money] NULL,
[ValueCode09] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ValueAmount09] [money] NULL,
[ValueCode10] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ValueAmount10] [money] NULL,
[ValueCode11] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ValueAmount11] [money] NULL,
[ValueCode12] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ValueAmount12] [money] NULL,
[ValueCode13] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ValueAmount13] [money] NULL,
[ValueCode14] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ValueAmount14] [money] NULL,
[ValueCode15] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ValueAmount15] [money] NULL,
[ValueCode16] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ValueAmount16] [money] NULL,
[ValueCode17] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ValueAmount17] [money] NULL,
[ValueCode18] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ValueAmount18] [money] NULL,
[ValueCode19] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ValueAmount19] [money] NULL,
[ValueCode20] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ValueAmount20] [money] NULL,
[ValueCode21] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ValueAmount21] [money] NULL,
[ValueCode22] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ValueAmount22] [money] NULL,
[ValueCode23] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ValueAmount23] [money] NULL,
[ValueCode24] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ValueAmount24] [money] NULL,
[ConditionCode01] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ConditionCode02] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ConditionCode03] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ConditionCode04] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ConditionCode05] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ConditionCode06] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ConditionCode07] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ConditionCode08] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ConditionCode09] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ConditionCode10] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ConditionCode11] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ConditionCode12] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ConditionCode13] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ConditionCode14] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ConditionCode15] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ConditionCode16] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ConditionCode17] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ConditionCode18] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ConditionCode19] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ConditionCode20] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ConditionCode21] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ConditionCode22] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ConditionCode23] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ConditionCode24] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceCode01] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceCodeDate01] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceCode02] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceCodeDate02] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceCode03] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceCodeDate03] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceCode04] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceCodeDate04] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceCode05] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceCodeDate05] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceCode06] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceCodeDate06] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceCode07] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceCodeDate07] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceCode08] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceCodeDate08] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceCode09] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceCodeDate09] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceCode10] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceCodeDate10] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceCode11] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceCodeDate11] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceCode12] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceCodeDate12] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceCode13] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceCodeDate13] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceCode14] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceCodeDate14] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceCode15] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceCodeDate15] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceCode16] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceCodeDate16] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceCode17] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceCodeDate17] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceCode18] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceCodeDate18] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceCode19] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceCodeDate19] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceCode20] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceCodeDate20] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceCode21] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceCodeDate21] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceCode22] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceCodeDate22] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceCode23] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceCodeDate23] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceCode24] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceCodeDate24] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceSpanCode01] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceSpanCodeStartDate01] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceSpanCodeEndDate01] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceSpanCode02] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceSpanCodeStartDate02] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceSpanCodeEndDate02] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceSpanCode03] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceSpanCodeStartDate03] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceSpanCodeEndDate03] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceSpanCode04] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceSpanCodeStartDate04] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceSpanCodeEndDate04] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceSpanCode05] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceSpanCodeStartDate05] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceSpanCodeEndDate05] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceSpanCode06] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceSpanCodeStartDate06] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceSpanCodeEndDate06] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceSpanCode07] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceSpanCodeStartDate07] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceSpanCodeEndDate07] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceSpanCode08] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceSpanCodeStartDate08] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceSpanCodeEndDate08] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceSpanCode09] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceSpanCodeStartDate09] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceSpanCodeEndDate09] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceSpanCode10] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceSpanCodeStartDate10] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceSpanCodeEndDate10] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceSpanCode11] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceSpanCodeStartDate11] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceSpanCodeEndDate11] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceSpanCode12] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceSpanCodeStartDate12] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceSpanCodeEndDate12] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceSpanCode13] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceSpanCodeStartDate13] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceSpanCodeEndDate13] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceSpanCode14] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceSpanCodeStartDate14] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceSpanCodeEndDate14] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceSpanCode15] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceSpanCodeStartDate15] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceSpanCodeEndDate15] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceSpanCode16] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceSpanCodeStartDate16] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceSpanCodeEndDate16] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceSpanCode17] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceSpanCodeStartDate17] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceSpanCodeEndDate17] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceSpanCode18] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceSpanCodeStartDate18] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceSpanCodeEndDate18] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceSpanCode19] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceSpanCodeStartDate19] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceSpanCodeEndDate19] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceSpanCode20] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceSpanCodeStartDate20] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceSpanCodeEndDate20] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceSpanCode21] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceSpanCodeStartDate21] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceSpanCodeEndDate21] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceSpanCode22] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceSpanCodeStartDate22] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceSpanCodeEndDate22] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceSpanCode23] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceSpanCodeStartDate23] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceSpanCodeEndDate23] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceSpanCode24] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceSpanCodeStartDate24] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OccurrenceSpanCodeEndDate24] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ExternalInjuryCode01] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ExternalInjuryCodePOA01] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ExternalInjuryCode02] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ExternalInjuryCodePOA02] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ExternalInjuryCode03] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ExternalInjuryCodePOA03] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ExternalInjuryCode04] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ExternalInjuryCodePOA04] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ExternalInjuryCode05] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ExternalInjuryCodePOA05] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ExternalInjuryCode06] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ExternalInjuryCodePOA06] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ExternalInjuryCode07] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ExternalInjuryCodePOA07] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ExternalInjuryCode08] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ExternalInjuryCodePOA08] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ExternalInjuryCode09] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ExternalInjuryCodePOA09] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ExternalInjuryCode10] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ExternalInjuryCodePOA10] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ExternalInjuryCode11] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ExternalInjuryCodePOA11] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ExternalInjuryCode12] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ExternalInjuryCodePOA12] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PatientsReasonforVisitCode01] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PatientsReasonforVisitCode02] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PatientsReasonforVisitCode03] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CCAIBabelProfessionalID] [int] NULL,
[FileNameProfessional] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CCAIBabelProfessionalHistoryID] [int] NOT NULL IDENTITY(1, 1)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CCAIBabelProfessionalHistory] ADD CONSTRAINT [PK_CCAIBabelProfessionalHistory] PRIMARY KEY CLUSTERED  ([CCAIBabelProfessionalHistoryID]) ON [PRIMARY]
GO
