CREATE TABLE [dbo].[CCAIClaimDetailExtract]
(
[Claim Number] [int] NOT NULL,
[Member ID#] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Member First Name] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Member Last Name] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DOB] [datetime] NULL,
[Gender] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Claim Status] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[POS] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TOS] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TOB] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HRC] [char] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[From Date] [smalldatetime] NULL,
[To Date] [smalldatetime] NULL,
[CPT] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Modifier1] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Modifier2] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Modifier3] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Modifier4] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Units] [int] NULL,
[Amount Billed] [money] NULL,
[Allowed Charge] [money] NULL,
[Copay] [money] NULL,
[Coinsurance] [money] NULL,
[Total Allowed] [money] NULL,
[Amount Paid] [money] NULL,
[DOR] [datetime] NULL,
[DOP] [smalldatetime] NULL,
[Adjudication Code] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Adjudication Code Description] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Authorization Number] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Referral Number] [int] NULL,
[Check Number] [int] NULL,
[Rendering Provider #] [int] NULL,
[Rendering Provider Last] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Rendiering Provider First] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Rendering Provider Network Status] [smallint] NULL,
[Rendering Provider Facility Status] [smallint] NULL,
[Rendering Provider NPI] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Rendering Provider Specialty Code] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Rendering Provider Specialty] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Tax ID#] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Box 32 Name] [char] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Box 32 Street] [char] (55) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Box 32 Street 2] [char] (55) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Box 32 City] [char] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Box 32 State] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Box 32 Zip] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Box 33 Payee Provider #] [int] NULL,
[Box 33 Payee Provider Last] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Box 33 Payee Provider First] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Box 33 Payee Provider NPI] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Box 33 Payee Provider Address Type] [tinyint] NULL,
[Box 33 Payee Provider Street] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Box 33 Payee Provider Street 2] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Box 33 Payee Provider City] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Box 33 Payee Provider State] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Box 33 Payee Provider Zip] [varchar] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PCP Provider #] [int] NULL,
[PCP Last] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PCP First] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SequenceNumber] [int] NOT NULL,
[LineItemControlNumber] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Claimtype] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DischargeStatus] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AdmissionDate] [smalldatetime] NULL,
[DischargeDate] [smalldatetime] NULL,
[AdmissionSourceCode] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Payor] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
