CREATE TABLE [dbo].[GuildNetPharmacy_PharmacyClaim]
(
[CR-RECORD-TYPE] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CR-CLAIM-NUMBER] [varchar] (14) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CR-CLAIM-TYPE] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CR-TRANSACTION-TYPE] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CR-RX-NUMBER] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CR-REFILL-FLAG-NO] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CR-PROCESSING-DATE-CCYYMMDD] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CR-ADJUDICATION-DATE] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CR-ORIG-DISPENSING-DATE ] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CR-COMPOUND-FLAG] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CR-MEMBER-ID] [varchar] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CR-MEMBER-BIRTH-DATE] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CR-EMPLOYER-GROUP-ID] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CR-BENEFIT-PLAN-ID] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CR-BENEFIT-SET-SEQ-NUMBER] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CR-RIDER-CODE] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CR-PRIOR-APPROVAL-CODE] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CR-NDC-NUMBER] [varchar] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CR-DISPENSING-DATE] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CR-QUANTITY-DISPENSED] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CR-DAYS-SUPPLY] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CR-DRUG-NAME] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CR-CLAIM-AMOUNT] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FILLER1  (used for reject code 1, 2)] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CR-MAC-PRICING-IND] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CR-ORIG-CLAIM-AMOUNT] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[       CR-PROV-ID] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[       CR-PROV-ID-LOC] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CR-INGREDIENT-COST-CLAIMED] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CR-INGREDIENT-COST-PAID] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CR-COPAY-AMOUNT ] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[        CR-REGION] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[        FILLER2] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FILLER3  (used for reject code 3)] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CR-END-OF-CYCLE-DATE-CCYYMMDD] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CR-DATE-PRESCRIPTION-WRITTEN] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CR-CLAIM-CAP-REDUCED] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CR-CLAIM-COINSURANCE] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CR-CLAIM-DAW] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CR-CLAIM-DEDUCTIBLE] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CR-CLAIM-NETWORK-CODE] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CR-CLAIM-FEE-SUBMITTED] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CR-CLAIM-FEE-APPROVED] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CR-GC-CATEGORY-CODE] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CR-CLAIM-LOB] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CR-ADJUDICATION-RIDER] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FILLER4 (ESI, Plan Indicator, Admin Fee) ] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CR-FORMULARY-STATUS] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CR-CLAIM-PAST-MBR-ID] [varchar] (14) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CR-CLAIM-SITE] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CR-PIN-NO] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CR-AHFS-CODE] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CR-GCN-CODE] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CR-GPI-CODE] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CR-GC3-CODE] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CR-CLAIM-STEP-THERAPY] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CR-DRUG-NAME-GROUP] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CR-GENERIC-NAME ] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CR-PROVIDER-NPI-ID] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CR-ORIGIN-CODE] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CR-WAC-AMT-N] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CR-MAC-AMT-N ] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CR-AWP-AMT-N] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CR-REVERSAL-CLAIM-NUM] [varchar] (14) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CR-DRUG-TIER] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CR-DR-ID] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CR-COB-FLAG] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CR-COB-AMT-N] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CR-RX-NUMBER-FULL] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Tax Amount] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Generic Product Indicator (GPI)] [varchar] (14) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Date Billed] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Member Last Name] [varchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Member First Name] [varchar] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Member Middle Initial] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Member Gender] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Age] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Relationship Code] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Dependent Code] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Member PCP Assignment] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Member Program] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DOB Default] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Patient Location] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Submitted DOB] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Submitted Gender] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Payee Check Name] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Payee Check Address] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Payee City] [varchar] (17) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Payee State] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Payee Zip Code] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Payee Zip Code – Expanded] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Plan Type] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Master Group Number] [varchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Expanded Group Number] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ESI Group Number] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Group Name] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Employee Last Name] [varchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Employee First Name] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Employee Middle Initial] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Employee DOB] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Employee Address] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Employee City] [varchar] (17) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Employee State] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Employee Zip Code] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Employee Zip Code – Expanded] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Employee Gender] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Prescriber Qualifier] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Physician Name] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Provider Contract] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Claim Admin Fee] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Calculated Billing Copay Amount] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Ancillary Amount] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Max. out of pocket amount applied] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Program Stop Loss amount applied] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Brand/Generic Code] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Drug Conflict Code 1] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Drug Conflict Code 2] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Drug Conflict Code 3] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DUR Overflow] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DUR Intervention] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DUR Outcome Code] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Dosage Code] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Drug Strength] [varchar] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Pharmacy Service Type] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Pharmacy Qualifier] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[U&C Amount] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HRA Applied Amount] [varchar] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HRA ESI Fund] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Maintenance Drug Indicator] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Drug Legal Status] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PICA Drug Code] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Federal Drug Class Code] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Product Type] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FSA Vendor Code  ] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Other Coverage Code] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Medicare D Covered Drug] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Retro LICS Code ] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Retro LICS Amount] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ LICS Subsidy Amount] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Med B Drug] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Med B Claim] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Copay Tier Level Number ] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Office of Inspector General (OIG) flag] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ANDA Flag] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CDH Response ID] [varchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CDH ESI Response Code] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HRA Flag] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HRA Single Book Flag] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HRA Request Amount] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Vendor  ID (outbound)] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Deductible Single Book Flag] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Maximum Out of Pocket Single Book Flag] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Plan Stop Loss Single Book Flag] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TDS Single Book Flag] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Vaccine Pharmacy Type] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Vaccine Admin Amount] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Vaccine Admin Type] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CDH – Vendor Value] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ACR Admin Flag] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Member ACR amount] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Supplemental Payer Paid Amount] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Supplemental Payer Copay Amount] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Supplemental Payer Coverage Code] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Supplemental Payer Covered Deductible Amount] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Supplemental Payer Covered Copay Amount ] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Supplemental Payer Covered Ancillary] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Supplemental Payer Covered Copay Add on Amount] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Patient Residence   ] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NX exists Indicator] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Prescription Origin Code] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COB Recovery Amount] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Filler5] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Pre COB Billed Claim Amount] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Drug Calculated Discount Amount] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Drug Discount Exclusion Reason Code] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Drug Discount Applicable Code] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Drug Discount Eligible Cost Amount] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PDE Delete Code ] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[M-I Compound] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[M-I Compound Coverage Option] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[M-I Level Of Effort ] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[M-I Professional Service Fee Amount] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[M-I Compound Ingredient Count] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[M-I Compound MED-D Eligible ] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[M-I Compound Med-D Ineligible ] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[M-I Compound Med-D Flat Copay Amount] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[M-I Compound Med-D Percent Copay Amount] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[M-I Compound Med-D Eligible Member Paid Amount] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[M-I Compound Med-D Eligible Plan Paid Amount ] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[M-I Compound Med-D Eligible Cost Amount] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Batch Number] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PHR-PHARMACY-NABP-NO] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MED D Benefit Beginning Phase Cd] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MED D Benefit Ending Phase Cd] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[QCARE Benefit Set Value or GHI Category Code] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MED D TrOOP Switch] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MED D TrOOP YTD Amount] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CMS TrOOP Limit Switch] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Date and Time Stamp] [varchar] (26) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Transaction ID] [varchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[X-Ref Transaction ID] [varchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Transaction Type Code] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Adjustment Reason Type Code] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ESI Batch ID] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Payment Reference Number] [varchar] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CR-CLAIM-AMOUNT-EXP] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SCB (Sub Client Billing) Ingredient Costs] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SCB (Sub Client Billing) Dispensing Fees] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SCB (Sub Client Billing) Sales Tax] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SCB (Sub Client Billing) Admin Fee] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SCB (Sub Client Billing) Claim Amount] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SCB (Sub Client Billing) Ancillary Adjustment Amount] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SCB Cost Basis] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FILLER6   ] [varchar] (33) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FileName] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LoadDate] [datetime] NULL,
[GKEY] [int] NOT NULL IDENTITY(1, 1)
) ON [PRIMARY]
GO
