CREATE USER [AllSchemaOwner] WITHOUT LOGIN
GO
GRANT ALTER ANY SYMMETRIC KEY TO [AllSchemaOwner]
GRANT CREATE CERTIFICATE TO [AllSchemaOwner]
GRANT VIEW DEFINITION TO [AllSchemaOwner]
GRANT VIEW DATABASE STATE TO [AllSchemaOwner]
