CREATE TABLE [fact].[OES_DOS]
(
[OES_DOSID] [bigint] NOT NULL IDENTITY(1, 1),
[ChaseID] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DOS_FromDate] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DOS_ToDate] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [fact].[OES_DOS] ADD CONSTRAINT [PK_OES_DOS] PRIMARY KEY CLUSTERED  ([OES_DOSID]) ON [PRIMARY]
GO
