CREATE TABLE [stage].[OEC]
(
[OEC_BK] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ClaimID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DiagnosisCode] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DiagnosisCodeOrder] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DxCodesBillTypeCd] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ICD_Indicator] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DOS_FromDate] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DOS_ToDate] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Eff_Date] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Exp_Date] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ContractCode] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CentauriClientID] [int] NULL,
[CentauriMemberID] [int] NULL,
[CentauriProviderID] [int] NULL,
[CentauriNetworkID] [int] NULL,
[VendorID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProviderAddr1] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProviderAddr2] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProviderCity] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProviderState] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProviderZip] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProviderPhone] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProviderFax] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VendorAddr1] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VendorAddr2] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VendorCity] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VendorState] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VendorZip] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VendorPhone] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VendorFax] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CentauriOECProjectID] [int] NULL,
[MemberHICN] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ChaseID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ChasePriority] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MedicalRecordID] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProviderRelationsRep] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProviderSpecialty] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProviderSpecialty2] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProviderSpecialty3] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PricingID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SVCTaxID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MHFacilityFlag] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NetworkIndicator] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Claim_Category_Primary1] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Claim_Category_Primary2] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Claim_Category_Primary3] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Claim_Category_Secondary1] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Claim_Category_Secondary2] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Claim_Category_Secondary3] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MHMD] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OfficeName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OfficeAddress] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OfficeCity] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OfficeState] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OfficeZip] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DNC] [bit] NULL
) ON [PRIMARY]
GO
