CREATE TABLE [stage].[MOR]
(
[recordsource] [varchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LoadDate] [datetime] NULL,
[contractnumber] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RunDate] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[recordtypecode] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HICN] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lastname] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[firstname] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[mi] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dob] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[gender] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ssn] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AgeGroup] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MedicaidDisabled] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MedicaidAged] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OriginallyDisabled] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PaymentYearandMonth] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ESRD] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CANCER_IMMUNE] [int] NULL,
[CHF_COPD] [int] NULL,
[CHF_RENAL] [int] NULL,
[COPD_CARD_RESP_FAIL] [int] NULL,
[DIABETES_CHF] [int] NULL,
[SEPSIS_CARD_RESP_FAIL] [int] NULL,
[MEDICAID] [int] NULL,
[DISABLED_PRESSURE_ULCER] [int] NULL,
[ART_OPENINGS_PRESSURE_ULCER] [int] NULL,
[ASP_SPEC_BACT_PNEUM_PRES_ULC] [int] NULL,
[COPD_ASP_SPEC_BACT_PNEUM] [int] NULL,
[SCHIZOPHRENIA_CHF] [int] NULL,
[SCHIZOPHRENIA_COPD] [int] NULL,
[SCHIZOPHRENIA_SEIZURES] [int] NULL,
[SEPSIS_ARTIF_OPENINGS] [int] NULL,
[SEPSIS_ASP_SPEC_BACT_PNEUM] [int] NULL,
[SEPSIS_PRESSURE_ULCER] [int] NULL,
[INT1] [int] NULL,
[INT2] [int] NULL,
[INT3] [int] NULL,
[INT4] [int] NULL,
[INT5] [int] NULL,
[INT6] [int] NULL,
[HCC] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ClientID] [int] NULL,
[CentauriMemberID] [bigint] NULL,
[MOR_BK] [varchar] (305) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
