CREATE TABLE [stage].[UserDetail_ADV]
(
[CentauriUserid] [int] NULL,
[RemovedDate] [smalldatetime] NULL,
[IsAdmin] [bit] NULL,
[IsScanTech] [bit] NULL,
[IsScheduler] [bit] NULL,
[IsReviewer] [bit] NULL,
[IsQA] [bit] NULL,
[IsHRA] [bit] NULL,
[IsActive] [bit] NULL,
[only_work_selected_hours] [bit] NULL,
[only_work_selected_zipcodes] [bit] NULL,
[deactivate_after] [smalldatetime] NULL,
[linked_provider_id] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CentauriProviderID] [int] NULL,
[IsClient] [bit] NULL,
[IsSchedulerSV] [bit] NULL,
[IsScanTechSV] [bit] NULL,
[IsChangePasswordOnFirstLogin] [bit] NULL,
[isQCC] [bit] NULL,
[willing2travell] [smallint] NULL,
[linked_scheduler_user_pk] [int] NULL,
[EmploymentStatus] [tinyint] NULL,
[EmploymentAgency] [tinyint] NULL,
[isAllowDownload] [bit] NULL,
[CoderLevel] [tinyint] NULL,
[IsSchedulerManager] [bit] NULL,
[IsInvoiceAccountant] [bit] NULL,
[IsBillingAccountant] [bit] NULL,
[IsManagementUser] [bit] NULL,
[ClientID] [int] NULL,
[LoadDate] [datetime] NULL
) ON [PRIMARY]
GO
