CREATE TABLE [dbo].[S_ClaimDetail]
(
[S_ClaimDetail_RK] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[LoadDate] [datetime] NOT NULL,
[H_Claim_RK] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ClaimStatus] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[POS] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TOS] [nchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TOB] [nchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HRC] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FromDate] [datetime] NULL,
[ToDate] [datetime] NULL,
[CPT] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Modifier1] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Modifier2] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Modifier3] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Modifier4] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Units] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AmountBilled] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AllowedCharge] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Copay] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Coinsurance] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TotalAllowed] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AmountPaid] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DOR] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DOP] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AdjudicationCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AdjudicationCodeDesc] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AuthorizationNumber] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReferralNumber] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CheckNumber] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RenderingProviderNum] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RenderingProviderCPI] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RenderingProviderLName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RenderingProviderFName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RenderingProviderNetworkStatus] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RenderingProviderFacilityStatus] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RenderingProviderNPI] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RenderingProviderSpecialtyCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RenderingProviderSpecialty] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RenderingProviderLocation_RK] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TaxID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PayeeProviderNum] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PayeeProviderCPI] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PayeeProviderLName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PayeeProviderFName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PayeeProviderNPI] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PayeeProviderLocation_RK] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PayeeProviderAddressType] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PayeeProviderAddress1] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PayeeProviderAddress2] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PayeeProviderCity] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PayeeProviderState] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PayeeProviderZip] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PCPProviderNum] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PCPProviderCPI] [nchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PCPLName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PCPFName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SequenceNumber] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LineItemControlNumber] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ClaimType] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DischargeStatus] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AdmissionDate] [datetime] NULL,
[DischargeDate] [datetime] NULL,
[AdmissionSourceCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Payor] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HashDiff] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RecordEndDate] [datetime] NULL,
[RecordSource] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[S_ClaimDetail] ADD CONSTRAINT [PK_S_ClaimDetail_1] PRIMARY KEY CLUSTERED  ([S_ClaimDetail_RK]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[S_ClaimDetail] ADD CONSTRAINT [FK_S_ClaimDetail_H_Claim] FOREIGN KEY ([H_Claim_RK]) REFERENCES [dbo].[H_Claim] ([H_Claim_RK])
GO
