SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
 
 
-- ============================================= 
-- Author:		Travis Parker 
-- Create date:	02/15/2017 
-- Description:	Updates the reference keys in the TRR staging tables 
-- ============================================= 
CREATE PROCEDURE [dbo].[spTRRUpdateReferenceKeys] 
AS 
    BEGIN 
	 
        DECLARE @CurrentDate DATETIME = GETDATE(); 
 
        SET NOCOUNT ON; 
 
        UPDATE  s 
        SET     s.TRR_BK = UPPER(CONCAT(RTRIM(LTRIM(COALESCE(HICN, ''))), ':', RTRIM(LTRIM(COALESCE(RecordType, ''))), ':', 
                                      RTRIM(LTRIM(COALESCE(ContractNumber, ''))), ':', RTRIM(LTRIM(COALESCE(TransactionReplyCode, ''))), ':', 
                                      RTRIM(LTRIM(COALESCE(TransactionTypeCode, ''))), ':', RTRIM(LTRIM(COALESCE(SystemAssignedTransactionTrackingID, ''))))) 
        FROM    CHSStaging.dbo.TRRStaging s 
 
        UPDATE  s 
        SET     s.TRRVerbatim_BK = UPPER(CONCAT(RTRIM(LTRIM(COALESCE(HICN, ''))), ':', RTRIM(LTRIM(COALESCE(RecordType, ''))), ':', 
                                      RTRIM(LTRIM(COALESCE(ContractNumber, ''))), ':', RTRIM(LTRIM(COALESCE(TransactionAcceptRejectStatus, ''))), ':', 
                                      RTRIM(LTRIM(COALESCE(SystemAssignedTransactionTrackingID, ''))))) 
        FROM    CHSStaging.dbo.TRRVerbatimStaging s 
 
        UPDATE  CHSStaging.dbo.TRRStaging 
        SET     L_MemberTRR_RK = UPPER(CONVERT(CHAR(32), HASHBYTES('MD5', 
                                                                    UPPER(CONCAT(RTRIM(LTRIM(COALESCE(CentauriMemberID, ''))), ':', 
                                                                                 RTRIM(LTRIM(COALESCE(TRR_BK, '')))))), 2)) , 
                S_MemberHICN_RK = UPPER(CONVERT(CHAR(32), HASHBYTES('MD5', 
                                                                    UPPER(CONCAT(RTRIM(LTRIM(COALESCE(CentauriMemberID, ''))), ':', 
                                                                                 RTRIM(LTRIM(COALESCE(HICN, ''))), ':', 
                                                                                 RTRIM(LTRIM(COALESCE(LoadDate, ''))), ':', 
                                                                                 RTRIM(LTRIM(COALESCE(FileName, '')))))), 2)) , 
                S_MemberHICN_HashDiff = UPPER(CONVERT(CHAR(32), HASHBYTES('MD5', 
                                                                          UPPER(CONCAT(RTRIM(LTRIM(COALESCE(CentauriMemberID, ''))), ':', 
                                                                                       RTRIM(LTRIM(COALESCE(HICN, '')))))), 2)) , 
			 S_MemberDemo_RK = UPPER(CONVERT(CHAR(32), HASHBYTES('MD5', 
                                                             UPPER(CONCAT(RTRIM(LTRIM(COALESCE(CentauriMemberID, ''))), ':',
														    RTRIM(LTRIM(COALESCE(FirstName, ''))), ':',  
														    RTRIM(LTRIM(COALESCE(Surname, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(MiddleInitial, ''))), ':',  
														    RTRIM(LTRIM(COALESCE(GenderCode, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(DOB, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(LoadDate, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(FileName, '')))))), 2)) , 
			 S_MemberDemo_HashDiff = UPPER(CONVERT(CHAR(32), HASHBYTES('MD5', 
                                                             UPPER(CONCAT(RTRIM(LTRIM(COALESCE(FirstName, ''))), ':',  
														    RTRIM(LTRIM(COALESCE(Surname, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(MiddleInitial, ''))), ':',  
														    RTRIM(LTRIM(COALESCE(GenderCode, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(DOB, '')))))), 2)) , 
			 H_TRR_RK = UPPER(CONVERT(CHAR(32), HASHBYTES('MD5', 
                                                             UPPER(RTRIM(LTRIM(COALESCE(TRR_BK, ''))))), 2)) , 
                S_TRR_RK = UPPER(CONVERT(CHAR(32), HASHBYTES('MD5', 
                                                             UPPER(CONCAT(RTRIM(LTRIM(COALESCE(TRR_BK, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(HICN, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(Surname, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(FirstName, ''))), ':',  
														    RTRIM(LTRIM(COALESCE(MiddleInitial, ''))), ':',  
														    RTRIM(LTRIM(COALESCE(GenderCode, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(DOB, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(RecordType, ''))), ':',  
														    RTRIM(LTRIM(COALESCE(ContractNumber, ''))), ':',  
														    RTRIM(LTRIM(COALESCE(StateCode, ''))), ':',  
														    RTRIM(LTRIM(COALESCE(CountyCode, ''))), ':',  
														    RTRIM(LTRIM(COALESCE(DisabilityIndicator, ''))), ':',  
														    RTRIM(LTRIM(COALESCE(HospiceIndicator, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(Institutional_NHC_HC_BS_Indicator, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(ESRDIndicator, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(TransactionReplyCode, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(TransactionTypeCode, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(EntitlementTypeCode, ''))), ':',  
														    RTRIM(LTRIM(COALESCE(EffectiveDate, ''))), ':',  
														    RTRIM(LTRIM(COALESCE(WAIndicator, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(PlanBenefitPackageID, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(Filler, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(TransactionDate, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(UIInitiatedChangeFlag, ''))), ':',  
														    RTRIM(LTRIM(COALESCE(TRCValue, ''))), ':',  
														    RTRIM(LTRIM(COALESCE(DistrictOfficeCode, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(PrevPartD_Contract_PBP_ForTroopTransfer, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(Filler2, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(SourceID, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(PriorPlanBenefitPackageID, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(ApplicationDate, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(UIUserOrganizationDesignation, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(OutOfAreaFlag, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(SegmentNumber, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(PartC_BeneficiaryPremium, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(PartD_BeneficiaryPremium, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(ElectionType, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(EnrollmentSource, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(PartD_OptOutFlag, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(PremiumWithholdOption_PartsC_D, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(CumulativeNumberOfUncoveredMonths, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(CreditableCoverageFlag, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(EmployerSubsidyOverrideFlag, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(ProcessingTimestamp, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(EndDate, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(SubmittedNumberOfUncoveredMonths, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(Filler3, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(SecondaryDrugInsuranceFlag, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(SecondaryRxID, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(SecondaryRxGroup, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(EGHP, ''))), ':',  
														    RTRIM(LTRIM(COALESCE(PartD_LowIncomePremiumSubsidyLevel, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(LowIncomeCoPayCategory, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(LowIncomePeriodEffectiveDate, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(PartD_LateEnrollmentPenaltyAmount, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(PartD_LateEnrollmentPenaltyWaivedAmount, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(PartD_LateEnrollmentPenaltySubsidyAmount, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(LowIncomePartD_PremiumSubsidyAmount, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(PartD_RxBIN, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(PartD_RxPCN, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(PartD_RxGroup, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(PartD_RxID, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(SecondaryRxBIN, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(SecondaryRxPCN, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(DeMinimisDifferentialAmount, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(MSPStatusFlag, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(LowIncomePeriodEndDate, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(LowIncomeSubsidySourceCode, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(EnrolleeTypeFlagPBPLevel, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(ApplicationDateIndicator, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(TRCShortName, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(DisenrollmentReasonCode, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(MMPOptOutFlag, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(CleanUpID, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(POSDrugEditUpdateDeleteFlag, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(POSDrugEditStatus, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(POSDrugEditClass, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(POSDrugEditCode, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(NotificationDate, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(ImplementationDate, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(TerminationDate, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(NotificationPOSDrugEditCode, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(Filler4, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(SystemAssignedTransactionTrackingID, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(PlanAssignedTransactionTrackingID, ''))), ':', 
														    RTRIM(LTRIM(COALESCE(FileName, ''))), ':',  
														    RTRIM(LTRIM(COALESCE(LoadDate, '')))))), 2)) , 
                S_TRR_HashDiff = UPPER(CONVERT(CHAR(32), HASHBYTES('MD5', 
                                                             UPPER(CONCAT(RTRIM(LTRIM(COALESCE(TRR_BK, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(HICN, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(Surname, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(FirstName, ''))), ':',  
														    RTRIM(LTRIM(COALESCE(MiddleInitial, ''))), ':',  
														    RTRIM(LTRIM(COALESCE(GenderCode, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(DOB, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(RecordType, ''))), ':',  
														    RTRIM(LTRIM(COALESCE(ContractNumber, ''))), ':',  
														    RTRIM(LTRIM(COALESCE(StateCode, ''))), ':',  
														    RTRIM(LTRIM(COALESCE(CountyCode, ''))), ':',  
														    RTRIM(LTRIM(COALESCE(DisabilityIndicator, ''))), ':',  
														    RTRIM(LTRIM(COALESCE(HospiceIndicator, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(Institutional_NHC_HC_BS_Indicator, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(ESRDIndicator, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(TransactionReplyCode, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(TransactionTypeCode, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(EntitlementTypeCode, ''))), ':',  
														    RTRIM(LTRIM(COALESCE(EffectiveDate, ''))), ':',  
														    RTRIM(LTRIM(COALESCE(WAIndicator, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(PlanBenefitPackageID, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(Filler, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(TransactionDate, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(UIInitiatedChangeFlag, ''))), ':',  
														    RTRIM(LTRIM(COALESCE(TRCValue, ''))), ':',  
														    RTRIM(LTRIM(COALESCE(DistrictOfficeCode, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(PrevPartD_Contract_PBP_ForTroopTransfer, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(Filler2, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(SourceID, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(PriorPlanBenefitPackageID, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(ApplicationDate, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(UIUserOrganizationDesignation, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(OutOfAreaFlag, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(SegmentNumber, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(PartC_BeneficiaryPremium, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(PartD_BeneficiaryPremium, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(ElectionType, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(EnrollmentSource, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(PartD_OptOutFlag, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(PremiumWithholdOption_PartsC_D, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(CumulativeNumberOfUncoveredMonths, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(CreditableCoverageFlag, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(EmployerSubsidyOverrideFlag, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(ProcessingTimestamp, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(EndDate, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(SubmittedNumberOfUncoveredMonths, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(Filler3, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(SecondaryDrugInsuranceFlag, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(SecondaryRxID, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(SecondaryRxGroup, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(EGHP, ''))), ':',  
														    RTRIM(LTRIM(COALESCE(PartD_LowIncomePremiumSubsidyLevel, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(LowIncomeCoPayCategory, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(LowIncomePeriodEffectiveDate, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(PartD_LateEnrollmentPenaltyAmount, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(PartD_LateEnrollmentPenaltyWaivedAmount, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(PartD_LateEnrollmentPenaltySubsidyAmount, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(LowIncomePartD_PremiumSubsidyAmount, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(PartD_RxBIN, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(PartD_RxPCN, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(PartD_RxGroup, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(PartD_RxID, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(SecondaryRxBIN, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(SecondaryRxPCN, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(DeMinimisDifferentialAmount, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(MSPStatusFlag, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(LowIncomePeriodEndDate, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(LowIncomeSubsidySourceCode, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(EnrolleeTypeFlagPBPLevel, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(ApplicationDateIndicator, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(TRCShortName, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(DisenrollmentReasonCode, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(MMPOptOutFlag, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(CleanUpID, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(POSDrugEditUpdateDeleteFlag, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(POSDrugEditStatus, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(POSDrugEditClass, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(POSDrugEditCode, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(NotificationDate, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(ImplementationDate, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(TerminationDate, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(NotificationPOSDrugEditCode, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(Filler4, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(SystemAssignedTransactionTrackingID, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(PlanAssignedTransactionTrackingID, '')))))), 2)) ; 
	    
	   UPDATE  CHSStaging.dbo.TRRVerbatimStaging 
        SET     L_MemberTRRVerbatim_RK = UPPER(CONVERT(CHAR(32), HASHBYTES('MD5', 
                                                                    UPPER(CONCAT(RTRIM(LTRIM(COALESCE(CentauriMemberID, ''))), ':', 
                                                                                 RTRIM(LTRIM(COALESCE(TRRVerbatim_BK, '')))))), 2)) , 
                S_MemberHICN_RK = UPPER(CONVERT(CHAR(32), HASHBYTES('MD5', 
                                                                    UPPER(CONCAT(RTRIM(LTRIM(COALESCE(CentauriMemberID, ''))), ':', 
                                                                                 RTRIM(LTRIM(COALESCE(HICN, ''))), ':', 
                                                                                 RTRIM(LTRIM(COALESCE(LoadDate, ''))), ':', 
                                                                                 RTRIM(LTRIM(COALESCE(FileName, '')))))), 2)) , 
                S_MemberHICN_HashDiff = UPPER(CONVERT(CHAR(32), HASHBYTES('MD5', 
                                                                          UPPER(CONCAT(RTRIM(LTRIM(COALESCE(CentauriMemberID, ''))), ':', 
                                                                                       RTRIM(LTRIM(COALESCE(HICN, '')))))), 2)) , 
			 S_MemberDemo_RK = UPPER(CONVERT(CHAR(32), HASHBYTES('MD5', 
                                                             UPPER(CONCAT(RTRIM(LTRIM(COALESCE(CentauriMemberID, ''))), ':',
														    RTRIM(LTRIM(COALESCE(FirstName, ''))), ':',  
														    RTRIM(LTRIM(COALESCE(Surname, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(MiddleInitial, ''))), ':',  
														    RTRIM(LTRIM(COALESCE(GenderCode, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(DOB, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(LoadDate, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(FileName, '')))))), 2)) , 
			 S_MemberDemo_HashDiff = UPPER(CONVERT(CHAR(32), HASHBYTES('MD5', 
                                                             UPPER(CONCAT(RTRIM(LTRIM(COALESCE(FirstName, ''))), ':',  
														    RTRIM(LTRIM(COALESCE(Surname, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(MiddleInitial, ''))), ':',  
														    RTRIM(LTRIM(COALESCE(GenderCode, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(DOB, '')))))), 2)) , 
			 H_TRRVerbatim_RK = UPPER(CONVERT(CHAR(32), HASHBYTES('MD5', 
                                                             UPPER(RTRIM(LTRIM(COALESCE(TRRVerbatim_BK, ''))))), 2)) , 
                S_TRRVerbatim_RK = UPPER(CONVERT(CHAR(32), HASHBYTES('MD5', 
                                                             UPPER(CONCAT(RTRIM(LTRIM(COALESCE(TRRVerbatim_BK, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(HICN, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(Surname, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(FirstName, ''))), ':',  
														    RTRIM(LTRIM(COALESCE(MiddleInitial, ''))), ':',  
														    RTRIM(LTRIM(COALESCE(GenderCode, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(DOB, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(RecordType, ''))), ':',  
														    RTRIM(LTRIM(COALESCE(ContractNumber, ''))), ':',  
														    RTRIM(LTRIM(COALESCE(PlanTransactionText, ''))), ':',  
														    RTRIM(LTRIM(COALESCE(Filler, ''))), ':',  
														    RTRIM(LTRIM(COALESCE(TransactionAcceptRejectStatus, ''))), ':',  
														    RTRIM(LTRIM(COALESCE(SystemAssignedTransactionTrackingID, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(PlanAssignedTransactionTrackingID, ''))), ':', 
														    RTRIM(LTRIM(COALESCE(FileName, ''))), ':',  
														    RTRIM(LTRIM(COALESCE(LoadDate, '')))))), 2)) , 
                S_TRRVerbatim_HashDiff = UPPER(CONVERT(CHAR(32), HASHBYTES('MD5', 
                                                             UPPER(CONCAT(RTRIM(LTRIM(COALESCE(TRRVerbatim_BK, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(HICN, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(Surname, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(FirstName, ''))), ':',  
														    RTRIM(LTRIM(COALESCE(MiddleInitial, ''))), ':',  
														    RTRIM(LTRIM(COALESCE(GenderCode, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(DOB, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(RecordType, ''))), ':',  
														    RTRIM(LTRIM(COALESCE(ContractNumber, ''))), ':',  
														    RTRIM(LTRIM(COALESCE(PlanTransactionText, ''))), ':',  
														    RTRIM(LTRIM(COALESCE(Filler, ''))), ':',  
														    RTRIM(LTRIM(COALESCE(TransactionAcceptRejectStatus, ''))), ':',  
														    RTRIM(LTRIM(COALESCE(SystemAssignedTransactionTrackingID, ''))), ':', 
                                                                          RTRIM(LTRIM(COALESCE(PlanAssignedTransactionTrackingID, '')))))), 2)) ; 
 
 
    END; 
 
 
GO
