CREATE TABLE [stage].[GuildNetGoldTrackertoCentauriforTargetListupdated12302016]
(
[Project ID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Client ID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CIN] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MEDICARE NO] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gender] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[First Name] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Last Name] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MEMBER DOB] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Provider Name] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Provider Address] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STREET2] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Provider City] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Provider State] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Provider Zip] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Potential CLAIM NO] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Provider NPI] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Chart Received] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Date] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Other Notes] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NewAddress] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NewZip] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ChaseID] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PhoneUSed] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FAXUSed] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CentuariProviderID] [bigint] NULL,
[Member_PK] [bigint] NULL,
[Provider_PK] [bigint] NULL,
[ProviderMaster_PK] [bigint] NULL,
[ProviderOffice_PK] [bigint] NULL,
[Provider_Last_Name] [varchar] (75) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Provider_First_Name] [varchar] (75) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
