CREATE TABLE [stage].[GuildNetFIDATrackertoCentauriforTargetListupdated12292016]
(
[Project ID] [varchar] (50) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[Client ID] [varchar] (50) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[CIN] [varchar] (50) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[MEDICARENO] [varchar] (50) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[Gender] [varchar] (50) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[Member Name] [varchar] (250) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[DOB] [varchar] (50) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[Provider Name] [varchar] (250) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[Provider Address] [varchar] (250) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[Address 2] [varchar] (50) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[Provider City] [varchar] (50) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[Provider State] [varchar] (50) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[Provider Zip] [varchar] (50) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[Potential CLAIM_NUMBER] [varchar] (50) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[PROV_NPI] [varchar] (50) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[CL_EXT_2003_PROV_NAME] [varchar] (50) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[Chart Received (Y)] [varchar] (50) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[Date] [varchar] (50) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[Other Notes] [varchar] (250) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[NewAddress] [varchar] (250) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[NewZip] [varchar] (15) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[CentuariProviderID] [bigint] NULL,
[Member_PK] [bigint] NULL,
[Provider_PK] [bigint] NULL,
[ProviderMaster_PK] [bigint] NULL,
[ProviderOffice_PK] [bigint] NULL,
[Chase_ID] [varchar] (20) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[PhoneUSed] [varchar] (15) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[FAXUSed] [varchar] (15) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[Provider_Last_Name] [varchar] (75) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[Provider_First_Name] [varchar] (75) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[member_Last_Name] [varchar] (75) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[member_First_Name] [varchar] (75) COLLATE SQL_Latin1_General_CP437_CI_AI NULL
) ON [PRIMARY]
GO
