SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [Proxy].[EventKey] AS
SELECT  [AfterDOBDays],
        [AfterDOBMonths],
        [Allow],
        [AllowEndDate],
        [AllowLab],
		[AllowSupplemental],
        [BatchID],
        [BeginDate],
        [BeginDays],
        [BeginMonths],
        [BitClaimAttribsAllowed],
        [BitClaimAttribsDenied],
        [BitClaimSrcTypesAllowed],
        [BitClaimSrcTypesDenied],
        [BitSpecialtiesAllowed],
        [BitSpecialtiesDenied],
        [ClaimTypeID],
        [Code],
        [CodeID],
        [CodeTypeID],
        [CountAllowed],
        [CountCriteria],
        [CountDenied],
        [DataRunID],
        [DataSetID],
        [DefaultDays],
        [DefaultValue],
        [Descr],
        [EndDate],
        [EndDays],
        [EndMonths],
        [EventCritCodeID],
        [EventCritDescr],
        [EventCritGuid],
        [EventCritID],
        [EventGuid],
        [EventID],
        [EventOptGuid],
        [EventOptID],
        [EventTypeID],
        [ExpireDate],
        [Gender],
        [HasClaimAttribReqs],
        [HasCodeReqs],
        [HasDateReqs],
        [HasEnrollReqs],
        [HasMemberReqs],
        [HasProviderReqs],
        [IsClaimAttrib],
        [MeasureSetID],
        [OptionNbr],
        [RankOrder],
        [Reference1],
        [Reference2],
        [Reference3],
        [Reference4],
        [RequireEndDate],
        [RequireEnrolled],
        [RequireOnly],
        [RequirePaid],
        [RequirePrimary],
        [Require1stRank],
        Value,
        ValueTypeID
FROM    Internal.[EventKey]
WHERE	(SpId = @@SPID);
GO
