SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- =============================================
-- Author:		Paul Johnson
-- Create date: 09/14/2016
-- Description:	Loads the tblMemberHash with the hashdiff key
-- Usage		EXECUTE adv.sp_LoadMemberWChash @CCI
-- =============================================
CREATE PROCEDURE [adv].[spLoadMemberWCHash]
    @CCI INT ,
    @DATE DATETIME
AS
    BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
        SET NOCOUNT ON;

    -- Insert statements for procedure here

        INSERT  INTO adv.StagingHash
                ( HashDiff ,
                  ClientID ,
                  TableName ,
                  CreateDate
                )
                SELECT  UPPER(CONVERT(CHAR(32), HASHBYTES('MD5',
                                                          UPPER(CONCAT(RTRIM(LTRIM(COALESCE(a.Member_PK,
                                                              ''))), ':',
                                                              RTRIM(LTRIM(COALESCE(a.HICNumber,
                                                              ''))), ':',
                                                              RTRIM(LTRIM(COALESCE(a.Member_ID,
                                                              ''))), ':',
                                                              RTRIM(LTRIM(COALESCE(a.Lastname,
                                                              ''))), ':',
                                                              RTRIM(LTRIM(COALESCE(a.Firstname,
                                                              ''))), ':',
                                                              RTRIM(LTRIM(COALESCE(a.DOB,
                                                              ''))), ':',
                                                              RTRIM(LTRIM(COALESCE(a.Gender,
                                                              ''))), ':',
                                                              RTRIM(LTRIM(COALESCE(a.Address,
                                                              ''))), ':',
                                                              RTRIM(LTRIM(COALESCE(a.ZipCode_PK,
                                                              ''))), ':',
                                                              RTRIM(LTRIM(COALESCE(a.Contact_Number,
                                                              ''))), ':',
                                                              RTRIM(LTRIM(COALESCE(a.PID,
                                                              ''))), ':',
                                                              RTRIM(LTRIM(COALESCE(a.Segment_PK,
                                                              ''))), ':',
                                                              RTRIM(LTRIM(COALESCE(a.ChartPriority,
                                                              ''))), ':',
                                                              RTRIM(LTRIM(COALESCE(a.Ref_Number,
                                                              ''))), ':',
                                                              RTRIM(LTRIM(COALESCE(a.Latitude,
                                                              ''))), ':',
                                                              RTRIM(LTRIM(COALESCE(a.Longitude,
                                                              ''))), ':',
                                                              RTRIM(LTRIM(COALESCE(a.parent_gardian,
                                                              ''))), ':',
                                                              RTRIM(LTRIM(COALESCE(a.preferred_practitioner_gender,
                                                              ''))), ':',
                                                              RTRIM(LTRIM(COALESCE(a.Cell_Number,
                                                              ''))), ':',
                                                              RTRIM(LTRIM(COALESCE(a.Email_Address,
                                                              ''))), ':',
                                                              RTRIM(LTRIM(COALESCE(a.does_not_speak_english,
                                                              ''))), ':',
                                                              RTRIM(LTRIM(COALESCE(a.unable_to_determine_language,
                                                              ''))), ':',
                                                              RTRIM(LTRIM(COALESCE(a.speaking_language,
                                                              ''))), ':',
                                                              RTRIM(LTRIM(COALESCE(a.language_line_will_be_required_for_the_visit,
                                                              ''))), ':',
                                                              RTRIM(LTRIM(COALESCE(a.plan_unable_to_validate_client_vendor_relationship,
                                                              ''))), ':',
                                                              RTRIM(LTRIM(COALESCE(a.preferred_method_of_contact,
                                                              ''))), ':',
                                                              RTRIM(LTRIM(COALESCE(a.permission_to_leave_voicemail,
                                                              ''))), ':',
                                                              RTRIM(LTRIM(COALESCE(a.Orig_Address,
                                                              ''))), ':',
                                                              RTRIM(LTRIM(COALESCE(a.Orig_ZipCode_PK,
                                                              ''))), ':',
                                                              RTRIM(LTRIM(COALESCE(a.Orig_Contact_Number,
                                                              ''))), ':',
                                                              RTRIM(LTRIM(COALESCE(a.Orig_Email_Address,
                                                              ''))), ':',
                                                              RTRIM(LTRIM(COALESCE(a.place_of_assessment_is_not_members_home,
                                                              ''))), ':',
                                                              RTRIM(LTRIM(COALESCE(a.Home_Address,
                                                              ''))), ':',
                                                              RTRIM(LTRIM(COALESCE(a.Home_ZipCode_PK,
                                                              ''))), ':',
                                                              RTRIM(LTRIM(COALESCE(a.Home_Contact_Number,
                                                              ''))), ':',
                                                              RTRIM(LTRIM(COALESCE(a.Home_Email_Address,
                                                              ''))), ':',
                                                              RTRIM(LTRIM(COALESCE(a.members_power_of_attorney,
                                                              ''))), ':',
                                                              RTRIM(LTRIM(COALESCE(a.POA_Name,
                                                              ''))), ':',
                                                              RTRIM(LTRIM(COALESCE(a.POA_Address,
                                                              ''))), ':',
                                                              RTRIM(LTRIM(COALESCE(a.POA_ZipCode_PK,
                                                              ''))), ':',
                                                              RTRIM(LTRIM(COALESCE(a.POA_Contact_Number,
                                                              ''))), ':',
                                                              RTRIM(LTRIM(COALESCE(a.POA_Email_Address,
                                                              ''))), ':',
                                                              RTRIM(LTRIM(COALESCE(a.Client_PK,
                                                              ''))), ':',
                                                              RTRIM(LTRIM(COALESCE(a.Eff_Date,
                                                              ''))), ':',
                                                              RTRIM(LTRIM(COALESCE(a.Exp_Date,
                                                              '')))))), 2)) ,
                        @CCI ,
                        'tblMember' ,
                        @DATE
                FROM    adv.tblMemberWCStage a
                        LEFT OUTER JOIN adv.StagingHash b ON UPPER(CONVERT(CHAR(32), HASHBYTES('MD5',
                                                              UPPER(CONCAT(RTRIM(LTRIM(COALESCE(a.Member_PK,
                                                              ''))), ':',
                                                              RTRIM(LTRIM(COALESCE(a.HICNumber,
                                                              ''))), ':',
                                                              RTRIM(LTRIM(COALESCE(a.Member_ID,
                                                              ''))), ':',
                                                              RTRIM(LTRIM(COALESCE(a.Lastname,
                                                              ''))), ':',
                                                              RTRIM(LTRIM(COALESCE(a.Firstname,
                                                              ''))), ':',
                                                              RTRIM(LTRIM(COALESCE(a.DOB,
                                                              ''))), ':',
                                                              RTRIM(LTRIM(COALESCE(a.Gender,
                                                              ''))), ':',
                                                              RTRIM(LTRIM(COALESCE(a.Address,
                                                              ''))), ':',
                                                              RTRIM(LTRIM(COALESCE(a.ZipCode_PK,
                                                              ''))), ':',
                                                              RTRIM(LTRIM(COALESCE(a.Contact_Number,
                                                              ''))), ':',
                                                              RTRIM(LTRIM(COALESCE(a.PID,
                                                              ''))), ':',
                                                              RTRIM(LTRIM(COALESCE(a.Segment_PK,
                                                              ''))), ':',
                                                              RTRIM(LTRIM(COALESCE(a.ChartPriority,
                                                              ''))), ':',
                                                              RTRIM(LTRIM(COALESCE(a.Ref_Number,
                                                              ''))), ':',
                                                              RTRIM(LTRIM(COALESCE(a.Latitude,
                                                              ''))), ':',
                                                              RTRIM(LTRIM(COALESCE(a.Longitude,
                                                              ''))), ':',
                                                              RTRIM(LTRIM(COALESCE(a.parent_gardian,
                                                              ''))), ':',
                                                              RTRIM(LTRIM(COALESCE(a.preferred_practitioner_gender,
                                                              ''))), ':',
                                                              RTRIM(LTRIM(COALESCE(a.Cell_Number,
                                                              ''))), ':',
                                                              RTRIM(LTRIM(COALESCE(a.Email_Address,
                                                              ''))), ':',
                                                              RTRIM(LTRIM(COALESCE(a.does_not_speak_english,
                                                              ''))), ':',
                                                              RTRIM(LTRIM(COALESCE(a.unable_to_determine_language,
                                                              ''))), ':',
                                                              RTRIM(LTRIM(COALESCE(a.speaking_language,
                                                              ''))), ':',
                                                              RTRIM(LTRIM(COALESCE(a.language_line_will_be_required_for_the_visit,
                                                              ''))), ':',
                                                              RTRIM(LTRIM(COALESCE(a.plan_unable_to_validate_client_vendor_relationship,
                                                              ''))), ':',
                                                              RTRIM(LTRIM(COALESCE(a.preferred_method_of_contact,
                                                              ''))), ':',
                                                              RTRIM(LTRIM(COALESCE(a.permission_to_leave_voicemail,
                                                              ''))), ':',
                                                              RTRIM(LTRIM(COALESCE(a.Orig_Address,
                                                              ''))), ':',
                                                              RTRIM(LTRIM(COALESCE(a.Orig_ZipCode_PK,
                                                              ''))), ':',
                                                              RTRIM(LTRIM(COALESCE(a.Orig_Contact_Number,
                                                              ''))), ':',
                                                              RTRIM(LTRIM(COALESCE(a.Orig_Email_Address,
                                                              ''))), ':',
                                                              RTRIM(LTRIM(COALESCE(a.place_of_assessment_is_not_members_home,
                                                              ''))), ':',
                                                              RTRIM(LTRIM(COALESCE(a.Home_Address,
                                                              ''))), ':',
                                                              RTRIM(LTRIM(COALESCE(a.Home_ZipCode_PK,
                                                              ''))), ':',
                                                              RTRIM(LTRIM(COALESCE(a.Home_Contact_Number,
                                                              ''))), ':',
                                                              RTRIM(LTRIM(COALESCE(a.Home_Email_Address,
                                                              ''))), ':',
                                                              RTRIM(LTRIM(COALESCE(a.members_power_of_attorney,
                                                              ''))), ':',
                                                              RTRIM(LTRIM(COALESCE(a.POA_Name,
                                                              ''))), ':',
                                                              RTRIM(LTRIM(COALESCE(a.POA_Address,
                                                              ''))), ':',
                                                              RTRIM(LTRIM(COALESCE(a.POA_ZipCode_PK,
                                                              ''))), ':',
                                                              RTRIM(LTRIM(COALESCE(a.POA_Contact_Number,
                                                              ''))), ':',
                                                              RTRIM(LTRIM(COALESCE(a.POA_Email_Address,
                                                              ''))), ':',
                                                              RTRIM(LTRIM(COALESCE(a.Client_PK,
                                                              ''))), ':',
                                                              RTRIM(LTRIM(COALESCE(a.Eff_Date,
                                                              ''))), ':',
                                                              RTRIM(LTRIM(COALESCE(a.Exp_Date,
                                                              '')))))), 2)) = b.HashDiff
                                                             AND b.ClientID = @CCI
                                                             AND b.TableName = 'tblMember'
                WHERE   b.HashDiff IS NULL;
    END;
GO
