SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO




CREATE PROC [raps].[spClearResponseStaging]
AS
     SET NOCOUNT ON;
     SET XACT_ABORT ON;

     TRUNCATE TABLE raps.RAPS_RESPONSE_AAA
	TRUNCATE TABLE raps.RAPS_RESPONSE_BBB
	TRUNCATE TABLE raps.RAPS_RESPONSE_CCC
	TRUNCATE TABLE raps.RAPS_RESPONSE_YYY
	TRUNCATE TABLE raps.RAPS_RESPONSE_ZZZ


GO
