CREATE TABLE [dbo].[S_RAPS_Response_CCC]
(
[S_RAPS_Response_CCCID] [bigint] NOT NULL IDENTITY(1, 1),
[S_RAPS_Response_CCC_RK] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[H_RAPS_Response_RK] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[RecordID] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SeqNo] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SeqErrorCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PatientControlNo] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HicNo] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HicErrorCode] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PatientDOB] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DOBErrorCode] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProviderType1] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FromDate1] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ThruDate1] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DeleteIND1] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DiagnosisCode1] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DiagClstrErrorA1] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DiagClstrErrorB1] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProviderType2] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FromDate2] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ThruDate2] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DeleteIND2] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DiagnosisCode2] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DiagClstrErrorA2] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DiagClstrErrorB2] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProviderType3] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FromDate3] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ThruDate3] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DeleteIND3] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DiagnosisCode3] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DiagClstrErrorA3] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DiagClstrErrorB3] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProviderType4] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FromDate4] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ThruDate4] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DeleteIND4] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DiagnosisCode4] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DiagClstrErrorA4] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DiagClstrErrorB4] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProviderType5] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FromDate5] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ThruDate5] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DeleteIND5] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DiagnosisCode5] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DiagClstrErrorA5] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DiagClstrErrorB5] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProviderType6] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FromDate6] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ThruDate6] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DeleteIND6] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DiagnosisCode6] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DiagClstrErrorA6] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DiagClstrErrorB6] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProviderType7] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FromDate7] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ThruDate7] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DeleteIND7] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DiagnosisCode7] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DiagClstrErrorA7] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DiagClstrErrorB7] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProviderType8] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FromDate8] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ThruDate8] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DeleteIND8] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DiagnosisCode8] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DiagClstrErrorA8] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DiagClstrErrorB8] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProviderType9] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FromDate9] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ThruDate9] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DeleteIND9] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DiagnosisCode9] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DiagClstrErrorA9] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DiagClstrErrorB9] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProviderType10] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FromDate10] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ThruDate10] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DeleteIND10] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DiagnosisCode10] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DiagClstrErrorA10] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DiagClstrErrorB10] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CorrectedHicNo] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RiskAssessmentCode1] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RiskAssessmentCodeError1] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RiskAssessmentCode2] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RiskAssessmentCodeError2] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RiskAssessmentCode3] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RiskAssessmentCodeError3] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RiskAssessmentCode4] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RiskAssessmentCodeError4] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RiskAssessmentCode5] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RiskAssessmentCodeError5] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RiskAssessmentCode6] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RiskAssessmentCodeError6] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RiskAssessmentCode7] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RiskAssessmentCodeError7] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RiskAssessmentCode8] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RiskAssessmentCodeError8] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RiskAssessmentCode9] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RiskAssessmentCodeError9] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RiskAssessmentCode10] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RiskAssessmentCodeError10] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HashDiff] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[LoadDate] [datetime] NOT NULL CONSTRAINT [DF_S_RAPS_Response_CCC_LoadDate] DEFAULT (getdate()),
[RecordSource] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[RecordEndDate] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[S_RAPS_Response_CCC] ADD CONSTRAINT [PK_S_RAPS_Response_CCC] PRIMARY KEY CLUSTERED  ([S_RAPS_Response_CCCID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_LoadDate] ON [dbo].[S_RAPS_Response_CCC] ([LoadDate]) INCLUDE ([DiagClstrErrorA1], [DiagClstrErrorA10], [DiagClstrErrorA2], [DiagClstrErrorA3], [DiagClstrErrorA4], [DiagClstrErrorA5], [DiagClstrErrorA6], [DiagClstrErrorA7], [DiagClstrErrorA8], [DiagClstrErrorA9], [DiagClstrErrorB1], [DiagClstrErrorB10], [DiagClstrErrorB2], [DiagClstrErrorB3], [DiagClstrErrorB4], [DiagClstrErrorB5], [DiagClstrErrorB6], [DiagClstrErrorB7], [DiagClstrErrorB8], [DiagClstrErrorB9], [DiagnosisCode1], [DiagnosisCode10], [DiagnosisCode2], [DiagnosisCode3], [DiagnosisCode4], [DiagnosisCode5], [DiagnosisCode6], [DiagnosisCode7], [DiagnosisCode8], [DiagnosisCode9], [DOBErrorCode], [FromDate1], [FromDate10], [FromDate2], [FromDate3], [FromDate4], [FromDate5], [FromDate6], [FromDate7], [FromDate8], [FromDate9], [H_RAPS_Response_RK], [HicErrorCode], [HicNo], [PatientControlNo], [PatientDOB], [ProviderType1], [ProviderType10], [ProviderType2], [ProviderType3], [ProviderType4], [ProviderType5], [ProviderType6], [ProviderType7], [ProviderType8], [ProviderType9], [RecordSource], [RiskAssessmentCode1], [RiskAssessmentCode10], [RiskAssessmentCode2], [RiskAssessmentCode3], [RiskAssessmentCode4], [RiskAssessmentCode5], [RiskAssessmentCode6], [RiskAssessmentCode7], [RiskAssessmentCode8], [RiskAssessmentCode9], [RiskAssessmentCodeError1], [RiskAssessmentCodeError10], [RiskAssessmentCodeError2], [RiskAssessmentCodeError3], [RiskAssessmentCodeError4], [RiskAssessmentCodeError5], [RiskAssessmentCodeError6], [RiskAssessmentCodeError7], [RiskAssessmentCodeError8], [RiskAssessmentCodeError9], [SeqNo], [ThruDate1], [ThruDate10], [ThruDate2], [ThruDate3], [ThruDate4], [ThruDate5], [ThruDate6], [ThruDate7], [ThruDate8], [ThruDate9]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_EndDate] ON [dbo].[S_RAPS_Response_CCC] ([RecordEndDate]) INCLUDE ([H_RAPS_Response_RK], [HashDiff], [S_RAPS_Response_CCC_RK]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_S_RAPS_Response_CCC] ON [dbo].[S_RAPS_Response_CCC] ([S_RAPS_Response_CCC_RK]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[S_RAPS_Response_CCC] ADD CONSTRAINT [FK_S_RAPS_Response_CCC_H_RAPS_Response] FOREIGN KEY ([H_RAPS_Response_RK]) REFERENCES [dbo].[H_RAPS_Response] ([H_RAPS_Response_RK])
GO
