IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'IMIHEALTH\George.Graves')
CREATE LOGIN [IMIHEALTH\George.Graves] FROM WINDOWS
GO
CREATE USER [IMIHEALTH\George.Graves] FOR LOGIN [IMIHEALTH\George.Graves]
GO
GRANT VIEW DEFINITION TO [IMIHEALTH\George.Graves]
