CREATE TABLE [dbo].[PAMeasureIntake]
(
[PAMeasureIntakeID] [int] NOT NULL IDENTITY(1, 1),
[MemberID] [int] NULL,
[QuestionA] [bit] NULL,
[QuestionB] [bit] NULL,
[SmokingQuestion1] [bit] NULL,
[SmokingQuestion2] [bit] NULL,
[SmokingQuestion3] [bit] NULL,
[SmokingQuestion4] [bit] NULL,
[SmokingQuestion5] [bit] NULL,
[SmokingQuestion6] [bit] NULL,
[SmokingQuestion7] [bit] NULL,
[SmokingQuestion8] [bit] NULL,
[DepressionQuestion1] [bit] NULL,
[DepressionQuestion1a] [bit] NULL,
[DepressionQuestion2] [bit] NULL,
[DepressionQuestion3] [bit] NULL,
[SmokingQuestion1_Date] [date] NULL,
[SmokingQuestion4_Date] [date] NULL,
[SmokingQuestion5_Date] [date] NULL,
[SmokingQuestion6_Date] [date] NULL,
[SmokingQuestion8_Date] [date] NULL,
[DepressionQuestion1_Date] [date] NULL,
[DepressionQuestion1a_Date] [date] NULL,
[DepressionQuestion2_Date] [date] NULL,
[DepressionQuestion3_Date] [date] NULL,
[QuestionA_Date] [date] NULL,
[QuestionB1_Date] [date] NULL,
[QuestionB2_Date] [date] NULL,
[DepressionScreeningTool] [int] NULL,
[PostpartumQuestionA] [bit] NULL,
[PostpartumQuestionA_Date] [date] NULL,
[PostpartumQuestion4] [bit] NULL,
[PostpartumQuestion4_Date] [date] NULL,
[PostpartumQuestion4a] [bit] NULL,
[PostpartumQuestion4a_Date] [date] NULL,
[PostpartumQuestion5] [bit] NULL,
[PostpartumQuestion5_Date] [date] NULL,
[PostpartumQuestion6] [bit] NULL,
[PostpartumQuestion6_Date] [date] NULL,
[PostpartumScreeningTool] [int] NULL,
[CreatedDate] [datetime] NULL CONSTRAINT [DF_PAMeasureIntake_CreatedDate] DEFAULT (getdate()),
[LastUpdatedDate] [datetime] NULL,
[PursuitEventID] [int] NOT NULL,
[RiskFactorQuestion1] [bit] NULL,
[RiskFactorQuestion2] [bit] NULL,
[RiskFactorQuestion3] [bit] NULL,
[RiskFactorQuestion4] [bit] NULL,
[RiskFactorQuestion1_Date] [date] NULL,
[RiskFactorQuestion2_Date] [date] NULL,
[RiskFactorQuestion3_Date] [date] NULL,
[RiskFactorQuestion4_Date] [date] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PAMeasureIntake] ADD CONSTRAINT [PK_PAMeasureIntake] PRIMARY KEY CLUSTERED  ([PAMeasureIntakeID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PAMeasureIntake] ADD CONSTRAINT [fk_PAMeasureIntake_PursuitEvent] FOREIGN KEY ([PursuitEventID]) REFERENCES [dbo].[PursuitEvent] ([PursuitEventID])
GO
