SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
 
 
-- ============================================= 
-- Author:		Paul Johnson 
-- Create date: 09/19/2016 
--Update 09/27/2016 Adding LoadDate to Primary Key PJ 
--Update 09/29/2018 Adding Channel_PK and EDGEMemberID  PJ 
-- Description:	Data Vault Suspect Load Satelites 
-- ============================================= 
CREATE PROCEDURE [dbo].[spDV_Suspect_LoadSats] 
	-- Add the parameters for the stored procedure here 
    @CCI VARCHAR(50) 
AS 
    BEGIN 
	-- SET NOCOUNT ON added to prevent extra result sets from 
	-- interfering with SELECT statements. 
        SET NOCOUNT ON; 
 
--**S_SuspectDetail LOAD 
 
        INSERT  INTO [dbo].[S_SuspectDetail] 
                ( [S_SuspectDetail_RK] , 
                  [LoadDate] , 
                  [H_Suspect_RK] , 
                  [IsScanned] , 
                  [IsCNA] , 
                  [IsCoded] , 
                  [IsQA] , 
                  [Scanned_User_PK] , 
                  [CNA_User_PK] , 
                  [Coded_User_PK] , 
                  [QA_User_PK] , 
                  [Scanned_Date] , 
                  [CNA_Date] , 
                  [Coded_Date] , 
                  [QA_Date] , 
                  [IsDiagnosisCoded] , 
                  [IsNotesCoded] , 
                  [LastAccessed_Date] , 
                  [LastUpdated] , 
                  [dtCreated] , 
                  [IsInvoiced] , 
                  [MemberStatus] , 
                  [ProspectiveFormStatus] , 
                  [InvoiceRec_Date] , 
                  [ChartRec_FaxIn_Date] , 
                  [ChartRec_MailIn_Date] , 
                  [ChartRec_InComp_Date] , 
                  [IsHighPriority] , 
                  [IsInComp_Replied] , 
                  [ChaseID] , 
                  [ContractCode] , 
                  [REN_PROVIDER_SPECIALTY] , 
                  [ChartPriority] , 
                  [ChartRec_Date] , 
                  [InvoiceExt_Date] , 
				  [Channel_PK] , 
				  [EDGEMemberID], 
                  [HashDiff] , 
                  [RecordSource], 
				  Provider_PK 
                ) 
                SELECT  UPPER(CONVERT(CHAR(32), HASHBYTES('MD5', 
                                                          UPPER(CONCAT(RTRIM(LTRIM(COALESCE(rw.CSI, 
                                                              ''))), ':', 
															  RTRIM(LTRIM(COALESCE(rw.[Provider_PK], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[IsScanned], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[IsCNA], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[IsCoded], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[IsQA], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[Scanned_User_PK], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[CNA_User_PK], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[Coded_User_PK], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[QA_User_PK], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[Scanned_Date], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[CNA_Date], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[Coded_Date], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[QA_Date], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[IsDiagnosisCoded], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[IsNotesCoded], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[LastAccessed_Date], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[LastUpdated], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[dtCreated], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[IsInvoiced], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[MemberStatus], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[ProspectiveFormStatus], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[InvoiceRec_Date], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[ChartRec_FaxIn_Date], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[ChartRec_MailIn_Date], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[ChartRec_InComp_Date], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[IsHighPriority], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[IsInComp_Replied], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.ChaseID, 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.ContractCode, 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.REN_PROVIDER_SPECIALTY, 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.ChartPriority, 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.ChartRec_Date, 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.InvoiceExt_Date, 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[Channel_PK] , 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[EDGEMemberID], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[LoadDate], 
                                                              '')))))), 2)) , 
                        LoadDate , 
                        SuspectHashKey , 
                        [IsScanned] , 
                        [IsCNA] , 
                        [IsCoded] , 
                        [IsQA] , 
                        [Scanned_User_PK] , 
                        [CNA_User_PK] , 
                        [Coded_User_PK] , 
                        [QA_User_PK] , 
                        [Scanned_Date] , 
                        [CNA_Date] , 
                        [Coded_Date] , 
                        [QA_Date] , 
                        [IsDiagnosisCoded] , 
                        [IsNotesCoded] , 
                        [LastAccessed_Date] , 
                        [LastUpdated] , 
                        [dtCreated] , 
                        [IsInvoiced] , 
                        [MemberStatus] , 
                        [ProspectiveFormStatus] , 
                        [InvoiceRec_Date] , 
                        [ChartRec_FaxIn_Date] , 
                        [ChartRec_MailIn_Date] , 
                        [ChartRec_InComp_Date] , 
                        [IsHighPriority] , 
                        [IsInComp_Replied] , 
                        [ChaseID] , 
                        [ContractCode] , 
                        [REN_PROVIDER_SPECIALTY] , 
                        [ChartPriority] , 
                        [ChartRec_Date] , 
                        [InvoiceExt_Date] , 
						 [Channel_PK] , 
				  [EDGEMemberID], 
                        UPPER(CONVERT(CHAR(32), HASHBYTES('MD5', 
                                                          UPPER(CONCAT(RTRIM(LTRIM(COALESCE(rw.[IsScanned], 
                                                              ''))), ':', 
															   RTRIM(LTRIM(COALESCE(rw.[Provider_PK], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[IsCNA], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[IsCoded], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[IsQA], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[Scanned_User_PK], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[CNA_User_PK], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[Coded_User_PK], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[QA_User_PK], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[Scanned_Date], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[CNA_Date], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[Coded_Date], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[QA_Date], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[IsDiagnosisCoded], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[IsNotesCoded], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[LastAccessed_Date], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[LastUpdated], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[dtCreated], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[IsInvoiced], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[MemberStatus], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[ProspectiveFormStatus], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[InvoiceRec_Date], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[ChartRec_FaxIn_Date], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[ChartRec_MailIn_Date], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[ChartRec_InComp_Date], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[IsHighPriority], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[IsInComp_Replied], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.ChaseID, 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.ContractCode, 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.REN_PROVIDER_SPECIALTY, 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.ChartPriority, 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.ChartRec_Date, 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.InvoiceExt_Date, 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[Channel_PK] , 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[EDGEMemberID], 
                                                              '')))))), 2)) , 
                        RecordSource, 
						rw.Provider_PK 
                FROM    CHSStaging.adv.tblSuspectWCStage rw WITH ( NOLOCK ) 
                WHERE   UPPER(CONVERT(CHAR(32), HASHBYTES('MD5', 
                                                          UPPER(CONCAT(RTRIM(LTRIM(COALESCE(rw.[IsScanned], 
                                                              ''))), ':', 
															   RTRIM(LTRIM(COALESCE(rw.[Provider_PK], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[IsCNA], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[IsCoded], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[IsQA], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[Scanned_User_PK], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[CNA_User_PK], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[Coded_User_PK], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[QA_User_PK], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[Scanned_Date], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[CNA_Date], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[Coded_Date], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[QA_Date], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[IsDiagnosisCoded], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[IsNotesCoded], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[LastAccessed_Date], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[LastUpdated], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[dtCreated], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[IsInvoiced], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[MemberStatus], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[ProspectiveFormStatus], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[InvoiceRec_Date], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[ChartRec_FaxIn_Date], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[ChartRec_MailIn_Date], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[ChartRec_InComp_Date], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[IsHighPriority], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[IsInComp_Replied], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.ChaseID, 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.ContractCode, 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.REN_PROVIDER_SPECIALTY, 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.ChartPriority, 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.ChartRec_Date, 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.InvoiceExt_Date, 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[Channel_PK] , 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[EDGEMemberID], 
                                                              '')))))), 2)) NOT IN ( 
                        SELECT  HashDiff 
                        FROM    S_SuspectDetail 
                        WHERE   H_Suspect_RK = rw.SuspectHashKey 
                                AND RecordEndDate IS NULL ) 
                        AND rw.CCI = @CCI 
                GROUP BY UPPER(CONVERT(CHAR(32), HASHBYTES('MD5', 
                                                          UPPER(CONCAT(RTRIM(LTRIM(COALESCE(rw.CSI, 
                                                              ''))), ':', 
															  RTRIM(LTRIM(COALESCE(rw.[Provider_PK], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[IsScanned], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[IsCNA], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[IsCoded], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[IsQA], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[Scanned_User_PK], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[CNA_User_PK], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[Coded_User_PK], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[QA_User_PK], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[Scanned_Date], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[CNA_Date], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[Coded_Date], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[QA_Date], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[IsDiagnosisCoded], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[IsNotesCoded], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[LastAccessed_Date], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[LastUpdated], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[dtCreated], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[IsInvoiced], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[MemberStatus], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[ProspectiveFormStatus], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[InvoiceRec_Date], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[ChartRec_FaxIn_Date], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[ChartRec_MailIn_Date], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[ChartRec_InComp_Date], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[IsHighPriority], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[IsInComp_Replied], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.ChaseID, 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.ContractCode, 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.REN_PROVIDER_SPECIALTY, 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.ChartPriority, 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.ChartRec_Date, 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.InvoiceExt_Date, 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[Channel_PK] , 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[EDGEMemberID], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[LoadDate], 
                                                              '')))))), 2)) , 
                        LoadDate , 
                        SuspectHashKey , 
                        [IsScanned] , 
                        [IsCNA] , 
                        [IsCoded] , 
                        [IsQA] , 
                        [Scanned_User_PK] , 
                        [CNA_User_PK] , 
                        [Coded_User_PK] , 
                        [QA_User_PK] , 
                        [Scanned_Date] , 
                        [CNA_Date] , 
                        [Coded_Date] , 
                        [QA_Date] , 
                        [IsDiagnosisCoded] , 
                        [IsNotesCoded] , 
                        [LastAccessed_Date] , 
                        [LastUpdated] , 
                        [dtCreated] , 
                        [IsInvoiced] , 
                        [MemberStatus] , 
                        [ProspectiveFormStatus] , 
                        [InvoiceRec_Date] , 
                        [ChartRec_FaxIn_Date] , 
                        [ChartRec_MailIn_Date] , 
                        [ChartRec_InComp_Date] , 
                        [IsHighPriority] , 
                        [IsInComp_Replied] , 
                        [ChaseID] , 
                        [ContractCode] , 
                        [REN_PROVIDER_SPECIALTY] , 
                        [ChartPriority] , 
                        [ChartRec_Date] , 
                        [InvoiceExt_Date] , 
						 [Channel_PK] , 
				  [EDGEMemberID], 
                        UPPER(CONVERT(CHAR(32), HASHBYTES('MD5', 
                                                          UPPER(CONCAT(RTRIM(LTRIM(COALESCE(rw.[IsScanned], 
                                                              ''))), ':', 
															   RTRIM(LTRIM(COALESCE(rw.[Provider_PK], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[IsCNA], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[IsCoded], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[IsQA], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[Scanned_User_PK], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[CNA_User_PK], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[Coded_User_PK], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[QA_User_PK], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[Scanned_Date], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[CNA_Date], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[Coded_Date], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[QA_Date], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[IsDiagnosisCoded], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[IsNotesCoded], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[LastAccessed_Date], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[LastUpdated], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[dtCreated], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[IsInvoiced], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[MemberStatus], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[ProspectiveFormStatus], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[InvoiceRec_Date], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[ChartRec_FaxIn_Date], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[ChartRec_MailIn_Date], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[ChartRec_InComp_Date], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[IsHighPriority], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[IsInComp_Replied], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.ChaseID, 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.ContractCode, 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.REN_PROVIDER_SPECIALTY, 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.ChartPriority, 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.ChartRec_Date, 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.InvoiceExt_Date, 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[Channel_PK] , 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[EDGEMemberID], 
                                                              '')))))), 2)) , 
                        RecordSource, 
						rw.Provider_PK; 
 
	--RECORD END DATE CLEANUP 
        UPDATE  dbo.S_SuspectDetail 
        SET     RecordEndDate = ( SELECT    DATEADD(ss, -1, MIN(z.LoadDate)) 
                                  FROM      dbo.S_SuspectDetail z 
                                  WHERE     z.H_Suspect_RK = a.H_Suspect_RK 
                                            AND z.LoadDate > a.LoadDate 
                                ) 
        FROM    dbo.S_SuspectDetail a 
        WHERE   a.RecordEndDate IS NULL;  
 
		 
--**S_SuspectChartRecLog LOAD 
 
        INSERT  INTO [dbo].[S_SuspectChartRecLog] 
                ( [S_SuspectChartRecLog_RK] , 
                  [LoadDate] , 
                  [H_Suspect_RK] , 
                  [User_PK] , 
                  [Log_Date] , 
                  [Log_Info] , 
                  [HashDiff] , 
                  [RecordSource] 
                ) 
                SELECT  UPPER(CONVERT(CHAR(32), HASHBYTES('MD5', 
                                                          UPPER(CONCAT(RTRIM(LTRIM(COALESCE(b.CSI, 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[User_PK], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[Log_Date], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[Log_Info], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[LoadDate], 
                                                              '')))))), 2)) , 
                        rw.LoadDate , 
                        b.SuspectHashKey , 
                        rw.[User_PK] , 
                        rw.[Log_Date] , 
                        rw.[Log_Info] , 
                        UPPER(CONVERT(CHAR(32), HASHBYTES('MD5', 
                                                          UPPER(CONCAT(RTRIM(LTRIM(COALESCE(rw.[User_PK], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[Log_Date], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[Log_Info], 
                                                              '')))))), 2)) , 
                        rw.RecordSource 
                FROM    CHSStaging.adv.tblSuspectChartRecLogStage rw 
                        INNER JOIN CHSStaging.adv.tblSuspectWCStage b WITH ( NOLOCK ) ON rw.Suspect_PK = b.Suspect_PK 
                WHERE   UPPER(CONVERT(CHAR(32), HASHBYTES('MD5', 
                                                          UPPER(CONCAT(RTRIM(LTRIM(COALESCE(rw.[User_PK], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[Log_Date], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[Log_Info], 
                                                              '')))))), 2)) NOT IN ( 
                        SELECT  HashDiff 
                        FROM    S_SuspectChartRecLog 
                        WHERE   H_Suspect_RK = b.SuspectHashKey 
                                AND RecordEndDate IS NULL ) 
                        AND rw.CCI = @CCI 
                GROUP BY UPPER(CONVERT(CHAR(32), HASHBYTES('MD5', 
                                                           UPPER(CONCAT(RTRIM(LTRIM(COALESCE(b.CSI, 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[User_PK], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[Log_Date], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[Log_Info], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[LoadDate], 
                                                              '')))))), 2)) , 
                        rw.LoadDate , 
                        b.SuspectHashKey , 
                        rw.[User_PK] , 
                        rw.[Log_Date] , 
                        rw.[Log_Info] , 
                        UPPER(CONVERT(CHAR(32), HASHBYTES('MD5', 
                                                          UPPER(CONCAT(RTRIM(LTRIM(COALESCE(rw.[User_PK], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[Log_Date], 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(rw.[Log_Info], 
                                                              '')))))), 2)) , 
                        rw.RecordSource; 
 
	--RECORD END DATE CLEANUP 
        UPDATE  dbo.S_SuspectChartRecLog 
        SET     RecordEndDate = ( SELECT    DATEADD(ss, -1, MIN(z.LoadDate)) 
                                  FROM      dbo.S_SuspectChartRecLog z 
                                  WHERE     z.H_Suspect_RK = a.H_Suspect_RK 
                                            AND z.LoadDate > a.LoadDate 
                                ) 
        FROM    dbo.S_SuspectChartRecLog a 
        WHERE   a.RecordEndDate IS NULL;  
 
 
 
			 
--**S_SuspectDOS LOAD 
 
        INSERT  INTO [dbo].[S_SuspectDOS] 
                ( [S_SuspectDOS_RK] , 
                  [LoadDate] , 
                  [H_Suspect_RK] , 
                  [SuspectDOS_PK] , 
                  [DOS_From] , 
                  [DOS_To] , 
                  [HashDiff] , 
                  [RecordSource] 
                ) 
                SELECT  UPPER(CONVERT(CHAR(32), HASHBYTES('MD5', 
                                                          UPPER(CONCAT(RTRIM(LTRIM(COALESCE(b.CSI, 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(a.SuspectDOS_PK, 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(a.DOS_From, 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(a.DOS_To, 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(a.[LoadDate], 
                                                              '')))))), 2)) , 
                        a.LoadDate , 
                        b.SuspectHashKey , 
                        a.[SuspectDOS_PK] , 
                        a.[DOS_From] , 
                        a.[DOS_To] , 
                        UPPER(CONVERT(CHAR(32), HASHBYTES('MD5', 
                                                          UPPER(CONCAT(RTRIM(LTRIM(COALESCE(a.SuspectDOS_PK, 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(a.DOS_From, 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(a.DOS_To, 
                                                              '')))))), 2)) , 
                        a.RecordSource 
                FROM    CHSStaging.adv.tblSuspectDOSStage a 
                        INNER JOIN CHSStaging.adv.tblSuspectWCStage b WITH ( NOLOCK ) ON a.Suspect_PK = b.Suspect_PK 
                WHERE   UPPER(CONVERT(CHAR(32), HASHBYTES('MD5', 
                                                          UPPER(CONCAT(RTRIM(LTRIM(COALESCE(a.SuspectDOS_PK, 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(a.DOS_From, 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(a.DOS_To, 
                                                              '')))))), 2)) NOT IN ( 
                        SELECT  HashDiff 
                        FROM    S_SuspectDOS 
                        WHERE   H_Suspect_RK = b.SuspectHashKey 
                                AND RecordEndDate IS NULL ) 
                        AND a.CCI = @CCI 
                GROUP BY UPPER(CONVERT(CHAR(32), HASHBYTES('MD5', 
                                                           UPPER(CONCAT(RTRIM(LTRIM(COALESCE(b.CSI, 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(a.SuspectDOS_PK, 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(a.DOS_From, 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(a.DOS_To, 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(a.[LoadDate], 
                                                              '')))))), 2)) , 
                        a.LoadDate , 
                        b.SuspectHashKey , 
                        a.[SuspectDOS_PK] , 
                        a.[DOS_From] , 
                        a.[DOS_To] , 
                        UPPER(CONVERT(CHAR(32), HASHBYTES('MD5', 
                                                          UPPER(CONCAT(RTRIM(LTRIM(COALESCE(a.SuspectDOS_PK, 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(a.DOS_From, 
                                                              ''))), ':', 
                                                              RTRIM(LTRIM(COALESCE(a.DOS_To, 
                                                              '')))))), 2)) , 
                        a.RecordSource; 
 
	--RECORD END DATE CLEANUP 
        UPDATE  dbo.S_SuspectDOS 
        SET     RecordEndDate = ( SELECT    DATEADD(ss, -1, MIN(z.LoadDate)) 
                                  FROM      dbo.S_SuspectDOS z 
                                  WHERE     z.H_Suspect_RK = a.H_Suspect_RK 
                                            AND z.LoadDate > a.LoadDate 
                                ) 
        FROM    dbo.S_SuspectDOS a 
        WHERE   a.RecordEndDate IS NULL;  
 
 
 
 
 
    END; 
 
 
 
 
 
GO
