SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


-- =============================================
-- Author:		Travis Parker
-- Create date:	12/15/2016
-- Description:	Updates the reference keys in the Apixio staging table
-- =============================================
CREATE PROCEDURE [dbo].[spUpdateApixioReferenceKeys]
AS
    BEGIN
	
        SET NOCOUNT ON;


        UPDATE  a
        SET     a.ApixioReturn_BK = CONCAT(RTRIM(LTRIM(COALESCE(a.CHART_ID, ''))), ':', RTRIM(LTRIM(COALESCE(a.ICD9, ''))), ':', RTRIM(LTRIM(COALESCE(a.ICD10, ''))), ':', RTRIM(LTRIM(COALESCE(a.PAGE, '')))) ,
                a.H_ApixioReturn_RK = UPPER(CONVERT(CHAR(32), HASHBYTES('MD5', UPPER(CONCAT(RTRIM(LTRIM(COALESCE(a.CHART_ID, ''))), ':', RTRIM(LTRIM(COALESCE(a.ICD9, ''))), ':', RTRIM(LTRIM(COALESCE(a.ICD10, ''))), ':', RTRIM(LTRIM(COALESCE(a.PAGE, '')))))), 2)) ,
                a.H_Provider_RK = UPPER(CONVERT( CHAR(32), HASHBYTES('MD5', UPPER(RTRIM(LTRIM(COALESCE(a.CentauriProviderID, ''))))), 2)),
			 a.H_Member_RK = UPPER(CONVERT( CHAR(32), HASHBYTES('MD5', UPPER(RTRIM(LTRIM(COALESCE(a.CentauriMemberID, ''))))), 2)),
			 a.L_MemberApixioReturn_RK = UPPER(CONVERT( CHAR(32), HASHBYTES('MD5', UPPER(CONCAT(RTRIM(LTRIM(COALESCE(a.CentauriMemberID, ''))), ':', RTRIM(LTRIM(COALESCE(a.CHART_ID, ''))), ':', RTRIM(LTRIM(COALESCE(a.ICD9, ''))), ':', RTRIM(LTRIM(COALESCE(a.ICD10, ''))), ':', RTRIM(LTRIM(COALESCE(a.PAGE, '')))))), 2)),
			 a.L_ProviderApixioReturn_RK = UPPER(CONVERT( CHAR(32), HASHBYTES('MD5', UPPER(CONCAT(RTRIM(LTRIM(COALESCE(a.CentauriProviderID, ''))), ':', RTRIM(LTRIM(COALESCE(a.CHART_ID, ''))), ':', RTRIM(LTRIM(COALESCE(a.ICD9, ''))), ':', RTRIM(LTRIM(COALESCE(a.ICD10, ''))), ':', RTRIM(LTRIM(COALESCE(a.PAGE, '')))))), 2)),
			 a.L_SuspectApixioReturn_RK = UPPER(CONVERT( CHAR(32), HASHBYTES('MD5', UPPER(CONCAT(RTRIM(LTRIM(COALESCE(a.Suspect_PK, ''))), ':', RTRIM(LTRIM(COALESCE(a.CHART_ID, ''))), ':', RTRIM(LTRIM(COALESCE(a.ICD9, ''))), ':', RTRIM(LTRIM(COALESCE(a.ICD10, ''))), ':', RTRIM(LTRIM(COALESCE(a.PAGE, '')))))), 2)),
			 a.S_ApixioReturn_RK = UPPER(CONVERT( CHAR(32), HASHBYTES('MD5', UPPER(CONCAT(RTRIM(LTRIM(COALESCE(a.FileName, ''))), ':', RTRIM(LTRIM(COALESCE(a.LoadDate, ''))), ':', RTRIM(LTRIM(COALESCE(a.REFERENCE_NBR, ''))), ':', RTRIM(LTRIM(COALESCE(a.PROVIDER_NPI, ''))), ':', RTRIM(LTRIM(COALESCE(a.PROVIDER_LAST, ''))), ':', RTRIM(LTRIM(COALESCE(a.PROVIDER_FIRST, ''))), ':', RTRIM(LTRIM(COALESCE(a.DATE_OF_SERVICE, ''))), ':', RTRIM(LTRIM(COALESCE(a.PROVIDER_TYPE, ''))), ':', RTRIM(LTRIM(COALESCE(a.MEMBER_ID, ''))), ':', RTRIM(LTRIM(COALESCE(a.MEMBER_HICN, ''))), ':', RTRIM(LTRIM(COALESCE(a.MEMBER_LAST, ''))), ':', RTRIM(LTRIM(COALESCE(a.MEMBER_FIRST, ''))), ':', RTRIM(LTRIM(COALESCE(a.MEMBER_DOB, ''))), ':', RTRIM(LTRIM(COALESCE(a.MEMBER_GENDER, ''))), ':', RTRIM(LTRIM(COALESCE(a.HCC, ''))), ':', RTRIM(LTRIM(COALESCE(a.ICD9, ''))), ':', RTRIM(LTRIM(COALESCE(a.ICD10, ''))), ':', RTRIM(LTRIM(COALESCE(a.COMMENTS, ''))), ':', RTRIM(LTRIM(COALESCE(a.PATIENT_UUID, ''))), ':', RTRIM(LTRIM(COALESCE(a.DOCUMENT_UUID, ''))), ':', RTRIM(LTRIM(COALESCE(a.CHART_ID, ''))), ':', RTRIM(LTRIM(COALESCE(a.PAGE, ''))), ':', RTRIM(LTRIM(COALESCE(a.CODER_HISTORY, ''))), ':', RTRIM(LTRIM(COALESCE(a.CODER_ANNOTATION_HISTORY, ''))), ':', RTRIM(LTRIM(COALESCE(a.CODING_DATE, ''))), ':', RTRIM(LTRIM(COALESCE(a.DELIVERED, ''))), ':', RTRIM(LTRIM(COALESCE(a.PHASECOMPLETE, '')))))), 2)),
			 a.S_ApixioReturn_HashDiff = UPPER(CONVERT( CHAR(32), HASHBYTES('MD5', UPPER(CONCAT(RTRIM(LTRIM(COALESCE(a.REFERENCE_NBR, ''))), ':', RTRIM(LTRIM(COALESCE(a.PROVIDER_NPI, ''))), ':', RTRIM(LTRIM(COALESCE(a.PROVIDER_LAST, ''))), ':', RTRIM(LTRIM(COALESCE(a.PROVIDER_FIRST, ''))), ':', RTRIM(LTRIM(COALESCE(a.DATE_OF_SERVICE, ''))), ':', RTRIM(LTRIM(COALESCE(a.PROVIDER_TYPE, ''))), ':', RTRIM(LTRIM(COALESCE(a.MEMBER_ID, ''))), ':', RTRIM(LTRIM(COALESCE(a.MEMBER_HICN, ''))), ':', RTRIM(LTRIM(COALESCE(a.MEMBER_LAST, ''))), ':', RTRIM(LTRIM(COALESCE(a.MEMBER_FIRST, ''))), ':', RTRIM(LTRIM(COALESCE(a.MEMBER_DOB, ''))), ':', RTRIM(LTRIM(COALESCE(a.MEMBER_GENDER, ''))), ':', RTRIM(LTRIM(COALESCE(a.HCC, ''))), ':', RTRIM(LTRIM(COALESCE(a.ICD9, ''))), ':', RTRIM(LTRIM(COALESCE(a.ICD10, ''))), ':', RTRIM(LTRIM(COALESCE(a.COMMENTS, ''))), ':', RTRIM(LTRIM(COALESCE(a.PATIENT_UUID, ''))), ':', RTRIM(LTRIM(COALESCE(a.DOCUMENT_UUID, ''))), ':', RTRIM(LTRIM(COALESCE(a.CHART_ID, ''))), ':', RTRIM(LTRIM(COALESCE(a.PAGE, ''))), ':', RTRIM(LTRIM(COALESCE(a.CODER_HISTORY, ''))), ':', RTRIM(LTRIM(COALESCE(a.CODER_ANNOTATION_HISTORY, ''))), ':', RTRIM(LTRIM(COALESCE(a.CODING_DATE, ''))), ':', RTRIM(LTRIM(COALESCE(a.DELIVERED, ''))), ':', RTRIM(LTRIM(COALESCE(a.PHASECOMPLETE, '')))))), 2)),
			 a.S_ProviderMasterDemo_RK = UPPER(CONVERT( CHAR(32), HASHBYTES('MD5', UPPER(CONCAT(RTRIM(LTRIM(COALESCE(a.FileName, ''))), ':', RTRIM(LTRIM(COALESCE(a.LoadDate, ''))), ':', RTRIM(LTRIM(COALESCE(a.CentauriProviderID, ''))), ':', RTRIM(LTRIM(COALESCE(a.PROVIDER_NPI, ''))), ':', RTRIM(LTRIM(COALESCE(a.PROVIDER_LAST, ''))), ':', RTRIM(LTRIM(COALESCE(a.PROVIDER_FIRST, '')))))), 2)),
			 a.S_ProviderMasterDemo_HashDiff = UPPER(CONVERT( CHAR(32), HASHBYTES('MD5', UPPER(CONCAT(RTRIM(LTRIM(COALESCE(a.CentauriProviderID, ''))), ':', RTRIM(LTRIM(COALESCE(a.PROVIDER_NPI, ''))), ':', RTRIM(LTRIM(COALESCE(a.PROVIDER_LAST, ''))), ':', RTRIM(LTRIM(COALESCE(a.PROVIDER_FIRST, '')))))), 2)),
			 a.S_MemberDemo_RK = UPPER(CONVERT( CHAR(32), HASHBYTES('MD5', UPPER(CONCAT(RTRIM(LTRIM(COALESCE(a.FileName, ''))), ':', RTRIM(LTRIM(COALESCE(a.LoadDate, ''))), ':', RTRIM(LTRIM(COALESCE(a.CentauriMemberID, ''))), ':', RTRIM(LTRIM(COALESCE(a.MEMBER_ID, ''))), ':', RTRIM(LTRIM(COALESCE(a.MEMBER_LAST, ''))), ':', RTRIM(LTRIM(COALESCE(a.MEMBER_FIRST, ''))), ':', RTRIM(LTRIM(COALESCE(a.MEMBER_DOB, ''))), ':', RTRIM(LTRIM(COALESCE(a.MEMBER_GENDER, '')))))), 2)),
			 a.S_MemberDemo_HashDiff = UPPER(CONVERT( CHAR(32), HASHBYTES('MD5', UPPER(CONCAT(RTRIM(LTRIM(COALESCE(a.CentauriMemberID, ''))), ':', RTRIM(LTRIM(COALESCE(a.MEMBER_ID, ''))), ':', RTRIM(LTRIM(COALESCE(a.MEMBER_LAST, ''))), ':', RTRIM(LTRIM(COALESCE(a.MEMBER_FIRST, ''))), ':', RTRIM(LTRIM(COALESCE(a.MEMBER_DOB, ''))), ':', RTRIM(LTRIM(COALESCE(a.MEMBER_GENDER, '')))))), 2)),
			 a.S_MemberHICN_RK = UPPER(CONVERT( CHAR(32), HASHBYTES('MD5', UPPER(CONCAT(RTRIM(LTRIM(COALESCE(a.FileName, ''))), ':', RTRIM(LTRIM(COALESCE(a.LoadDate, ''))), ':', RTRIM(LTRIM(COALESCE(a.CentauriMemberID, ''))), ':', RTRIM(LTRIM(COALESCE(a.MEMBER_HICN, '')))))), 2)),
			 a.S_MemberHICN_HashDiff = UPPER(CONVERT( CHAR(32), HASHBYTES('MD5', UPPER(CONCAT(RTRIM(LTRIM(COALESCE(a.CentauriMemberID, ''))), ':', RTRIM(LTRIM(COALESCE(a.MEMBER_HICN, '')))))), 2)),
			 a.H_Suspect_RK = s.H_Suspect_RK
	   FROM CHSStaging.dbo.ApixioReturn  a --19135
	   INNER JOIN dbo.H_Suspect s ON a.Suspect_PK = s.ClientSuspectID
	   WHERE a.Suspect_PK IS NOT NULL;


    END;



GO
