CREATE TABLE [dbo].[WellCareCIOXChaseList_10252016]
(
[ContractNumber] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MemberId] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MemberHIC] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MemberFirstName] [varchar] (75) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MemberLastName] [varchar] (75) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MemberGender] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MemberDOB] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Source] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BusinessUnit] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LOB] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FacilityType] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProviderID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProviderSpecialty] [varchar] (75) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProviderFirstName] [varchar] (75) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProviderLastName] [varchar] (75) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProviderAddress1] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProviderAddress2] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProviderCity] [varchar] (75) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProviderState] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProviderZip] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProviderPhone] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProviderFax] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProviderContact] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProviderGroupName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProjectID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProjectName] [varchar] (75) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CentralizedHandling] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CentralizedHandlingCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CentralizedHandlingContactName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CentralizedHandlingContactPhone] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SpecialHandlingInstructions] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ClientChartID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[User Defined Text1] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[User Defined Text2] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[User Defined Text3] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[User Defined Text4] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[User Defined Category 1`] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[User Defined Category 2] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[User Defined Date1] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[User Defined Date2] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[User Defined Number 1] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[User Defined Number 2] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BegDOS] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EndDOS] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GroupTIN] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NewAddress] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NewZip] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AdvanceAddress] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AdvanceZIP] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AddressUsed] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ZIPUsed] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CentauriProviderID] [bigint] NULL,
[H_Provider_RK] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProviderMaster_PK] [int] NULL,
[ProviderOffice_PK] [int] NULL,
[Member_PK] [int] NULL,
[Provider_PK] [int] NULL,
[ExistingProvider] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
