CREATE TABLE [dbo].[ExecutiveDashboard_ExtractSummary]
(
[RecID] [int] NOT NULL IDENTITY(1, 1),
[ClientID] [int] NOT NULL,
[ProjectID] [int] NOT NULL,
[ProjectName] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Week1ExtractActualCnt] [int] NULL CONSTRAINT [DF__Executive__Week1__6129AC58] DEFAULT ((0)),
[Week1ExtractGoalCnt] [int] NULL CONSTRAINT [DF__Executive__Week1__621DD091] DEFAULT ((0)),
[Week2ExtractActualCnt] [int] NULL CONSTRAINT [DF__Executive__Week2__6311F4CA] DEFAULT ((0)),
[Week2ExtractGoalCnt] [int] NULL CONSTRAINT [DF__Executive__Week2__64061903] DEFAULT ((0)),
[Week3ExtractActualCnt] [int] NULL CONSTRAINT [DF__Executive__Week3__64FA3D3C] DEFAULT ((0)),
[Week3ExtractGoalCnt] [int] NULL CONSTRAINT [DF__Executive__Week3__65EE6175] DEFAULT ((0)),
[Week4ExtractActualCnt] [int] NULL CONSTRAINT [DF__Executive__Week4__66E285AE] DEFAULT ((0)),
[Week4ExtractGoalCnt] [int] NULL CONSTRAINT [DF__Executive__Week4__67D6A9E7] DEFAULT ((0)),
[Week5ExtractActualCnt] [int] NULL CONSTRAINT [DF__Executive__Week5__68CACE20] DEFAULT ((0)),
[Week5ExtractGoalCnt] [int] NULL CONSTRAINT [DF__Executive__Week5__69BEF259] DEFAULT ((0)),
[Week6ExtractActualCnt] [int] NULL CONSTRAINT [DF__Executive__Week6__6AB31692] DEFAULT ((0)),
[Week6ExtractGoalCnt] [int] NULL CONSTRAINT [DF__Executive__Week6__6BA73ACB] DEFAULT ((0)),
[Week7ExtractActualCnt] [int] NULL CONSTRAINT [DF__Executive__Week7__6C9B5F04] DEFAULT ((0)),
[Week7ExtractGoalCnt] [int] NULL CONSTRAINT [DF__Executive__Week7__6D8F833D] DEFAULT ((0)),
[Week8ExtractActualCnt] [int] NULL CONSTRAINT [DF__Executive__Week8__6E83A776] DEFAULT ((0)),
[Week8ExtractGoalCnt] [int] NULL CONSTRAINT [DF__Executive__Week8__6F77CBAF] DEFAULT ((0)),
[Week9ExtractActualCnt] [int] NULL CONSTRAINT [DF__Executive__Week9__706BEFE8] DEFAULT ((0)),
[Week9ExtractGoalCnt] [int] NULL CONSTRAINT [DF__Executive__Week9__71601421] DEFAULT ((0)),
[Week10ExtractActualCnt] [int] NULL CONSTRAINT [DF__Executive__Week1__7254385A] DEFAULT ((0)),
[Week10ExtractGoalCnt] [int] NULL CONSTRAINT [DF__Executive__Week1__73485C93] DEFAULT ((0)),
[Week11ExtractActualCnt] [int] NULL CONSTRAINT [DF__Executive__Week1__743C80CC] DEFAULT ((0)),
[Week11ExtractGoalCnt] [int] NULL CONSTRAINT [DF__Executive__Week1__7530A505] DEFAULT ((0)),
[Week12ExtractActualCnt] [int] NULL CONSTRAINT [DF__Executive__Week1__7624C93E] DEFAULT ((0)),
[Week12ExtractGoalCnt] [int] NULL CONSTRAINT [DF__Executive__Week1__7718ED77] DEFAULT ((0)),
[Week13ExtractActualCnt] [int] NULL CONSTRAINT [DF__Executive__Week1__780D11B0] DEFAULT ((0)),
[Week13ExtractGoalCnt] [int] NULL CONSTRAINT [DF__Executive__Week1__790135E9] DEFAULT ((0)),
[Week14ExtractActualCnt] [int] NULL CONSTRAINT [DF__Executive__Week1__79F55A22] DEFAULT ((0)),
[Week14ExtractGoalCnt] [int] NULL CONSTRAINT [DF__Executive__Week1__7AE97E5B] DEFAULT ((0)),
[Week15ExtractActualCnt] [int] NULL CONSTRAINT [DF__Executive__Week1__7BDDA294] DEFAULT ((0)),
[Week15ExtractGoalCnt] [int] NULL CONSTRAINT [DF__Executive__Week1__7CD1C6CD] DEFAULT ((0)),
[Week16ExtractActualCnt] [int] NULL CONSTRAINT [DF__Executive__Week1__7DC5EB06] DEFAULT ((0)),
[Week16ExtractGoalCnt] [int] NULL CONSTRAINT [DF__Executive__Week1__7EBA0F3F] DEFAULT ((0)),
[Week17ExtractActualCnt] [int] NULL CONSTRAINT [DF__Executive__Week1__7FAE3378] DEFAULT ((0)),
[Week17ExtractGoalCnt] [int] NULL CONSTRAINT [DF__Executive__Week1__00A257B1] DEFAULT ((0)),
[Week18ExtractActualCnt] [int] NULL CONSTRAINT [DF__Executive__Week1__01967BEA] DEFAULT ((0)),
[Week18ExtractGoalCnt] [int] NULL CONSTRAINT [DF__Executive__Week1__028AA023] DEFAULT ((0)),
[Week19ExtractActualCnt] [int] NULL CONSTRAINT [DF__Executive__Week1__037EC45C] DEFAULT ((0)),
[Week19ExtractGoalCnt] [int] NULL CONSTRAINT [DF__Executive__Week1__0472E895] DEFAULT ((0)),
[Week20ExtractActualCnt] [int] NULL CONSTRAINT [DF__Executive__Week2__05670CCE] DEFAULT ((0)),
[Week20ExtractGoalCnt] [int] NULL CONSTRAINT [DF__Executive__Week2__065B3107] DEFAULT ((0)),
[Week21ExtractActualCnt] [int] NULL CONSTRAINT [DF__Executive__Week2__074F5540] DEFAULT ((0)),
[Week21ExtractGoalCnt] [int] NULL CONSTRAINT [DF__Executive__Week2__08437979] DEFAULT ((0))
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ExecutiveDashboard_ExtractSummary] ADD CONSTRAINT [UQ__Executiv__360414FEC2F5B599] UNIQUE NONCLUSTERED  ([RecID]) ON [PRIMARY]
GO
