CREATE TABLE [dbo].[Member]
(
[MemberID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Member] ADD CONSTRAINT [PK_Member] PRIMARY KEY CLUSTERED  ([MemberID]) WITH (FILLFACTOR=80) ON [PRIMARY]
GO
