CREATE TABLE [dbo].[etl_mapping_document]
(
[EtlMappingDocumentID] [int] NOT NULL IDENTITY(1, 1),
[SrcDatabase] [sys].[sysname] NOT NULL,
[SrcSchema] [sys].[sysname] NOT NULL,
[SrcTable] [sys].[sysname] NOT NULL,
[SrcColumn] [sys].[sysname] NOT NULL,
[SrcColumnOrder] [smallint] NULL,
[SrcSQL] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SrcColumn_max_length] [smallint] NULL,
[SrcColumn_max_data] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SrcColumn_min_data] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TargTable] [sys].[sysname] NULL,
[TargColumn] [sys].[sysname] NULL,
[TargDatatype] [sys].[sysname] NULL,
[TargColumnMaxLength] [smallint] NULL,
[TargColumnComment] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Man1ProfileID] [int] NULL,
[Man1MaxErrPerc] [numeric] (6, 2) NULL,
[Man1IsFatal] [bit] NULL,
[Man2ProfileID] [int] NULL,
[Man2MaxErrPerc] [numeric] (6, 2) NULL,
[Man2IsFatal] [bit] NULL,
[Man3ProfileID] [int] NULL,
[Man3MaxErrPerc] [numeric] (6, 2) NULL,
[Man3IsFatal] [bit] NULL,
[Man4ProfileID] [int] NULL,
[Man4MaxErrPerc] [numeric] (6, 2) NULL,
[Man4IsFatal] [bit] NULL,
[Man5ProfileID] [int] NULL,
[Man5MaxErrPerc] [numeric] (6, 2) NULL,
[Man5IsFatal] [bit] NULL,
[Man6ProfileID] [int] NULL,
[Man6MaxErrPerc] [numeric] (6, 2) NULL,
[Man6IsFatal] [bit] NULL,
[Man7ProfileID] [int] NULL,
[Man7MaxErrPerc] [numeric] (6, 2) NULL,
[Man7IsFatal] [bit] NULL,
[Man8ProfileID] [int] NULL,
[Man8MaxErrPerc] [numeric] (6, 2) NULL,
[Man8IsFatal] [bit] NULL,
[Man9ProfileID] [int] NULL,
[Man9MaxErrPerc] [numeric] (6, 2) NULL,
[Man9IsFatal] [bit] NULL,
[Man10ProfileID] [int] NULL,
[Man10MaxErrPerc] [numeric] (6, 2) NULL,
[Man10IsFatal] [bit] NULL
) ON [PRIMARY]
GO
