CREATE TABLE [dbo].[Member]
(
[MemberID] [int] NOT NULL IDENTITY(1, 1),
[Address1] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address2] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[City] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Client] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerMemberID] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DataSource] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateOfBirth] [datetime] NULL,
[Gender] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ihds_member_id] [int] NOT NULL,
[NameFirst] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NameLast] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NameMiddleInitial] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Phone] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[State] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ZipCode] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RowID] [int] NULL,
[Ethnicity] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InterpreterFlag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MemberLanguage] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Race] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EthnicitySource] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OtherLanguage] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OtherLanguageSource] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RaceSource] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SpokenLanguage] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SpokenLanguageSource] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WrittenLanguage] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WrittenLanguageSource] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[County] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MedicareID] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HedisMeasureID] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateRowCreated] [datetime] NULL,
[DateValidBegin] [datetime] NULL,
[DateValidEnd] [datetime] NULL,
[HashValue] [binary] (16) NULL,
[IsEmployee] [bit] NULL,
[IsRetired] [bit] NULL,
[IsSubscriber] [bit] NULL,
[NameSuffix] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IsUpdated] [bit] NULL,
[MedicareNumber] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MedicaidNumber] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MedicaidID] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MedicalRecordNumber] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AssignedClinic] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SourceSystem] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EmployeeNo] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSN] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [dbo_member]
GO
