CREATE TABLE [dbo].[Provider]
(
[ProviderID] [int] NOT NULL IDENTITY(100, 1),
[Client] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DataSource] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateRowCreated] [datetime] NULL,
[ihds_prov_id] [int] NULL,
[NameFirst] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NameLast] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NameMiddleInitial] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NameSuffix] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NPI] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProviderType] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RowID] [int] NULL,
[ProviderPrescribingPrivFlag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CDProviderFlag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DentistFlag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EyeCareFlag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MentalHealthFlag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NephrologistFlag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NursePractFlag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OBGynFlag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PCPFlag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PhysicianAsstFlag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProviderPaidInpatientRateFlag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProviderPaidOutpatientRateFlag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerProviderID] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ClinicalPharmacistFlag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AnesthesiologistFlag] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProviderFullName] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AmbulanceFlag] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DMEFlag] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HospitalFlag] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SNFFlag] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address2] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[City] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[State] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Zip] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Phone] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fax] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DurableMedEquipmentFlag] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RegisteredNurseFlag] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SkilledNursingFacFlag] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SurgeonFlag] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CardiologistFlag] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GastroenterologistFlag] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EndocrinologistFlag] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProviderCounty] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProviderEmail] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HedisMeasureID] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Contracted] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TaxID] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [dbo_Provider]
GO
