CREATE TABLE [dbo].[ClaimNEW]
(
[ClaimID] [int] NOT NULL IDENTITY(1, 1),
[LoadInstanceFileID] [int] NULL,
[RowFileID] [bigint] NULL,
[BillingProviderID] [int] NULL,
[BillType] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ClaimType] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ClaimTypeIndicator] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Client] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DataSource] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateAdmitted] [datetime] NULL,
[DateClaimPaid] [datetime] NULL,
[DateDischarged] [datetime] NULL,
[DateRowCreated] [datetime] NULL,
[DateServiceBegin] [datetime] NULL,
[DateServiceEnd] [datetime] NULL,
[DateValidBegin] [datetime] NULL,
[DateValidEnd] [datetime] NULL,
[DiagnosisCode1] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DiagnosisCode2] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DiagnosisCode3] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DiagnosisCode4] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DiagnosisCode5] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DiagnosisCode6] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DiagnosisCode7] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DiagnosisCode8] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DiagnosisCode9] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DiagnosisCode10] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DiagnosisCode11] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DiagnosisCode12] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DiagnosisCode13] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DiagnosisCode14] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DiagnosisCode15] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DiagnosisCode16] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DiagnosisCode17] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DiagnosisCode18] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DiagnosisCode19] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DiagnosisCode20] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DischargeStatus] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DiagnosisRelatedGroup] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HashValue] [binary] (16) NULL,
[HealthPlanID] [int] NULL,
[HedisMeasureID] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ihds_member_id] [int] NULL,
[ihds_prov_id_attending] [int] NULL,
[ihds_prov_id_billing] [int] NULL,
[ihds_prov_id_med_group] [int] NULL,
[ihds_prov_id_pcp] [int] NULL,
[ihds_prov_id_referring] [int] NULL,
[ihds_prov_id_servicing] [int] NULL,
[ihds_prov_id_vendor] [int] NULL,
[IsUpdated] [bit] NULL,
[MedicarePaidIndicator] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MemberID] [int] NULL,
[PatientStatus] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PayerClaimID] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PayerClaimIDSuffix] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PayerID] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PlaceOfService] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RecordType] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReferringProviderID] [int] NULL,
[RowID] [int] NULL,
[ServicingProviderID] [int] NULL,
[SurgicalProcedure1] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SurgicalProcedure2] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SurgicalProcedure3] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SurgicalProcedure4] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SurgicalProcedure5] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SurgicalProcedure6] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ClaimDisallowReason] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ClaimStatus] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DiagnosisRelatedGroupType] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MemberAge] [numeric] (6, 1) NULL,
[CustomerMemberID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EmployerGroup] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EmployerDivision] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BusinessUnit] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerServicingProvID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MemberGroupId] [int] NULL,
[BenefitPlanId] [int] NULL,
[LineOfBusinessID] [int] NULL,
[ihds_prov_id_admitting] [int] NULL,
[ServicingProvID] [int] NULL,
[ServicingProvSpecialty] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ServicingProvSpecialtyDesc] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ServicingProvType] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ServicingProvTypeDesc] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ServicingProvIPA] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ServicingProvParFlag] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ServicingProvMedicalGroupID] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AdmittingProvID] [int] NULL,
[AdmittingProvSpecialty] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AdmittingProvSpecialtyDesc] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AdmittingProvType] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AdmittingProvTypeDesc] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AdmittingProvIPA] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AdmittingProvParFlag] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AdmittingProvMedicalGroupID] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AttendingProvID] [int] NULL,
[AttendingProvSpecialty] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AttendingProvSpecialtyDesc] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AttendingProvType] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AttendingProvTypeDesc] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AttendingProvIPA] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AttendingProvParFlag] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AttendingProvMedicalGroupID] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PCPID] [int] NULL,
[PCPSpecialty] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PCPSpecialtyDesc] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PCPType] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PCPTypeDesc] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PCPIPA] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PCPMedicalGroupID] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AdmitType] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LineOfBusiness] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PlanCode] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PayerVendorID] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VendorID] [int] NULL,
[AdmitSource] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ClaimSubmissionMethod] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ClaimCreateDate] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ClaimUpdateDate] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ClaimCreateUser] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ClaimUpdateUser] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReferringProvID] [int] NULL,
[ReferringProvSpecialty] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReferringProvSpecialtyDesc] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReferringProvType] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReferringProvTypeDesc] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReferringProvIPA] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReferringProvParFlag] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReferringProvMedicalGroupID] [int] NULL,
[SupplementalDataCategory] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SupplementalDataFlag] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerClaimID] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerVendorID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AdmittingDiagnosisCode] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateClaimReceived] [datetime] NULL,
[ReportedClaimNumber] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerPOA1] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerPOA2] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerPOA3] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerPOA4] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerPOA5] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerPOA6] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerPOA7] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerPOA8] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerEligibilityID] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ServicingProvNPI] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerPOA9] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ServicingProvTaxonomyCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MemberGender] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PatientControlNo] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerBenefitPlanDesc] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerSponsor] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReimburseMemberFlag] [bit] NULL,
[SourceSystem] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerEnrollID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerPlanID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerEligibleOrigID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerCarrerid] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerInsuredID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PlanDescription] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PlanType] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EligibleOrganizationName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EligibleOrganizationType] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CarrierName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CarrierType] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerAuthNumber] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerSecondaryAuthNumber] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ExternalCauseInjuryDiag1] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ExternalCauseInjuryDiag2] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ExternalCauseInjuryDiag3] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ExternalCauseInjuryDiag4] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ExternalCauseInjuryDiag5] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ExternalCauseInjuryDiag6] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ExternalCauseInjuryDiag7] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ExternalCauseInjuryDiag8] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ExternalCauseInjuryDiag9] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ExternalCauseInjuryDiag10] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ExternalCauseInjuryDiag11] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ExternalCauseInjuryDiag12] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SurgicalProcedure1Date] [datetime] NULL,
[SurgicalProcedure2Date] [datetime] NULL,
[SurgicalProcedure3Date] [datetime] NULL,
[SurgicalProcedure4Date] [datetime] NULL,
[SurgicalProcedure5Date] [datetime] NULL,
[SurgicalProcedure6Date] [datetime] NULL,
[AdmitHour] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerPOA10] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerPOA11] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerPOA12] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerVendorName] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DischargeHour] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EligibilityID] [int] NULL,
[ExternalCauseInjuryDiag13] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TotalAmountBilledClaim] [numeric] (11, 2) NULL,
[SupplementalDataCode] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ICDCodeType] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
