CREATE TABLE [imiETL].[BuildHistory]
(
[BuildHistoryID] [int] NOT NULL IDENTITY(1, 1),
[LoadInstanceID] [int] NULL,
[UpdateRDSMflag] [bit] NULL,
[UpdateProfiles] [bit] NULL,
[RunMPI] [bit] NULL,
[UpdateStaging] [bit] NULL,
[UpdateMara] [bit] NULL,
[MaraStartDate] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MaraEndDate] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UpdateHedis] [bit] NULL,
[HedisStartDate] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HedisEndDate] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HedisCurYearMonth] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UpdateHedisV2] [bit] NULL,
[HedisV2BatchSize] [int] NULL,
[UpdateDW01] [bit] NULL,
[DWStartDate] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DWEndDate] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RunDate] [datetime] NULL,
[CompleteBuild] [bit] NULL,
[ValidBuild] [bit] NULL,
[TestFlag] [bit] NULL,
[TestNameChar] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RDSMUpdateStart] [datetime] NULL,
[RDSMUpdateEnd] [datetime] NULL,
[ProfileStart] [datetime] NULL,
[ProfileEnd] [datetime] NULL,
[MPIStart] [datetime] NULL,
[MPIEnd] [datetime] NULL,
[StagingUpdateStart] [datetime] NULL,
[StagingUpdateEnd] [datetime] NULL,
[MaraUpdateStart] [datetime] NULL,
[MaraUpdateEnd] [datetime] NULL,
[HedisUpdateStart] [datetime] NULL,
[HedisUpdateEnd] [datetime] NULL,
[HedisV2UpdateStart] [datetime] NULL,
[HedisV2UpdateEnd] [datetime] NULL,
[DW01UpdateStart] [datetime] NULL,
[DW01UpdateEnd] [datetime] NULL,
[BuildEnd] [datetime] NULL
) ON [PRIMARY]
GO
