SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- =============================================
-- Author:		Jason Franks
-- Create date: 6/17/2015
-- Description: Merges the Weekly NPI file with the NPI Master Table
-- =============================================
CREATE PROCEDURE [dbo].[prMergeNPIWeekly]
	
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

    -- Insert statements for procedure here
	-- NPI_MASTER -------------------------------------------------------------

MERGE CHSDW.REF.[NPI_MASTER] AS t
USING (SELECT * FROM [CHSStaging].[dbo].[NPI_MASTER_WklyStage] WITH(NOLOCK)) as s
ON ( t.[NPI] = s.[NPI] )
WHEN MATCHED THEN UPDATE SET
[NPI] = s.[NPI],
[Entity Type Code] = s.[Entity Type Code],
[Replacement NPI] = s.[Replacement NPI],
[Employer Identification Number (EIN)] = s.[Employer Identification Number (EIN)],
[Provider Organization Name (Legal Business Name)] = s.[Provider Organization Name (Legal Business Name)],
[Provider Last Name (Legal Name)] = s.[Provider Last Name (Legal Name)],
[Provider First Name] = s.[Provider First Name],
[Provider Middle Name] = s.[Provider Middle Name],
[Provider Name Prefix Text] = s.[Provider Name Prefix Text],
[Provider Name Suffix Text] = s.[Provider Name Suffix Text],
[Provider Credential Text] = s.[Provider Credential Text],
[Provider Other Organization Name] = s.[Provider Other Organization Name],
[Provider Other Organization Name Type Code] = s.[Provider Other Organization Name Type Code],
[Provider Other Last Name] = s.[Provider Other Last Name],
[Provider Other First Name] = s.[Provider Other First Name],
[Provider Other Middle Name] = s.[Provider Other Middle Name],
[Provider Other Name Prefix Text] = s.[Provider Other Name Prefix Text],
[Provider Other Name Suffix Text] = s.[Provider Other Name Suffix Text],
[Provider Other Credential Text] = s.[Provider Other Credential Text],
[Provider Other Last Name Type Code] = s.[Provider Other Last Name Type Code],
[Provider First Line Business Mailing Address] = s.[Provider First Line Business Mailing Address],
[Provider Second Line Business Mailing Address] = s.[Provider Second Line Business Mailing Address],
[Provider Business Mailing Address City Name] = s.[Provider Business Mailing Address City Name],
[Provider Business Mailing Address State Name] = s.[Provider Business Mailing Address State Name],
[Provider Business Mailing Address Postal Code] = s.[Provider Business Mailing Address Postal Code],
[Provider Business Mailing Address Country Code (If outside U S )] = s.[Provider Business Mailing Address Country Code (If outside U S )],
[Provider Business Mailing Address Telephone Number] = s.[Provider Business Mailing Address Telephone Number],
[Provider Business Mailing Address Fax Number] = s.[Provider Business Mailing Address Fax Number],
[Provider First Line Business Practice Location Address] = s.[Provider First Line Business Practice Location Address],
[Provider Second Line Business Practice Location Address] = s.[Provider Second Line Business Practice Location Address],
[Provider Business Practice Location Address City Name] = s.[Provider Business Practice Location Address City Name],
[Provider Business Practice Location Address State Name] = s.[Provider Business Practice Location Address State Name],
[Provider Business Practice Location Address Postal Code] = s.[Provider Business Practice Location Address Postal Code],
[Provider Business Practice Location Address Country Code (If outside U S )] = s.[Provider Business Practice Location Address Country Code (If outside U S )],
[Provider Business Practice Location Address Telephone Number] = s.[Provider Business Practice Location Address Telephone Number],
[Provider Business Practice Location Address Fax Number] = s.[Provider Business Practice Location Address Fax Number],
[Provider Enumeration Date] = s.[Provider Enumeration Date],
[Last Update Date] = s.[Last Update Date],
[NPI Deactivation Reason Code] = s.[NPI Deactivation Reason Code],
[NPI Deactivation Date] = s.[NPI Deactivation Date],
[NPI Reactivation Date] = s.[NPI Reactivation Date],
[Provider Gender Code] = s.[Provider Gender Code],
[Authorized Official Last Name] = s.[Authorized Official Last Name],
[Authorized Official First Name] = s.[Authorized Official First Name],
[Authorized Official Middle Name] = s.[Authorized Official Middle Name],
[Authorized Official Title or Position] = s.[Authorized Official Title or Position],
[Authorized Official Telephone Number] = s.[Authorized Official Telephone Number],
[Healthcare Provider Taxonomy Code_1] = s.[Healthcare Provider Taxonomy Code_1],
[Provider License Number_1] = s.[Provider License Number_1],
[Provider License Number State Code_1] = s.[Provider License Number State Code_1],
[Healthcare Provider Primary Taxonomy Switch_1] = s.[Healthcare Provider Primary Taxonomy Switch_1],
[Healthcare Provider Taxonomy Code_2] = s.[Healthcare Provider Taxonomy Code_2],
[Provider License Number_2] = s.[Provider License Number_2],
[Provider License Number State Code_2] = s.[Provider License Number State Code_2],
[Healthcare Provider Primary Taxonomy Switch_2] = s.[Healthcare Provider Primary Taxonomy Switch_2],
[Healthcare Provider Taxonomy Code_3] = s.[Healthcare Provider Taxonomy Code_3],
[Provider License Number_3] = s.[Provider License Number_3],
[Provider License Number State Code_3] = s.[Provider License Number State Code_3],
[Healthcare Provider Primary Taxonomy Switch_3] = s.[Healthcare Provider Primary Taxonomy Switch_3],
[Healthcare Provider Taxonomy Code_4] = s.[Healthcare Provider Taxonomy Code_4],
[Provider License Number_4] = s.[Provider License Number_4],
[Provider License Number State Code_4] = s.[Provider License Number State Code_4],
[Healthcare Provider Primary Taxonomy Switch_4] = s.[Healthcare Provider Primary Taxonomy Switch_4],
[Healthcare Provider Taxonomy Code_5] = s.[Healthcare Provider Taxonomy Code_5],
[Provider License Number_5] = s.[Provider License Number_5],
[Provider License Number State Code_5] = s.[Provider License Number State Code_5],
[Healthcare Provider Primary Taxonomy Switch_5] = s.[Healthcare Provider Primary Taxonomy Switch_5],
[Healthcare Provider Taxonomy Code_6] = s.[Healthcare Provider Taxonomy Code_6],
[Provider License Number_6] = s.[Provider License Number_6],
[Provider License Number State Code_6] = s.[Provider License Number State Code_6],
[Healthcare Provider Primary Taxonomy Switch_6] = s.[Healthcare Provider Primary Taxonomy Switch_6],
[Healthcare Provider Taxonomy Code_7] = s.[Healthcare Provider Taxonomy Code_7],
[Provider License Number_7] = s.[Provider License Number_7],
[Provider License Number State Code_7] = s.[Provider License Number State Code_7],
[Healthcare Provider Primary Taxonomy Switch_7] = s.[Healthcare Provider Primary Taxonomy Switch_7],
[Healthcare Provider Taxonomy Code_8] = s.[Healthcare Provider Taxonomy Code_8],
[Provider License Number_8] = s.[Provider License Number_8],
[Provider License Number State Code_8] = s.[Provider License Number State Code_8],
[Healthcare Provider Primary Taxonomy Switch_8] = s.[Healthcare Provider Primary Taxonomy Switch_8],
[Healthcare Provider Taxonomy Code_9] = s.[Healthcare Provider Taxonomy Code_9],
[Provider License Number_9] = s.[Provider License Number_9],
[Provider License Number State Code_9] = s.[Provider License Number State Code_9],
[Healthcare Provider Primary Taxonomy Switch_9] = s.[Healthcare Provider Primary Taxonomy Switch_9],
[Healthcare Provider Taxonomy Code_10] = s.[Healthcare Provider Taxonomy Code_10],
[Provider License Number_10] = s.[Provider License Number_10],
[Provider License Number State Code_10] = s.[Provider License Number State Code_10],
[Healthcare Provider Primary Taxonomy Switch_10] = s.[Healthcare Provider Primary Taxonomy Switch_10],
[Healthcare Provider Taxonomy Code_11] = s.[Healthcare Provider Taxonomy Code_11],
[Provider License Number_11] = s.[Provider License Number_11],
[Provider License Number State Code_11] = s.[Provider License Number State Code_11],
[Healthcare Provider Primary Taxonomy Switch_11] = s.[Healthcare Provider Primary Taxonomy Switch_11],
[Healthcare Provider Taxonomy Code_12] = s.[Healthcare Provider Taxonomy Code_12],
[Provider License Number_12] = s.[Provider License Number_12],
[Provider License Number State Code_12] = s.[Provider License Number State Code_12],
[Healthcare Provider Primary Taxonomy Switch_12] = s.[Healthcare Provider Primary Taxonomy Switch_12],
[Healthcare Provider Taxonomy Code_13] = s.[Healthcare Provider Taxonomy Code_13],
[Provider License Number_13] = s.[Provider License Number_13],
[Provider License Number State Code_13] = s.[Provider License Number State Code_13],
[Healthcare Provider Primary Taxonomy Switch_13] = s.[Healthcare Provider Primary Taxonomy Switch_13],
[Healthcare Provider Taxonomy Code_14] = s.[Healthcare Provider Taxonomy Code_14],
[Provider License Number_14] = s.[Provider License Number_14],
[Provider License Number State Code_14] = s.[Provider License Number State Code_14],
[Healthcare Provider Primary Taxonomy Switch_14] = s.[Healthcare Provider Primary Taxonomy Switch_14],
[Healthcare Provider Taxonomy Code_15] = s.[Healthcare Provider Taxonomy Code_15],
[Provider License Number_15] = s.[Provider License Number_15],
[Provider License Number State Code_15] = s.[Provider License Number State Code_15],
[Healthcare Provider Primary Taxonomy Switch_15] = s.[Healthcare Provider Primary Taxonomy Switch_15],
[Other Provider Identifier_1] = s.[Other Provider Identifier_1],
[Other Provider Identifier Type Code_1] = s.[Other Provider Identifier Type Code_1],
[Other Provider Identifier State_1] = s.[Other Provider Identifier State_1],
[Other Provider Identifier Issuer_1] = s.[Other Provider Identifier Issuer_1],
[Other Provider Identifier_2] = s.[Other Provider Identifier_2],
[Other Provider Identifier Type Code_2] = s.[Other Provider Identifier Type Code_2],
[Other Provider Identifier State_2] = s.[Other Provider Identifier State_2],
[Other Provider Identifier Issuer_2] = s.[Other Provider Identifier Issuer_2],
[Other Provider Identifier_3] = s.[Other Provider Identifier_3],
[Other Provider Identifier Type Code_3] = s.[Other Provider Identifier Type Code_3],
[Other Provider Identifier State_3] = s.[Other Provider Identifier State_3],
[Other Provider Identifier Issuer_3] = s.[Other Provider Identifier Issuer_3],
[Other Provider Identifier_4] = s.[Other Provider Identifier_4],
[Other Provider Identifier Type Code_4] = s.[Other Provider Identifier Type Code_4],
[Other Provider Identifier State_4] = s.[Other Provider Identifier State_4],
[Other Provider Identifier Issuer_4] = s.[Other Provider Identifier Issuer_4],
[Other Provider Identifier_5] = s.[Other Provider Identifier_5],
[Other Provider Identifier Type Code_5] = s.[Other Provider Identifier Type Code_5],
[Other Provider Identifier State_5] = s.[Other Provider Identifier State_5],
[Other Provider Identifier Issuer_5] = s.[Other Provider Identifier Issuer_5],
[Other Provider Identifier_6] = s.[Other Provider Identifier_6],
[Other Provider Identifier Type Code_6] = s.[Other Provider Identifier Type Code_6],
[Other Provider Identifier State_6] = s.[Other Provider Identifier State_6],
[Other Provider Identifier Issuer_6] = s.[Other Provider Identifier Issuer_6],
[Other Provider Identifier_7] = s.[Other Provider Identifier_7],
[Other Provider Identifier Type Code_7] = s.[Other Provider Identifier Type Code_7],
[Other Provider Identifier State_7] = s.[Other Provider Identifier State_7],
[Other Provider Identifier Issuer_7] = s.[Other Provider Identifier Issuer_7],
[Other Provider Identifier_8] = s.[Other Provider Identifier_8],
[Other Provider Identifier Type Code_8] = s.[Other Provider Identifier Type Code_8],
[Other Provider Identifier State_8] = s.[Other Provider Identifier State_8],
[Other Provider Identifier Issuer_8] = s.[Other Provider Identifier Issuer_8],
[Other Provider Identifier_9] = s.[Other Provider Identifier_9],
[Other Provider Identifier Type Code_9] = s.[Other Provider Identifier Type Code_9],
[Other Provider Identifier State_9] = s.[Other Provider Identifier State_9],
[Other Provider Identifier Issuer_9] = s.[Other Provider Identifier Issuer_9],
[Other Provider Identifier_10] = s.[Other Provider Identifier_10],
[Other Provider Identifier Type Code_10] = s.[Other Provider Identifier Type Code_10],
[Other Provider Identifier State_10] = s.[Other Provider Identifier State_10],
[Other Provider Identifier Issuer_10] = s.[Other Provider Identifier Issuer_10],
[Other Provider Identifier_11] = s.[Other Provider Identifier_11],
[Other Provider Identifier Type Code_11] = s.[Other Provider Identifier Type Code_11],
[Other Provider Identifier State_11] = s.[Other Provider Identifier State_11],
[Other Provider Identifier Issuer_11] = s.[Other Provider Identifier Issuer_11],
[Other Provider Identifier_12] = s.[Other Provider Identifier_12],
[Other Provider Identifier Type Code_12] = s.[Other Provider Identifier Type Code_12],
[Other Provider Identifier State_12] = s.[Other Provider Identifier State_12],
[Other Provider Identifier Issuer_12] = s.[Other Provider Identifier Issuer_12],
[Other Provider Identifier_13] = s.[Other Provider Identifier_13],
[Other Provider Identifier Type Code_13] = s.[Other Provider Identifier Type Code_13],
[Other Provider Identifier State_13] = s.[Other Provider Identifier State_13],
[Other Provider Identifier Issuer_13] = s.[Other Provider Identifier Issuer_13],
[Other Provider Identifier_14] = s.[Other Provider Identifier_14],
[Other Provider Identifier Type Code_14] = s.[Other Provider Identifier Type Code_14],
[Other Provider Identifier State_14] = s.[Other Provider Identifier State_14],
[Other Provider Identifier Issuer_14] = s.[Other Provider Identifier Issuer_14],
[Other Provider Identifier_15] = s.[Other Provider Identifier_15],
[Other Provider Identifier Type Code_15] = s.[Other Provider Identifier Type Code_15],
[Other Provider Identifier State_15] = s.[Other Provider Identifier State_15],
[Other Provider Identifier Issuer_15] = s.[Other Provider Identifier Issuer_15],
[Other Provider Identifier_16] = s.[Other Provider Identifier_16],
[Other Provider Identifier Type Code_16] = s.[Other Provider Identifier Type Code_16],
[Other Provider Identifier State_16] = s.[Other Provider Identifier State_16],
[Other Provider Identifier Issuer_16] = s.[Other Provider Identifier Issuer_16],
[Other Provider Identifier_17] = s.[Other Provider Identifier_17],
[Other Provider Identifier Type Code_17] = s.[Other Provider Identifier Type Code_17],
[Other Provider Identifier State_17] = s.[Other Provider Identifier State_17],
[Other Provider Identifier Issuer_17] = s.[Other Provider Identifier Issuer_17],
[Other Provider Identifier_18] = s.[Other Provider Identifier_18],
[Other Provider Identifier Type Code_18] = s.[Other Provider Identifier Type Code_18],
[Other Provider Identifier State_18] = s.[Other Provider Identifier State_18],
[Other Provider Identifier Issuer_18] = s.[Other Provider Identifier Issuer_18],
[Other Provider Identifier_19] = s.[Other Provider Identifier_19],
[Other Provider Identifier Type Code_19] = s.[Other Provider Identifier Type Code_19],
[Other Provider Identifier State_19] = s.[Other Provider Identifier State_19],
[Other Provider Identifier Issuer_19] = s.[Other Provider Identifier Issuer_19],
[Other Provider Identifier_20] = s.[Other Provider Identifier_20],
[Other Provider Identifier Type Code_20] = s.[Other Provider Identifier Type Code_20],
[Other Provider Identifier State_20] = s.[Other Provider Identifier State_20],
[Other Provider Identifier Issuer_20] = s.[Other Provider Identifier Issuer_20],
[Other Provider Identifier_21] = s.[Other Provider Identifier_21],
[Other Provider Identifier Type Code_21] = s.[Other Provider Identifier Type Code_21],
[Other Provider Identifier State_21] = s.[Other Provider Identifier State_21],
[Other Provider Identifier Issuer_21] = s.[Other Provider Identifier Issuer_21],
[Other Provider Identifier_22] = s.[Other Provider Identifier_22],
[Other Provider Identifier Type Code_22] = s.[Other Provider Identifier Type Code_22],
[Other Provider Identifier State_22] = s.[Other Provider Identifier State_22],
[Other Provider Identifier Issuer_22] = s.[Other Provider Identifier Issuer_22],
[Other Provider Identifier_23] = s.[Other Provider Identifier_23],
[Other Provider Identifier Type Code_23] = s.[Other Provider Identifier Type Code_23],
[Other Provider Identifier State_23] = s.[Other Provider Identifier State_23],
[Other Provider Identifier Issuer_23] = s.[Other Provider Identifier Issuer_23],
[Other Provider Identifier_24] = s.[Other Provider Identifier_24],
[Other Provider Identifier Type Code_24] = s.[Other Provider Identifier Type Code_24],
[Other Provider Identifier State_24] = s.[Other Provider Identifier State_24],
[Other Provider Identifier Issuer_24] = s.[Other Provider Identifier Issuer_24],
[Other Provider Identifier_25] = s.[Other Provider Identifier_25],
[Other Provider Identifier Type Code_25] = s.[Other Provider Identifier Type Code_25],
[Other Provider Identifier State_25] = s.[Other Provider Identifier State_25],
[Other Provider Identifier Issuer_25] = s.[Other Provider Identifier Issuer_25],
[Other Provider Identifier_26] = s.[Other Provider Identifier_26],
[Other Provider Identifier Type Code_26] = s.[Other Provider Identifier Type Code_26],
[Other Provider Identifier State_26] = s.[Other Provider Identifier State_26],
[Other Provider Identifier Issuer_26] = s.[Other Provider Identifier Issuer_26],
[Other Provider Identifier_27] = s.[Other Provider Identifier_27],
[Other Provider Identifier Type Code_27] = s.[Other Provider Identifier Type Code_27],
[Other Provider Identifier State_27] = s.[Other Provider Identifier State_27],
[Other Provider Identifier Issuer_27] = s.[Other Provider Identifier Issuer_27],
[Other Provider Identifier_28] = s.[Other Provider Identifier_28],
[Other Provider Identifier Type Code_28] = s.[Other Provider Identifier Type Code_28],
[Other Provider Identifier State_28] = s.[Other Provider Identifier State_28],
[Other Provider Identifier Issuer_28] = s.[Other Provider Identifier Issuer_28],
[Other Provider Identifier_29] = s.[Other Provider Identifier_29],
[Other Provider Identifier Type Code_29] = s.[Other Provider Identifier Type Code_29],
[Other Provider Identifier State_29] = s.[Other Provider Identifier State_29],
[Other Provider Identifier Issuer_29] = s.[Other Provider Identifier Issuer_29],
[Other Provider Identifier_30] = s.[Other Provider Identifier_30],
[Other Provider Identifier Type Code_30] = s.[Other Provider Identifier Type Code_30],
[Other Provider Identifier State_30] = s.[Other Provider Identifier State_30],
[Other Provider Identifier Issuer_30] = s.[Other Provider Identifier Issuer_30],
[Other Provider Identifier_31] = s.[Other Provider Identifier_31],
[Other Provider Identifier Type Code_31] = s.[Other Provider Identifier Type Code_31],
[Other Provider Identifier State_31] = s.[Other Provider Identifier State_31],
[Other Provider Identifier Issuer_31] = s.[Other Provider Identifier Issuer_31],
[Other Provider Identifier_32] = s.[Other Provider Identifier_32],
[Other Provider Identifier Type Code_32] = s.[Other Provider Identifier Type Code_32],
[Other Provider Identifier State_32] = s.[Other Provider Identifier State_32],
[Other Provider Identifier Issuer_32] = s.[Other Provider Identifier Issuer_32],
[Other Provider Identifier_33] = s.[Other Provider Identifier_33],
[Other Provider Identifier Type Code_33] = s.[Other Provider Identifier Type Code_33],
[Other Provider Identifier State_33] = s.[Other Provider Identifier State_33],
[Other Provider Identifier Issuer_33] = s.[Other Provider Identifier Issuer_33],
[Other Provider Identifier_34] = s.[Other Provider Identifier_34],
[Other Provider Identifier Type Code_34] = s.[Other Provider Identifier Type Code_34],
[Other Provider Identifier State_34] = s.[Other Provider Identifier State_34],
[Other Provider Identifier Issuer_34] = s.[Other Provider Identifier Issuer_34],
[Other Provider Identifier_35] = s.[Other Provider Identifier_35],
[Other Provider Identifier Type Code_35] = s.[Other Provider Identifier Type Code_35],
[Other Provider Identifier State_35] = s.[Other Provider Identifier State_35],
[Other Provider Identifier Issuer_35] = s.[Other Provider Identifier Issuer_35],
[Other Provider Identifier_36] = s.[Other Provider Identifier_36],
[Other Provider Identifier Type Code_36] = s.[Other Provider Identifier Type Code_36],
[Other Provider Identifier State_36] = s.[Other Provider Identifier State_36],
[Other Provider Identifier Issuer_36] = s.[Other Provider Identifier Issuer_36],
[Other Provider Identifier_37] = s.[Other Provider Identifier_37],
[Other Provider Identifier Type Code_37] = s.[Other Provider Identifier Type Code_37],
[Other Provider Identifier State_37] = s.[Other Provider Identifier State_37],
[Other Provider Identifier Issuer_37] = s.[Other Provider Identifier Issuer_37],
[Other Provider Identifier_38] = s.[Other Provider Identifier_38],
[Other Provider Identifier Type Code_38] = s.[Other Provider Identifier Type Code_38],
[Other Provider Identifier State_38] = s.[Other Provider Identifier State_38],
[Other Provider Identifier Issuer_38] = s.[Other Provider Identifier Issuer_38],
[Other Provider Identifier_39] = s.[Other Provider Identifier_39],
[Other Provider Identifier Type Code_39] = s.[Other Provider Identifier Type Code_39],
[Other Provider Identifier State_39] = s.[Other Provider Identifier State_39],
[Other Provider Identifier Issuer_39] = s.[Other Provider Identifier Issuer_39],
[Other Provider Identifier_40] = s.[Other Provider Identifier_40],
[Other Provider Identifier Type Code_40] = s.[Other Provider Identifier Type Code_40],
[Other Provider Identifier State_40] = s.[Other Provider Identifier State_40],
[Other Provider Identifier Issuer_40] = s.[Other Provider Identifier Issuer_40],
[Other Provider Identifier_41] = s.[Other Provider Identifier_41],
[Other Provider Identifier Type Code_41] = s.[Other Provider Identifier Type Code_41],
[Other Provider Identifier State_41] = s.[Other Provider Identifier State_41],
[Other Provider Identifier Issuer_41] = s.[Other Provider Identifier Issuer_41],
[Other Provider Identifier_42] = s.[Other Provider Identifier_42],
[Other Provider Identifier Type Code_42] = s.[Other Provider Identifier Type Code_42],
[Other Provider Identifier State_42] = s.[Other Provider Identifier State_42],
[Other Provider Identifier Issuer_42] = s.[Other Provider Identifier Issuer_42],
[Other Provider Identifier_43] = s.[Other Provider Identifier_43],
[Other Provider Identifier Type Code_43] = s.[Other Provider Identifier Type Code_43],
[Other Provider Identifier State_43] = s.[Other Provider Identifier State_43],
[Other Provider Identifier Issuer_43] = s.[Other Provider Identifier Issuer_43],
[Other Provider Identifier_44] = s.[Other Provider Identifier_44],
[Other Provider Identifier Type Code_44] = s.[Other Provider Identifier Type Code_44],
[Other Provider Identifier State_44] = s.[Other Provider Identifier State_44],
[Other Provider Identifier Issuer_44] = s.[Other Provider Identifier Issuer_44],
[Other Provider Identifier_45] = s.[Other Provider Identifier_45],
[Other Provider Identifier Type Code_45] = s.[Other Provider Identifier Type Code_45],
[Other Provider Identifier State_45] = s.[Other Provider Identifier State_45],
[Other Provider Identifier Issuer_45] = s.[Other Provider Identifier Issuer_45],
[Other Provider Identifier_46] = s.[Other Provider Identifier_46],
[Other Provider Identifier Type Code_46] = s.[Other Provider Identifier Type Code_46],
[Other Provider Identifier State_46] = s.[Other Provider Identifier State_46],
[Other Provider Identifier Issuer_46] = s.[Other Provider Identifier Issuer_46],
[Other Provider Identifier_47] = s.[Other Provider Identifier_47],
[Other Provider Identifier Type Code_47] = s.[Other Provider Identifier Type Code_47],
[Other Provider Identifier State_47] = s.[Other Provider Identifier State_47],
[Other Provider Identifier Issuer_47] = s.[Other Provider Identifier Issuer_47],
[Other Provider Identifier_48] = s.[Other Provider Identifier_48],
[Other Provider Identifier Type Code_48] = s.[Other Provider Identifier Type Code_48],
[Other Provider Identifier State_48] = s.[Other Provider Identifier State_48],
[Other Provider Identifier Issuer_48] = s.[Other Provider Identifier Issuer_48],
[Other Provider Identifier_49] = s.[Other Provider Identifier_49],
[Other Provider Identifier Type Code_49] = s.[Other Provider Identifier Type Code_49],
[Other Provider Identifier State_49] = s.[Other Provider Identifier State_49],
[Other Provider Identifier Issuer_49] = s.[Other Provider Identifier Issuer_49],
[Other Provider Identifier_50] = s.[Other Provider Identifier_50],
[Other Provider Identifier Type Code_50] = s.[Other Provider Identifier Type Code_50],
[Other Provider Identifier State_50] = s.[Other Provider Identifier State_50],
[Other Provider Identifier Issuer_50] = s.[Other Provider Identifier Issuer_50],
[Is Sole Proprietor] = s.[Is Sole Proprietor],
[Is Organization Subpart] = s.[Is Organization Subpart],
[Parent Organization LBN] = s.[Parent Organization LBN],
[Parent Organization TIN] = s.[Parent Organization TIN],
[Authorized Official Name Prefix Text] = s.[Authorized Official Name Prefix Text],
[Authorized Official Name Suffix Text] = s.[Authorized Official Name Suffix Text],
[Authorized Official Credential Text] = s.[Authorized Official Credential Text],
[Healthcare Provider Taxonomy Group_1] = s.[Healthcare Provider Taxonomy Group_1],
[Healthcare Provider Taxonomy Group_2] = s.[Healthcare Provider Taxonomy Group_2],
[Healthcare Provider Taxonomy Group_3] = s.[Healthcare Provider Taxonomy Group_3],
[Healthcare Provider Taxonomy Group_4] = s.[Healthcare Provider Taxonomy Group_4],
[Healthcare Provider Taxonomy Group_5] = s.[Healthcare Provider Taxonomy Group_5],
[Healthcare Provider Taxonomy Group_6] = s.[Healthcare Provider Taxonomy Group_6],
[Healthcare Provider Taxonomy Group_7] = s.[Healthcare Provider Taxonomy Group_7],
[Healthcare Provider Taxonomy Group_8] = s.[Healthcare Provider Taxonomy Group_8],
[Healthcare Provider Taxonomy Group_9] = s.[Healthcare Provider Taxonomy Group_9],
[Healthcare Provider Taxonomy Group_10] = s.[Healthcare Provider Taxonomy Group_10],
[Healthcare Provider Taxonomy Group_11] = s.[Healthcare Provider Taxonomy Group_11],
[Healthcare Provider Taxonomy Group_12] = s.[Healthcare Provider Taxonomy Group_12],
[Healthcare Provider Taxonomy Group_13] = s.[Healthcare Provider Taxonomy Group_13],
[Healthcare Provider Taxonomy Group_14] = s.[Healthcare Provider Taxonomy Group_14],
[Healthcare Provider Taxonomy Group_15] = s.[Healthcare Provider Taxonomy Group_15]
 WHEN NOT MATCHED BY TARGET THEN
    INSERT(
	[NPI],
[Entity Type Code],
[Replacement NPI],
[Employer Identification Number (EIN)],
[Provider Organization Name (Legal Business Name)],
[Provider Last Name (Legal Name)],
[Provider First Name],
[Provider Middle Name],
[Provider Name Prefix Text],
[Provider Name Suffix Text],
[Provider Credential Text],
[Provider Other Organization Name],
[Provider Other Organization Name Type Code],
[Provider Other Last Name],
[Provider Other First Name],
[Provider Other Middle Name],
[Provider Other Name Prefix Text],
[Provider Other Name Suffix Text],
[Provider Other Credential Text],
[Provider Other Last Name Type Code],
[Provider First Line Business Mailing Address],
[Provider Second Line Business Mailing Address],
[Provider Business Mailing Address City Name],
[Provider Business Mailing Address State Name],
[Provider Business Mailing Address Postal Code],
[Provider Business Mailing Address Country Code (If outside U S )],
[Provider Business Mailing Address Telephone Number],
[Provider Business Mailing Address Fax Number],
[Provider First Line Business Practice Location Address],
[Provider Second Line Business Practice Location Address],
[Provider Business Practice Location Address City Name],
[Provider Business Practice Location Address State Name],
[Provider Business Practice Location Address Postal Code],
[Provider Business Practice Location Address Country Code (If outside U S )],
[Provider Business Practice Location Address Telephone Number],
[Provider Business Practice Location Address Fax Number],
[Provider Enumeration Date],
[Last Update Date],
[NPI Deactivation Reason Code],
[NPI Deactivation Date],
[NPI Reactivation Date],
[Provider Gender Code],
[Authorized Official Last Name],
[Authorized Official First Name],
[Authorized Official Middle Name],
[Authorized Official Title or Position],
[Authorized Official Telephone Number],
[Healthcare Provider Taxonomy Code_1],
[Provider License Number_1],
[Provider License Number State Code_1],
[Healthcare Provider Primary Taxonomy Switch_1],
[Healthcare Provider Taxonomy Code_2],
[Provider License Number_2],
[Provider License Number State Code_2],
[Healthcare Provider Primary Taxonomy Switch_2],
[Healthcare Provider Taxonomy Code_3],
[Provider License Number_3],
[Provider License Number State Code_3],
[Healthcare Provider Primary Taxonomy Switch_3],
[Healthcare Provider Taxonomy Code_4],
[Provider License Number_4],
[Provider License Number State Code_4],
[Healthcare Provider Primary Taxonomy Switch_4],
[Healthcare Provider Taxonomy Code_5],
[Provider License Number_5],
[Provider License Number State Code_5],
[Healthcare Provider Primary Taxonomy Switch_5],
[Healthcare Provider Taxonomy Code_6],
[Provider License Number_6],
[Provider License Number State Code_6],
[Healthcare Provider Primary Taxonomy Switch_6],
[Healthcare Provider Taxonomy Code_7],
[Provider License Number_7],
[Provider License Number State Code_7],
[Healthcare Provider Primary Taxonomy Switch_7],
[Healthcare Provider Taxonomy Code_8],
[Provider License Number_8],
[Provider License Number State Code_8],
[Healthcare Provider Primary Taxonomy Switch_8],
[Healthcare Provider Taxonomy Code_9],
[Provider License Number_9],
[Provider License Number State Code_9],
[Healthcare Provider Primary Taxonomy Switch_9],
[Healthcare Provider Taxonomy Code_10],
[Provider License Number_10],
[Provider License Number State Code_10],
[Healthcare Provider Primary Taxonomy Switch_10],
[Healthcare Provider Taxonomy Code_11],
[Provider License Number_11],
[Provider License Number State Code_11],
[Healthcare Provider Primary Taxonomy Switch_11],
[Healthcare Provider Taxonomy Code_12],
[Provider License Number_12],
[Provider License Number State Code_12],
[Healthcare Provider Primary Taxonomy Switch_12],
[Healthcare Provider Taxonomy Code_13],
[Provider License Number_13],
[Provider License Number State Code_13],
[Healthcare Provider Primary Taxonomy Switch_13],
[Healthcare Provider Taxonomy Code_14],
[Provider License Number_14],
[Provider License Number State Code_14],
[Healthcare Provider Primary Taxonomy Switch_14],
[Healthcare Provider Taxonomy Code_15],
[Provider License Number_15],
[Provider License Number State Code_15],
[Healthcare Provider Primary Taxonomy Switch_15],
[Other Provider Identifier_1],
[Other Provider Identifier Type Code_1],
[Other Provider Identifier State_1],
[Other Provider Identifier Issuer_1],
[Other Provider Identifier_2],
[Other Provider Identifier Type Code_2],
[Other Provider Identifier State_2],
[Other Provider Identifier Issuer_2],
[Other Provider Identifier_3],
[Other Provider Identifier Type Code_3],
[Other Provider Identifier State_3],
[Other Provider Identifier Issuer_3],
[Other Provider Identifier_4],
[Other Provider Identifier Type Code_4],
[Other Provider Identifier State_4],
[Other Provider Identifier Issuer_4],
[Other Provider Identifier_5],
[Other Provider Identifier Type Code_5],
[Other Provider Identifier State_5],
[Other Provider Identifier Issuer_5],
[Other Provider Identifier_6],
[Other Provider Identifier Type Code_6],
[Other Provider Identifier State_6],
[Other Provider Identifier Issuer_6],
[Other Provider Identifier_7],
[Other Provider Identifier Type Code_7],
[Other Provider Identifier State_7],
[Other Provider Identifier Issuer_7],
[Other Provider Identifier_8],
[Other Provider Identifier Type Code_8],
[Other Provider Identifier State_8],
[Other Provider Identifier Issuer_8],
[Other Provider Identifier_9],
[Other Provider Identifier Type Code_9],
[Other Provider Identifier State_9],
[Other Provider Identifier Issuer_9],
[Other Provider Identifier_10],
[Other Provider Identifier Type Code_10],
[Other Provider Identifier State_10],
[Other Provider Identifier Issuer_10],
[Other Provider Identifier_11],
[Other Provider Identifier Type Code_11],
[Other Provider Identifier State_11],
[Other Provider Identifier Issuer_11],
[Other Provider Identifier_12],
[Other Provider Identifier Type Code_12],
[Other Provider Identifier State_12],
[Other Provider Identifier Issuer_12],
[Other Provider Identifier_13],
[Other Provider Identifier Type Code_13],
[Other Provider Identifier State_13],
[Other Provider Identifier Issuer_13],
[Other Provider Identifier_14],
[Other Provider Identifier Type Code_14],
[Other Provider Identifier State_14],
[Other Provider Identifier Issuer_14],
[Other Provider Identifier_15],
[Other Provider Identifier Type Code_15],
[Other Provider Identifier State_15],
[Other Provider Identifier Issuer_15],
[Other Provider Identifier_16],
[Other Provider Identifier Type Code_16],
[Other Provider Identifier State_16],
[Other Provider Identifier Issuer_16],
[Other Provider Identifier_17],
[Other Provider Identifier Type Code_17],
[Other Provider Identifier State_17],
[Other Provider Identifier Issuer_17],
[Other Provider Identifier_18],
[Other Provider Identifier Type Code_18],
[Other Provider Identifier State_18],
[Other Provider Identifier Issuer_18],
[Other Provider Identifier_19],
[Other Provider Identifier Type Code_19],
[Other Provider Identifier State_19],
[Other Provider Identifier Issuer_19],
[Other Provider Identifier_20],
[Other Provider Identifier Type Code_20],
[Other Provider Identifier State_20],
[Other Provider Identifier Issuer_20],
[Other Provider Identifier_21],
[Other Provider Identifier Type Code_21],
[Other Provider Identifier State_21],
[Other Provider Identifier Issuer_21],
[Other Provider Identifier_22],
[Other Provider Identifier Type Code_22],
[Other Provider Identifier State_22],
[Other Provider Identifier Issuer_22],
[Other Provider Identifier_23],
[Other Provider Identifier Type Code_23],
[Other Provider Identifier State_23],
[Other Provider Identifier Issuer_23],
[Other Provider Identifier_24],
[Other Provider Identifier Type Code_24],
[Other Provider Identifier State_24],
[Other Provider Identifier Issuer_24],
[Other Provider Identifier_25],
[Other Provider Identifier Type Code_25],
[Other Provider Identifier State_25],
[Other Provider Identifier Issuer_25],
[Other Provider Identifier_26],
[Other Provider Identifier Type Code_26],
[Other Provider Identifier State_26],
[Other Provider Identifier Issuer_26],
[Other Provider Identifier_27],
[Other Provider Identifier Type Code_27],
[Other Provider Identifier State_27],
[Other Provider Identifier Issuer_27],
[Other Provider Identifier_28],
[Other Provider Identifier Type Code_28],
[Other Provider Identifier State_28],
[Other Provider Identifier Issuer_28],
[Other Provider Identifier_29],
[Other Provider Identifier Type Code_29],
[Other Provider Identifier State_29],
[Other Provider Identifier Issuer_29],
[Other Provider Identifier_30],
[Other Provider Identifier Type Code_30],
[Other Provider Identifier State_30],
[Other Provider Identifier Issuer_30],
[Other Provider Identifier_31],
[Other Provider Identifier Type Code_31],
[Other Provider Identifier State_31],
[Other Provider Identifier Issuer_31],
[Other Provider Identifier_32],
[Other Provider Identifier Type Code_32],
[Other Provider Identifier State_32],
[Other Provider Identifier Issuer_32],
[Other Provider Identifier_33],
[Other Provider Identifier Type Code_33],
[Other Provider Identifier State_33],
[Other Provider Identifier Issuer_33],
[Other Provider Identifier_34],
[Other Provider Identifier Type Code_34],
[Other Provider Identifier State_34],
[Other Provider Identifier Issuer_34],
[Other Provider Identifier_35],
[Other Provider Identifier Type Code_35],
[Other Provider Identifier State_35],
[Other Provider Identifier Issuer_35],
[Other Provider Identifier_36],
[Other Provider Identifier Type Code_36],
[Other Provider Identifier State_36],
[Other Provider Identifier Issuer_36],
[Other Provider Identifier_37],
[Other Provider Identifier Type Code_37],
[Other Provider Identifier State_37],
[Other Provider Identifier Issuer_37],
[Other Provider Identifier_38],
[Other Provider Identifier Type Code_38],
[Other Provider Identifier State_38],
[Other Provider Identifier Issuer_38],
[Other Provider Identifier_39],
[Other Provider Identifier Type Code_39],
[Other Provider Identifier State_39],
[Other Provider Identifier Issuer_39],
[Other Provider Identifier_40],
[Other Provider Identifier Type Code_40],
[Other Provider Identifier State_40],
[Other Provider Identifier Issuer_40],
[Other Provider Identifier_41],
[Other Provider Identifier Type Code_41],
[Other Provider Identifier State_41],
[Other Provider Identifier Issuer_41],
[Other Provider Identifier_42],
[Other Provider Identifier Type Code_42],
[Other Provider Identifier State_42],
[Other Provider Identifier Issuer_42],
[Other Provider Identifier_43],
[Other Provider Identifier Type Code_43],
[Other Provider Identifier State_43],
[Other Provider Identifier Issuer_43],
[Other Provider Identifier_44],
[Other Provider Identifier Type Code_44],
[Other Provider Identifier State_44],
[Other Provider Identifier Issuer_44],
[Other Provider Identifier_45],
[Other Provider Identifier Type Code_45],
[Other Provider Identifier State_45],
[Other Provider Identifier Issuer_45],
[Other Provider Identifier_46],
[Other Provider Identifier Type Code_46],
[Other Provider Identifier State_46],
[Other Provider Identifier Issuer_46],
[Other Provider Identifier_47],
[Other Provider Identifier Type Code_47],
[Other Provider Identifier State_47],
[Other Provider Identifier Issuer_47],
[Other Provider Identifier_48],
[Other Provider Identifier Type Code_48],
[Other Provider Identifier State_48],
[Other Provider Identifier Issuer_48],
[Other Provider Identifier_49],
[Other Provider Identifier Type Code_49],
[Other Provider Identifier State_49],
[Other Provider Identifier Issuer_49],
[Other Provider Identifier_50],
[Other Provider Identifier Type Code_50],
[Other Provider Identifier State_50],
[Other Provider Identifier Issuer_50],
[Is Sole Proprietor],
[Is Organization Subpart],
[Parent Organization LBN],
[Parent Organization TIN],
[Authorized Official Name Prefix Text],
[Authorized Official Name Suffix Text],
[Authorized Official Credential Text],
[Healthcare Provider Taxonomy Group_1],
[Healthcare Provider Taxonomy Group_2],
[Healthcare Provider Taxonomy Group_3],
[Healthcare Provider Taxonomy Group_4],
[Healthcare Provider Taxonomy Group_5],
[Healthcare Provider Taxonomy Group_6],
[Healthcare Provider Taxonomy Group_7],
[Healthcare Provider Taxonomy Group_8],
[Healthcare Provider Taxonomy Group_9],
[Healthcare Provider Taxonomy Group_10],
[Healthcare Provider Taxonomy Group_11],
[Healthcare Provider Taxonomy Group_12],
[Healthcare Provider Taxonomy Group_13],
[Healthcare Provider Taxonomy Group_14],
[Healthcare Provider Taxonomy Group_15])
	
	VALUES(
	s.[NPI],
s.[Entity Type Code],
s.[Replacement NPI],
s.[Employer Identification Number (EIN)],
s.[Provider Organization Name (Legal Business Name)],
s.[Provider Last Name (Legal Name)],
s.[Provider First Name],
s.[Provider Middle Name],
s.[Provider Name Prefix Text],
s.[Provider Name Suffix Text],
s.[Provider Credential Text],
s.[Provider Other Organization Name],
s.[Provider Other Organization Name Type Code],
s.[Provider Other Last Name],
s.[Provider Other First Name],
s.[Provider Other Middle Name],
s.[Provider Other Name Prefix Text],
s.[Provider Other Name Suffix Text],
s.[Provider Other Credential Text],
s.[Provider Other Last Name Type Code],
s.[Provider First Line Business Mailing Address],
s.[Provider Second Line Business Mailing Address],
s.[Provider Business Mailing Address City Name],
s.[Provider Business Mailing Address State Name],
s.[Provider Business Mailing Address Postal Code],
s.[Provider Business Mailing Address Country Code (If outside U S )],
s.[Provider Business Mailing Address Telephone Number],
s.[Provider Business Mailing Address Fax Number],
s.[Provider First Line Business Practice Location Address],
s.[Provider Second Line Business Practice Location Address],
s.[Provider Business Practice Location Address City Name],
s.[Provider Business Practice Location Address State Name],
s.[Provider Business Practice Location Address Postal Code],
s.[Provider Business Practice Location Address Country Code (If outside U S )],
s.[Provider Business Practice Location Address Telephone Number],
s.[Provider Business Practice Location Address Fax Number],
s.[Provider Enumeration Date],
s.[Last Update Date],
s.[NPI Deactivation Reason Code],
s.[NPI Deactivation Date],
s.[NPI Reactivation Date],
s.[Provider Gender Code],
s.[Authorized Official Last Name],
s.[Authorized Official First Name],
s.[Authorized Official Middle Name],
s.[Authorized Official Title or Position],
s.[Authorized Official Telephone Number],
s.[Healthcare Provider Taxonomy Code_1],
s.[Provider License Number_1],
s.[Provider License Number State Code_1],
s.[Healthcare Provider Primary Taxonomy Switch_1],
s.[Healthcare Provider Taxonomy Code_2],
s.[Provider License Number_2],
s.[Provider License Number State Code_2],
s.[Healthcare Provider Primary Taxonomy Switch_2],
s.[Healthcare Provider Taxonomy Code_3],
s.[Provider License Number_3],
s.[Provider License Number State Code_3],
s.[Healthcare Provider Primary Taxonomy Switch_3],
s.[Healthcare Provider Taxonomy Code_4],
s.[Provider License Number_4],
s.[Provider License Number State Code_4],
s.[Healthcare Provider Primary Taxonomy Switch_4],
s.[Healthcare Provider Taxonomy Code_5],
s.[Provider License Number_5],
s.[Provider License Number State Code_5],
s.[Healthcare Provider Primary Taxonomy Switch_5],
s.[Healthcare Provider Taxonomy Code_6],
s.[Provider License Number_6],
s.[Provider License Number State Code_6],
s.[Healthcare Provider Primary Taxonomy Switch_6],
s.[Healthcare Provider Taxonomy Code_7],
s.[Provider License Number_7],
s.[Provider License Number State Code_7],
s.[Healthcare Provider Primary Taxonomy Switch_7],
s.[Healthcare Provider Taxonomy Code_8],
s.[Provider License Number_8],
s.[Provider License Number State Code_8],
s.[Healthcare Provider Primary Taxonomy Switch_8],
s.[Healthcare Provider Taxonomy Code_9],
s.[Provider License Number_9],
s.[Provider License Number State Code_9],
s.[Healthcare Provider Primary Taxonomy Switch_9],
s.[Healthcare Provider Taxonomy Code_10],
s.[Provider License Number_10],
s.[Provider License Number State Code_10],
s.[Healthcare Provider Primary Taxonomy Switch_10],
s.[Healthcare Provider Taxonomy Code_11],
s.[Provider License Number_11],
s.[Provider License Number State Code_11],
s.[Healthcare Provider Primary Taxonomy Switch_11],
s.[Healthcare Provider Taxonomy Code_12],
s.[Provider License Number_12],
s.[Provider License Number State Code_12],
s.[Healthcare Provider Primary Taxonomy Switch_12],
s.[Healthcare Provider Taxonomy Code_13],
s.[Provider License Number_13],
s.[Provider License Number State Code_13],
s.[Healthcare Provider Primary Taxonomy Switch_13],
s.[Healthcare Provider Taxonomy Code_14],
s.[Provider License Number_14],
s.[Provider License Number State Code_14],
s.[Healthcare Provider Primary Taxonomy Switch_14],
s.[Healthcare Provider Taxonomy Code_15],
s.[Provider License Number_15],
s.[Provider License Number State Code_15],
s.[Healthcare Provider Primary Taxonomy Switch_15],
s.[Other Provider Identifier_1],
s.[Other Provider Identifier Type Code_1],
s.[Other Provider Identifier State_1],
s.[Other Provider Identifier Issuer_1],
s.[Other Provider Identifier_2],
s.[Other Provider Identifier Type Code_2],
s.[Other Provider Identifier State_2],
s.[Other Provider Identifier Issuer_2],
s.[Other Provider Identifier_3],
s.[Other Provider Identifier Type Code_3],
s.[Other Provider Identifier State_3],
s.[Other Provider Identifier Issuer_3],
s.[Other Provider Identifier_4],
s.[Other Provider Identifier Type Code_4],
s.[Other Provider Identifier State_4],
s.[Other Provider Identifier Issuer_4],
s.[Other Provider Identifier_5],
s.[Other Provider Identifier Type Code_5],
s.[Other Provider Identifier State_5],
s.[Other Provider Identifier Issuer_5],
s.[Other Provider Identifier_6],
s.[Other Provider Identifier Type Code_6],
s.[Other Provider Identifier State_6],
s.[Other Provider Identifier Issuer_6],
s.[Other Provider Identifier_7],
s.[Other Provider Identifier Type Code_7],
s.[Other Provider Identifier State_7],
s.[Other Provider Identifier Issuer_7],
s.[Other Provider Identifier_8],
s.[Other Provider Identifier Type Code_8],
s.[Other Provider Identifier State_8],
s.[Other Provider Identifier Issuer_8],
s.[Other Provider Identifier_9],
s.[Other Provider Identifier Type Code_9],
s.[Other Provider Identifier State_9],
s.[Other Provider Identifier Issuer_9],
s.[Other Provider Identifier_10],
s.[Other Provider Identifier Type Code_10],
s.[Other Provider Identifier State_10],
s.[Other Provider Identifier Issuer_10],
s.[Other Provider Identifier_11],
s.[Other Provider Identifier Type Code_11],
s.[Other Provider Identifier State_11],
s.[Other Provider Identifier Issuer_11],
s.[Other Provider Identifier_12],
s.[Other Provider Identifier Type Code_12],
s.[Other Provider Identifier State_12],
s.[Other Provider Identifier Issuer_12],
s.[Other Provider Identifier_13],
s.[Other Provider Identifier Type Code_13],
s.[Other Provider Identifier State_13],
s.[Other Provider Identifier Issuer_13],
s.[Other Provider Identifier_14],
s.[Other Provider Identifier Type Code_14],
s.[Other Provider Identifier State_14],
s.[Other Provider Identifier Issuer_14],
s.[Other Provider Identifier_15],
s.[Other Provider Identifier Type Code_15],
s.[Other Provider Identifier State_15],
s.[Other Provider Identifier Issuer_15],
s.[Other Provider Identifier_16],
s.[Other Provider Identifier Type Code_16],
s.[Other Provider Identifier State_16],
s.[Other Provider Identifier Issuer_16],
s.[Other Provider Identifier_17],
s.[Other Provider Identifier Type Code_17],
s.[Other Provider Identifier State_17],
s.[Other Provider Identifier Issuer_17],
s.[Other Provider Identifier_18],
s.[Other Provider Identifier Type Code_18],
s.[Other Provider Identifier State_18],
s.[Other Provider Identifier Issuer_18],
s.[Other Provider Identifier_19],
s.[Other Provider Identifier Type Code_19],
s.[Other Provider Identifier State_19],
s.[Other Provider Identifier Issuer_19],
s.[Other Provider Identifier_20],
s.[Other Provider Identifier Type Code_20],
s.[Other Provider Identifier State_20],
s.[Other Provider Identifier Issuer_20],
s.[Other Provider Identifier_21],
s.[Other Provider Identifier Type Code_21],
s.[Other Provider Identifier State_21],
s.[Other Provider Identifier Issuer_21],
s.[Other Provider Identifier_22],
s.[Other Provider Identifier Type Code_22],
s.[Other Provider Identifier State_22],
s.[Other Provider Identifier Issuer_22],
s.[Other Provider Identifier_23],
s.[Other Provider Identifier Type Code_23],
s.[Other Provider Identifier State_23],
s.[Other Provider Identifier Issuer_23],
s.[Other Provider Identifier_24],
s.[Other Provider Identifier Type Code_24],
s.[Other Provider Identifier State_24],
s.[Other Provider Identifier Issuer_24],
s.[Other Provider Identifier_25],
s.[Other Provider Identifier Type Code_25],
s.[Other Provider Identifier State_25],
s.[Other Provider Identifier Issuer_25],
s.[Other Provider Identifier_26],
s.[Other Provider Identifier Type Code_26],
s.[Other Provider Identifier State_26],
s.[Other Provider Identifier Issuer_26],
s.[Other Provider Identifier_27],
s.[Other Provider Identifier Type Code_27],
s.[Other Provider Identifier State_27],
s.[Other Provider Identifier Issuer_27],
s.[Other Provider Identifier_28],
s.[Other Provider Identifier Type Code_28],
s.[Other Provider Identifier State_28],
s.[Other Provider Identifier Issuer_28],
s.[Other Provider Identifier_29],
s.[Other Provider Identifier Type Code_29],
s.[Other Provider Identifier State_29],
s.[Other Provider Identifier Issuer_29],
s.[Other Provider Identifier_30],
s.[Other Provider Identifier Type Code_30],
s.[Other Provider Identifier State_30],
s.[Other Provider Identifier Issuer_30],
s.[Other Provider Identifier_31],
s.[Other Provider Identifier Type Code_31],
s.[Other Provider Identifier State_31],
s.[Other Provider Identifier Issuer_31],
s.[Other Provider Identifier_32],
s.[Other Provider Identifier Type Code_32],
s.[Other Provider Identifier State_32],
s.[Other Provider Identifier Issuer_32],
s.[Other Provider Identifier_33],
s.[Other Provider Identifier Type Code_33],
s.[Other Provider Identifier State_33],
s.[Other Provider Identifier Issuer_33],
s.[Other Provider Identifier_34],
s.[Other Provider Identifier Type Code_34],
s.[Other Provider Identifier State_34],
s.[Other Provider Identifier Issuer_34],
s.[Other Provider Identifier_35],
s.[Other Provider Identifier Type Code_35],
s.[Other Provider Identifier State_35],
s.[Other Provider Identifier Issuer_35],
s.[Other Provider Identifier_36],
s.[Other Provider Identifier Type Code_36],
s.[Other Provider Identifier State_36],
s.[Other Provider Identifier Issuer_36],
s.[Other Provider Identifier_37],
s.[Other Provider Identifier Type Code_37],
s.[Other Provider Identifier State_37],
s.[Other Provider Identifier Issuer_37],
s.[Other Provider Identifier_38],
s.[Other Provider Identifier Type Code_38],
s.[Other Provider Identifier State_38],
s.[Other Provider Identifier Issuer_38],
s.[Other Provider Identifier_39],
s.[Other Provider Identifier Type Code_39],
s.[Other Provider Identifier State_39],
s.[Other Provider Identifier Issuer_39],
s.[Other Provider Identifier_40],
s.[Other Provider Identifier Type Code_40],
s.[Other Provider Identifier State_40],
s.[Other Provider Identifier Issuer_40],
s.[Other Provider Identifier_41],
s.[Other Provider Identifier Type Code_41],
s.[Other Provider Identifier State_41],
s.[Other Provider Identifier Issuer_41],
s.[Other Provider Identifier_42],
s.[Other Provider Identifier Type Code_42],
s.[Other Provider Identifier State_42],
s.[Other Provider Identifier Issuer_42],
s.[Other Provider Identifier_43],
s.[Other Provider Identifier Type Code_43],
s.[Other Provider Identifier State_43],
s.[Other Provider Identifier Issuer_43],
s.[Other Provider Identifier_44],
s.[Other Provider Identifier Type Code_44],
s.[Other Provider Identifier State_44],
s.[Other Provider Identifier Issuer_44],
s.[Other Provider Identifier_45],
s.[Other Provider Identifier Type Code_45],
s.[Other Provider Identifier State_45],
s.[Other Provider Identifier Issuer_45],
s.[Other Provider Identifier_46],
s.[Other Provider Identifier Type Code_46],
s.[Other Provider Identifier State_46],
s.[Other Provider Identifier Issuer_46],
s.[Other Provider Identifier_47],
s.[Other Provider Identifier Type Code_47],
s.[Other Provider Identifier State_47],
s.[Other Provider Identifier Issuer_47],
s.[Other Provider Identifier_48],
s.[Other Provider Identifier Type Code_48],
s.[Other Provider Identifier State_48],
s.[Other Provider Identifier Issuer_48],
s.[Other Provider Identifier_49],
s.[Other Provider Identifier Type Code_49],
s.[Other Provider Identifier State_49],
s.[Other Provider Identifier Issuer_49],
s.[Other Provider Identifier_50],
s.[Other Provider Identifier Type Code_50],
s.[Other Provider Identifier State_50],
s.[Other Provider Identifier Issuer_50],
s.[Is Sole Proprietor],
s.[Is Organization Subpart],
s.[Parent Organization LBN],
s.[Parent Organization TIN],
s.[Authorized Official Name Prefix Text],
s.[Authorized Official Name Suffix Text],
s.[Authorized Official Credential Text],
s.[Healthcare Provider Taxonomy Group_1],
s.[Healthcare Provider Taxonomy Group_2],
s.[Healthcare Provider Taxonomy Group_3],
s.[Healthcare Provider Taxonomy Group_4],
s.[Healthcare Provider Taxonomy Group_5],
s.[Healthcare Provider Taxonomy Group_6],
s.[Healthcare Provider Taxonomy Group_7],
s.[Healthcare Provider Taxonomy Group_8],
s.[Healthcare Provider Taxonomy Group_9],
s.[Healthcare Provider Taxonomy Group_10],
s.[Healthcare Provider Taxonomy Group_11],
s.[Healthcare Provider Taxonomy Group_12],
s.[Healthcare Provider Taxonomy Group_13],
s.[Healthcare Provider Taxonomy Group_14],
s.[Healthcare Provider Taxonomy Group_15]);
	--WHEN NOT MATCHED BY SOURCE THEN DELETE; 
 



END
GO
