CREATE TABLE [dbo].[S_100003_MemberMonth]
(
[ClientMemberID] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[MEMBERGENDER] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RELATIONSHIP] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MEMBERAGE] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MEMBERBIRTHDATE] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MEMBERSTATE] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MEMBERZIPCODE] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MEMBERCOUNTY] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SPANFROMDATE] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SPANTODATE] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ELIGIBILITYSTARTDATE] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ELIGIBILITYENDDATE] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EMPLOYERGROUPID] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EMPLOYERGROUPMODIFIER] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BENEFITPLANID] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BENEFITSEQUENCENUMBER] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LINEOFBUSINESS] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RIDEROPTION] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BENEFITTIER] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COMPANYCODE] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COMPANYNAME] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BASEPLANCODE] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BASEPLANDESCRIPTION] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PRODUCTCODE] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PRODUCTDESCRIPTION] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PRODUCTTYPECODE] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PRODUCTTYPECODEDEFINITION] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SEGMENTCODE] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SEGMENTDEFINITION] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PROVIDERID] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PROVIDERLOCATIONSUFFIX] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PRIMARYSPECIALTYCODE] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SERVICINGSTATEZIPCODE] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MEDICALCENTERNUMBER] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MEDICALCENTERNAME] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RISKENTITYNAME] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HOSPITALRISKCOHORT] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NETWORKSUBDELIVERYSYSTEMNAME] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SUBDELIVERYSYSTEMCODE] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SUBDELIVERYSYSTEMDESC] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DELIVERYSYSTEMCODE] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DELIVERYSYSTEMDESC] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ACOINDICATOR] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LoadDate] [datetime] NULL,
[RecordSource] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MemberHashKey] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ClientHashKey] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CMI] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CCI] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[H_100003_Member_RK] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[S_100003_MemberMonth_RK] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[S_100003_MemberMonth] ADD CONSTRAINT [PK__S_100003__93C25651CDB76B68] PRIMARY KEY CLUSTERED  ([S_100003_MemberMonth_RK]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_ClientMemberID] ON [dbo].[S_100003_MemberMonth] ([ClientMemberID]) INCLUDE ([LINEOFBUSINESS], [MEMBERBIRTHDATE], [MEMBERGENDER]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[S_100003_MemberMonth] ADD CONSTRAINT [FK_S_100003_MemberMonth_work_H_100003_Member] FOREIGN KEY ([H_100003_Member_RK]) REFERENCES [dbo].[H_100003_Member] ([H_Member_RK])
GO
EXEC sp_addextendedproperty N'MS_Description', N'HASH(CMI:SpanFromDate:SpanToDate:EligibilityStartDate:EligibilityEndDate:LoadDate:RecordSource)', 'SCHEMA', N'dbo', 'TABLE', N'S_100003_MemberMonth', 'COLUMN', N'S_100003_MemberMonth_RK'
GO
