IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'INTERNAL\DUSTIN.RESCH')
CREATE LOGIN [INTERNAL\DUSTIN.RESCH] FROM WINDOWS
GO
CREATE USER [INTERNAL\DUSTIN.RESCH] FOR LOGIN [INTERNAL\DUSTIN.RESCH]
GO
