CREATE TABLE [adv].[tblMemberStage]
(
[Member_PK] [bigint] NOT NULL,
[HICNumber] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Member_ID] [varchar] (22) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Lastname] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Firstname] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DOB] [date] NULL,
[Gender] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ZipCode_PK] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Contact_Number] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ChaseID] [bigint] NULL,
[PID] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[REN_PROVIDER_SPECIALTY] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Segment_PK] [tinyint] NULL,
[ChartPriority] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Ref_Number] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Latitude] [float] NULL,
[Longitude] [float] NULL,
[parent_gardian] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[preferred_practitioner_gender] [tinyint] NULL,
[Cell_Number] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Email_Address] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[does_not_speak_english] [bit] NULL,
[unable_to_determine_language] [bit] NULL,
[speaking_language] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[language_line_will_be_required_for_the_visit] [bit] NULL,
[plan_unable_to_validate_client_vendor_relationship] [bit] NULL,
[preferred_method_of_contact] [tinyint] NULL,
[permission_to_leave_voicemail] [bit] NULL,
[Orig_Address] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Orig_ZipCode_PK] [int] NULL,
[Orig_Contact_Number] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Orig_Email_Address] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[place_of_assessment_is_not_members_home] [bit] NULL,
[Home_Address] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Home_ZipCode_PK] [int] NULL,
[Home_Contact_Number] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Home_Email_Address] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[members_power_of_attorney] [bit] NULL,
[POA_Name] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[POA_Address] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[POA_ZipCode_PK] [int] NULL,
[POA_Contact_Number] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[POA_Email_Address] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Client_PK] [tinyint] NULL,
[Client] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RecordSource] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LoadDate] [datetime] NULL CONSTRAINT [DF__tblMember__LoadD__4F8953B3] DEFAULT (getdate()),
[MemberHashKey] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ClientHashKey] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CCI] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CMI] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [adv].[tblMemberStage] ADD CONSTRAINT [PK_tblMemberStage] PRIMARY KEY CLUSTERED  ([Member_PK]) WITH (FILLFACTOR=80) ON [PRIMARY]
GO
