CREATE TABLE [dbo].[IVA_MasterHCC]
(
[RecordID] [int] NOT NULL IDENTITY(1, 1),
[ClientID] [int] NULL,
[HIOS] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MemberID] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EdgeEnrolleeID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MemberLastName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MemberFirstName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MemberDOB] [date] NULL,
[MemberGender] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DXCode] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FromDOSDate] [date] NULL,
[ThruDOSDate] [date] NULL,
[ClaimID] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProviderMasterPK] [int] NULL,
[ProviderID] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProviderName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NPI] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SuspectPK] [int] NULL,
[ScannedFlag] [int] NULL,
[CNAFlag] [int] NULL,
[ChaseID] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HCC] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CodedFlag] [int] NULL CONSTRAINT [DF__IVA_Maste__Coded__16085442] DEFAULT ((0)),
[CodedSource] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NewDOSFlag] [int] NULL CONSTRAINT [DF__IVA_Maste__NewDO__16FC787B] DEFAULT ((0)),
[FirstCoderID] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FirstCoderName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FirstCoderInitials] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FirstCoderOutCome] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FirstCoderDXCodeNotes] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FirstCoderAdditionalNotes] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SecondCoderID] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SecondCoderName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SecondCoderInitials] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SecondCoderOutCome] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SecondCoderDXCodeNotes] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SecondCoderAdditionalNotes] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ClientFileName] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[IVA_MasterHCC] ADD CONSTRAINT [UQ__IVA_Mast__FBDF78C8FD89BB20] UNIQUE NONCLUSTERED  ([RecordID]) ON [PRIMARY]
GO
