CREATE TABLE [dbo].[TempXML837]
(
[Id] [int] NOT NULL IDENTITY(1, 1),
[XMLData] [xml] NULL,
[LoadedDateTime] [datetime] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[TempXML837] ADD CONSTRAINT [PK__TempXML8__3214EC070891DA83] PRIMARY KEY CLUSTERED  ([Id]) ON [PRIMARY]
GO
