CREATE TABLE [dbo].[HealthPortChartDetail]
(
[Month Billed] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Customer] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Customer Name] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Invoice] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Invoice Date] [datetime] NULL,
[Address1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[City] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[State] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Zip] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Patient Name] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Site #] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Site Name] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Site Address] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Site City] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Site Zip] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Site State or Province] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TOTAL PAGES] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Invoice Amount] [money] NULL,
[Payments] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cancelled] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Written Off] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Open Balance] [money] NULL,
[Patient DOB] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Patient Attention To] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RevisedMemberDOB] [int] NULL,
[IncludeFlag] [int] NULL,
[MemberLastName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MemberFirstName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HICNumber] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InScopeFlag] [int] NULL,
[InvoiceMatchFlag] [int] NULL
) ON [PRIMARY]
GO
