CREATE TABLE [dbo].[Provider_Stage_Raw]
(
[NetworkID] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NetworkName] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProviderTypeDescription] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProviderTypeCode] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProviderLastName] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProviderFirstName] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PrimarySpecialty] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SpecialtyTypeCode] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NPI] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VidaProID] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address2] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ZipCode] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[County] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[City] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[State] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RecordSource] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CCI] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Phone] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fax] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CPI] [int] NULL,
[ProviderHashKey] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NetworkHashKey] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ClientHashKey] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ClientName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SeqNum] [int] NULL,
[Mobile] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[URL] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Email] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LoadDate] [datetime] NULL
) ON [PRIMARY]
GO
