CREATE TABLE [dbo].[OCR_PDF_Text]
(
[RecID] [int] NOT NULL IDENTITY(1, 1),
[FileName] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FileText] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[OCR_PDF_Text] ADD CONSTRAINT [PK_OCR_PDF_Text] PRIMARY KEY CLUSTERED  ([RecID]) ON [PRIMARY]
GO
