CREATE TABLE [dbo].[CCAI_FHN_SAMPLE_CDC]
(
[ID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Chase_Report_Link_ID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Loc_ID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Review_Date] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reviewer] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HBA_Serv_Dt] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HBA_Tst_Type] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HBA_Tst_Level] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Eye_Serv_Dt] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Eye_Check1] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Eye_Check2] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Eye_Check3] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Eye_Check4] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LDL_Serv_Dt] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LDL_Level] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LDL_Chol] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LDL_HDLC] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LDL_Triglyc] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LDL_Lipo] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LDL_Calc] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Neph_Serv_Dt] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Neph_Urine_Test] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Neph_Neph] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Neph_Renal] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Neph_Med_Attn] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Neph_AceArb] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BP_Serv_dt] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Systolic_BP] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Diastolic_BP] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gest_Excl] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Excl_Age] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Excl_Cabg] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Excl_IVD] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Excl_CHF] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Excl_Prior_MI] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Excl_Dementia] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Excl_Blindness] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Excl_Amputation] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Excl_Aneurysm] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Diab_Diag] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Valid_Data_Error] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Complete] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Exclusions_Complete] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Rec_Status] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Rec_Source] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Column 45] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Column 46] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Last_Touched] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
