CREATE TABLE [x12].[LoopOthSubInfo]
(
[OthSubInfo_RowID] [int] NULL,
[OthSubInfo_RowIDParent] [int] NULL,
[OthSubInfo_CentauriClientID] [int] NULL,
[OthSubInfo_FileLogID] [int] NULL,
[OthSubInfo_TransactionImplementationConventionReference] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OthSubInfo_TransactionControlNumber] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OthSubInfo_LoopID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OthSubInfo_PayerResponsibilitySequenceNumberCode_SBR01] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OthSubInfo_IndividualRelationshipCode_SBR02] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OthSubInfo_ReferenceIdentification_SBR03] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OthSubInfo_Name_SBR04] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OthSubInfo_InsuranceTypeCode_SBR05] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OthSubInfo_CoordinationOfBenefitsCode_SBR06] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OthSubInfo_YesNoConditionOrResponseCode_SBR07] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OthSubInfo_EmploymentStatusCode_SBR08] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OthSubInfo_ClaimFilingIndicatorCode_SBR09] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OthSubInfo_ClaimFilingIndicatorCode_OI01] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OthSubInfo_ClaimSubmissionReasonCode_OI02] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OthSubInfo_YesNoConditionOrResponseCode_OI03] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OthSubInfo_PatientSignatureSourceCode_OI04] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OthSubInfo_ProviderAgreementCode_OI05] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OthSubInfo_ReleaseofInformationCode_OI06] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OthSubInfo_Quantity_MIA01] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OthSubInfo_MonetaryAmount_MIA02] [varchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OthSubInfo_Quantity_MIA03] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OthSubInfo_MonetaryAmount_MIA04] [varchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OthSubInfo_ReferenceIdentification_MIA05] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OthSubInfo_MonetaryAmount_MIA06] [varchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OthSubInfo_MonetaryAmount_MIA07] [varchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OthSubInfo_MonetaryAmount_MIA08] [varchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OthSubInfo_MonetaryAmount_MIA09] [varchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OthSubInfo_MonetaryAmount_MIA10] [varchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OthSubInfo_MonetaryAmount_MIA11] [varchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OthSubInfo_MonetaryAmount_MIA12] [varchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OthSubInfo_MonetaryAmount_MIA13] [varchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OthSubInfo_MonetaryAmount_MIA14] [varchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OthSubInfo_Quantity_MIA15] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OthSubInfo_MonetaryAmount_MIA16] [varchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OthSubInfo_MonetaryAmount_MIA17] [varchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OthSubInfo_MonetaryAmount_MIA18] [varchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OthSubInfo_MonetaryAmount_MIA19] [varchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OthSubInfo_ReferenceIdentification_MIA20] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OthSubInfo_ReferenceIdentification_MIA21] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OthSubInfo_ReferenceIdentification_MIA22] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OthSubInfo_ReferenceIdentification_MIA23] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OthSubInfo_MonetaryAmount_MIA24] [varchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OthSubInfo_PercentageAsDecimal_MOA01] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OthSubInfo_MonetaryAmount_MOA02] [varchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OthSubInfo_ReferenceIdentification_MOA03] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OthSubInfo_ReferenceIdentification_MOA04] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OthSubInfo_ReferenceIdentification_MOA05] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OthSubInfo_ReferenceIdentification_MOA06] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OthSubInfo_ReferenceIdentification_MOA07] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OthSubInfo_MonetaryAmount_MOA08] [varchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OthSubInfo_MonetaryAmount_MOA09] [varchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
