CREATE TABLE [dbo].[MHHS_Recon_20170122]
(
[MemberNumber] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Chart ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MBR-SVC TIN] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ChaseID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[clcl_id] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LowDateOfService] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MemberFullName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MemberFirstName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MemberLastName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DOB] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DxCodesBillTypeCd] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BillingProviderName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BillingProviderNPI] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BillingProviderUniqueID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BillingProviderTIN] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BillingProviderTinName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ServiceProviderName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ServiceProviderNPI] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ServiceProviderUniqueID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ServiceProviderTIN] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ServiceProviderTinName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Claim_Category_Primary1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Claim_Category_Primary2] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Claim_Category_Primary3] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Claim_Category_Secondary1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Claim_Category_Secondary2] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Claim_Category_Secondary3] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Provider_Specialty_Desc1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Provider_Specialty_Desc2] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Provider_Specialty_Desc3] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IDCD_ID1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IDCD_ID2] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IDCD_ID3] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IDCD_ID4] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IDCD_ID5] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IDCD_ID6] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IDCD_ID7] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IDCD_ID8] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IDCD_ID9] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IDCD_ID10] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IDCD_ID11] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IDCD_ID12] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IDCD_ID13] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IDCD_ID14] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IDCD_ID15] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IDCD_ID16] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IDCD_ID17] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IDCD_ID18] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IDCD_ID19] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IDCD_ID20] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IDCD_ID21] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IDCD_ID22] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IDCD_ID23] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IDCD_ID24] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IDCD_ID25] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IDCD_ID26] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IDCD_ID27] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IDCD_ID28] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IDCD_ID29] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IDCD_ID30] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Retrieved?] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Full Account #] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Suspect_PK] [int] NULL,
[IsProcessed] [bit] NULL CONSTRAINT [DF_MHHS_Recon_20170122_IsProcessed] DEFAULT ((0)),
[Chart_File_Name] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
