IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'INTERNAL\Melody.Jones')
CREATE LOGIN [INTERNAL\Melody.Jones] FROM WINDOWS
GO
CREATE USER [INTERNAL\Melody.Jones] FOR LOGIN [INTERNAL\Melody.Jones] WITH DEFAULT_SCHEMA=[INTERNAL\Melody.Jones]
GO
GRANT CREATE SYNONYM TO [INTERNAL\Melody.Jones]
