CREATE TABLE [Internal].[EventKey]
(
[AfterDOBDays] [smallint] NOT NULL,
[AfterDOBMonths] [smallint] NOT NULL,
[Allow] [bit] NOT NULL,
[AllowEndDate] [bit] NOT NULL,
[AllowLab] [bit] NOT NULL,
[AllowSupplemental] [bit] NOT NULL CONSTRAINT [DF_EventKey_AllowSupplemental] DEFAULT ((0)),
[BatchID] [int] NOT NULL,
[BeginDate] [datetime] NULL,
[BeginDays] [smallint] NULL,
[BeginMonths] [smallint] NULL,
[BitClaimAttribsAllowed] [bigint] NOT NULL CONSTRAINT [DF_EventKey_BitAttributes] DEFAULT ((0)),
[BitClaimAttribsDenied] [bigint] NOT NULL CONSTRAINT [DF_EventKey_BitClaimAttribsDenied] DEFAULT ((0)),
[BitClaimSrcTypesAllowed] [bigint] NOT NULL CONSTRAINT [DF_EventKey_BitClaimSrcTypesAllowed] DEFAULT ((0)),
[BitClaimSrcTypesDenied] [bigint] NOT NULL CONSTRAINT [DF_EventKey_BitClaimSrcTypesDenied] DEFAULT ((0)),
[BitSpecialtiesAllowed] [bigint] NOT NULL CONSTRAINT [DF_EventKey_BitSpecialtiesAllowed] DEFAULT ((0)),
[BitSpecialtiesDenied] [bigint] NOT NULL CONSTRAINT [DF_EventKey_BitSpecialties] DEFAULT ((0)),
[ClaimTypeID] [tinyint] NOT NULL,
[Code] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CodeID] [int] NOT NULL,
[CodeTypeID] [tinyint] NULL,
[CountAllowed] [int] NULL,
[CountCriteria] [int] NULL,
[CountDenied] [int] NULL,
[DataRunID] [int] NOT NULL,
[DataSetID] [int] NOT NULL,
[DefaultDays] [int] NULL,
[DefaultValue] [decimal] (18, 6) NULL,
[Descr] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[EndDate] [datetime] NULL,
[EndDays] [smallint] NULL,
[EndMonths] [smallint] NULL,
[EventCritCodeID] [int] NOT NULL,
[EventCritDescr] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[EventCritGuid] [uniqueidentifier] NOT NULL,
[EventCritID] [int] NOT NULL,
[EventGuid] [uniqueidentifier] NOT NULL,
[EventID] [int] NOT NULL,
[EventOptGuid] [uniqueidentifier] NOT NULL,
[EventOptID] [int] NOT NULL,
[EventTypeID] [tinyint] NOT NULL,
[ExpireDate] [datetime] NULL,
[Gender] [tinyint] NULL,
[HasClaimAttribReqs] [bit] NOT NULL,
[HasCodeReqs] [bit] NOT NULL,
[HasDateReqs] [bit] NOT NULL,
[HasEnrollReqs] [bit] NOT NULL,
[HasMemberReqs] [bit] NOT NULL,
[HasProviderReqs] [bit] NOT NULL,
[IsClaimAttrib] [bit] NULL,
[MeasureSetID] [int] NOT NULL,
[OptionNbr] [tinyint] NOT NULL,
[RankOrder] [smallint] NULL,
[Reference1] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reference2] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reference3] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reference4] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RequireEndDate] [bit] NOT NULL,
[RequireEnrolled] [bit] NOT NULL,
[RequireOnly] [bit] NOT NULL,
[RequirePaid] [bit] NOT NULL,
[RequirePrimary] [bit] NOT NULL,
[Require1stRank] [bit] NOT NULL,
[SpId] [int] NOT NULL CONSTRAINT [DF_EventKey_SpId] DEFAULT (@@spid),
[Value] [decimal] (18, 6) NULL,
[ValueTypeID] [tinyint] NULL
) ON [PRIMARY]
GO
ALTER TABLE [Internal].[EventKey] ADD CONSTRAINT [PK_Internal_EventKey] PRIMARY KEY CLUSTERED  ([SpId], [CodeID], [EventID], [OptionNbr], [EventCritID], [EventCritCodeID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_Internal_EventKey_CodeIDAndRankOrder] ON [Internal].[EventKey] ([SpId], [CodeID], [RankOrder]) INCLUDE ([Allow], [BeginDate], [ClaimTypeID], [EndDate], [EventCritID], [EventID], [EventOptID], [EventTypeID], [OptionNbr]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_Internal_EventKey_HasEnrollReqs] ON [Internal].[EventKey] ([SpId], [HasEnrollReqs], [EventCritID]) INCLUDE ([RequireEnrolled]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_Internal_EventKey_HasMemberReqs] ON [Internal].[EventKey] ([SpId], [HasMemberReqs], [EventCritID]) INCLUDE ([AfterDOBDays], [AfterDOBMonths], [EndDate], [Gender]) ON [PRIMARY]
GO
