CREATE TABLE [Log].[EntityEnrollment]
(
[ActualBeginDate] [datetime] NULL,
[ActualBeginGap] [smallint] NULL,
[ActualBeginGapDays] [smallint] NULL,
[ActualEndDate] [datetime] NULL,
[ActualEndGap] [smallint] NULL,
[ActualEndGapDays] [smallint] NULL,
[ActualEnrollGroupID] [int] NULL,
[ActualFirstRow] [bit] NOT NULL,
[ActualGapDays] [smallint] NULL,
[ActualGapMaxDays] [smallint] NULL,
[ActualGaps] [smallint] NULL,
[ActualHasAnchor] [tinyint] NOT NULL,
[ActualHasPayer] [tinyint] NOT NULL,
[ActualLastRow] [bit] NOT NULL,
[AdminGapDays] [smallint] NOT NULL,
[AdminGaps] [smallint] NOT NULL,
[AnchorDate] [datetime] NULL,
[BatchID] [int] NOT NULL,
[BeginDate] [datetime] NOT NULL,
[BeginDOBDate] [datetime] NULL,
[BeginEnrollDate] [datetime] NULL,
[BenefitID] [smallint] NOT NULL,
[BitBenefits] [bigint] NOT NULL CONSTRAINT [DF_EntityEnrollment_BitBenefits] DEFAULT ((0)),
[BitProductLines] [bigint] NOT NULL CONSTRAINT [DF_EntityEnrollment_BitProductLines] DEFAULT ((0)),
[DataRunID] [int] NOT NULL,
[DataSetID] [int] NOT NULL,
[DSMemberID] [bigint] NOT NULL,
[EndDate] [datetime] NULL,
[EndDOBDate] [datetime] NULL,
[EndEnrollDate] [datetime] NULL,
[EnrollGroupID] [int] NOT NULL,
[EnrollItemID] [bigint] NOT NULL,
[EnrollSegBeginDate] [datetime] NOT NULL,
[EnrollSegEndDate] [datetime] NULL,
[EntityBaseID] [bigint] NOT NULL,
[EntityEnrollID] [bigint] NOT NULL,
[EntityEnrollSetID] [bigint] NULL,
[EntityEnrollSetLineID] [bigint] NULL,
[EntityID] [int] NOT NULL,
[GapDays] [smallint] NOT NULL,
[Gaps] [smallint] NOT NULL,
[Gender] [tinyint] NULL,
[Iteration] [tinyint] NOT NULL,
[LastSegBeginDate] [datetime] NULL,
[LastSegEndDate] [datetime] NULL,
[LogID] [bigint] NOT NULL IDENTITY(1, 1),
[LogTime] [datetime] NOT NULL CONSTRAINT [DF_EntityEnrollment_LogTime] DEFAULT (getdate()),
[LogUser] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_EntityEnrollment_LogUser] DEFAULT (suser_sname()),
[MeasEnrollID] [int] NOT NULL,
[OptionNbr] [tinyint] NOT NULL,
[OwnerID] [int] NOT NULL,
[PayerDate] [datetime] NULL,
[Priority] [smallint] NULL,
[ProductClassID] [tinyint] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [Log].[EntityEnrollment] ADD CONSTRAINT [PK_Log_EntityEnrollment] PRIMARY KEY CLUSTERED  ([LogID]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_Log_EntityEnrollment_BatchID] ON [Log].[EntityEnrollment] ([BatchID], [DataRunID], [DataSetID], [DSMemberID], [LogID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_Log_EntityEnrollment_DSMemberID] ON [Log].[EntityEnrollment] ([DSMemberID], [DataRunID], [BatchID], [DataSetID], [OwnerID]) ON [PRIMARY]
GO
