CREATE SCHEMA [CGF_REP]
AUTHORIZATION [dbo]
GO
GRANT ALTER ON SCHEMA:: [CGF_REP] TO [INTERNAL\brandon.rodman]
GO
GRANT CONTROL ON SCHEMA:: [CGF_REP] TO [INTERNAL\brandon.rodman]
GO
GRANT SELECT ON SCHEMA:: [CGF_REP] TO [INTERNAL\brandon.rodman]
GO
GRANT UPDATE ON SCHEMA:: [CGF_REP] TO [INTERNAL\brandon.rodman]
GO
GRANT EXECUTE ON SCHEMA:: [CGF_REP] TO [INTERNAL\brandon.rodman]
GO
