CREATE TABLE [dbo].[ICD9_Master]
(
[ICD-9-CM CODE] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ICD-9-CM CODE DESCRIPTION] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CATEGORY DESCRIPTION] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BODY SYSTEM] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
