CREATE TABLE [dbo].[FHN_HFS_RegistryFile_20160707]
(
[Provider_Number] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Provider_Name] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Provider_StreetAddress] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Provider_StreetAddress2] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Provider_City] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Provider_State] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Provider_ZipCode] [varchar] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Provider_LicenseNum] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Provider_Type] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Enrollent_Status] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Maternal-Child_Provider] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CategoryofService1] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CategoryofService2] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CategoryofService3] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CategoryofService4] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CategoryofService5] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CategoryofService6] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CategoryofService7] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CategoryofService8] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CategoryofService9] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CategoryofService10] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CategoryofService11] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CategoryofService12] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CategoryofService13] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CategoryofService14] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CategoryofService15] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CategoryofService16] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CategoryofService17] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CategoryofService18] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CategoryofService19] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CategoryofService20] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CategoryofService21] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CategoryofService22] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CategoryofService23] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CategoryofService24] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CategoryofService25] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EligBeginForCategoryofService] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EligEndForCategoryofService] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Provider_FaxNumber] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Provider_MedicarePartANumber] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Provider_DEA_Num] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UniquePhysicianID] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProviderAMAorADANum] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EnrollmentBeginDate] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EnrollmentEndDate] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NPI] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Filler] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Stuff] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MoreStuff] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RecID] [int] NOT NULL IDENTITY(1, 1)
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[FHN_HFS_RegistryFile_20160707] ADD CONSTRAINT [PK_FHN_HFS_RegistryFile_20160707] PRIMARY KEY CLUSTERED  ([RecID]) ON [PRIMARY]
GO
