CREATE TABLE [dbo].[WellCare_2ndChaseList]
(
[Chart ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Contract Number] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Altegra LID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Altegra Project] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Member ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HICN] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[First Name] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Last Name] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gender] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DOB] [datetime] NULL,
[LOB] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Prov ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PROV LAST] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PROV FIRST] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ADDRESS] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ADDRESS 2] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CITY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STATE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ZIP] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PHONE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FAX] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GROUP] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PROJECT] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CHART STATUS] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COMMENT] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[For updates only] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Crosswalk] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Altegra] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Centauri] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CIOX] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LORI UPDATES] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SYS_INFO_UPDATE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SYS_Member_ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SYS_HICN] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SYS_First_Name] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SYS_LAST_Name] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SYS_Gender] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SYS_DOB] [datetime] NULL,
[SYS_PROVIDER_ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SYS_SEQ_PROV_ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SYS_NPI] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IncludeFlag] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ExcludeReason] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NewAddress] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NewZip] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProviderMaster_PK] [int] NULL,
[ProviderOffice_PK] [int] NULL,
[Member_PK] [int] NULL,
[Provider_PK] [int] NULL,
[ExclusionTab1] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ExclusionTab2] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CentauriProviderID] [bigint] NULL,
[H_Provider_RK] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AdvanceAddress] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AdvanceZIP] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
