CREATE TABLE [dbo].[161208 WellCare Top 100 Locations_LYDIA]
(
[LocationID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Chase List 1] [float] NULL,
[Chase List 2] [float] NULL,
[Chase List 3] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[City] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[state] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ZipCode] [float] NULL,
[county] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ContactNumber] [float] NULL,
[ContactPerson] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FaxNumber] [float] NULL,
[GroupName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProviderOffice_CHS] [float] NULL,
[ProviderCount] [bigint] NULL,
[RemainingChaseCount] [float] NULL,
[TotalCharts] [float] NULL,
[Sch_Start] [datetime] NULL,
[Sch_End] [datetime] NULL,
[ScheduleType] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CHS Assigned] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Category] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Next Steps] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F24] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[T100 CL01] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[T100 CL02] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[T100 NY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[T100 FL] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[20+ FL] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F30] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
