CREATE TABLE [dbo].[MH_MA_RedTab_20161116]
(
[CLAIM_ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PROC_CD_Only] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MODIF] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[POS_DESC] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MemberNumber] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FULL_NAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RELAT_DESC] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BIRTH_DT] [datetime] NULL,
[GRP_NAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PRODUCTLINE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PROD_DESC] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LO_SERV_DT] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PD_DT] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PAYEE_PROV_KEY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PAYEE_NATL_PROV_ID] [float] NULL,
[PAYEE_PROV_NAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PAYEE_PRIM_ADDR_LN_1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PAYEE_PRIM_ADDR_LN_2] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PAYEE_PRIM_CITY_NAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PAYEE_PRIM_STATE_CD] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PAYEE_PRIM_POSTAL] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PAYEE_PRIM_PHONE_NUM] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SERV_PROV_KEY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SVC_NATL_PROV_ID] [float] NULL,
[SVC_PROV_NAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SVC_PRIM_ADDR_LN_1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SVC_PRIM_ADDR_LN_2] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SVC_PRIM_CITY_NAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SVC_PRIM_STATE_CD] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SVC_PRIM_POSTAL] [float] NULL,
[SVC_PRIM_PHONE_NUM] [float] NULL,
[SVC_PRIM_SPEC_DESC] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CLMF_PRPR_ID_FAC] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PRPR_NAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MCTN_ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PRAD_PHONE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PRAD_ADDR1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PRAD_ADDR2] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PRAD_CITY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PRAD_STATE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PRAD_ZIP] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CleanAddress] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CleanZip] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AdvancePhone] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NewChaseID] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NewAddress] [bit] NULL,
[IsScheduled] [bit] NULL,
[IsScanned] [bit] NULL,
[OfficeStatus] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ChaseID] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NewProvider] [bit] NULL,
[Member_PK] [int] NULL,
[DOS_FromDate] [date] NULL,
[DOS_ThruDate] [date] NULL,
[CentauriProviderID] [int] NULL
) ON [PRIMARY]
GO
