CREATE TABLE [dbo].[MH_IVA_13FinalCharts]
(
[member ID and tax ID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Client_ID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Member_ID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[meme_hicn] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Member_Last_Name] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Member_First_Name] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Member_DOB] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Member_Gender] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Provider_ID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Provider_NPI] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Provider_Last_Name] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Provider_First_Name] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Provider_Specialty] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Provider_Office_Address] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Provider_office_City] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Provider_Office_State] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Provider_Office_Zip] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CLAIM_ID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Diagnosis_Code] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ICD9_ICD10_Ind] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DOS_FromDate] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Dos_ToDate] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PRICING_ID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SVC_TAX_ID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MHFacilityFlag] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NetworkIndicator] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[clhp_med_rec_no] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SVC_FIRST_NAME] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SVC_LAST_NAME] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SVC_PRIM_ADDR_LN_1] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SVC_PRIM_ADDR_LN_2] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SVC_PRIM_ADDR_LN_3] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SVC_PRIM_CITY_NAME] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SVC_PRIM_STATE_CD] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SVC_PRIM_POSTAL] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SVC_PRIM_PHONE_NUM] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Column 36] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
