CREATE TABLE [dbo].[WellcareAltegra2ChasesText]
(
[Project] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CHASE ID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Chart Status ] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HICN] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MemberLastName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MemberFirstName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MemberDOB] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GroupName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AddressLine1] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AddressLine2] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[City] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[State] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Zipcode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Phone] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fax] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ClientPrvID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProviderLastName] [varchar] (75) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProviderFirstName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProviderType] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[POS] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NewAddress] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NewZip] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AdvanceAddress] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AdvanceZIP] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AddressUsed] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ZIPUsed] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CentauriProviderID] [bigint] NULL,
[H_Provider_RK] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProviderMaster_PK] [int] NULL,
[ProviderOffice_PK] [int] NULL,
[Member_PK] [int] NULL,
[Provider_PK] [int] NULL,
[ExistingProvider] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ExistingProvider0] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Existing] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AdvancePhone] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AdvanceFax] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LOB] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
