CREATE TABLE [dbo].[FHN_HEDISCareCollaborationData]
(
[MEASURE_DESC] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MEM_NBR] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DENOM] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SAMPLE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SAMPLE_NUMBER] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MEM_LNAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MEM_FNAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MEM_DOB] [datetime] NULL,
[MEM_GENDER] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MEM_ADDR1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MEM_ADDR2] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MEM_CITY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MEM_STATE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MEM_ZIP] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MEM_PHONE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GUARD_LNAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GUARD_FNAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GUARD_ADDR1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GUARD_ADDR2] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GUARD_CITY] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GUARD_STATE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GUARD_ZIP] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PCP ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PCP HFS Num] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PCP Name] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PHO ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PHO Network] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PCP Months] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NUM DOS] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Lab Result] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PCP Closed Gap] [float] NULL,
[c-Gap_PCP ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[c-Gap_PCP HFS Num] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[c-Gap_PCP Name] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[c-Gap_PHO ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[c-Gap_PHO Network] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NUM_1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NUM_2] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Systolic BP] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Diastolic BP] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PMT] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RPT_RunDate] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FullMeasureDescription] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DisplayName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
