CREATE TABLE [dbo].[ICD10_Master]
(
[ICD-10-CM CODE] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ICD-10-CM CODE DESCRIPTION] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CHRONIC INDICATOR] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BODY SYSTEM] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
