CREATE SCHEMA [stage]
AUTHORIZATION [dbo]
GO
GRANT ALTER ON SCHEMA:: [stage] TO [INTERNAL\Paul.Johnson]
GO
GRANT CONTROL ON SCHEMA:: [stage] TO [INTERNAL\Paul.Johnson]
GO
GRANT VIEW DEFINITION ON SCHEMA:: [stage] TO [INTERNAL\Paul.Johnson]
GO
GRANT SELECT ON SCHEMA:: [stage] TO [INTERNAL\Paul.Johnson]
GO
GRANT INSERT ON SCHEMA:: [stage] TO [INTERNAL\Paul.Johnson]
GO
GRANT DELETE ON SCHEMA:: [stage] TO [INTERNAL\Paul.Johnson]
GO
GRANT UPDATE ON SCHEMA:: [stage] TO [INTERNAL\Paul.Johnson]
GO
GRANT EXECUTE ON SCHEMA:: [stage] TO [INTERNAL\Paul.Johnson]
GO
