CREATE TABLE [Test100].[Member]
(
[ProductID] [int] NULL,
[MemberID] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UniversalMemberID] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MedicareID] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MedicaidID] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSN] [char] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Confidential] [int] NULL,
[NameLast] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NameFirst] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NameMiddleInitial] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NameSuffix] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DOB] [datetime] NULL,
[DOD] [int] NULL,
[Gender] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Race] [char] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ContactLastName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ContactFirstName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ContactMiddleInitial] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ContactGender] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ContactAddress1] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ContactAddress2] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ContactCity] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ContactCounty] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ContactState] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ContactZipCode] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ContactTelephone] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Language] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AltLanguage1] [int] NULL,
[AltLanguage2] [int] NULL,
[Hispanic] [int] NULL,
[Interpreter] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LanguageSource] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WrittenLanguage] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WrittenLanguageSource] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OtherLanguage] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OtherLanguageSource] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RaceSource] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EthnicitySource] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MemberCustom1] [int] NULL,
[MemberCustom2] [int] NULL,
[MemberCustom3] [int] NULL,
[MemberCustom4] [int] NULL,
[AsOfDate] [datetime] NULL,
[SourceID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
