CREATE SCHEMA [RDSM]
AUTHORIZATION [dbo]
GO
GRANT INSERT ON SCHEMA:: [RDSM] TO [SSRS_REPORTING]
GO
GRANT DELETE ON SCHEMA:: [RDSM] TO [SSRS_REPORTING]
GO
GRANT UPDATE ON SCHEMA:: [RDSM] TO [SSRS_REPORTING]
GO
