CREATE TABLE [CGF].[ResultsByMember_backup20160825_0804]
(
[Client] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BeginSeedDate] [datetime] NOT NULL,
[EndSeedDate] [datetime] NOT NULL,
[MeasureSet] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CustomerMemberID] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IHDSMemberID] [int] NULL,
[Age] [tinyint] NULL,
[AgeMonths] [smallint] NULL,
[Gender] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DataRunGuid] [uniqueidentifier] NOT NULL,
[DataSetGuid] [uniqueidentifier] NOT NULL,
[DataSourceGuid] [uniqueidentifier] NOT NULL,
[ExclusionType] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ExclusionTypeGuid] [uniqueidentifier] NULL,
[IsDenominator] [int] NULL,
[IsExclusion] [int] NULL,
[IsNumerator] [int] NULL,
[Measure] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[MeasureDesc] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[MeasureXrefGuid] [uniqueidentifier] NOT NULL,
[Metric] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[MetricDesc] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[MetricXrefGuid] [uniqueidentifier] NOT NULL,
[MeasureMetricDesc] [varchar] (145) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ResultRowGuid] [uniqueidentifier] NOT NULL,
[ResultType] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ResultTypeGuid] [uniqueidentifier] NOT NULL,
[MemberID] [int] NOT NULL,
[EligibilityID] [int] NULL,
[MemberProviderID] [int] NULL,
[ProviderID] [int] NULL,
[ProviderMedicalGroupID] [int] NULL,
[PopulationDesc] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EnrollmentGroupNum] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EnrollmentGroupDesc] [varchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
