CREATE TABLE [dbo].[Provider]
(
[ProviderID] [int] NOT NULL IDENTITY(1, 1),
[BoardCertification1] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BoardCertification2] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Client] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DataSource] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateOfBirth] [datetime] NULL,
[DateRowCreated] [datetime] NULL,
[DateValidBegin] [datetime] NULL,
[DateValidEnd] [datetime] NULL,
[DEANumber] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EIN] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gender] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HashValue] [binary] (16) NULL,
[HedisMeasureID] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ihds_prov_id] [int] NULL,
[InstanceID] [int] NULL,
[IsUpdated] [bit] NULL,
[LicenseNumber] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MedicaidID] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NameFirst] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NameLast] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NameMiddleInitial] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NamePrefix] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NameSuffix] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NameTitle] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NetworkID] [int] NULL,
[NPI] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProviderType] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RowID] [int] NULL,
[SpecialtyCode1] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SpecialtyCode2] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSN] [char] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TaxID] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UPIN] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProviderPrescribingPrivFlag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CDProviderFlag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DentistFlag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EyeCareFlag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MentalHealthFlag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NephrologistFlag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NursePractFlag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OBGynFlag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PCPFlag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PhysicianAsstFlag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProviderPaidInpatientRateFlag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProviderPaidOutpatientRateFlag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerProviderID] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NameShort] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SpecialtyCode1Desc] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SpecialtyCode2Desc] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProviderTypeDesc] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ClinicalPharmacistFlag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AnesthesiologistFlag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProviderFullName] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AmbulanceFlag] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DurableMedEquipmentFlag] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HospitalFlag] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RegisteredNurseFlag] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SkilledNursingFacFlag] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SurgeonFlag] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TaxonomyCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerProviderID2] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SourceSystem] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NursMidWife] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FamPract] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DMEFLag] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SNFFlag] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Provider] ADD CONSTRAINT [pk_Provider] PRIMARY KEY CLUSTERED  ([ProviderID]) ON [PRIMARY]
GO
CREATE STATISTICS [sp_pk_Provider] ON [dbo].[Provider] ([ProviderID])
GO
