CREATE TABLE [dbo].[ClarityIDCardLog]
(
[RowID] [int] NOT NULL IDENTITY(1, 1),
[RunDate] [datetime] NULL,
[SentToClarity] [int] NOT NULL,
[MemberNumber] [varchar] (28) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FullName] [varchar] (97) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LineOfBusiness] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[GroupNo] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MRN] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PCPNo] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PCPName] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PCPPhone] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Address1] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address2] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[City] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[State] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Zip] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HICN] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PlanCode] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StartDate] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AuxDate] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Language] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HouseholdNo] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SubscriberName] [varchar] (95) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Age] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DOB] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Communication] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DateIssued] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LISCopayCategory] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[LISLevel] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ActionCode] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SystemID] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ClinicName] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ClinicAddress] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ClinicPhone] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ClinicLongName] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[RelationshipCode] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EnrollID] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
