CREATE TABLE [dbo].[PharmacyClaim]
(
[PharmacyClaimID] [int] NOT NULL IDENTITY(1, 1),
[ClaimNumber] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Client] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CostCopay] [money] NULL,
[CostDispensingFee] [money] NULL,
[CostIngredient] [money] NULL,
[CostPatientPay] [money] NULL,
[CostPlanPay] [money] NULL,
[CostSalesTax] [money] NULL,
[CostTotal] [money] NULL,
[DataSource] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateDispensed] [datetime] NULL,
[DateOrdered] [datetime] NULL,
[DatePaid] [datetime] NULL,
[DaysSupply] [smallint] NULL,
[DrugDescription] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DrugDosageForm] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DrugGenericName] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GPINumber] [varchar] (14) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HashValue] [binary] (16) NULL,
[HealthPlanID] [int] NULL,
[ihds_member_id] [int] NULL,
[IsFormulary] [bit] NULL,
[IsUpdated] [bit] NULL,
[LoadInstanceFileID] [int] NULL,
[RowFileID] [bigint] NULL,
[MemberID] [int] NULL,
[NDC] [varchar] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PharmacyID] [int] NULL,
[Quantity] [decimal] (11, 3) NULL,
[RowID] [int] NULL,
[PrescribingProviderID] [int] NULL,
[ihds_prov_id_prescribing] [int] NULL,
[RefillNumber] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DispenseAsWrittenCode] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IsMailOrder] [bit] NULL,
[COBCode] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CompoundCode] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CostDeductibleAmt] [money] NULL,
[PhysicianNPI] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DrugName] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IsGeneric] [bit] NULL,
[CustomerGroupNumber] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PharmacyTaxID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PhysicianFirstName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PhysicianLastName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SubmittedPrescriberID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CostOtherPayerAmt] [money] NULL,
[Headquartercode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SourceSystem] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RejectReasonDesc] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ClaimStatusCode] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MedicareCode] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RxNumber] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PharmacyClaim] ADD CONSTRAINT [pk_PharmacyClaim] PRIMARY KEY CLUSTERED  ([PharmacyClaimID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [idx6] ON [dbo].[PharmacyClaim] ([MemberID]) ON [PRIMARY]
GO
CREATE STATISTICS [sp_pk_PharmacyClaim] ON [dbo].[PharmacyClaim] ([PharmacyClaimID])
GO
