CREATE TABLE [dbo].[BrXref_ClaimLineItem]
(
[BusRuleDtlID] [int] NOT NULL IDENTITY(1, 1),
[ClaimLineItemID] [bigint] NULL,
[ClaimCat1Name] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ClaimCat2Name] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ClaimCat3Name] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ClaimLineNetAmtPerDay] [numeric] (11, 2) NULL,
[ClaimPaidFlag] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DHMPPrevIPDischargeWithin30Days] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EDVisit] [int] NULL,
[FirstACSAdmitFlag] [bit] NULL,
[FirstBedDayFlag] [int] NULL,
[HighTechScanBilledAmt] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HighTechScanCategory] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HighTechScanFlag] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HighTechScanNetAmt] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IPAdmit] [int] NULL,
[IPAdmitBilledAmt] [numeric] (11, 2) NULL,
[IPAdmitNetAmt] [numeric] (11, 2) NULL,
[IPDays] [int] NULL,
[IPDaysBilledAmt] [numeric] (11, 2) NULL,
[IPDaysNetAmt] [numeric] (11, 2) NULL,
[IPDischarge] [int] NULL,
[IPMaternityClaimFlag] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LastBedDayFlag] [int] NULL,
[MonthlyStatementFlag] [bit] NULL,
[MthStmtCheckDate] [datetime] NULL,
[NextIPAdmitWithin07Days] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NextIPAdmitWithin15Days] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NextIPAdmitWithin30Days] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NextIPAdmitWithin45Days] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NextIPAdmitWithin90Days] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NextOfficeVisitWithin07Days] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NextOfficeVisitWithin15Days] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NextOfficeVisitWithin30Days] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NextOfficeVisitWithin45Days] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NextOfficeVisitWithin90Days] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NonDHMPPrevIPDischargeWithin30Days] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OfficeVisitBilledAmt] [numeric] (11, 2) NULL,
[OfficeVisitNetAmt] [numeric] (11, 2) NULL,
[OfficeVisits] [int] NULL,
[PrevIPDischargeWithin07Days] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PrevIPDischargeWithin15Days] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PrevIPDischargeWithin30Days] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PrevIPDischargeWithin45Days] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PrevIPDischargeWithin90Days] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SNFAdmit] [int] NULL,
[SNFAdmitBilledAmt] [numeric] (11, 2) NULL,
[SNFAdmitNetAmt] [numeric] (11, 2) NULL,
[SNFDays] [int] NULL,
[SNFDaysBilledAmt] [numeric] (11, 2) NULL,
[SNFDaysNetAmt] [numeric] (11, 2) NULL,
[SNFFirstBedDayFlag] [int] NULL,
[SNFLastBedDayFlag] [int] NULL,
[TotalIPAdmitNetAmt] [numeric] (11, 2) NULL,
[UrgentCareVisit] [int] NULL,
[DiagTestCategory] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SAPCheckNo] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Top10ProcedureFlag] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AmountAllowedBenefitWithCCF] [numeric] (18, 0) NULL,
[AmountAllowedProviderWithCCF] [numeric] (18, 0) NULL,
[AmountNetPaymentWithCCF] [numeric] (18, 0) NULL,
[AmountTotalChargeWithCCF] [numeric] (18, 0) NULL,
[AmountTotalExpense] [numeric] (18, 0) NULL,
[CompletionFactor] [numeric] (18, 0) NULL,
[DateSAPCheck] [datetime] NULL,
[NetAmtPerDay] [numeric] (18, 0) NULL,
[OfficeVisit] [int] NULL,
[OtherVisit] [int] NULL,
[OutpatientHospVisit] [int] NULL,
[UnitsWithCCF] [numeric] (18, 0) NULL
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [idxClaimLineItem] ON [dbo].[BrXref_ClaimLineItem] ([ClaimLineItemID]) ON [NDX]
GO
CREATE STATISTICS [sp_idxClaimLineItem] ON [dbo].[BrXref_ClaimLineItem] ([ClaimLineItemID])
GO
