CREATE TABLE [dbo].[Claim]
(
[ClaimID] [int] NOT NULL IDENTITY(1, 1),
[LoadInstanceFileID] [int] NULL,
[RowFileID] [bigint] NULL,
[BillType] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ClaimType] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Client] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DataSource] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateRowCreated] [datetime] NULL,
[DateServiceBegin] [datetime] NULL,
[DateServiceEnd] [datetime] NULL,
[DiagnosisCode1] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DiagnosisCode2] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DiagnosisCode3] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DiagnosisCode4] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DiagnosisCode5] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DiagnosisCode6] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DiagnosisCode7] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DiagnosisCode8] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DiagnosisCode9] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DiagnosisCode10] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DiagnosisRelatedGroup] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HashValue] [binary] (16) NULL,
[HealthPlanID] [int] NULL,
[ihds_member_id] [int] NULL,
[ihds_prov_id_admitting] [int] NULL,
[ihds_prov_id_attending] [int] NULL,
[ihds_prov_id_pcp] [int] NULL,
[ihds_prov_id_referring] [int] NULL,
[ihds_prov_id_servicing] [int] NULL,
[IsUpdated] [bit] NULL,
[MemberID] [int] NULL,
[PatientStatus] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerClaimID] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PlaceOfService] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RowID] [int] NULL,
[ServicingProvID] [int] NULL,
[SurgicalProcedure1] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SurgicalProcedure2] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SurgicalProcedure3] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SurgicalProcedure4] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SurgicalProcedure5] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SurgicalProcedure6] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ClaimStatus] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DiagnosisCode11] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DiagnosisCode12] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DiagnosisCode13] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DiagnosisCode14] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DiagnosisCode15] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DiagnosisCode16] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DiagnosisCode17] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DiagnosisCode18] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DiagnosisCode19] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DiagnosisCode20] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PCPID] [int] NULL,
[PCPSpecialty] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PCPSpecialtyDesc] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PCPType] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PCPTypeDesc] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PCPIPA] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PCPMedicalGroupID] [int] NULL,
[AdmittingProvID] [int] NULL,
[AdmittingProvType] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AdmittingProvTypeDesc] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AdmittingProvSpecialty] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AdmittingProvSpecialtyDesc] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AdmittingProvIPA] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AdmittingProvParFlag] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AdmittingProvMedicalGroupID] [int] NULL,
[AttendingProvID] [int] NULL,
[AttendingProvType] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AttendingProvTypeDesc] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AttendingProvSpecialty] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AttendingProvSpecialtyDesc] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AttendingProvIPA] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AttendingProvParFlag] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AttendingProvMedicalGroupID] [int] NULL,
[ServicingProvType] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ServicingProvTypeDesc] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ServicingProvSpecialty] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ServicingProvSpecialtyDesc] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ServicingProvIPA] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ServicingProvParFlag] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ServicingProvMedicalGroupID] [int] NULL,
[ReferringProvID] [int] NULL,
[ReferringProvType] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReferringProvTypeDesc] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReferringProvSpecialty] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReferringProvSpecialtyDesc] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReferringProvIPA] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReferringProvParFlag] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReferringProvMedicalGroupID] [int] NULL,
[AdmitType] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LineOfBusiness] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerVendorID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VendorID] [int] NULL,
[MemberAge] [numeric] (10, 1) NULL,
[MemberGroupID] [int] NULL,
[AdmitSource] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ClaimSubmissionMethod] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ClaimCreateDate] [datetime] NULL,
[ClaimUpdateDate] [datetime] NULL,
[ClaimUpdateUser] [varchar] (120) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ClaimCreateUser] [varchar] (120) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PlanCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AdmittingDiagnosisCode] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateClaimReceived] [datetime] NULL,
[ReportedClaimNumber] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerPOA1] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerPOA2] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerPOA3] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerPOA4] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerPOA5] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerPOA6] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerPOA7] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerPOA8] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerEligibilityID] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ServicingProvNPI] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerPOA9] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ServicingProvTaxonomyCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MemberGender] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PatientControlNo] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerBenefitPlanDesc] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerSponsor] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReimburseMemberFlag] [bit] NULL,
[SourceSystem] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerEnrollID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerPlanID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerEligibleOrigID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerCarrerid] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerInsuredID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PlanDescription] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PlanType] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EligibleOrganizationName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EligibleOrganizationType] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CarrierName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CarrierType] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerAuthNumber] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerSecondaryAuthNumber] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ExternalCauseInjuryDiag1] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ExternalCauseInjuryDiag2] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ExternalCauseInjuryDiag3] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ExternalCauseInjuryDiag4] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ExternalCauseInjuryDiag5] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ExternalCauseInjuryDiag6] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ExternalCauseInjuryDiag7] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ExternalCauseInjuryDiag8] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ExternalCauseInjuryDiag9] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ExternalCauseInjuryDiag10] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ExternalCauseInjuryDiag11] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ExternalCauseInjuryDiag12] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SurgicalProcedure1Date] [datetime] NULL,
[SurgicalProcedure2Date] [datetime] NULL,
[SurgicalProcedure3Date] [datetime] NULL,
[SurgicalProcedure4Date] [datetime] NULL,
[SurgicalProcedure5Date] [datetime] NULL,
[SurgicalProcedure6Date] [datetime] NULL,
[DateAdmitted] [datetime] NULL,
[AdmitHour] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerPOA10] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerPOA11] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerPOA12] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerVendorName] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateDischarged] [datetime] NULL,
[DischargeHour] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EligibilityID] [int] NULL,
[ExternalCauseInjuryDiag13] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TotalAmountBilledClaim] [numeric] (11, 2) NULL,
[AdmitSourceDesc] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AdmitTypeDesc] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AmountClaimHeaderBilled] [numeric] (18, 0) NULL,
[AttendingProviderID] [int] NULL,
[BenefitPlanId] [int] NULL,
[BillingProviderID] [int] NULL,
[BusinessUnit] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ClaimDisallowReason] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ClaimTypeIndicator] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustermerUserID2] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerAuthID] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerBatch] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerEligibleOrgID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerHIDUD1] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerMemberID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerPCPIPA] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerPCPIPADescription] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerPCPIPAName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerPOA13] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerPOA14] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerPOA15] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerPOA16] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerPOA17] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerPOA18] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerPOA19] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerPOA20] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerProviderType] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerProvRefNum] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerSecondaryAuthID] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerServicingProvID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerServicingProvIPA] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerSponsorID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateClaimPaid] [datetime] NULL,
[DateCleanClaim] [datetime] NULL,
[DateCreated] [datetime] NULL,
[DatePrime] [datetime] NULL,
[DateThru] [datetime] NULL,
[DateUpdated] [datetime] NULL,
[DateValidBegin] [datetime] NULL,
[DateValidEnd] [datetime] NULL,
[DCN] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DiagnosisCode1Desc] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DiagnosisCode2Desc] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DiagnosisCode3Desc] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DiagnosisCode4Desc] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DiagnosisCode5Desc] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DiagnosisCode6Desc] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DiagnosisCode7Desc] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DiagnosisCode8Desc] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DiagnosisCode9Desc] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DiagnosisRelatedGroupType] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DischargeStatus] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EmployerDivision] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EmployerGroup] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HedisMeasureID] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ihds_prov_id_billing] [int] NULL,
[ihds_prov_id_med_group] [int] NULL,
[ihds_prov_id_Operating] [int] NULL,
[ihds_prov_id_Other1] [int] NULL,
[ihds_prov_id_Other2] [int] NULL,
[ihds_prov_id_vendor] [int] NULL,
[InpatientOutpatientIndicator] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LineOfBusinessID] [int] NULL,
[LoadInstanceID] [int] NULL,
[MedicarePaidIndicator] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OperatingProvID] [int] NULL,
[OperatingProvIPA] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OperatingProvMedicalGroupID] [int] NULL,
[OperatingProvParFlag] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OperatingProvSpecialty] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OperatingProvSpecialtyDesc] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OperatingProvType] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OperatingProvTypeDesc] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Other1ProvID] [int] NULL,
[Other1ProvSpecialty] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Other1ProvSpecialtyDesc] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Other1ProvType] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Other1ProvTypeDesc] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Other2ProvID] [int] NULL,
[Other2ProvSpecialty] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Other2ProvSpecialtyDesc] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Other2ProvType] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Other2ProvTypeDesc] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PayerClaimID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PayerClaimIDSuffix] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PayerID] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PCPProviderID] [int] NULL,
[PlaceOfServiceDesc] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProgramID] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PRVDiag1] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PRVDiag10] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PRVDiag2] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PRVDiag3] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PRVDiag4] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PRVDiag5] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PRVDiag6] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PRVDiag7] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PRVDiag8] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PRVDiag9] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RecCreateID] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RecordType] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RecUpdateID] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReferringProviderID] [int] NULL,
[ServicingProviderID] [int] NULL,
[SupplementalDataCategory] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SupplementalDataFlag] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SurgicalProcedure1Desc] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SurgicalProcedure2Desc] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SurgicalProcedure3Desc] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SurgicalProcedure4Desc] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SurgicalProcedure5Desc] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SurgicalProcedure6Desc] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Claim] ADD CONSTRAINT [pk_Claim] PRIMARY KEY CLUSTERED  ([ClaimID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [idxClaimMemberID] ON [dbo].[Claim] ([MemberID]) ON [NDX]
GO
CREATE NONCLUSTERED INDEX [idxClaimServicingProvID] ON [dbo].[Claim] ([ServicingProvID]) ON [NDX]
GO
CREATE STATISTICS [sp_pk_Claim] ON [dbo].[Claim] ([ClaimID])
GO
CREATE STATISTICS [sp_idxClaimMemberID] ON [dbo].[Claim] ([MemberID])
GO
CREATE STATISTICS [sp_idxClaimServicingProvID] ON [dbo].[Claim] ([ServicingProvID])
GO
