CREATE TABLE [dbo].[AuthHeader]
(
[AuthHeaderID] [int] NOT NULL IDENTITY(1, 1),
[Client] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DataSource] [varchar] (17) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CustomerAuthNumber] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerSecondaryAuthNumber] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AuthorizationUpdateDate] [datetime] NULL,
[AuthorizationUpdateUsr] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AuthorizationInsertDate] [datetime] NULL,
[AuthorizaitonInsertUsr] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Review_Type] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reviewer] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PrimeDate] [datetime] NULL,
[thruDate] [datetime] NULL,
[SecondaryAuthFlag] [varchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CertificationType] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CertificationTypeDesc] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[OverturnDays] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Edc] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EstSurgeryDate] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PriorDayAdmit] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DaysVisitsIndicator] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DaysVisitsIndicatorDesc] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[OutcomeCode] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OutcomeDesc] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ImpactCode] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ImpactDesc] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DispositionCode] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DispositionDesc] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CaseReferralHour] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CaseReferralReturnHour] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AdmitTypeCode] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AdmitTypeDesc] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[AdmitReasonCode] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AdmitReasonDesc] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TplCode] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TplDescription_1] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TplDescription_2] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DischargeDiagnosis] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FirstReviewDate] [datetime] NULL,
[NextReviewDate] [datetime] NULL,
[LateNotification] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ClosedReasonCode] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DeniedReasonCode] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DeniedReasonCodeDesc] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DeniedDate] [datetime] NULL,
[HoldReasonCode] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HoldDate] [datetime] NULL,
[UserDefined_1] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[AuthLinkedToClaimFlag] [varchar] (19) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PlaceOfService] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SourceSystem] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AuthHeader] ADD CONSTRAINT [pk_Auth] PRIMARY KEY CLUSTERED  ([AuthHeaderID]) ON [PRIMARY]
GO
CREATE STATISTICS [sp_pk_AuthHeader] ON [dbo].[AuthHeader] ([AuthHeaderID])
GO
