CREATE TABLE [dbo].[ClaimLineItem]
(
[ClaimLineItemID] [int] NOT NULL IDENTITY(1, 1),
[LoadInstanceFileID] [int] NULL,
[RowFileID] [bigint] NULL,
[AmountBilled] [money] NULL,
[AmountCoinsurance] [money] NULL,
[AmountCopay] [money] NULL,
[AmountDeductible] [money] NULL,
[AmountDisallowed] [money] NULL,
[AmountNetPayment] [money] NULL,
[AmountTotalCharge] [money] NULL,
[ClaimDisallowReason] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ClaimID] [int] NULL,
[Client] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DataSource] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DatePaid] [datetime] NULL,
[DateRowCreated] [datetime] NULL,
[DateServiceBegin] [datetime] NULL,
[DateServiceEnd] [datetime] NULL,
[DiagnosisCode] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HashValue] [binary] (16) NULL,
[LineItemNumber] [smallint] NULL,
[CustomerClaimID] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerClaimLineID] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RevenueCode] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Units] [numeric] (10, 2) NULL,
[IsUpdated] [bit] NULL,
[RowID] [int] NULL,
[CPTProcedureCodeModifier1] [char] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CPTProcedureCodeModifier2] [char] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CPTProcedureCodeModifier3] [char] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HCPCSProcedureCode] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CPTProcedureCode] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DatePosted] [datetime] NULL,
[DateCheckProcessed] [datetime] NULL,
[ClaimLineCreateDate] [datetime] NULL,
[ClaimLineUpdateDate] [datetime] NULL,
[ClaimLineUpdateUser] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ClaimLineCreateUser] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ClaimStatus] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProcessingStatus] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AdjudicationMethod] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerProcedureCode] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerAlternateProcedureCode] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CPTProcedureCodeModifier4] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AmountWithhold] [numeric] (11, 2) NULL,
[AdjustmentReason] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AmountAllowed] [numeric] (11, 2) NULL,
[NotCoveredReason] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CompanyCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AmountInterest] [money] NULL,
[AmountOtherCarrier] [money] NULL,
[AmountPaidNet] [money] NULL,
[AmountPenalty] [money] NULL,
[AmountPatientResp] [money] NULL,
[ClaimAllowReasonCode] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ClaimCopayReasonCode] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ClaimCoinsuranceReasonCode] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ClaimWithholdReasonCode] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ClaimDeductibleReasonCode] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ClaimNotCoveredReasonCode] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ClaimOtherCarrierReasonCode] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ClaimAllowReasonDesc] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ClaimCopayReasonDesc] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ClaimCoinsuranceReasonDesc] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ClaimWithholdReasonDesc] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ClaimDeductibleReasonDesc] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ClaimNotCoveredReasonDesc] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ClaimOtherCarrierReasonDesc] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SourceSystem] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CapitatedFlag] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerLineNumber] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerSubLineCode] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[XcelysMedicalDefinition] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[XcelysMedicalDefinitionDesc] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HCPCSApc] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NDCCode] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AccountingFund] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AdjustReason] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AmountAllowedBenefit] [money] NULL,
[AmountAllowedProvider] [money] NULL,
[AmountAllowedReason] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AmountBenefit] [money] NULL,
[AmountCOB] [money] NULL,
[AmountCOBSavings] [money] NULL,
[AmountCoinsuranceReason] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AmountCopayReason] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AmountDeniedBenefit] [money] NULL,
[AmountDeniedProvider] [money] NULL,
[AmountDiscount] [money] NULL,
[AmountFeeForService] [money] NULL,
[AmountGrossPayment] [money] NULL,
[AmountMedicarePaid] [money] NULL,
[AmountNotCovered] [numeric] (18, 0) NULL,
[AmountNotCoveredReason] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AmountNotCoveredReasonDesc] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AmountSequestration] [money] NULL,
[AmountWithold] [money] NULL,
[APTransactionID] [int] NULL,
[BilledProcedureCode] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BilledProcedureCodeDesc] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BilledProcedureGrouping] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BilledProcedureModifierCode] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CLaimLineDiagnosisCode] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CoveredDays] [numeric] (18, 0) NULL,
[CPT_II] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CPTCode] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CPTProcedureCodeDesc] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CPTProcedureCodeGrouping] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerAPTransaction] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerHIDUD1] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerLineNo] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateAdjusted] [datetime] NULL,
[DateCheckDate] [datetime] NULL,
[DateClaimPosted] [datetime] NULL,
[DateValidBegin] [datetime] NULL,
[DateValidEnd] [datetime] NULL,
[FeeSchedule] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HedisMeasureID] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IsHighTechImage] [bit] NULL,
[LoadInstanceID] [int] NULL,
[PayerClaimID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PayerClaimLineID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PaymentStatus] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PlaceOfService] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PlaceOfServiceCode] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PlaceOfServiceCodeIndicator] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProcedureCodeModifier] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SubNumber] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TypeOfService] [char] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ClaimLineItem] ADD CONSTRAINT [pk_ClaimLineItem] PRIMARY KEY CLUSTERED  ([ClaimLineItemID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [idxClaimLineItemClaimID] ON [dbo].[ClaimLineItem] ([ClaimID]) ON [NDX]
GO
CREATE NONCLUSTERED INDEX [idxCustomerClaimID] ON [dbo].[ClaimLineItem] ([CustomerClaimID]) ON [NDX]
GO
CREATE NONCLUSTERED INDEX [idx_ClmUpdt] ON [dbo].[ClaimLineItem] ([DatePaid]) ON [NDX]
GO
CREATE NONCLUSTERED INDEX [idx_SorceSystemCov1] ON [dbo].[ClaimLineItem] ([SourceSystem]) ON [NDX]
GO
CREATE STATISTICS [sp_idxClaimLineItemClaimID] ON [dbo].[ClaimLineItem] ([ClaimID])
GO
CREATE STATISTICS [sp_pk_ClaimLineItem] ON [dbo].[ClaimLineItem] ([ClaimLineItemID])
GO
CREATE STATISTICS [sp_idxCustomerClaimID] ON [dbo].[ClaimLineItem] ([CustomerClaimID])
GO
CREATE STATISTICS [sp_idx_ClmUpdt] ON [dbo].[ClaimLineItem] ([DatePaid])
GO
CREATE STATISTICS [spidx_ClmUpdt] ON [dbo].[ClaimLineItem] ([DatePaid])
GO
CREATE STATISTICS [sp_idx_SorceSystemCov1] ON [dbo].[ClaimLineItem] ([SourceSystem])
GO
