IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'INTERNAL\CHSTESTDB02$')
CREATE LOGIN [INTERNAL\CHSTESTDB02$] FROM WINDOWS
GO
CREATE USER [INTERNAL\CHSTESTDB02$] FOR LOGIN [INTERNAL\CHSTESTDB02$]
GO
