IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'INTERNAL\CHSSQLDevOps')
CREATE LOGIN [INTERNAL\CHSSQLDevOps] FROM WINDOWS
GO
CREATE USER [INTERNAL\CHSSQLDevOps] FOR LOGIN [INTERNAL\CHSSQLDevOps]
GO
