IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'INTERNAL\Quality.Team')
CREATE LOGIN [INTERNAL\Quality.Team] FROM WINDOWS
GO
CREATE USER [INTERNAL\Quality.Team] FOR LOGIN [INTERNAL\Quality.Team] WITH DEFAULT_SCHEMA=[INTERNAL\Quality.Team]
GO
GRANT VIEW DEFINITION TO [INTERNAL\Quality.Team]
