CREATE TABLE [dbo].[H_HEDIS]
(
[H_HEDIS_RK] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[HEDIS_BK] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[LoadDate] [datetime] NOT NULL,
[RecordSource] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[H_HEDIS] ADD CONSTRAINT [PK_H_HEDIS] PRIMARY KEY CLUSTERED  ([H_HEDIS_RK]) ON [PRIMARY]
GO
