IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'IMIHEALTH\DHMP.SQL.Dev')
CREATE LOGIN [IMIHEALTH\DHMP.SQL.Dev] FROM WINDOWS
GO
CREATE USER [IMIHEALTH\DHMP.SQL.Dev] FOR LOGIN [IMIHEALTH\DHMP.SQL.Dev]
GO
