IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'IMIHEALTH\SP.DHMP.Members')
CREATE LOGIN [IMIHEALTH\SP.DHMP.Members] FROM WINDOWS
GO
CREATE USER [IMIHEALTH\SP.DHMP.Members] FOR LOGIN [IMIHEALTH\SP.DHMP.Members]
GO
