SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- =============================================
-- Author:		Jason Franks
-- Create date: 1/27/2016
-- Description:	Data Vault MMR Load
-- =============================================
CREATE PROCEDURE [dbo].[prDV_MMR_LoadSats]
	-- Add the parameters for the stored procedure here
	AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

--**[S_MMRDetail] LOAD

		INSERT INTO [dbo].[S_MMRDetail]
		(
			S_MMR_RK,
			LoadDate,
			H_MMR_RK,
			ContractNbr,
			FileRunDate,
			PaymentDate,
			HICN,
			LastName,
			FirstInit,
			Gender,
			DOB,
			Age_Group,
			StateCountyCode,
			Out_Of_Area_Ind,
			PartA_Entitle_Ind,
			PartB_Entitle_Ind,
			HospiceInd,
			ESRDInd,
			AgedDisabledMSPInd,
			InstitutionalInd,
			NHCInd,
			NewMedicareBenificiaryMedicaidStatus,
			LTIFlg,
			MedicaidInd,
			PIPDCGCatg,
			Default_Risk_Factor_Code,
			Risk_Adjust_FactorA,
			Risk_Adjust_FactorB,
			Nbr_of_Pay_Adjust_Mths_Part_A,
			Nbr_of_Pay_Adjust_Mths_Part_B,
			Adjust_Reason_Code,
			Pay_Adjust_MSA_Start_Date,
			Pay_Adjust_MSA_End_Date,
			Demographic_Pay_Adjust_Amt_A,
			Demographic_Pay_Adjust_Amt_B,
			Monthly_Pay_Adjust_Amt_A,
			Monthly_Pay_Adjust_Amt_B,
			LIS_Premium_Subsidy,
			ESRD_MSP_Flg,
			MSA_Part_A_Deposit_Recovery_Amt,
			MSA_Part_B_Deposit_Recovery_Amt,
			Nbr_of_MSA_Deposit_Recovery_Mths,
			Current_Medicaid_Status,
			Risk_Adjsuter_Age_Group,
			Prevous_Disable_Ratio,
			De_Minimis,
			Beneficiary_Dual_Part_D_Enroll_Status_Flg,
			PlanBenefitPkg_Id,
			RaceInd,
			RAFactorTypeCode,
			FrailtyInd,
			OrigReasonforEntitle_Code,
			LagInd,
			SegmentID,
			EnrollmentSource,
			EGHPFlg,
			PartC_Premium_PartA_Amt,
			PartC_Premium_PartB_Amt,
			Rebate_PartA_Cost_Sharing_Reduct,
			Rebate_PartB_Cost_Sharing_Reduct,
			Rebate_Other_PartA_Mandat_Suplmt_Benefits,
			Rebate_Other_PartB_Mandat_Suplmt_Benefits,
			Rebate_PartB_Prem_Reduct_Part_A_Amt,
			Rebate_PartB_Prem_Reduct_Part_B_Amt,
			Rebate_PartD_Suplmt_Benefit_Part_A_Amt,
			Rebate_PartD_Suplmt_Benefit_Part_B_Amt,
			Total_PartA_MA_Payment,
			Total_PartB_MA_Payment,
			Total_MA_Payment_Amt,
			PartD_RA_Factor,
			PartD_Low_Income_Indicator,
			PartD_Low_Income_Multiplier,
			PartD_Long_Term_Institut_Ind,
			PartD_Long_Term_Institut_Multi,
			Rebate_for_PartD_Basic_Prem_Reduct,
			PartD_Basic_Premium_Amount,
			PartD_Direct_Subsidy_Mthly_Pay_Amt,
			ReinsuranceSubsidyAmount,
			LIS_CostSharingAmount,
			Total_PartD_Payment,
			NbrPaymtAdjustmtMthsPartD,
			PACE_PremiumAddOn,
			PACE_CostSharingAddOn,
			PartC_FrailtyScoreFactor,
			MSPFactor,
			MSPReduct_Adjustmt_Amt_PartA,
			MSP_Reduct_Adjustmt_Amt_PartB,
			MedicaidDualStatus_Code,
			PartD_Coverage_Gap_Discount_Amt,
			PartD_RAFactorType,
			Default_PartD_RiskFactor_Code,
			PartA_Risk_Adjstd_Mthly_Rate_Amt_for_Pymt_Adj,
			PartB_Risk_Adjstd_Mthly_Rate_Amt_for_Pymt_Adj,
			PartD_Direct_Subsidy_Mthly_Rate_Amt_for_Pymt_Adj,
			CleanupID,
			HashDiff,
			RecordSource)

		SELECT 
				upper(convert(char(32), HashBytes('MD5',
				UPPER(Concat(
				RTRIM(LTRIM(COALESCE(MMR_RK_Hash,''))),':',
				RTRIM(LTRIM(COALESCE(SeqNum,''))))
					)),2)),
			LoadDate,
				UPPER(convert(char(32), HashBytes('MD5',
				UPPER(Concat(
				RTRIM(LTRIM(COALESCE(MMR_RK_Hash,''))),':',
				RTRIM(LTRIM(COALESCE(SeqNum,''))),':',
				RTRIM(LTRIM(COALESCE(CCI,''))))
			)),2)),
			MCO_Contract_Nbr,
			File_Run_Date,
			Payment_YYYYMM,
			HICN_Nbr,
			Last_Name,
			First_Initial,
			Gender,
			Birth_Date,
			Age_Group,
			State_County_Code,
			Out_Of_Area_Ind,
			Part_A_Entitle_Ind,
			Part_B_Entitle_Ind,
			Hospice_Ind,
			ESRD_Ind,
			Aged_Disabled_MSP_Ind,
			Institutional_Ind,
			NHC_Ind,
			New_Medicare_Benificiary_Medicaid_Status,
			LTI_Flg,
			Medicaid_Ind,
			PIP_DCG_Catg,
			Default_Risk_Factor_Code,
			Risk_Adjust_Factor_A,
			Risk_Adjust_Factor_B,
			Nbr_of_Pay_Adjust_Mths_Part_A,
			Nbr_of_Pay_Adjust_Mths_Part_B,
			Adjust_Reason_Code,
			Pay_Adjust_MSA_Start_Date,
			Pay_Adjust_MSA_End_Date,
			Demographic_Pay_Adjust_Amt_A,
			Demographic_Pay_Adjust_Amt_B,
			Monthly_Pay_Adjust_Amt_A,
			Monthly_Pay_Adjust_Amt_B,
			LIS_Premium_Subsidy,
			ESRD_MSP_Flg,
			MSA_Part_A_Deposit_Recovery_Amt,
			MSA_Part_B_Deposit_Recovery_Amt,
			Nbr_of_MSA_Deposit_Recovery_Mths,
			Current_Medicaid_Status,
			Risk_Adjsuter_Age_Group,
			Prevous_Disable_Ratio,
			De_Minimis,
			Beneficiary_Dual_Part_D_Enroll_Status_Flg,
			Plan_Benefit_Pkg_Id,
			Race_Ind,
			RA_Factor_Type_Code,
			Frailty_Ind,
			Orig_Reason_for_Entitle_Code,
			Lag_Ind,
			Segment_ID,
			Enrollment_Source,
			EGHP_Flg,
			Part_C_Premium_Part_A_Amt,
			Part_C_Premium_Part_B_Amt,
			Rebate_Part_A_Cost_Sharing_Reduct,
			Rebate_Part_B_Cost_Sharing_Reduct,
			Rebate_Other_Part_A_Mandat_Suplmt_Benefits,
			Rebate_Other_Part_B_Mandat_Suplmt_Benefits,
			Rebate_Part_B_Prem_Reduct_Part_A_Amt,
			Rebate_Part_B_Prem_Reduct_Part_B_Amt,
			Rebate_Part_D_Suplmt_Benefit_Part_A_Amt,
			Rebate_Part_D_Suplmt_Benefit_Part_B_Amt,
			Total_Part_A_MA_Payment,
			Total_Part_B_MA_Payment,
			Total_MA_Payment_Amt,
			Part_D_RA_Factor,
			Part_D_Low_Income_Indicator,
			Part_D_Low_Income_Multiplier,
			Part_D_Long_Term_Institut_Ind,
			Part_D_Long_Term_Institut_Multi,
			Rebate_for_Part_D_Basic_Prem_Reduct,
			Part_D_Basic_Premium_Amount,
			Part_D_Direct_Subsidy_Mthly_Pay_Amt,
			Reinsurance_Subsidy_Amount,
			LIS_Cost_Sharing_Amount,
			Total_Part_D_Payment,
			Nbr_of_Paymt_Adjustmt_Mths_Part_D,
			PACE_Premium_Add_On,
			PACE_Cost_Sharing_Add_On,
			Part_C_Frailty_Score_Factor,
			MSP_Factor,
			MSP_Reduct_Adjustmt_Amt_Part_A,
			MSP_Reduct_Adjustmt_Amt_Part_B,
			Medicaid_Dual_Status_Code,
			Part_D_Coverage_Gap_Discount_Amt,
			Part_D_RA_Factor_Type,
			Default_Part_D_Risk_Factor_Code,
			Part_A_Risk_Adjstd_Mthly_Rate_Amt_for_Pymt_Adj,
			Part_B_Risk_Adjstd_Mthly_Rate_Amt_for_Pymt_Adj,
			Part_D_Direct_Subsidy_Mthly_Rate_Amt_for_Pymt_Adj,
			Cleanup_ID,			
			upper(convert(char(32), HashBytes('MD5',
			Upper(Concat(
					RTRIM(LTRIM(COALESCE(MMR_RK_Hash,''))),':',
					RTRIM(LTRIM(COALESCE(SeqNum,''))))
			)),2)),
			RecordSource					 
		FROM CHSStaging.dbo.MMR_STAGE WITH(NOLOCK)
		WHERE
        upper(convert(char(32), HashBytes('MD5',
			Upper(Concat(
					RTRIM(LTRIM(COALESCE(MMR_RK_Hash,''))),':',
					RTRIM(LTRIM(COALESCE(SeqNum,''))))
			)),2)) NOT IN (SELECT HashDiff FROM S_MMRDetail WHERE RecordEndDate IS null)

		GROUP BY
			MMR_RK_Hash,
			LoadDate,
			upper(convert(char(32), HashBytes('MD5',
		Upper(Concat(
				RTRIM(LTRIM(COALESCE(MMR_RK_Hash,''))),':',
				RTRIM(LTRIM(COALESCE(SeqNum,''))),':',
				RTRIM(LTRIM(COALESCE(CCI,''))))
			)),2)),
			MCO_Contract_Nbr,
			File_Run_Date,
			Payment_YYYYMM,
			HICN_Nbr,
			Last_Name,
			First_Initial,
			Gender,
			Birth_Date,
			Age_Group,
			State_County_Code,
			Out_Of_Area_Ind,
			Part_A_Entitle_Ind,
			Part_B_Entitle_Ind,
			Hospice_Ind,
			ESRD_Ind,
			Aged_Disabled_MSP_Ind,
			Institutional_Ind,
			NHC_Ind,
			New_Medicare_Benificiary_Medicaid_Status,
			LTI_Flg,
			Medicaid_Ind,
			PIP_DCG_Catg,
			Default_Risk_Factor_Code,
			Risk_Adjust_Factor_A,
			Risk_Adjust_Factor_B,
			Nbr_of_Pay_Adjust_Mths_Part_A,
			Nbr_of_Pay_Adjust_Mths_Part_B,
			Adjust_Reason_Code,
			Pay_Adjust_MSA_Start_Date,
			Pay_Adjust_MSA_End_Date,
			Demographic_Pay_Adjust_Amt_A,
			Demographic_Pay_Adjust_Amt_B,
			Monthly_Pay_Adjust_Amt_A,
			Monthly_Pay_Adjust_Amt_B,
			LIS_Premium_Subsidy,
			ESRD_MSP_Flg,
			MSA_Part_A_Deposit_Recovery_Amt,
			MSA_Part_B_Deposit_Recovery_Amt,
			Nbr_of_MSA_Deposit_Recovery_Mths,
			Current_Medicaid_Status,
			Risk_Adjsuter_Age_Group,
			Prevous_Disable_Ratio,
			De_Minimis,
			Beneficiary_Dual_Part_D_Enroll_Status_Flg,
			Plan_Benefit_Pkg_Id,
			Race_Ind,
			RA_Factor_Type_Code,
			Frailty_Ind,
			Orig_Reason_for_Entitle_Code,
			Lag_Ind,
			Segment_ID,
			Enrollment_Source,
			EGHP_Flg,
			Part_C_Premium_Part_A_Amt,
			Part_C_Premium_Part_B_Amt,
			Rebate_Part_A_Cost_Sharing_Reduct,
			Rebate_Part_B_Cost_Sharing_Reduct,
			Rebate_Other_Part_A_Mandat_Suplmt_Benefits,
			Rebate_Other_Part_B_Mandat_Suplmt_Benefits,
			Rebate_Part_B_Prem_Reduct_Part_A_Amt,
			Rebate_Part_B_Prem_Reduct_Part_B_Amt,
			Rebate_Part_D_Suplmt_Benefit_Part_A_Amt,
			Rebate_Part_D_Suplmt_Benefit_Part_B_Amt,
			Total_Part_A_MA_Payment,
			Total_Part_B_MA_Payment,
			Total_MA_Payment_Amt,
			Part_D_RA_Factor,
			Part_D_Low_Income_Indicator,
			Part_D_Low_Income_Multiplier,
			Part_D_Long_Term_Institut_Ind,
			Part_D_Long_Term_Institut_Multi,
			Rebate_for_Part_D_Basic_Prem_Reduct,
			Part_D_Basic_Premium_Amount,
			Part_D_Direct_Subsidy_Mthly_Pay_Amt,
			Reinsurance_Subsidy_Amount,
			LIS_Cost_Sharing_Amount,
			Total_Part_D_Payment,
			Nbr_of_Paymt_Adjustmt_Mths_Part_D,
			PACE_Premium_Add_On,
			PACE_Cost_Sharing_Add_On,
			Part_C_Frailty_Score_Factor,
			MSP_Factor,
			MSP_Reduct_Adjustmt_Amt_Part_A,
			MSP_Reduct_Adjustmt_Amt_Part_B,
			Medicaid_Dual_Status_Code,
			Part_D_Coverage_Gap_Discount_Amt,
			Part_D_RA_Factor_Type,
			Default_Part_D_Risk_Factor_Code,
			Part_A_Risk_Adjstd_Mthly_Rate_Amt_for_Pymt_Adj,
			Part_B_Risk_Adjstd_Mthly_Rate_Amt_for_Pymt_Adj,
			Part_D_Direct_Subsidy_Mthly_Rate_Amt_for_Pymt_Adj,
			Cleanup_ID,			
			upper(convert(char(32), HashBytes('MD5',
			Upper(Concat(
					RTRIM(LTRIM(COALESCE(MMR_RK_Hash,''))),':',
					RTRIM(LTRIM(COALESCE(SeqNum,''))))
			)),2)),
			RecordSource


			  --RECORD END DATE CLEANUP
			UPDATE dbo.S_MMRDetail set
			RecordEndDate = (
			 Select 
			  DATEADD(ss,-1,Min(z.LoadDate))
			 From
			 dbo.S_MMRDetail z
			 Where
			  z.H_MMR_RK = a.H_MMR_RK
			  and z.LoadDate > a.LoadDate
			  )
			FROM 
			 dbo.S_MMRDetail a
			Where a.RecordEndDate Is Null 

			
END


--USE CHSDW_DEV
--SELECT COLUMN_NAME +',' 
--FROM INFORMATION_SCHEMA.COLUMNS
--WHERE TABLE_NAME = 'S_MMRDETAIL' AND TABLE_SCHEMA='dbo'
--ORDER BY ORDINAL_POSITION
GO
