CREATE TABLE [dbo].[tmpClaim02]
(
[MEMBER_ID] [varchar] (50) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[MEMBER_INDIVIDUAL_ID] [varchar] (50) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[CLAIM_ID] [varchar] (70) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[FROM_DATE_OF_SERVICE] [varchar] (50) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[TO_DATE_OF_SERVICE] [varchar] (50) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[REN_NPI] [varchar] (50) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[ICD9_CODE] [varchar] (50) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[DX_CODE_QUALIFIER] [varchar] (50) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[REN_TIN] [varchar] (50) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[REN_PIN] [varchar] (50) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[PID] [varchar] (50) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[CHASE_ID] [varchar] (50) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[PAT_REF_NBR] [varchar] (50) COLLATE SQL_Latin1_General_CP437_CI_AI NULL
) ON [PRIMARY]
GO
