CREATE TABLE [stage].[MemorilaHermannChaseCommerical2016_12_15]
(
[clcl_id] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[MemberNumber] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[LowDateOfService] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[Paid_Dt] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[BIRTH_DT] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[SEX_CD] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[PRODUCTPLAN] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[PRODUCTNAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[Admit Date] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[Discharge Date] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[CLASS_PLAN_ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[MemberFullName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[MemberFirstName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[MemberLastName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[BillingProviderName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[BillingProviderNPI] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[BillingProviderUniqueID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[BillingProviderTIN] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[BillingProviderTinName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[PAYEE_PRIM_ADDR_LN_1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[PAYEE_PRIM_ADDR_LN_2] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[PAYEE_PRIM_ADDR_LN_3] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[PAYEE_PRIM_CITY_NAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[PAYEE_PRIM_STATE_CD] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[PAYEE_PRIM_POSTAL] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[PAYEE_PRIM_PHONE_NUM] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[PAYEE_PRIM_FAX_NUM] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[ServiceProviderName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[ServiceProviderNPI] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[ServiceProviderUniqueID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[ServiceProviderTIN] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[ServiceProviderTinName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[SVC_PRIM_ADDR_LN_1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[SVC_PRIM_ADDR_LN_2] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[SVC_PRIM_ADDR_LN_3] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[SVC_PRIM_CITY_NAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[SVC_PRIM_STATE_CD] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[SVC_PRIM_POSTAL] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[SVC_PRIM_PHONE_NUM] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[SVC_PRIM_FAX_NUM] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[FAC_ProviderName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[FAC_ProviderNPI] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[FAC_UniqueID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[FAC_ProviderTIN] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[FAC_ProviderTinName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[FAC_PRIM_ADDR_LN_1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[FAC_PRIM_ADDR_LN_2] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[FAC_PRIM_ADDR_LN_3] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[FAC_PRIM_CITY_NAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[FAC_PRIM_STATE_CD] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[FAC_PRIM_POSTAL] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[FAC_PRIM_PHONE_NUM] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[FAC_PRIM_FAX_NUM] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[Claim_Category_Primary1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[Claim_Category_Primary2] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[Claim_Category_Primary3] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[Claim_Category_Secondary1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[Claim_Category_Secondary2] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[Claim_Category_Secondary3] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[Provider_Specialty_Desc1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[Provider_Specialty_Desc2] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[Provider_Specialty_Desc3] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[Claim Category] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[MHMD?] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[PrimaryProvider_ProviderName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[PrimaryProvider_ProviderNPI] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[PrimaryProvider_UniqueID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[PrimaryProvider_ProviderTIN] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[PrimaryProvider_ProviderTinName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[PrimaryProvider_PRIM_ADDR_LN_1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[PrimaryProvider_PRIM_ADDR_LN_2] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[PrimaryProvider_PRIM_ADDR_LN_3] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[PrimaryProvider_PRIM_CITY_NAME] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[PrimaryProvider_PRIM_STATE_CD] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[PrimaryProvider_PRIM_POSTAL] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[PrimaryProvider_PRIM_PHONE_NUM] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[PrimaryProvider_PRIM_FAX_NUM] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[Unique Chart ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[hash] [varchar] (50) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[NewAddress] [varchar] (250) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[NewZip] [varchar] (15) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[RawAddresstoUse] [varchar] (250) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[RawZIPtoUse] [varchar] (15) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[PhoneUSed] [varchar] (15) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[FAXUSed] [varchar] (15) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[NPIUsed] [varchar] (15) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[CentuariProviderID] [bigint] NULL,
[Member_PK] [bigint] NULL,
[Provider_PK] [bigint] NULL,
[ProviderMaster_PK] [bigint] NULL,
[ProviderOffice_PK] [bigint] NULL,
[Omit] [char] (1) COLLATE SQL_Latin1_General_CP437_CI_AI NULL,
[UniqueChart] [char] (1) COLLATE SQL_Latin1_General_CP437_CI_AI NULL
) ON [PRIMARY]
GO
