CREATE TABLE [stage].[MHHS-HIX1603 move to CHASE LIST 02 - DNC (002)]
(
[MHHS-HIX1603 Chase ID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MHMD] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
