IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'SSRS_REPORTING')
CREATE LOGIN [SSRS_REPORTING] WITH PASSWORD = 'p@ssw0rd'
GO
CREATE USER [SSRS_REPORTING] FOR LOGIN [SSRS_REPORTING]
GO
GRANT ALTER TO [SSRS_REPORTING]
GRANT EXECUTE TO [SSRS_REPORTING]
GRANT VIEW DEFINITION TO [SSRS_REPORTING]
